#bdfx-data
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'ves_pkg buildDir RootDir GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'bdfx-data' ) )
allFiles = sca_util.getFilesRecursiveByExt(
    pj( RootDir, 'share', 'bdfx-data' ),
    [ '.common', '.fs', '.vs', '.osg', '.jpg', '.png' ] )
fileBundle.addFiles( allFiles )
