##Builds VE-Builder translator base class
import os, sys, string
pj = os.path.join

Import('baseEnv libPath ves_pkg LIBDIR')

sources = Split("""
   cfdTranslatorToVTK.cxx 
""")

headers = Split("""
   cfdTranslatorToVTK.h 
""")
##srcs = map(lambda s: pj('#', 'VE_CE', 'Utilities', s), srcs)

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['VE_UtilLib'])
lib_env.ParseConfig('flagpoll vtk Boost.Filesystem --libs --cflags')

if baseEnv['StaticOnly'] == "no":
   lib = ves_pkg.createStaticAndSharedLibrary('TranslatorToVTKLib',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createStaticLibrary('TranslatorToVTKLib', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Builder', 'Translator', 'cfdTranslatorToVTK'))
lib.build()
