##Builds loaderToVtk program
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR GetPlatform buildDir vtk_options')

srcs = Split("""
   main.cxx
""")
srcs = map(lambda s: pj('#', buildDir, 'VE_Builder', 'Translator', 'DataLoader', s), srcs)

env = ves_pkg.getEnv().Copy()
env.Append(LIBPATH = [pj('#', buildDir, 'VE_Xplorer','Utilities'),
                      pj('#', buildDir, 'VE_Builder','Translator','cfdTranslatorToVTK'),
                      pj('#', buildDir, 'VE_Builder','Translator','DataLoader') ],
           LIBS = ['VE_UtilLib', 'DataLoaderLib', 'TranslatorToVTKLib'])

env.ParseConfig('flagpoll Boost.Filesystem --atleast-version=%s --cflags --libs'%env['BoostVersion'])
vtk_options.apply( env )
prog = ves_pkg.createProgram('loaderToVtk', env, 'bin')
prog.addSources( srcs )
prog.build()


