##Builds loaderToVtk program
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR GetPlatform buildDir vtk_options')

srcs = Split("""
   main.cxx
""")
srcs = map(lambda s: pj('#', buildDir, 'src', 'ves', 'builder', 'DataLoader', s), srcs)

env = ves_pkg.getEnv().Copy()
env.Append(LIBPATH = [pj('#', buildDir, 'src','builder','util'),
                      pj('#', buildDir, 'src','builder','cfdTranslatorToVTK'),
                      pj('#', buildDir, 'src','builder','DataLoader') ],
           LIBS = ['ves_xplorer_util', 'ves_builder_dataloader', 'ves_builder_translator_base'])

env.ParseConfig('flagpoll Boost.Filesystem --atleast-version=%s --cflags --libs'%env['BoostVersion'])
vtk_options.apply( env )
prog = ves_pkg.createProgram('loaderToVtk', env, 'bin')
prog.addSources( srcs )
prog.build()


