##Builds VE_Utils
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('baseEnv ves_pkg LIBDIR buildDir xerces_options wxwidgets_options RootDir')

srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'util') )
sources = sca_util.getSourcesRecursive( srcDir )
headers = sca_util.getHeadersRecursive( srcDir )

lib_env = ves_pkg.getEnv().Clone()

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_util',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_util', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves', 'util'))
lib.build()

srcSubdirs = Split("""
    icons
""")

for d in srcSubdirs:
     SConscript( dirs = d )

