##Builds VE_XMLLib
import os, sys, string
##import practice
pj = os.path.join

Import('baseEnv')
Import('libPath')
Import('cfdHostType')

srcs = Split("""
   CreationEventHandler.cxx 
   Command.cxx
   DataValuePair.cxx
   FloatArray.cxx
   OneDDoubleArray.cxx
   TwoDDoubleArray.cxx
   ThreeDDoubleArray.cxx
   OneDIntArray.cxx
   TwoDIntArray.cxx
   ThreeDIntArray.cxx
   OneDStringArray.cxx
   ParameterBlock.cxx
   StateInfo.cxx
   Transform.cxx
   User.cxx
   XMLCreator.cxx
   XMLObject.cxx
   XMLObjectFactory.cxx
   XMLReaderWriter.cxx
   DOMDocumentManager.cxx
""")
##srcs = map(lambda s: pj('#', 'VE_Open', 'XML', s), srcs)

env = baseEnv.Copy()

env.ParseConfig('flagpoll xerces apr-1 apr-util-1 --libs --cflags')
##Get apr config.
##if cfdHostType == "Darwin":
##    suffix = "-1-config"
##else:
##    suffix = "-config"
#env.ParseConfig('apr%s --includes --cppflags --link-ld --libs' %suffix)
#env.ParseConfig('apu%s --includes --link-ld --libs' %suffix)

targetLib = pj(libPath, 'VE_XMLLib')
env.SharedLibrary(target = targetLib, source = srcs)
