##Builds VE_XMLLib
import os, sys, string 
import SConsAddons.Util as sca_util
##import practice
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR xerces_options')

sources = sca_util.getSourcesRecursive('.')
headers = sca_util.getHeadersRecursive('.')
##srcs = map(lambda s: pj('#', 'VE_Open', 'XML', s), srcs)

lib_env = ves_pkg.getEnv().Copy()
##Get apr config.
if baseEnv.has_key('AprVersion'):
   if baseEnv[ 'AprVersion' ] >= "1.0":
      lib_env.ParseConfig('flagpoll apr-1 apr-util-1 --libs --cflags' )
   else:
      lib_env.ParseConfig('flagpoll apr apr-util --libs --cflags' )
else:
   lib_env.ParseConfig('flagpoll apr apr-util --libs --cflags' )

xerces_options.apply( lib_env )
if baseEnv['StaticOnly'] == "no":
   lib = ves_pkg.createStaticAndSharedLibrary('VE_XML',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createStaticLibrary('VE_XML', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Open', 'XML'))
lib.build()
