##Builds GraphicalPlugin<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR buildDir vtk_options osg_options xerces_options')

sources = Split("""
    PluginBase.cxx
""")

headers = Split("""
    PluginBase.h
""")

##srcs = map(lambda s: pj('#', 'VE_Xplorer', 'GraphicalPlugin', s), srcs)

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['VE_SceneGraph%s' %(execOsgPatTag),
                   'VE_XplorerLib%s' %(execOsgPatTag),
                   'VE_TextureBasedLib%s' %(execOsgPatTag),
                   'VE_UtilLib', 'VE_XML'])
lib_env.Append(LIBPATH = [pj('#', buildDir, 'VE_Xplorer','SceneGraph'),
                        pj('#', buildDir, 'VE_Xplorer','XplorerHandlers'),
                        pj('#', buildDir, 'VE_Xplorer','Utilities'),
                        pj('#', buildDir, 'VE_Xplorer','TextureBased'),
                        pj('#', buildDir, 'VE_Open','XML')])
lib_env.ParseConfig('flagpoll vrjuggler --atleast-version=%s --libs --cflags bullet --libs --cflags'%lib_env['VRJugglerVersion'])
lib_env.ParseConfig('flagpoll Boost.Filesystem --atleast-version=%s --libs --cflags'%lib_env['BoostVersion'])

vtk_options.apply( lib_env )
osg_options.apply( lib_env )
xerces_options.apply( lib_env )

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('GraphicalPlugin',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('GraphicalPlugin', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Xplorer', 'GraphicalPlugin'))
lib.build()
