##Builds GraphicalPlugin<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('execOsgPatTag')
Import('libPath')

srcs = Split("""
    cfdVEBaseClass.cxx
""")

##srcs = map(lambda s: pj('#', 'VE_Xplorer', 'GraphicalPlugin', s), srcs)

env = baseEnv.Copy()
env.Append(LIBS = ['VE_SceneGraphLib%s' %(execOsgPatTag),
                   'VE_XplorerLib%s' %(execOsgPatTag),
                   'VE_TextureBasedLib%s' %(execOsgPatTag),
                   'VE_UtilLib', 'VE_ModelLib', 'VE_XMLLib', 'VE_CADLib'])
env.ParseConfig('flagpoll Boost.Filesystem --libs --cflags')
env.ParseConfig('flagpoll osg vtk xerces vrjuggler --libs --cflags')

targetLib = pj(libPath, 'GraphicalPlugin%s' %(execOsgPatTag))
env.SharedLibrary(target = targetLib, source = srcs)
