##Builds CoinFunnel UI Plugin
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import( 'baseEnv ves_pkg buildDir RootDir vpr_options wxwidgets_options tao_options xerces_options GetPlatform' )
openDir = os.path.abspath( pj( RootDir, 'share', 'examples', 'CoinFunnel', 'CoinFunnelUI' ) )
sources = sca_util.getSourcesRecursive( openDir )
headers = sca_util.getHeadersRecursive( openDir )

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append( LIBS = ['ves_conductor_plugin',
                        'ves_open_xml' ] )
lib_env.Append( LIBPATH = [ pj('#', buildDir, 'src','ves','conductor' ),
                            pj('#', buildDir, 'src','ves','open', 'xml' ) ] )
#lib_env.Append( CPPPATH = [] )
if GetPlatform() == 'win32':
   lib_env.Append( CPPDEFINES = [ 'LOKI_DLL' ] )

vpr_options.apply( lib_env )
wxwidgets_options.apply( lib_env )
tao_options.apply( lib_env )
xerces_options.apply( lib_env )

if GetPlatform() == 'win32':
   lib_env['no_import_lib'] = 1
   #lib_env['SHLINKFLAGS'] = '$LINKFLAGS /dll /MANIFEST:NO'
   lib_env['WINDOWS_INSERT_MANIFEST'] = False

lib = ves_pkg.createLoadableModule( 'CoinFunnelUI', lib_env,
    installPrefix = pj( 'share', 'vesuite', 'examples', 'CoinFunnel', 'Plugins', 'UI', host_type ) )
   
lib.addSources( sources )
lib.build()
