##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform poco_options' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'Multiscale2' ) )
Multiscale2Dir = pj( RootDir, 'share', 'examples', 'Multiscale2' )

iveFile = sca_util.getFilesRecursiveByExt( Multiscale2Dir, [ '.ive' ] )
vsFile = sca_util.getFilesRecursiveByExt( Multiscale2Dir, [ '.vs' ] )
fsFile = sca_util.getFilesRecursiveByExt( Multiscale2Dir, [ '.fsh' ] )
fileBundle.addFiles( iveFile )
fileBundle.addFiles( vsFile )
fileBundle.addFiles( fsFile )

Multiscale2Subdirs = Split("""
    UserInterface
    GraphicalPlugin
""")

##Run SConscript files in all of these folders.
for d in Multiscale2Subdirs:
   SConscript( dirs = d )
