import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('Platform')

srcs = Split("""
   translateToVtk.cpp 
   starReader.cpp 
   avsReader.cpp 
   reiReader.cpp 
   en7Reader.cpp
   mfixReader.cpp  
   converter.cpp 
   gridConversion.cpp 
   fireReader.cpp 
   particle.cpp 
   fluentParticles.cpp 
   reiParticles.cpp 
   plot3dReader.cpp 
   jdMAPReader.cpp
   enSightGoldReader.cpp
""")

srcs = map(lambda s: pj('#', 'VE_Builder', 'Translator', s), srcs)

env = baseEnv.Copy()
env.Append(CPPPATH = [os.getcwd()])
env.Append(LIBPATH = '#',
              LIBS = 'Shared_Library')
env.Program(pj('#','bin',Platform,'Translator'), source = srcs)
