##Builds preprocessor program
import os, sys, string
pj = os.path.join

Import('ves_pkg LIBDIR PREFIX buildDir vtk_options')

srcs = Split("""
   multiPlaneVtkOutput.cxx
   preprocessor.cxx
""")

env = ves_pkg.getEnv().Copy()
env.Append( LIBPATH = [pj('#', buildDir, 'VE_Xplorer','Utilities')],
            LIBS = ['VE_UtilLib'])
env.ParseConfig('flagpoll Boost.Filesystem --atleast-version=%s --libs --cflags'%env['BoostVersion'])
vtk_options.apply( env )

prog = ves_pkg.createProgram('preprocessor', env, 'bin')
prog.addSources( srcs )
prog.build()
