##Builds preprocessor program
import os, sys, string
pj = os.path.join

Import('ves_pkg LIBDIR PREFIX buildDir vtk_options boost_options')

srcs = Split("""
   multiPlaneVtkOutput.cxx
   preprocessor.cxx
""")

env = ves_pkg.getEnv().Copy()
env.Append( LIBPATH = [pj('#', buildDir, 'src','ves','xplorer','util')],
            LIBS = ['ves_xplorer_util'])

boost_options.apply( env )
vtk_options.apply( env )

prog = ves_pkg.createProgram('preprocessor' + env["PROGSUFFIX"], env, 'bin')
prog.addSources( srcs )
prog.build()
