
BuildRequires:  Xerces-c Xerces-c-devel aaa_base acl attr autoconf automake bash binutils bison bzip2 coreutils cpio cpp devs diffutils doxygen e2fsprogs expat file filesystem findutils gawk gcc gettext glibc glibc-devel glibc-locale graphviz grep gzip info klogd libacl libattr libgcc libpng libstdc++ libtool m4 make man mktemp module-init-tools patch permissions popt procinfo procps psmisc pwdutils python python-devel python-wxGTK readline rpm sed sysvinit tar timezone unzip util-linux zlib zlib-devel

Name:         VE-Suite-Dependencies
License:      LGPL
Group:        System/Libraries
Autoreqprov:  on
Version:      1.0.2
Release:      1
Summary:      All third party packages necessary to build and run VE-Suite applications.
Source0:      VE-Suite-Dependencies-%{version}.tar.bz2
URL:          http://www.vesuite.org
Provides:     ve-suite-dependencies
BuildRoot:    %{_tmppath}/%{name}-%{version}-build

%description

This package contains all third party packages necessary to build and run 
VE-Suite applications bundled into one distribution.  This includes:
   * Bullet Physics           http://www.continuousphysics.com
   * VTK                      http://www.kitware.com/vtk/index.html
   * wxWidgets 2.8.0          http://www.wxwidgets.org

Authors:
--------
   Kenneth Mark Bryden, Ph.D <kmbryden@iastate.edu>

%package -n vtk-bin
Summary: The Visualization Toolkit
Version: 5.0.2
Release: 1
Group: Development/C++
License: Original
URL: http://www.vtk.org
Provides: vtk-bin

%description -n vtk-bin
The Visualization ToolKit (vtk) is a software system for 3D Computer Graphics
and Visualization.  VTK includes a textbook published by Kitware Inc.
([http://www.kitware.com/products/vtktextbook.html The Visualization Toolkit,
An Object-Oriented Approach to 3D Graphics]), a C++ class library, and Tcl,
Python and Java implementations based on the class library.
This distribution of VTK is a binary distribution specifically built for use
with VE-Suite.

Authors:
--------
   Kitware, Inc. <http://www.kitware.com>
   Ken Martin 
   Will Schroeder
   Bill Lorensen

%package -n bullet-bin
Summary: The Bullet Physics Library
Version: 2.4.2b
Release: 1
Group: Development/C++
License: zlib
URL: http://www.continuousphysics.com
Provides: bullet-bin

%description -n bullet-bin
Bullet is a 3D Collision Detection and Rigid Body Dynamics Library for games
and animation.  Free for commercial use, including Playstation 3, open source
under the ZLib License.  Discrete and continuous collision detection,
integrated into Blender 3D, and COLLADA 1.4 Physics import

Authors:
--------
   Erwin Coumans: Project Starter
   Gino van den Bergen: LinearMath classes
   Christer Ericson: parts of the voronoi simplex solver
   Simon Hobbs: 3d axis sweep and prune, Extras/SATCollision, separating axis
                theorem + SIMD code
   Dirk Gregorius: generic D6 constraint
   Erin Catto: accumulated impulse in sequential impulse
   Nathanael Presson: EPA penetration depth calculation
   Francisco Leon: GIMPACT Concave Concave collision
   Joerg Henrichs: make buildsystem (work in progress)
   Eric Sunshine: jam + msvcgen buildsystem
   Steve Baker: GPU physics and general implementation improvements
   Jay Lee: Double precision support
   Erwin Coumans: most other source code

%package -n wx28-bin
Summary: wxWidgets 2.8
Version: 2.8.0
Release: 1
Group: Development/C++
License: LGPL
URL: http://www.wxwidgets.org
Provides: wx28-bin

%description -n wx28-bin
wxWidgets is a cross platform GUI development toolkit.  This package provides 
the latest version 2.8.0 for VE-Suite since the latest releases of the SLE 10
SDK only provide 2.6.x.

Authors:
--------
Julian Smart
Robert Roebling
et al

## Define some generally useful macros 
## Macros that begin with an underscore, '_', are defined by the system in the
## rpm macro files; these are usually located in /usr/lib/rpm.

# The version macro defines the version of VE-Suite that we are using.
%define ve_suite_version 1.0.2

# The root macro defines the root location of the ve-suite installation.
# Changing this will change where ALL files go.
%define root %{_prefix}/ve-suite-%{ve_suite_version}/dependencies

# This is a standard rpm macro that untars the source ball into the build 
# directory.
%prep

%setup -q -n VE-Suite-Dependencies-%{ve_suite_version}

%build

# Since this is a binary RPM, do nothing for the build.

%install

# Copy files around to their proper locations.

# Clean the directory structure out if it exists.
if [ -d $RPM_BUILD_ROOT ]
then
   rm -rf $RPM_BUILD_ROOT
fi

# Create the directory structure.
mkdir -p $RPM_BUILD_ROOT%{_prefix}/ve-suite-%{ve_suite_version}

# Copy the binaries over 
cp -a $RPM_BUILD_DIR/* $RPM_BUILD_ROOT%{root}

# Copy the pkgconfig files over
mkdir -p $RPM_BUILD_ROOT/usr/lib/pkgconfig
mv lib/pkgconfig/bullet.pc $RPM_BUILD_ROOT/usr/lib/pkgconfig/bullet.pc
rm -rf $RPM_BUILD_ROOT%{root}/lib/pkgconfig


# Add the dep dir to the ld.so.conf file.
if [ -d /etc/ld.so.conf.d ]
then
   echo "%{root}/lib" > /etc/ld.so.conf.d/ve-suite-deps.conf
else
   echo "%{root}/lib" >> /etc/ld.so.conf
fi

%post
%{run_ldconfig}

%postun
# Remove the ve-suite-deps dirs from the ld.so.conf files. 
if [ -f /etc/ld.so.conf.d/ve-suite-deps.conf ]
then
   rm -f /etc/ld.so.conf.d/ve-suite-deps.conf
else
   cat /etc/ld.so.conf | grep -v "%{root}/lib" > /etc/ld.so.conf
fi
%{run_ldconfig}


%files
%dir %{root}/lib
%dir %{root}/include

# VTK 5.0 files
%files -n vtk-bin
%dir %{root}/lib/vtk-5.0
%dir %{root}/lib/vtk-5.0/CMake
%dir %{root}/lib/vtk-5.0/doxygen
%dir %{root}/lib/vtk-5.0/testing
%dir %{root}/include/vtk-5.0
%dir %{root}/include/vtk-5.0/vtkstd
%dir %{root}/include/vtk-5.0/vtksys
%dir %{root}/include/vtk-5.0/vtksys/ios
%dir %{root}/include/vtk-5.0/vtksys/stl
%dir %{root}/include/vtk-5.0/vtknetcdf
%dir %{root}/include/vtk-5.0/vtkjpeg
%dir %{root}/include/vtk-5.0/vtktiff
%dir %{root}/include/vtk-5.0/internal

%{root}/lib/libvtkfreetype.so.5.0.2
%{root}/lib/libvtkexpat.so.5.0.2
%{root}/lib/libvtktiff.so.5.0.2
%{root}/lib/libvtkFiltering.so.5.0.2
%{root}/lib/libvtkzlib.so.5.0.2
%{root}/lib/libvtkImaging.so.5.0.2
%{root}/lib/libvtkNetCDF.so.5.0.2
%{root}/lib/libvtkVolumeRendering.so.5.0.2
%{root}/lib/libvtksys.so.5.0.2
%{root}/lib/libvtkDICOMParser.so.5.0.2
%{root}/lib/libvtkCommon.so.5.0.2
%{root}/lib/libvtkjpeg.so.5.0.2
%{root}/lib/libvtkRendering.so.5.0.2
%{root}/lib/libvtkGenericFiltering.so.5.0.2
%{root}/lib/libvtkWidgets.so.5.0.2
%{root}/lib/libvtkftgl.so.5.0.2
%{root}/lib/libvtkIO.so.5.0.2
%{root}/lib/libvtkMPEG2Encode.so.5.0.2
%{root}/lib/libvtkGraphics.so.5.0.2
%{root}/lib/libvtkHybrid.so.5.0.2
%{root}/lib/libvtkCommon.so
%{root}/lib/libvtkCommon.so.5.0
%{root}/lib/libvtkDICOMParser.so
%{root}/lib/libvtkDICOMParser.so.5.0
%{root}/lib/libvtkFiltering.so
%{root}/lib/libvtkFiltering.so.5.0
%{root}/lib/libvtkGenericFiltering.so
%{root}/lib/libvtkGenericFiltering.so.5.0
%{root}/lib/libvtkGraphics.so
%{root}/lib/libvtkGraphics.so.5.0
%{root}/lib/libvtkHybrid.so
%{root}/lib/libvtkHybrid.so.5.0
%{root}/lib/libvtkIO.so
%{root}/lib/libvtkIO.so.5.0
%{root}/lib/libvtkImaging.so
%{root}/lib/libvtkImaging.so.5.0
%{root}/lib/libvtkMPEG2Encode.so
%{root}/lib/libvtkMPEG2Encode.so.5.0
%{root}/lib/libvtkNetCDF.so
%{root}/lib/libvtkNetCDF.so.5.0
%{root}/lib/libvtkParallel.so
%{root}/lib/libvtkParallel.so.5.0
%{root}/lib/libvtkRendering.so
%{root}/lib/libvtkRendering.so.5.0
%{root}/lib/libvtkVolumeRendering.so
%{root}/lib/libvtkVolumeRendering.so.5.0
%{root}/lib/libvtkWidgets.so
%{root}/lib/libvtkWidgets.so.5.0
%{root}/lib/libvtkexoIIc.so
%{root}/lib/libvtkexoIIc.so.5.0
%{root}/lib/libvtkexpat.so
%{root}/lib/libvtkexpat.so.5.0
%{root}/lib/libvtkfreetype.so
%{root}/lib/libvtkfreetype.so.5.0
%{root}/lib/libvtkftgl.so
%{root}/lib/libvtkftgl.so.5.0
%{root}/lib/libvtkjpeg.so
%{root}/lib/libvtkjpeg.so.5.0
%{root}/lib/libvtkpng.so
%{root}/lib/libvtkpng.so.5.0
%{root}/lib/libvtksys.so
%{root}/lib/libvtksys.so.5.0
%{root}/lib/libvtktiff.so
%{root}/lib/libvtktiff.so.5.0
%{root}/lib/libvtkzlib.so
%{root}/lib/libvtkzlib.so.5.0
%{root}/lib/vtk-5.0/VTKBuildSettings.cmake
%{root}/lib/vtk-5.0/CMake/vtkWrapperInit.data.in
%{root}/lib/vtk-5.0/CMake/vtkMakeInstantiator.h.in
%{root}/lib/vtk-5.0/CMake/vtkTclTkMacros.cmake
%{root}/lib/vtk-5.0/CMake/vtkLoadCMakeExtensions.cmake
%{root}/lib/vtk-5.0/CMake/vtkMakeInstantiator.cxx.in
%{root}/lib/vtk-5.0/CMake/vtkMakeInstantiator.cmake
%{root}/lib/vtk-5.0/CMake/vtkWrapTcl.cmake
%{root}/lib/vtk-5.0/CMake/vtkWrapPython.cmake
%{root}/lib/vtk-5.0/CMake/vtkWrapJava.cmake
%{root}/lib/vtk-5.0/doxygen/doc_codematch.pl
%{root}/lib/vtk-5.0/doxygen/doc_contributors.pl
%{root}/lib/vtk-5.0/doxygen/doc_version.pl
%{root}/lib/vtk-5.0/doxygen/paper-clip.gif
%{root}/lib/vtk-5.0/doxygen/doc_index.pl
%{root}/lib/vtk-5.0/doxygen/doc_cleanhtml.pl
%{root}/lib/vtk-5.0/doxygen/authors.txt
%{root}/lib/vtk-5.0/doxygen/doc_class2example.pl
%{root}/lib/vtk-5.0/doxygen/doc_index.stop
%{root}/lib/vtk-5.0/doxygen/doc_rmpath.pl
%{root}/lib/vtk-5.0/doxygen/vtk-logo.gif
%{root}/lib/vtk-5.0/doxygen/doc_readme.txt
%{root}/lib/vtk-5.0/doxygen/pic.gif
%{root}/lib/vtk-5.0/doxygen/doc_header2doxygen.pl
%{root}/lib/vtk-5.0/vtkIOKit.cmake
%{root}/lib/vtk-5.0/vtkGenericFilteringKit.cmake
%{root}/lib/vtk-5.0/testing/WindowsMangleList.py
%{root}/lib/vtk-5.0/testing/TestSetGet.tcl
%{root}/lib/vtk-5.0/testing/PrintSelfCheck.tcl
%{root}/lib/vtk-5.0/testing/rtImageTest.tcl
%{root}/lib/vtk-5.0/testing/HeaderTesting.py
%{root}/lib/vtk-5.0/testing/prtImageTest.tcl
%{root}/lib/vtk-5.0/testing/FindString.tcl
%{root}/lib/vtk-5.0/vtkImagingKit.cmake
%{root}/lib/vtk-5.0/vtkCommonKit.cmake
%{root}/lib/vtk-5.0/vtkGraphicsKit.cmake
%{root}/lib/vtk-5.0/VTKLibraryDepends.cmake
%{root}/lib/vtk-5.0/vtkFilteringKit.cmake
%{root}/lib/vtk-5.0/vtkParallelKit.cmake
%{root}/lib/vtk-5.0/vtkHybridKit.cmake
%{root}/lib/vtk-5.0/vtkWidgetsKit.cmake
%{root}/lib/vtk-5.0/vtkRenderingKit.cmake
%{root}/lib/vtk-5.0/VTKConfig.cmake
%{root}/lib/vtk-5.0/vtkVolumeRenderingKit.cmake
%{root}/lib/vtk-5.0/UseVTK.cmake
%{root}/lib/libvtkParallel.so.5.0.2
%{root}/lib/libvtkexoIIc.so.5.0.2
%{root}/lib/libvtkpng.so.5.0.2
%{root}/include/vtk-5.0/vtkImageIdealHighPass.h
%{root}/include/vtk-5.0/vtkOpenGLExtensionManager.h
%{root}/include/vtk-5.0/vtkUnstructuredGridVolumeMapper.h
%{root}/include/vtk-5.0/vtkUnstructuredGridPreIntegration.h
%{root}/include/vtk-5.0/vtkImageTracerWidget.h
%{root}/include/vtk-5.0/vtkCleanPolyData.h
%{root}/include/vtk-5.0/vtkPOutlineFilter.h
%{root}/include/vtk-5.0/vtkImagePadFilter.h
%{root}/include/vtk-5.0/vtkParametricConicSpiral.h
%{root}/include/vtk-5.0/vtkPolyDataNormals.h
%{root}/include/vtk-5.0/vtkSmoothPolyDataFilter.h
%{root}/include/vtk-5.0/vtkStdString.h
%{root}/include/vtk-5.0/vtkDataSetToDataObjectFilter.h
%{root}/include/vtk-5.0/vtkEnSightReader.h
%{root}/include/vtk-5.0/vtkProbeFilter.h
%{root}/include/vtk-5.0/vtkInformationInformationVectorKey.h
%{root}/include/vtk-5.0/vtkThresholdPoints.h
%{root}/include/vtk-5.0/vtkEnSightWriter.h
%{root}/include/vtk-5.0/vtkInformationVector.h
%{root}/include/vtk-5.0/vtkFunctionParser.h
%{root}/include/vtk-5.0/vtkPolyDataSourceWidget.h
%{root}/include/vtk-5.0/vtkDataSet.h
%{root}/include/vtk-5.0/vtkSliceCubes.h
%{root}/include/vtk-5.0/vtkExtractGrid.h
%{root}/include/vtk-5.0/vtkMetaImageReader.h
%{root}/include/vtk-5.0/vtkImageConstantPad.h
%{root}/include/vtk-5.0/vtkQuadraticTetra.h
%{root}/include/vtk-5.0/vtkArcPlotter.h
%{root}/include/vtk-5.0/vtkDebugLeaksManager.h
%{root}/include/vtk-5.0/vtkInputStream.h
%{root}/include/vtk-5.0/vtkBase64OutputStream.h
%{root}/include/vtk-5.0/vtkMetaImageWriter.h
%{root}/include/vtk-5.0/vtkImageLuminance.h
%{root}/include/vtk-5.0/vtkMatrixToHomogeneousTransform.h
%{root}/include/vtk-5.0/vtkGenericMovieWriter.h
%{root}/include/vtk-5.0/vtkPointLoad.h
%{root}/include/vtk-5.0/vtkParametricBoy.h
%{root}/include/vtk-5.0/vtkIdentityTransform.h
%{root}/include/vtk-5.0/vtkRegressionTestImage.h
%{root}/include/vtk-5.0/vtkPiecewiseFunction.h
%{root}/include/vtk-5.0/vtkScalarsToColors.h
%{root}/include/vtk-5.0/vtkRectilinearGridAlgorithm.h
%{root}/include/vtk-5.0/vtkInteractorStyleTrackballCamera.h
%{root}/include/vtk-5.0/vtkStructuredPointsSource.h
%{root}/include/vtk-5.0/vtkHierarchicalBoxDataSet.h
%{root}/include/vtk-5.0/vtkSTLReader.h
%{root}/include/vtk-5.0/vtkBranchExtentTranslator.h
%{root}/include/vtk-5.0/vtkPointSetSource.h
%{root}/include/vtk-5.0/vtkSelectVisiblePoints.h
%{root}/include/vtk-5.0/vtkProcessObject.h
%{root}/include/vtk-5.0/vtkPropAssembly.h
%{root}/include/vtk-5.0/vtkCellType.h
%{root}/include/vtk-5.0/vtkZLibDataCompressor.h
%{root}/include/vtk-5.0/vtkOpenGLCamera.h
%{root}/include/vtk-5.0/vtkLODProp3D.h
%{root}/include/vtk-5.0/vtkSTLWriter.h
%{root}/include/vtk-5.0/vtkRTAnalyticSource.h
%{root}/include/vtk-5.0/vtkSimpleElevationFilter.h
%{root}/include/vtk-5.0/vtk_freetype.h
%{root}/include/vtk-5.0/vtkParametricRoman.h
%{root}/include/vtk-5.0/vtkFunctionSet.h
%{root}/include/vtk-5.0/vtkImageMultipleInputOutputFilter.h
%{root}/include/vtk-5.0/vtkCellCenterDepthSort.h
%{root}/include/vtk-5.0/vtkImageEuclideanToPolar.h
%{root}/include/vtk-5.0/vtkVertex.h
%{root}/include/vtk-5.0/vtkWorldPointPicker.h
%{root}/include/vtk-5.0/vtkUGFacetReader.h
%{root}/include/vtk-5.0/vtkQuadraticQuad.h
%{root}/include/vtk-5.0/vtkUnstructuredGridVolumeRayCastFunction.h
%{root}/include/vtk-5.0/vtkStringArray.h
%{root}/include/vtk-5.0/vtkRIBLight.h
%{root}/include/vtk-5.0/vtkClipPolyData.h
%{root}/include/vtk-5.0/vtkWarpTo.h
%{root}/include/vtk-5.0/vtkBitArray.h
%{root}/include/vtk-5.0/vtkJPEGReader.h
%{root}/include/vtk-5.0/vtkImageStencilData.h
%{root}/include/vtk-5.0/vtkParametricEnneper.h
%{root}/include/vtk-5.0/vtkCardinalSpline.h
%{root}/include/vtk-5.0/vtkImageIterator.h
%{root}/include/vtk-5.0/vtkRenderWindowCollection.h
%{root}/include/vtk-5.0/vtkImageDivergence.h
%{root}/include/vtk-5.0/vtkRecursiveDividingCubes.h
%{root}/include/vtk-5.0/vtkJPEGWriter.h
%{root}/include/vtk-5.0/vtkAnnotatedCubeActor.h
%{root}/include/vtk-5.0/vtkStructuredGridAlgorithm.h
%{root}/include/vtk-5.0/vtkImageDilateErode3D.h
%{root}/include/vtk-5.0/vtkSmoothErrorMetric.h
%{root}/include/vtk-5.0/vtkCastToConcrete.h
%{root}/include/vtk-5.0/vtkImageMathematics.h
%{root}/include/vtk-5.0/vtkPDBReader.h
%{root}/include/vtk-5.0/vtkMutexLock.h
%{root}/include/vtk-5.0/vtkImplicitWindowFunction.h
%{root}/include/vtk-5.0/vtkSpherePuzzleArrows.h
%{root}/include/vtk-5.0/vtkVRMLImporter.h
%{root}/include/vtk-5.0/vtkSphericalDirectionEncoder.h
%{root}/include/vtk-5.0/vtkGenericDataSetTessellator.h
%{root}/include/vtk-5.0/vtkPolyDataToImageStencil.h
%{root}/include/vtk-5.0/vtkPerlinNoise.h
%{root}/include/vtk-5.0/vtkCaptionActor2D.h
%{root}/include/vtk-5.0/vtkTimeStamp.h
%{root}/include/vtk-5.0/vtkImageGaussianSmooth.h
%{root}/include/vtk-5.0/vtkBYUReader.h
%{root}/include/vtk-5.0/vtkImageGradient.h
%{root}/include/vtk-5.0/vtkByteSwap.h
%{root}/include/vtk-5.0/vtkInteractorStyleUnicam.h
%{root}/include/vtk-5.0/vtkOBBDicer.h
%{root}/include/vtk-5.0/vtkDataSetToPolyDataFilter.h
%{root}/include/vtk-5.0/vtkImageProgressIterator.h
%{root}/include/vtk-5.0/vtkIOStreamFwd.h
%{root}/include/vtk-5.0/vtkDataObjectSource.h
%{root}/include/vtk-5.0/vtkImageConnector.h
%{root}/include/vtk-5.0/vtkBYUWriter.h
%{root}/include/vtk-5.0/vtkRenderer.h
%{root}/include/vtk-5.0/vtkLandmarkTransform.h
%{root}/include/vtk-5.0/vtkXMLWriterC.h
%{root}/include/vtk-5.0/vtkPyramid.h
%{root}/include/vtk-5.0/vtkXMLPPolyDataReader.h
%{root}/include/vtk-5.0/vtkPlatonicSolidSource.h
%{root}/include/vtk-5.0/vtkPlaneCollection.h
%{root}/include/vtk-5.0/vtkToolkits.h
%{root}/include/vtk-5.0/vtkConvexPointSet.h
%{root}/include/vtk-5.0/vtkGenericCell.h
%{root}/include/vtk-5.0/vtkTextSource.h
%{root}/include/vtk-5.0/vtkBooleanTexture.h
%{root}/include/vtk-5.0/vtkPolyVertex.h
%{root}/include/vtk-5.0/vtkXMLPPolyDataWriter.h
%{root}/include/vtk-5.0/vtkPolyDataCollection.h
%{root}/include/vtk-5.0/vtkSocketController.h
%{root}/include/vtk-5.0/vtkGraphicsInstantiator.h
%{root}/include/vtk-5.0/vtkImageCheckerboard.h
%{root}/include/vtk-5.0/vtkGenericFilteringInstantiator.h
%{root}/include/vtk-5.0/vtkImplicitBoolean.h
%{root}/include/vtk-5.0/vtkMergeCells.h
%{root}/include/vtk-5.0/vtkXMLPStructuredDataReader.h
%{root}/include/vtk-5.0/vtkGenericClip.h
%{root}/include/vtk-5.0/vtkCellPicker.h
%{root}/include/vtk-5.0/vtkAxesActor.h
%{root}/include/vtk-5.0/vtkImageMarchingCubes.h
%{root}/include/vtk-5.0/vtkUnstructuredGridAlgorithm.h
%{root}/include/vtk-5.0/vtkPChacoReader.h
%{root}/include/vtk-5.0/vtkCornerAnnotation.h
%{root}/include/vtk-5.0/vtkIterativeClosestPointTransform.h
%{root}/include/vtk-5.0/vtkWedge.h
%{root}/include/vtk-5.0/vtkXMLPStructuredDataWriter.h
%{root}/include/vtk-5.0/vtkGenericContourFilter.h
%{root}/include/vtk-5.0/vtkDataSetAttributes.h
%{root}/include/vtk-5.0/vtkImageSource.h
%{root}/include/vtk-5.0/vtkCollectPolyData.h
%{root}/include/vtk-5.0/vtkPKdTree.h
%{root}/include/vtk-5.0/vtkHexagonalPrism.h
%{root}/include/vtk-5.0/vtkSplineFilter.h
%{root}/include/vtk-5.0/vtkImageDotProduct.h
%{root}/include/vtk-5.0/vtkOOGLExporter.h
%{root}/include/vtk-5.0/vtkOBBTree.h
%{root}/include/vtk-5.0/vtkXMLUtilities.h
%{root}/include/vtk-5.0/vtkVoxel.h
%{root}/include/vtk-5.0/vtkExtractRectilinearGrid.h
%{root}/include/vtk-5.0/vtkGenericRenderWindowInteractor.h
%{root}/include/vtk-5.0/vtkStructuredPointsGeometryFilter.h
%{root}/include/vtk-5.0/vtkSimpleCellTessellator.h
%{root}/include/vtk-5.0/vtkEnSight6Reader.h
%{root}/include/vtk-5.0/vtkRIBProperty.h
%{root}/include/vtk-5.0/vtkTextureMapToSphere.h
%{root}/include/vtk-5.0/vtkInformationObjectBaseKey.h
%{root}/include/vtk-5.0/vtkVolumeCollection.h
%{root}/include/vtk-5.0/vtkExtractTensorComponents.h
%{root}/include/vtk-5.0/vtkOpenGLRayCastImageDisplayHelper.h
%{root}/include/vtk-5.0/vtkPipelineSize.h
%{root}/include/vtk-5.0/vtkUnstructuredGridBunykRayCastFunction.h
%{root}/include/vtk-5.0/vtkImageSpatialFilter.h
%{root}/include/vtk-5.0/vtk3DWidget.h
%{root}/include/vtk-5.0/vtkCellLinks.h
%{root}/include/vtk-5.0/vtkImageImportExecutive.h
%{root}/include/vtk-5.0/vtkStructuredData.h
%{root}/include/vtk-5.0/vtkFixedPointVolumeRayCastMIPHelper.h
%{root}/include/vtk-5.0/vtkLegendBoxActor.h
%{root}/include/vtk-5.0/vtkAssembly.h
%{root}/include/vtk-5.0/vtkGenericProbeFilter.h
%{root}/include/vtk-5.0/vtkWindow.h
%{root}/include/vtk-5.0/vtkInformationKey.h
%{root}/include/vtk-5.0/vtkStructuredGridToStructuredGridFilter.h
%{root}/include/vtk-5.0/vtkCommonInstantiator.h
%{root}/include/vtk-5.0/vtkImplicitFunction.h
%{root}/include/vtk-5.0/vtkPolyDataStreamer.h
%{root}/include/vtk-5.0/vtkXMLPImageDataReader.h
%{root}/include/vtk-5.0/vtkPolyDataMapper2D.h
%{root}/include/vtk-5.0/vtkInformationKeyVectorKey.h
%{root}/include/vtk-5.0/vtkPDataSetReader.h
%{root}/include/vtk-5.0/vtkMatrixToLinearTransform.h
%{root}/include/vtk-5.0/vtkPostScriptWriter.h
%{root}/include/vtk-5.0/vtkXMLPImageDataWriter.h
%{root}/include/vtk-5.0/vtkImageStencil.h
%{root}/include/vtk-5.0/vtkPDataSetWriter.h
%{root}/include/vtk-5.0/vtkUnstructuredGridVolumeZSweepMapper.h
%{root}/include/vtk-5.0/vtkEarthSource.h
%{root}/include/vtk-5.0/vtkDataObjectToDataSetFilter.h
%{root}/include/vtk-5.0/vtkPixel.h
%{root}/include/vtk-5.0/vtkImageMaskBits.h
%{root}/include/vtk-5.0/vtkImageRGBToHSI.h
%{root}/include/vtk-5.0/vtkImageRGBToHSV.h
%{root}/include/vtk-5.0/vtkBlankStructuredGridWithImage.h
%{root}/include/vtk-5.0/vtkFastNumericConversion.h
%{root}/include/vtk-5.0/vtkBMPReader.h
%{root}/include/vtk-5.0/vtkImageChangeInformation.h
%{root}/include/vtk-5.0/vtkUnsignedIntArray.h
%{root}/include/vtk-5.0/vtkFixedPointVolumeRayCastHelper.h
%{root}/include/vtk-5.0/vtkRenderLargeImage.h
%{root}/include/vtk-5.0/vtkImageBlend.h
%{root}/include/vtk-5.0/vtkVolumeReader.h
%{root}/include/vtk-5.0/vtkRungeKutta2.h
%{root}/include/vtk-5.0/vtkRungeKutta4.h
%{root}/include/vtk-5.0/vtkBMPWriter.h
%{root}/include/vtk-5.0/vtkImageNoiseSource.h
%{root}/include/vtk-5.0/vtkFloatArray.h
%{root}/include/vtk-5.0/vtkPlane.h
%{root}/include/vtk-5.0/vtkImplicitVolume.h
%{root}/include/vtk-5.0/vtkImageOpenClose3D.h
%{root}/include/vtk-5.0/vtkVideoSource.h
%{root}/include/vtk-5.0/vtkOpenGL.h
%{root}/include/vtk-5.0/vtkHybridInstantiator.h
%{root}/include/vtk-5.0/vtkDynamicLoader.h
%{root}/include/vtk-5.0/DICOMParserMap.h
%{root}/include/vtk-5.0/vtkExecutive.h
%{root}/include/vtk-5.0/vtkVolume16Reader.h
%{root}/include/vtk-5.0/vtkDICOMImageReader.h
%{root}/include/vtk-5.0/vtkQuadraticTriangle.h
%{root}/include/vtk-5.0/vtkXYZMolReader.h
%{root}/include/vtk-5.0/vtkParallelRenderManager.h
%{root}/include/vtk-5.0/vtkTriangularTexture.h
%{root}/include/vtk-5.0/vtkXMLRectilinearGridReader.h
%{root}/include/vtk-5.0/vtkFixedPointVolumeRayCastCompositeHelper.h
%{root}/include/vtk-5.0/vtkEllipticalButtonSource.h
%{root}/include/vtk-5.0/vtkProjectedTetrahedraMapper.h
%{root}/include/vtk-5.0/vtkProgrammableGlyphFilter.h
%{root}/include/vtk-5.0/vtkPolyDataSource.h
%{root}/include/vtk-5.0/vtkStructuredGridToPolyDataFilter.h
%{root}/include/vtk-5.0/vtkXMLDataParser.h
%{root}/include/vtk-5.0/vtkStructuredGrid.h
%{root}/include/vtk-5.0/vtkObject.h
%{root}/include/vtk-5.0/vtkMatrix4x4.h
%{root}/include/vtk-5.0/vtkXMLRectilinearGridWriter.h
%{root}/include/vtk-5.0/vtkStreamTracer.h
%{root}/include/vtk-5.0/vtkCubeSource.h
%{root}/include/vtk-5.0/vtkStructuredGridOutlineFilter.h
%{root}/include/vtk-5.0/vtkImplicitSelectionLoop.h
%{root}/include/vtk-5.0/vtkRungeKutta45.h
%{root}/include/vtk-5.0/vtkImageDecomposeFilter.h
%{root}/include/vtk-5.0/vtkGlyph2D.h
%{root}/include/vtk-5.0/vtkGlyph3D.h
%{root}/include/vtk-5.0/vtkCurvatures.h
%{root}/include/vtk-5.0/vtkMedicalImageReader2.h
%{root}/include/vtk-5.0/vtkProgrammableAttributeDataFilter.h
%{root}/include/vtk-5.0/vtkCellDataToPointData.h
%{root}/include/vtk-5.0/vtkGenericAttribute.h
%{root}/include/vtk-5.0/vtkParallelInstantiator.h
%{root}/include/vtk-5.0/vtkInstantiator.h
%{root}/include/vtk-5.0/vtkPLYReader.h
%{root}/include/vtk-5.0/vtkInteractorStyleSwitch.h
%{root}/include/vtk-5.0/vtkSetGet.h
%{root}/include/vtk-5.0/vtkStructuredGridReader.h
%{root}/include/vtk-5.0/vtkReferenceCount.h
%{root}/include/vtk-5.0/vtkBSPIntersections.h
%{root}/include/vtk-5.0/vtkPLYWriter.h
%{root}/include/vtk-5.0/vtkStructuredGridWriter.h
%{root}/include/vtk-5.0/vtkImagingFactory.h
%{root}/include/vtk-5.0/vtkCellCenters.h
%{root}/include/vtk-5.0/vtkIdListCollection.h
%{root}/include/vtk-5.0/vtkImageTwoInputFilter.h
%{root}/include/vtk-5.0/vtkImageSpatialAlgorithm.h
%{root}/include/vtk-5.0/vtkPointSource.h
%{root}/include/vtk-5.0/vtkHierarchicalDataLevelFilter.h
%{root}/include/vtk-5.0/vtkSplineWidget.h
%{root}/include/vtk-5.0/vtkPlanes.h
%{root}/include/vtk-5.0/vtkImageLogarithmicScale.h
%{root}/include/vtk-5.0/vtkImageHybridMedian2D.h
%{root}/include/vtk-5.0/vtkInformationDoubleKey.h
%{root}/include/vtk-5.0/vtkTexturedSphereSource.h
%{root}/include/vtk-5.0/vtkExtractPolyDataPiece.h
%{root}/include/vtk-5.0/vtkUniformGrid.h
%{root}/include/vtk-5.0/vtkTransmitUnstructuredGridPiece.h
%{root}/include/vtk-5.0/vtkInteractorStyleJoystickCamera.h
%{root}/include/vtk-5.0/vtkHierarchicalDataExtractLevel.h
%{root}/include/vtk-5.0/vtkDataArrayTemplate.txx
%{root}/include/vtk-5.0/vtkColorTransferFunction.h
%{root}/include/vtk-5.0/vtkUnsignedShortArray.h
%{root}/include/vtk-5.0/vtkDataSetSource.h
%{root}/include/vtk-5.0/vtkTableExtentTranslator.h
%{root}/include/vtk-5.0/vtkCompositer.h
%{root}/include/vtk-5.0/vtkCursor3D.h
%{root}/include/vtk-5.0/vtkGarbageCollectorManager.h
%{root}/include/vtk-5.0/vtkHierarchicalDataInformation.h
%{root}/include/vtk-5.0/vtkAxes.h
%{root}/include/vtk-5.0/vtkDummyController.h
%{root}/include/vtk-5.0/vtkErrorCode.h
%{root}/include/vtk-5.0/vtkXMLPUnstructuredDataReader.h
%{root}/include/vtk-5.0/vtkFacetReader.h
%{root}/include/vtk-5.0/vtkCell.h
%{root}/include/vtk-5.0/vtkMarchingContourFilter.h
%{root}/include/vtk-5.0/vtkPlanesIntersection.h
%{root}/include/vtk-5.0/vtkInteractorStyleTrackballActor.h
%{root}/include/vtk-5.0/vtkPiecewiseFunctionAlgorithm.h
%{root}/include/vtk-5.0/vtkStructuredPointsToPolyDataFilter.h
%{root}/include/vtk-5.0/vtkXMLPUnstructuredDataWriter.h
%{root}/include/vtk-5.0/vtkFacetWriter.h
%{root}/include/vtk-5.0/vtkParametricEllipsoid.h
%{root}/include/vtk-5.0/vtkShepardMethod.h
%{root}/include/vtk-5.0/vtkGraphicsFactory.h
%{root}/include/vtk-5.0/vtkCompressCompositer.h
%{root}/include/vtk-5.0/vtkEnSightGoldReader.h
%{root}/include/vtk-5.0/vtkCone.h
%{root}/include/vtk-5.0/vtkInformationStringKey.h
%{root}/include/vtk-5.0/vtkExtentTranslator.h
%{root}/include/vtk-5.0/vtkIndent.h
%{root}/include/vtk-5.0/vtkImplicitSum.h
%{root}/include/vtk-5.0/vtkImagePlaneWidget.h
%{root}/include/vtk-5.0/vtkOverrideInformation.h
%{root}/include/vtk-5.0/vtkContourFilter.h
%{root}/include/vtk-5.0/vtkStructuredPoints.h
%{root}/include/vtk-5.0/vtkSimplePointsReader.h
%{root}/include/vtk-5.0/vtkInformationIntegerPointerKey.h
%{root}/include/vtk-5.0/vtkRectilinearGridReader.h
%{root}/include/vtk-5.0/vtkThreshold.h
%{root}/include/vtk-5.0/vtkBase64Utilities.h
%{root}/include/vtk-5.0/vtkDataArrayTemplateImplicit.txx
%{root}/include/vtk-5.0/vtkMPEG2Writer.h
%{root}/include/vtk-5.0/vtkTIFFReader.h
%{root}/include/vtk-5.0/vtkRectilinearGridWriter.h
%{root}/include/vtk-5.0/vtkXMLPolyDataReader.h
%{root}/include/vtk-5.0/vtkOpenGLLight.h
%{root}/include/vtk-5.0/vtkSphericalTransform.h
%{root}/include/vtk-5.0/vtkEncodedGradientEstimator.h
%{root}/include/vtk-5.0/vtkSubGroup.h
%{root}/include/vtk-5.0/vtkTIFFWriter.h
%{root}/include/vtk-5.0/vtkImageButterworthLowPass.h
%{root}/include/vtk-5.0/vtkXMLPolyDataWriter.h
%{root}/include/vtk-5.0/vtkSplitField.h
%{root}/include/vtk-5.0/vtkTupleInterpolator.h
%{root}/include/vtk-5.0/vtkIVExporter.h
%{root}/include/vtk-5.0/vtkProp3D.h
%{root}/include/vtk-5.0/vtkImageToPolyDataFilter.h
%{root}/include/vtk-5.0/vtkWeightedTransformFilter.h
%{root}/include/vtk-5.0/vtkImageGradientMagnitude.h
%{root}/include/vtk-5.0/vtkImageAppendComponents.h
%{root}/include/vtk-5.0/vtkTriangularTCoords.h
%{root}/include/vtk-5.0/vtkUnstructuredGridToUnstructuredGridFilter.h
%{root}/include/vtk-5.0/vtkRectilinearGridOutlineFilter.h
%{root}/include/vtk-5.0/vtkImageDifference.h
%{root}/include/vtk-5.0/vtkImagePermute.h
%{root}/include/vtk-5.0/vtkStripper.h
%{root}/include/vtk-5.0/vtkCylinderSource.h
%{root}/include/vtk-5.0/vtkTextMapper.h
%{root}/include/vtk-5.0/vtkImageCursor3D.h
%{root}/include/vtk-5.0/vtkInformationInformationKey.h
%{root}/include/vtk-5.0/vtkDataArrayTemplate.h
%{root}/include/vtk-5.0/vtkRectilinearGridClip.h
%{root}/include/vtk-5.0/vtkBoxWidget.h
%{root}/include/vtk-5.0/vtkOrderedTriangulator.h
%{root}/include/vtk-5.0/vtkImageViewer2.h
%{root}/include/vtk-5.0/vtkRectilinearSynchronizedTemplates.h
%{root}/include/vtk-5.0/vtkPointPicker.h
%{root}/include/vtk-5.0/vtkImageMapper.h
%{root}/include/vtk-5.0/vtkEdgePoints.h
%{root}/include/vtk-5.0/vtkAnimationScene.h
%{root}/include/vtk-5.0/vtkDiskSource.h
%{root}/include/vtk-5.0/vtkSimpleScalarTree.h
%{root}/include/vtk-5.0/vtkMoleculeReaderBase.h
%{root}/include/vtk-5.0/vtkParametricTorus.h
%{root}/include/vtk-5.0/vtkImageTranslateExtent.h
%{root}/include/vtk-5.0/vtkProgrammableDataObjectSource.h
%{root}/include/vtk-5.0/vtkHeap.h
%{root}/include/vtk-5.0/vtkParametricCrossCap.h
%{root}/include/vtk-5.0/vtkStructuredPointsCollection.h
%{root}/include/vtk-5.0/vtkImageAppend.h
%{root}/include/vtk-5.0/vtkLightKit.h
%{root}/include/vtk-5.0/vtkImageIslandRemoval2D.h
%{root}/include/vtk-5.0/vtkRotationalExtrusionFilter.h
%{root}/include/vtk-5.0/vtkIOStream.h
%{root}/include/vtk-5.0/vtkImageSeedConnectivity.h
%{root}/include/vtk-5.0/vtkImageDataGeometryFilter.h
%{root}/include/vtk-5.0/vtkAVSucdReader.h
%{root}/include/vtk-5.0/vtkXMLFileOutputWindow.h
%{root}/include/vtk-5.0/vtkCutMaterial.h
%{root}/include/vtk-5.0/vtkOutlineCornerSource.h
%{root}/include/vtk-5.0/vtkUnstructuredGridHomogeneousRayIntegrator.h
%{root}/include/vtk-5.0/vtkAppendFilter.h
%{root}/include/vtk-5.0/vtkSampleFunction.h
%{root}/include/vtk-5.0/vtk_jpeg.h
%{root}/include/vtk-5.0/vtkThresholdTextureCoords.h
%{root}/include/vtk-5.0/vtkCallbackCommand.h
%{root}/include/vtk-5.0/vtkSynchronizedTemplates2D.h
%{root}/include/vtk-5.0/vtkSynchronizedTemplates3D.h
%{root}/include/vtk-5.0/DICOMFile.h
%{root}/include/vtk-5.0/vtkRectilinearGridToPolyDataFilter.h
%{root}/include/vtk-5.0/vtkActorCollection.h
%{root}/include/vtk-5.0/vtkHull.h
%{root}/include/vtk-5.0/vtkExtractVOI.h
%{root}/include/vtk-5.0/vtkParametricSpline.h
%{root}/include/vtk-5.0/vtkParametricSuperEllipsoid.h
%{root}/include/vtk-5.0/vtkXMLParser.h
%{root}/include/vtk-5.0/vtkHexahedron.h
%{root}/include/vtk-5.0/vtkParallelFactory.h
%{root}/include/vtk-5.0/vtkImageRange3D.h
%{root}/include/vtk-5.0/vtkCachedStreamingDemandDrivenPipeline.h
%{root}/include/vtk-5.0/vtkParallelCoordinatesActor.h
%{root}/include/vtk-5.0/vtkCylinder.h
%{root}/include/vtk-5.0/vtkFieldData.h
%{root}/include/vtk-5.0/vtkArrayCalculator.h
%{root}/include/vtk-5.0/DICOMCallback.h
%{root}/include/vtk-5.0/vtkPLOT3DReader.h
%{root}/include/vtk-5.0/vtkAbstractMapper3D.h
%{root}/include/vtk-5.0/vtkSubPixelPositionEdgels.h
%{root}/include/vtk-5.0/vtkImageToImageFilter.h
%{root}/include/vtk-5.0/vtkPlaneSource.h
%{root}/include/vtk-5.0/vtkImageSeparableConvolution.h
%{root}/include/vtk-5.0/vtkGenericGlyph3DFilter.h
%{root}/include/vtk-5.0/vtkImporter.h
%{root}/include/vtk-5.0/vtkParametricRandomHills.h
%{root}/include/vtk-5.0/vtkRendererCollection.h
%{root}/include/vtk-5.0/vtkBase64InputStream.h
%{root}/include/vtk-5.0/vtkDataSetTriangleFilter.h
%{root}/include/vtk-5.0/vtkOpenGLRenderer.h
%{root}/include/vtk-5.0/vtkPSphereSource.h
%{root}/include/vtk-5.0/DICOMTypes.h
%{root}/include/vtk-5.0/vtkFixedPointRayCastImage.h
%{root}/include/vtk-5.0/vtkGreedyTerrainDecimation.h
%{root}/include/vtk-5.0/vtkObjectBase.h
%{root}/include/vtk-5.0/vtkLargeInteger.h
%{root}/include/vtk-5.0/vtkImageToImageStencil.h
%{root}/include/vtk-5.0/vtkPriorityQueue.h
%{root}/include/vtk-5.0/vtkCommunicator.h
%{root}/include/vtk-5.0/vtkParametricMobius.h
%{root}/include/vtk-5.0/vtkBoxClipDataSet.h
%{root}/include/vtk-5.0/vtkCubeAxesActor2D.h
%{root}/include/vtk-5.0/vtkSuperquadric.h
%{root}/include/vtk-5.0/vtkImageStencilSource.h
%{root}/include/vtk-5.0/vtkConfigure.h
%{root}/include/vtk-5.0/vtkDicer.h
%{root}/include/vtk-5.0/vtkLine.h
%{root}/include/vtk-5.0/vtkTransformPolyDataFilter.h
%{root}/include/vtk-5.0/vtkGenericAttributeCollection.h
%{root}/include/vtk-5.0/vtkEventForwarderCommand.h
%{root}/include/vtk-5.0/vtkEdgeTable.h
%{root}/include/vtk-5.0/vtkPNGReader.h
%{root}/include/vtk-5.0/vtkImageSinusoidSource.h
%{root}/include/vtk-5.0/vtkImageMapToColors.h
%{root}/include/vtk-5.0/vtkMath.h
%{root}/include/vtk-5.0/vtkMapperCollection.h
%{root}/include/vtk-5.0/vtkPolyDataToPolyDataFilter.h
%{root}/include/vtk-5.0/vtkPNGWriter.h
%{root}/include/vtk-5.0/vtkChacoReader.h
%{root}/include/vtk-5.0/vtkParticleReader.h
%{root}/include/vtk-5.0/vtkImagingInstantiator.h
%{root}/include/vtk-5.0/vtkSynchronizedTemplatesCutter3D.h
%{root}/include/vtk-5.0/vtkImageShrink3D.h
%{root}/include/vtk-5.0/vtkAbstractPicker.h
%{root}/include/vtk-5.0/vtkStreamLine.h
%{root}/include/vtk-5.0/vtk3DSImporter.h
%{root}/include/vtk-5.0/vtkShrinkPolyData.h
%{root}/include/vtk-5.0/vtkFeatureEdges.h
%{root}/include/vtk-5.0/vtkIVWriter.h
%{root}/include/vtk-5.0/vtkXMLImageDataReader.h
%{root}/include/vtk-5.0/vtkAbstractPropPicker.h
%{root}/include/vtk-5.0/vtkBrownianPoints.h
%{root}/include/vtk-5.0/vtkFilteringInformationKeyManager.h
%{root}/include/vtk-5.0/vtkVolume.h
%{root}/include/vtk-5.0/vtkWriter.h
%{root}/include/vtk-5.0/vtkPolyDataMapper.h
%{root}/include/vtk-5.0/vtkGridSynchronizedTemplates3D.h
%{root}/include/vtk-5.0/vtkPointDataToCellData.h
%{root}/include/vtk-5.0/vtkAMRBox.h
%{root}/include/vtk-5.0/vtkDecimatePro.h
%{root}/include/vtk-5.0/vtkParametricFunctionSource.h
%{root}/include/vtk-5.0/vtkCriticalSection.h
%{root}/include/vtk-5.0/vtkLODActor.h
%{root}/include/vtk-5.0/vtkXMLImageDataWriter.h
%{root}/include/vtk-5.0/vtkProperty.h
%{root}/include/vtk-5.0/vtkQuadraticWedge.h
%{root}/include/vtk-5.0/vtkImageExtractComponents.h
%{root}/include/vtk-5.0/vtkVRMLExporter.h
%{root}/include/vtk-5.0/vtkStructuredPointsToUnstructuredGridFilter.h
%{root}/include/vtk-5.0/vtkGenericDataSet.h
%{root}/include/vtk-5.0/vtkSimpleImageFilterExample.h
%{root}/include/vtk-5.0/vtkAbstractVolumeMapper.h
%{root}/include/vtk-5.0/vtkParametricDini.h
%{root}/include/vtk-5.0/vtkInteractorObserver.h
%{root}/include/vtk-5.0/vtkPCAAnalysisFilter.h
%{root}/include/vtk-5.0/vtkImageMirrorPad.h
%{root}/include/vtk-5.0/vtkAxisActor2D.h
%{root}/include/vtk-5.0/vtkRIBExporter.h
%{root}/include/vtk-5.0/vtkProgrammableSource.h
%{root}/include/vtk-5.0/vtkProjectedTerrainPath.h
%{root}/include/vtk-5.0/vtkImplicitDataSet.h
%{root}/include/vtk-5.0/vtkTransform.h
%{root}/include/vtk-5.0/vtkPolygon.h
%{root}/include/vtk-5.0/vtkCompositeDataIterator.h
%{root}/include/vtk-5.0/vtkImageIterateFilter.h
%{root}/include/vtk-5.0/vtkTransmitPolyDataPiece.h
%{root}/include/vtk-5.0/vtkVolumeRayCastFunction.h
%{root}/include/vtk-5.0/vtkImageGaussianSource.h
%{root}/include/vtk-5.0/vtkImageCast.h
%{root}/include/vtk-5.0/vtkTexture.h
%{root}/include/vtk-5.0/vtkProcrustesAlignmentFilter.h
%{root}/include/vtk-5.0/vtkRendererSource.h
%{root}/include/vtk-5.0/vtkRenderWindowInteractor.h
%{root}/include/vtk-5.0/vtkTypeInt64Array.h
%{root}/include/vtk-5.0/vtkQuadricDecimation.h
%{root}/include/vtk-5.0/vtkProp.h
%{root}/include/vtk-5.0/vtkImageAlgorithm.h
%{root}/include/vtk-5.0/vtkExtractUnstructuredGridPiece.h
%{root}/include/vtk-5.0/vtkDataObject.h
%{root}/include/vtk-5.0/vtkImageClip.h
%{root}/include/vtk-5.0/vtkGarbageCollector.h
%{root}/include/vtk-5.0/vtkImageData.h
%{root}/include/vtk-5.0/vtkMeshQuality.h
%{root}/include/vtk-5.0/vtkRotationFilter.h
%{root}/include/vtk-5.0/vtkScalarBarWidget.h
%{root}/include/vtk-5.0/vtkWindowLevelLookupTable.h
%{root}/include/vtk-5.0/vtkLocator.h
%{root}/include/vtk-5.0/vtkVisibilitySort.h
%{root}/include/vtk-5.0/vtkGraphLayoutFilter.h
%{root}/include/vtk-5.0/vtkWarpTransform.h
%{root}/include/vtk-5.0/vtkCollection.h
%{root}/include/vtk-5.0/vtkQuad.h
%{root}/include/vtk-5.0/vtkTextureMapToCylinder.h
%{root}/include/vtk-5.0/vtkInteractorStyleJoystickActor.h
%{root}/include/vtk-5.0/vtk_tiff.h
%{root}/include/vtk-5.0/vtkInteractorStyleTrackball.h
%{root}/include/vtk-5.0/vtkDataSetToStructuredGridFilter.h
%{root}/include/vtk-5.0/vtkDataSetMapper.h
%{root}/include/vtk-5.0/vtkFrustumCoverageCuller.h
%{root}/include/vtk-5.0/vtkClipVolume.h
%{root}/include/vtk-5.0/vtkOpenGLTexture.h
%{root}/include/vtk-5.0/vtkAttributeDataToFieldDataFilter.h
%{root}/include/vtk-5.0/vtkLongLongArray.h
%{root}/include/vtk-5.0/vtkDataArray.h
%{root}/include/vtk-5.0/vtkCellLocator.h
%{root}/include/vtk-5.0/vtkDataSetToUnstructuredGridFilter.h
%{root}/include/vtk-5.0/vtkPerspectiveTransform.h
%{root}/include/vtk-5.0/vtkDepthSortPolyData.h
%{root}/include/vtk-5.0/vtkXMLStructuredGridReader.h
%{root}/include/vtk-5.0/vtkOStreamWrapper.h
%{root}/include/vtk-5.0/vtkSmartPointerBase.h
%{root}/include/vtk-5.0/vtk_expat.h
%{root}/include/vtk-5.0/vtkButtonSource.h
%{root}/include/vtk-5.0/vtkQuaternionInterpolator.h
%{root}/include/vtk-5.0/vtkCompositeRenderManager.h
%{root}/include/vtk-5.0/vtkImageEllipsoidSource.h
%{root}/include/vtk-5.0/vtkInteractorStyle.h
%{root}/include/vtk-5.0/vtkStreamPoints.h
%{root}/include/vtk-5.0/vtkPImageWriter.h
%{root}/include/vtk-5.0/vtkXMLStructuredGridWriter.h
%{root}/include/vtk-5.0/vtkOutlineCornerFilter.h
%{root}/include/vtk-5.0/vtkHierarchicalPolyDataMapper.h
%{root}/include/vtk-5.0/vtkMaskPoints.h
%{root}/include/vtk-5.0/vtkImageNormalize.h
%{root}/include/vtk-5.0/vtkConnectivityFilter.h
%{root}/include/vtk-5.0/vtkMaskFields.h
%{root}/include/vtk-5.0/vtkApproximatingSubdivisionFilter.h
%{root}/include/vtk-5.0/vtkFixedPointVolumeRayCastCompositeShadeHelper.h
%{root}/include/vtk-5.0/vtkCell3D.h
%{root}/include/vtk-5.0/vtkImageFlip.h
%{root}/include/vtk-5.0/vtkImageQuantizeRGBToIndex.h
%{root}/include/vtk-5.0/vtkParametricSuperToroid.h
%{root}/include/vtk-5.0/vtkImageMedian3D.h
%{root}/include/vtk-5.0/vtkLineSource.h
%{root}/include/vtk-5.0/vtkAnimationCue.h
%{root}/include/vtk-5.0/vtkImageSkeleton2D.h
%{root}/include/vtk-5.0/vtkGenericCellTessellator.h
%{root}/include/vtk-5.0/vtkExtentSplitter.h
%{root}/include/vtk-5.0/vtkTransformToGrid.h
%{root}/include/vtk-5.0/vtkImageMagnify.h
%{root}/include/vtk-5.0/vtkXMLUnstructuredGridReader.h
%{root}/include/vtk-5.0/vtkHierarchicalDataSet.h
%{root}/include/vtk-5.0/vtkNonLinearCell.h
%{root}/include/vtk-5.0/vtkPointWidget.h
%{root}/include/vtk-5.0/vtkOBJReader.h
%{root}/include/vtk-5.0/vtkUnstructuredGridReader.h
%{root}/include/vtk-5.0/vtkIdList.h
%{root}/include/vtk-5.0/vtkXMLUnstructuredGridWriter.h
%{root}/include/vtk-5.0/vtkSpatialRepresentationFilter.h
%{root}/include/vtk-5.0/vtkType.h
%{root}/include/vtk-5.0/vtkXMLDataSetWriter.h
%{root}/include/vtk-5.0/vtkElevationFilter.h
%{root}/include/vtk-5.0/vtkCellTypes.h
%{root}/include/vtk-5.0/vtkXYPlotActor.h
%{root}/include/vtk-5.0/vtkMarchingSquares.h
%{root}/include/vtk-5.0/vtkUnstructuredGridWriter.h
%{root}/include/vtk-5.0/vtk3DS.h
%{root}/include/vtk-5.0/vtkStreamer.h
%{root}/include/vtk-5.0/vtkDistributedStreamTracer.h
%{root}/include/vtk-5.0/vtkScalarTree.h
%{root}/include/vtk-5.0/vtkImageSobel2D.h
%{root}/include/vtk-5.0/vtkImageSobel3D.h
%{root}/include/vtk-5.0/vtkDashedStreamLine.h
%{root}/include/vtk-5.0/vtkMapper2D.h
%{root}/include/vtk-5.0/vtkTimerLog.h
%{root}/include/vtk-5.0/vtkDataObjectCollection.h
%{root}/include/vtk-5.0/vtkAbstractMapper.h
%{root}/include/vtk-5.0/vtkExtractCells.h
%{root}/include/vtk-5.0/vtkFixedPointVolumeRayCastCompositeGOHelper.h
%{root}/include/vtk-5.0/vtkGAMBITReader.h
%{root}/include/vtk-5.0/vtkImplicitFunctionCollection.h
%{root}/include/vtk-5.0/vtkOpenGLImageActor.h
%{root}/include/vtk-5.0/vtkVolumeTextureMapper.h
%{root}/include/vtk-5.0/vtkCylindricalTransform.h
%{root}/include/vtk-5.0/vtkSocketCommunicator.h
%{root}/include/vtk-5.0/vtkExtractCTHPart.h
%{root}/include/vtk-5.0/vtkImageMultipleInputFilter.h
%{root}/include/vtk-5.0/vtkParametricFigure8Klein.h
%{root}/include/vtk-5.0/vtkImageAnisotropicDiffusion2D.h
%{root}/include/vtk-5.0/vtkImageAnisotropicDiffusion3D.h
%{root}/include/vtk-5.0/vtkVoidArray.h
%{root}/include/vtk-5.0/vtkPCellDataToPointData.h
%{root}/include/vtk-5.0/vtkDoubleArray.h
%{root}/include/vtk-5.0/vtkActor2DCollection.h
%{root}/include/vtk-5.0/vtkImageIterator.txx
%{root}/include/vtk-5.0/vtkBox.h
%{root}/include/vtk-5.0/vtkInformationExecutivePortKey.h
%{root}/include/vtk-5.0/vtkEnSight6BinaryReader.h
%{root}/include/vtk-5.0/vtkImplicitFunctionToImageStencil.h
%{root}/include/vtk-5.0/vtkStructuredGridSource.h
%{root}/include/vtk-5.0/vtkTextProperty.h
%{root}/include/vtk-5.0/vtkTypeInt32Array.h
%{root}/include/vtk-5.0/vtkUnstructuredGridVolumeRayIntegrator.h
%{root}/include/vtk-5.0/vtkThinPlateSplineTransform.h
%{root}/include/vtk-5.0/vtkRayCastImageDisplayHelper.h
%{root}/include/vtk-5.0/vtk_zlib.h
%{root}/include/vtk-5.0/vtkDebugLeaks.h
%{root}/include/vtk-5.0/vtkLight.h
%{root}/include/vtk-5.0/vtkPLinearExtrusionFilter.h
%{root}/include/vtk-5.0/vtkPLY.h
%{root}/include/vtk-5.0/vtkInteractorStyleUser.h
%{root}/include/vtk-5.0/vtkImageReslice.h
%{root}/include/vtk-5.0/vtkDataSetToDataSetFilter.h
%{root}/include/vtk-5.0/vtkTransformCollection.h
%{root}/include/vtk-5.0/vtkImageFourierCenter.h
%{root}/include/vtk-5.0/vtkImageHSVToRGB.h
%{root}/include/vtk-5.0/vtkExtractDataOverTime.h
%{root}/include/vtk-5.0/vtkObjectFactory.h
%{root}/include/vtk-5.0/vtkPointsProjectedHull.h
%{root}/include/vtk-5.0/vtkInteractorStyleImage.h
%{root}/include/vtk-5.0/vtkTypeInt8Array.h
%{root}/include/vtk-5.0/vtkGenericOutlineFilter.h
%{root}/include/vtk-5.0/vtkGenericInterpolatedVelocityField.h
%{root}/include/vtk-5.0/vtkImageMask.h
%{root}/include/vtk-5.0/DICOMParser.h
%{root}/include/vtk-5.0/vtkMergeDataObjectFilter.h
%{root}/include/vtk-5.0/vtkPassThroughFilter.h
%{root}/include/vtk-5.0/vtkDistributedDataFilter.h
%{root}/include/vtk-5.0/vtkPropPicker.h
%{root}/include/vtk-5.0/vtkGenericDataSetAlgorithm.h
%{root}/include/vtk-5.0/vtkexpat/expatDllConfig.h
%{root}/include/vtk-5.0/vtkexpat/expat.h
%{root}/include/vtk-5.0/vtkexpat/vtk_expat_mangle.h
%{root}/include/vtk-5.0/vtkXMLPDataSetWriter.h
%{root}/include/vtk-5.0/vtkWindowToImageFilter.h
%{root}/include/vtk-5.0/vtkProgrammableFilter.h
%{root}/include/vtk-5.0/vtkWindowedSincPolyDataFilter.h
%{root}/include/vtk-5.0/vtkAttributesErrorMetric.h
%{root}/include/vtk-5.0/vtkStructuredPointsToStructuredPointsFilter.h
%{root}/include/vtk-5.0/vtkImageDataStreamer.h
%{root}/include/vtk-5.0/vtkOutlineSource.h
%{root}/include/vtk-5.0/vtkMassProperties.h
%{root}/include/vtk-5.0/vtkImplicitModeller.h
%{root}/include/vtk-5.0/vtkInitialValueProblemSolver.h
%{root}/include/vtk-5.0/vtkPointSetToPointSetFilter.h
%{root}/include/vtk-5.0/vtkObjectFactoryCollection.h
%{root}/include/vtk-5.0/vtkHierarchicalDataSetAlgorithm.h
%{root}/include/vtk-5.0/vtkImageRFFT.h
%{root}/include/vtk-5.0/vtkMCubesReader.h
%{root}/include/vtk-5.0/vtkCompositeDataSet.h
%{root}/include/vtk-5.0/vtkRectilinearGridSource.h
%{root}/include/vtk-5.0/vtkRearrangeFields.h
%{root}/include/vtk-5.0/vtkMCubesWriter.h
%{root}/include/vtk-5.0/vtkCollectionIterator.h
%{root}/include/vtk-5.0/vtkTypeUInt64Array.h
%{root}/include/vtk-5.0/vtkCGMWriter.h
%{root}/include/vtk-5.0/vtkGridTransform.h
%{root}/include/vtk-5.0/vtkOpenGLPolyDataMapper2D.h
%{root}/include/vtk-5.0/vtkImageCanvasSource2D.h
%{root}/include/vtk-5.0/vtkEnSightMasterServerReader.h
%{root}/include/vtk-5.0/vtkMemoryLimitImageDataStreamer.h
%{root}/include/vtk-5.0/vtkTextActor3D.h
%{root}/include/vtk-5.0/vtkHomogeneousTransform.h
%{root}/include/vtk-5.0/vtkVoxelModeller.h
%{root}/include/vtk-5.0/vtkIOInstantiator.h
%{root}/include/vtk-5.0/vtkSphereSource.h
%{root}/include/vtk-5.0/vtkVolumeProperty.h
%{root}/include/vtk-5.0/vtkProp3DCollection.h
%{root}/include/vtk-5.0/vtkFixedPointVolumeRayCastMapper.h
%{root}/include/vtk-5.0/vtkIntArray.h
%{root}/include/vtk-5.0/vtkInformationDoubleVectorKey.h
%{root}/include/vtk-5.0/vtkOpenGLActor.h
%{root}/include/vtk-5.0/vtkXMLPDataReader.h
%{root}/include/vtk-5.0/vtkDataObjectAlgorithm.h
%{root}/include/vtk-5.0/vtkGenericSubdivisionErrorMetric.h
%{root}/include/vtk-5.0/vtkImageInPlaceFilter.h
%{root}/include/vtk-5.0/vtkXMLPDataWriter.h
%{root}/include/vtk-5.0/vtkDataCompressor.h
%{root}/include/vtk-5.0/vtkImageVariance3D.h
%{root}/include/vtk-5.0/vtkMergePoints.h
%{root}/include/vtk-5.0/vtkMergeFields.h
%{root}/include/vtk-5.0/vtkLoopSubdivisionFilter.h
%{root}/include/vtk-5.0/vtkUnstructuredGridVolumeRayCastMapper.h
%{root}/include/vtk-5.0/vtkDSPFilterDefinition.h
%{root}/include/vtk-5.0/vtkRenderingInstantiator.h
%{root}/include/vtk-5.0/vtkOverrideInformationCollection.h
%{root}/include/vtk-5.0/vtk_png.h
%{root}/include/vtk-5.0/vtkFreeTypeUtilities.h
%{root}/include/vtk-5.0/vtkPlaneWidget.h
%{root}/include/vtk-5.0/vtkTreeCompositer.h
%{root}/include/vtk-5.0/vtkDataSetToStructuredPointsFilter.h
%{root}/include/vtk-5.0/vtkIdTypeArray.h
%{root}/include/vtk-5.0/vtkImageCorrelation.h
%{root}/include/vtk-5.0/vtkImageMandelbrotSource.h
%{root}/include/vtk-5.0/vtkAmoebaMinimizer.h
%{root}/include/vtk-5.0/vtkLinkEdgels.h
%{root}/include/vtk-5.0/vtkTextActor.h
%{root}/include/vtk-5.0/vtkImplicitPlaneWidget.h
%{root}/include/vtk-5.0/vtkScaledTextActor.h
%{root}/include/vtk-5.0/vtkCellArray.h
%{root}/include/vtk-5.0/vtkImageWrapPad.h
%{root}/include/vtk-5.0/vtkEncodedGradientShader.h
%{root}/include/vtk-5.0/vtkDataReader.h
%{root}/include/vtk-5.0/vtkOutputWindow.h
%{root}/include/vtk-5.0/vtkGenericEdgeTable.h
%{root}/include/vtk-5.0/vtkSurfaceReconstructionFilter.h
%{root}/include/vtk-5.0/vtkOStrStreamWrapper.h
%{root}/include/vtk-5.0/vtkClipDataSet.h
%{root}/include/vtk-5.0/vtkImageContinuousDilate3D.h
%{root}/include/vtk-5.0/vtkTransformFilter.h
%{root}/include/vtk-5.0/vtkImageLogic.h
%{root}/include/vtk-5.0/vtkDataWriter.h
%{root}/include/vtk-5.0/vtkUnstructuredGridPartialPreIntegration.h
%{root}/include/vtk-5.0/vtkReflectionFilter.h
%{root}/include/vtk-5.0/vtkQuadricClustering.h
%{root}/include/vtk-5.0/vtkPolyData.h
%{root}/include/vtk-5.0/vtkInformationIdTypeKey.h
%{root}/include/vtk-5.0/vtkExtractGeometry.h
%{root}/include/vtk-5.0/vtkSubdivideTetra.h
%{root}/include/vtk-5.0/vtkImageGridSource.h
%{root}/include/vtk-5.0/vtkGeometryFilter.h
%{root}/include/vtk-5.0/vtkTypeUInt8Array.h
%{root}/include/vtk-5.0/vtkImageImport.h
%{root}/include/vtk-5.0/vtkImageLaplacian.h
%{root}/include/vtk-5.0/vtkImageCityBlockDistance.h
%{root}/include/vtk-5.0/DICOMConfig.h
%{root}/include/vtk-5.0/vtkXMLDataElement.h
%{root}/include/vtk-5.0/vtkImageIdealLowPass.h
%{root}/include/vtk-5.0/vtkVersion.h
%{root}/include/vtk-5.0/vtkDataArraySelection.h
%{root}/include/vtk-5.0/vtkStructuredPointsReader.h
%{root}/include/vtk-5.0/vtkpng/pngconf.h
%{root}/include/vtk-5.0/vtkpng/png.h
%{root}/include/vtk-5.0/vtkpng/pngDllConfig.h
%{root}/include/vtk-5.0/vtkpng/vtk_png_mangle.h
%{root}/include/vtk-5.0/vtkstd/map
%{root}/include/vtk-5.0/vtkstd/set
%{root}/include/vtk-5.0/vtkstd/list
%{root}/include/vtk-5.0/vtkstd/stdexcept
%{root}/include/vtk-5.0/vtkstd/deque
%{root}/include/vtk-5.0/vtkstd/queue
%{root}/include/vtk-5.0/vtkstd/stack
%{root}/include/vtk-5.0/vtkstd/exception
%{root}/include/vtk-5.0/vtkstd/algorithm
%{root}/include/vtk-5.0/vtkstd/string
%{root}/include/vtk-5.0/vtkstd/iterator
%{root}/include/vtk-5.0/vtkstd/vector
%{root}/include/vtk-5.0/vtkstd/numeric
%{root}/include/vtk-5.0/vtkstd/utility
%{root}/include/vtk-5.0/vtksys/ios/iostream
%{root}/include/vtk-5.0/vtksys/ios/sstream
%{root}/include/vtk-5.0/vtksys/ios/iosfwd
%{root}/include/vtk-5.0/vtksys/ios/fstream
%{root}/include/vtk-5.0/vtksys/stl/map
%{root}/include/vtk-5.0/vtksys/stl/set
%{root}/include/vtk-5.0/vtksys/stl/list
%{root}/include/vtk-5.0/vtksys/stl/deque
%{root}/include/vtk-5.0/vtksys/stl/queue
%{root}/include/vtk-5.0/vtksys/stl/stack
%{root}/include/vtk-5.0/vtksys/stl/functional
%{root}/include/vtk-5.0/vtksys/stl/string.hxx
%{root}/include/vtk-5.0/vtksys/stl/algorithm
%{root}/include/vtk-5.0/vtksys/stl/memory
%{root}/include/vtk-5.0/vtksys/stl/string
%{root}/include/vtk-5.0/vtksys/stl/iterator
%{root}/include/vtk-5.0/vtksys/stl/vector
%{root}/include/vtk-5.0/vtksys/stl/numeric
%{root}/include/vtk-5.0/vtksys/stl/utility
%{root}/include/vtk-5.0/vtksys/hashtable.hxx
%{root}/include/vtk-5.0/vtksys/Process.h
%{root}/include/vtk-5.0/vtksys/Configure.h
%{root}/include/vtk-5.0/vtksys/Directory.hxx
%{root}/include/vtk-5.0/vtksys/hash_set.hxx
%{root}/include/vtk-5.0/vtksys/hash_map.hxx
%{root}/include/vtk-5.0/vtksys/Base64.h
%{root}/include/vtk-5.0/vtksys/SystemTools.hxx
%{root}/include/vtk-5.0/vtksys/Configure.hxx
%{root}/include/vtk-5.0/vtksys/CommandLineArguments.hxx
%{root}/include/vtk-5.0/vtksys/hash_fun.hxx
%{root}/include/vtk-5.0/vtksys/SharedForward.h
%{root}/include/vtk-5.0/vtksys/RegularExpression.hxx
%{root}/include/vtk-5.0/vtkInteractorStyleTerrain.h
%{root}/include/vtk-5.0/vtkImageMapToWindowLevelColors.h
%{root}/include/vtk-5.0/vtkHierarchicalDataSetGeometryFilter.h
%{root}/include/vtk-5.0/vtkDiscreteMarchingCubes.h
%{root}/include/vtk-5.0/vtkTetra.h
%{root}/include/vtk-5.0/vtkPProbeFilter.h
%{root}/include/vtk-5.0/vtkQuantizePolyDataPoints.h
%{root}/include/vtk-5.0/vtkStructuredPointsWriter.h
%{root}/include/vtk-5.0/vtkDemandDrivenPipeline.h
%{root}/include/vtk-5.0/vtkFiniteDifferenceGradientEstimator.h
%{root}/include/vtk-5.0/vtkEnSightGoldBinaryReader.h
%{root}/include/vtk-5.0/vtkExtractUserDefinedPiece.h
%{root}/include/vtk-5.0/vtkSystemIncludes.h
%{root}/include/vtk-5.0/vtkFieldDataToAttributeDataFilter.h
%{root}/include/vtk-5.0/vtkAbstractTransform.h
%{root}/include/vtk-5.0/vtkDirectory.h
%{root}/include/vtk-5.0/vtkVolumeRayCastCompositeFunction.h
%{root}/include/vtk-5.0/vtkImageAccumulate.h
%{root}/include/vtk-5.0/vtkWarpScalar.h
%{root}/include/vtk-5.0/vtkSortDataArray.h
%{root}/include/vtk-5.0/vtkActor2D.h
%{root}/include/vtk-5.0/vtkSphere.h
%{root}/include/vtk-5.0/vtkCullerCollection.h
%{root}/include/vtk-5.0/vtkStructuredGridGeometryFilter.h
%{root}/include/vtk-5.0/vtkTesting.h
%{root}/include/vtk-5.0/vtkImageHSIToRGB.h
%{root}/include/vtk-5.0/vtkWidgetsInstantiator.h
%{root}/include/vtk-5.0/vtkGaussianCubeReader.h
%{root}/include/vtk-5.0/vtkInformationDataObjectKey.h
%{root}/include/vtk-5.0/vtkImageRectilinearWipe.h
%{root}/include/vtk-5.0/vtkImageContinuousErode3D.h
%{root}/include/vtk-5.0/vtkOpenGLProperty.h
%{root}/include/vtk-5.0/vtkUnsignedLongLongArray.h
%{root}/include/vtk-5.0/vtkPExodusReader.h
%{root}/include/vtk-5.0/vtkHierarchicalDataIterator.h
%{root}/include/vtk-5.0/vtkRectangularButtonSource.h
%{root}/include/vtk-5.0/vtkInformationIntegerKey.h
%{root}/include/vtk-5.0/vtkTypeUInt32Array.h
%{root}/include/vtk-5.0/vtkVolumeMapper.h
%{root}/include/vtk-5.0/vtkRecursiveSphereDirectionEncoder.h
%{root}/include/vtk-5.0/vtkExporter.h
%{root}/include/vtk-5.0/vtkXMLPStructuredGridReader.h
%{root}/include/vtk-5.0/vtkSimpleImageToImageFilter.h
%{root}/include/vtk-5.0/vtkImageButterworthHighPass.h
%{root}/include/vtk-5.0/vtkXMLDataReader.h
%{root}/include/vtk-5.0/vtkTubeFilter.h
%{root}/include/vtk-5.0/vtkSuperquadricSource.h
%{root}/include/vtk-5.0/vtkInformationExecutivePortVectorKey.h
%{root}/include/vtk-5.0/vtkTriangleStrip.h
%{root}/include/vtk-5.0/vtkXMLPStructuredGridWriter.h
%{root}/include/vtk-5.0/vtkInteractorStyleFlight.h
%{root}/include/vtk-5.0/vtkSource.h
%{root}/include/vtk-5.0/vtkPentagonalPrism.h
%{root}/include/vtk-5.0/vtkDataSetToImageFilter.h
%{root}/include/vtk-5.0/vtkUnstructuredGrid.h
%{root}/include/vtk-5.0/vtkKdNode.h
%{root}/include/vtk-5.0/vtkDuplicatePolyData.h
%{root}/include/vtk-5.0/vtkRegularPolygonSource.h
%{root}/include/vtk-5.0/vtkFixedPointVolumeRayCastCompositeGOShadeHelper.h
%{root}/include/vtk-5.0/vtkMergeFilter.h
%{root}/include/vtk-5.0/vtkGeneralTransform.h
%{root}/include/vtk-5.0/vtkTriangle.h
%{root}/include/vtk-5.0/vtkOutlineFilter.h
%{root}/include/vtk-5.0/vtkHierarchicalDataExtractDataSets.h
%{root}/include/vtk-5.0/vtkImageMapToRGBA.h
%{root}/include/vtk-5.0/vtkImageConvolve.h
%{root}/include/vtk-5.0/vtkDataObjectReader.h
%{root}/include/vtk-5.0/vtkFileOutputWindow.h
%{root}/include/vtk-5.0/vtkImageCacheFilter.h
%{root}/include/vtk-5.0/vtkMaskPolyData.h
%{root}/include/vtk-5.0/vtkInteractorStyleRubberBandZoom.h
%{root}/include/vtk-5.0/vtkDataArrayCollection.h
%{root}/include/vtk-5.0/vtkOpenGLRenderWindow.h
%{root}/include/vtk-5.0/vtkDataObjectWriter.h
%{root}/include/vtk-5.0/vtkVectorNorm.h
%{root}/include/vtk-5.0/vtkContourGrid.h
%{root}/include/vtk-5.0/vtkShrinkFilter.h
%{root}/include/vtk-5.0/vtkGenericGeometryFilter.h
%{root}/include/vtk-5.0/vtkSpline.h
%{root}/include/vtk-5.0/vtkLogLookupTable.h
%{root}/include/vtk-5.0/vtkLightCollection.h
%{root}/include/vtk-5.0/vtkTextureMapToPlane.h
%{root}/include/vtk-5.0/vtkVoxelContoursToSurfaceFilter.h
%{root}/include/vtk-5.0/vtkButterflySubdivisionFilter.h
%{root}/include/vtk-5.0/vtkDataSetAlgorithm.h
%{root}/include/vtk-5.0/vtkExodusIIWriter.h
%{root}/include/vtk-5.0/vtkGenericAdaptorCell.h
%{root}/include/vtk-5.0/vtkProjectedTexture.h
%{root}/include/vtk-5.0/vtkCameraInterpolator.h
%{root}/include/vtk-5.0/vtkVolumeRenderingFactory.h
%{root}/include/vtk-5.0/vtkLinearTransform.h
%{root}/include/vtk-5.0/vtkContourValues.h
%{root}/include/vtk-5.0/vtkRenderWindow.h
%{root}/include/vtk-5.0/vtkProperty2D.h
%{root}/include/vtk-5.0/vtkImageReader.h
%{root}/include/vtk-5.0/vtkPolyDataAlgorithm.h
%{root}/include/vtk-5.0/vtkWin32Header.h
%{root}/include/vtk-5.0/vtkVolumeTextureMapper2D.h
%{root}/include/vtk-5.0/vtkVolumeTextureMapper3D.h
%{root}/include/vtk-5.0/vtkInformationUnsignedLongKey.h
%{root}/include/vtk-5.0/vtkCellData.h
%{root}/include/vtk-5.0/vtkPoints.h
%{root}/include/vtk-5.0/vtkLineWidget.h
%{root}/include/vtk-5.0/vtkUnsignedCharArray.h
%{root}/include/vtk-5.0/vtkLabeledDataMapper.h
%{root}/include/vtk-5.0/vtkImageWriter.h
%{root}/include/vtk-5.0/vtkPolyLine.h
%{root}/include/vtk-5.0/vtkRectilinearGridGeometryFilter.h
%{root}/include/vtk-5.0/vtkTensor.h
%{root}/include/vtk-5.0/vtkBandedPolyDataContourFilter.h
%{root}/include/vtk-5.0/vtkTypeFloat64Array.h
%{root}/include/vtk-5.0/vtkGaussianSplatter.h
%{root}/include/vtk-5.0/vtkExtractVectorComponents.h
%{root}/include/vtk-5.0/vtkSpherePuzzle.h
%{root}/include/vtk-5.0/vtkRibbonFilter.h
%{root}/include/vtk-5.0/vtkTriangleFilter.h
%{root}/include/vtk-5.0/vtkUnstructuredGridVolumeRayCastIterator.h
%{root}/include/vtk-5.0/vtkExplicitCell.h
%{root}/include/vtk-5.0/vtkPieceScalars.h
%{root}/include/vtk-5.0/vtkMedicalImageProperties.h
%{root}/include/vtk-5.0/vtkExtractEdges.h
%{root}/include/vtk-5.0/vtkThreadedImageAlgorithm.h
%{root}/include/vtk-5.0/vtkPNMReader.h
%{root}/include/vtk-5.0/vtkVolumeRayCastIsosurfaceFunction.h
%{root}/include/vtk-5.0/vtkHyperStreamline.h
%{root}/include/vtk-5.0/vtkBSPCuts.h
%{root}/include/vtk-5.0/vtkStructuredGridClip.h
%{root}/include/vtk-5.0/vtkImageMagnitude.h
%{root}/include/vtk-5.0/vtkImageReader2Collection.h
%{root}/include/vtk-5.0/vtkTypeInt16Array.h
%{root}/include/vtk-5.0/vtkFollower.h
%{root}/include/vtk-5.0/vtkTransformTextureCoords.h
%{root}/include/vtk-5.0/vtkImageReader2Factory.h
%{root}/include/vtk-5.0/vtkVolumeRayCastMIPFunction.h
%{root}/include/vtk-5.0/vtkProcessIdScalars.h
%{root}/include/vtk-5.0/vtkPNMWriter.h
%{root}/include/vtk-5.0/vtkGenericCutter.h
%{root}/include/vtk-5.0/vtkGenericEnSightReader.h
%{root}/include/vtk-5.0/vtkThreadMessager.h
%{root}/include/vtk-5.0/vtkPOutlineCornerFilter.h
%{root}/include/vtk-5.0/vtkSignedCharArray.h
%{root}/include/vtk-5.0/vtkCompositeDataPipeline.h
%{root}/include/vtk-5.0/vtkPPolyDataNormals.h
%{root}/include/vtk-5.0/vtkWarpVector.h
%{root}/include/vtk-5.0/vtkImageViewer.h
%{root}/include/vtk-5.0/vtkKdTree.h
%{root}/include/vtk-5.0/vtkGlyphSource2D.h
%{root}/include/vtk-5.0/vtkImageReader2.h
%{root}/include/vtk-5.0/vtkPicker.h
%{root}/include/vtk-5.0/vtkExodusModel.h
%{root}/include/vtk-5.0/vtkVectorText.h
%{root}/include/vtk-5.0/vtkModelMetadata.h
%{root}/include/vtk-5.0/vtkQuadric.h
%{root}/include/vtk-5.0/vtkInteractorEventRecorder.h
%{root}/include/vtk-5.0/DICOMCMakeConfig.h
%{root}/include/vtk-5.0/vtkImageThreshold.h
%{root}/include/vtk-5.0/vtkRectilinearGrid.h
%{root}/include/vtk-5.0/vtkSLCReader.h
%{root}/include/vtk-5.0/vtkCuller.h
%{root}/include/vtk-5.0/vtknetcdf/ncconfig.h
%{root}/include/vtk-5.0/vtknetcdf/vtk_netcdf_mangle.h
%{root}/include/vtk-5.0/vtknetcdf/netcdf.h
%{root}/include/vtk-5.0/vtkUnstructuredGridToPolyDataFilter.h
%{root}/include/vtk-5.0/vtkArrowSource.h
%{root}/include/vtk-5.0/vtkQuadraticHexahedron.h
%{root}/include/vtk-5.0/vtkStreamingDemandDrivenPipeline.h
%{root}/include/vtk-5.0/vtkAppendPolyData.h
%{root}/include/vtk-5.0/vtkCharArray.h
%{root}/include/vtk-5.0/vtkUnstructuredGridSource.h
%{root}/include/vtk-5.0/vtkPolyDataConnectivityFilter.h
%{root}/include/vtk-5.0/vtkgl.h
%{root}/include/vtk-5.0/vtkjpeg/jpegDllConfig.h
%{root}/include/vtk-5.0/vtkjpeg/jerror.h
%{root}/include/vtk-5.0/vtkjpeg/jconfig.h
%{root}/include/vtk-5.0/vtkjpeg/jmorecfg.h
%{root}/include/vtk-5.0/vtkjpeg/jpeglib.h
%{root}/include/vtk-5.0/vtkjpeg/vtk_jpeg_mangle.h
%{root}/include/vtk-5.0/vtktiff/vtk_tiff_mangle.h
%{root}/include/vtk-5.0/vtktiff/tconf.h
%{root}/include/vtk-5.0/vtktiff/tiffDllConfig.h
%{root}/include/vtk-5.0/vtktiff/tiff.h
%{root}/include/vtk-5.0/vtktiff/tiffvers.h
%{root}/include/vtk-5.0/vtktiff/tiffio.h
%{root}/include/vtk-5.0/vtkExtractUnstructuredGrid.h
%{root}/include/vtk-5.0/vtkImageNonMaximumSuppression.h
%{root}/include/vtk-5.0/vtkzlib/zlibDllConfig.h
%{root}/include/vtk-5.0/vtkzlib/zconf.h
%{root}/include/vtk-5.0/vtkzlib/vtk_zlib_mangle.h
%{root}/include/vtk-5.0/vtkzlib/zlib.h
%{root}/include/vtk-5.0/vtkQuadraticPyramid.h
%{root}/include/vtk-5.0/vtkDEMReader.h
%{root}/include/vtk-5.0/vtkPOPReader.h
%{root}/include/vtk-5.0/vtkRectilinearGridToTetrahedra.h
%{root}/include/vtk-5.0/vtkVolumeRayCastMapper.h
%{root}/include/vtk-5.0/vtkDataArrayCollectionIterator.h
%{root}/include/vtk-5.0/vtkXMLStructuredDataReader.h
%{root}/include/vtk-5.0/vtkWindows.h
%{root}/include/vtk-5.0/vtkTypeTraits.h
%{root}/include/vtk-5.0/vtkBlankStructuredGrid.h
%{root}/include/vtk-5.0/vtkImageProgressIterator.txx
%{root}/include/vtk-5.0/vtkAssemblyNode.h
%{root}/include/vtk-5.0/vtkInformationRequestKey.h
%{root}/include/vtk-5.0/vtkXMLPRectilinearGridReader.h
%{root}/include/vtk-5.0/vtkXMLStructuredDataWriter.h
%{root}/include/vtk-5.0/vtkViewDependentErrorMetric.h
%{root}/include/vtk-5.0/vtkQuadraticEdge.h
%{root}/include/vtk-5.0/vtkPolyDataReader.h
%{root}/include/vtk-5.0/vtkOldStyleCallbackCommand.h
%{root}/include/vtk-5.0/vtkXMLPRectilinearGridWriter.h
%{root}/include/vtk-5.0/vtkAbstractArray.h
%{root}/include/vtk-5.0/vtkPolyDataWriter.h
%{root}/include/vtk-5.0/vtkGenericCellIterator.h
%{root}/include/vtk-5.0/vtkMarchingCubes.h
%{root}/include/vtk-5.0/vtkXOpenGLRenderWindow.h
%{root}/include/vtk-5.0/vtkAssemblyPath.h
%{root}/include/vtk-5.0/vtkOpenGLVolumeTextureMapper2D.h
%{root}/include/vtk-5.0/vtkOpenGLVolumeTextureMapper3D.h
%{root}/include/vtk-5.0/vtkXMLFileReadTester.h
%{root}/include/vtk-5.0/vtkMultiBlockPLOT3DReader.h
%{root}/include/vtk-5.0/vtkMultiThreader.h
%{root}/include/vtk-5.0/vtkDirectionEncoder.h
%{root}/include/vtk-5.0/vtkUnsignedLongArray.h
%{root}/include/vtk-5.0/vtkXMLUnstructuredDataReader.h
%{root}/include/vtk-5.0/vtkXMLReader.h
%{root}/include/vtk-5.0/vtkImageResample.h
%{root}/include/vtk-5.0/vtkGeometricErrorMetric.h
%{root}/include/vtk-5.0/vtkTrivialProducer.h
%{root}/include/vtk-5.0/vtkViewport.h
%{root}/include/vtk-5.0/vtkXMLUnstructuredDataWriter.h
%{root}/include/vtk-5.0/vtkXYPlotWidget.h
%{root}/include/vtk-5.0/vtkXMLPUnstructuredGridReader.h
%{root}/include/vtk-5.0/vtkPointData.h
%{root}/include/vtk-5.0/vtkPropCollection.h
%{root}/include/vtk-5.0/vtkXMLWriter.h
%{root}/include/vtk-5.0/vtkInterpolatingSubdivisionFilter.h
%{root}/include/vtk-5.0/vtkPointSet.h
%{root}/include/vtk-5.0/vtkCellDerivatives.h
%{root}/include/vtk-5.0/vtkTypeFloat32Array.h
%{root}/include/vtk-5.0/vtkAssemblyPaths.h
%{root}/include/vtk-5.0/vtkEmptyCell.h
%{root}/include/vtk-5.0/vtkLookupTable.h
%{root}/include/vtk-5.0/vtkActor.h
%{root}/include/vtk-5.0/vtkImageExport.h
%{root}/include/vtk-5.0/vtkXMLPUnstructuredGridWriter.h
%{root}/include/vtk-5.0/vtkReverseSense.h
%{root}/include/vtk-5.0/vtkImplicitTextureCoords.h
%{root}/include/vtk-5.0/vtkOBJExporter.h
%{root}/include/vtk-5.0/vtkGESignaReader.h
%{root}/include/vtk-5.0/vtkAssignAttribute.h
%{root}/include/vtk-5.0/vtkAlgorithm.h
%{root}/include/vtk-5.0/vtkShortArray.h
%{root}/include/vtk-5.0/vtkPiecewiseFunctionShiftScale.h
%{root}/include/vtk-5.0/vtkCoordinate.h
%{root}/include/vtk-5.0/vtkConeSource.h
%{root}/include/vtk-5.0/vtkExtractPolyDataGeometry.h
%{root}/include/vtk-5.0/vtkSphereWidget.h
%{root}/include/vtk-5.0/vtkOpenGLFreeTypeTextMapper.h
%{root}/include/vtk-5.0/vtkGenericStreamTracer.h
%{root}/include/vtk-5.0/vtkImageFourierFilter.h
%{root}/include/vtk-5.0/vtkDSPFilterGroup.h
%{root}/include/vtk-5.0/vtkPointSetAlgorithm.h
%{root}/include/vtk-5.0/vtkImageEuclideanDistance.h
%{root}/include/vtk-5.0/vtkParametricFunction.h
%{root}/include/vtk-5.0/vtkVolumeRenderingInstantiator.h
%{root}/include/vtk-5.0/vtkKochanekSpline.h
%{root}/include/vtk-5.0/vtkDataSetReader.h
%{root}/include/vtk-5.0/vtkImageFFT.h
%{root}/include/vtk-5.0/vtkLinearSubdivisionFilter.h
%{root}/include/vtk-5.0/vtkDataSetSurfaceFilter.h
%{root}/include/vtk-5.0/DICOMAppHelper.h
%{root}/include/vtk-5.0/vtkCamera.h
%{root}/include/vtk-5.0/vtkImageActor.h
%{root}/include/vtk-5.0/vtkTransformInterpolator.h
%{root}/include/vtk-5.0/vtkHedgeHog.h
%{root}/include/vtk-5.0/vtkPointLocator.h
%{root}/include/vtk-5.0/vtkSelectPolyData.h
%{root}/include/vtk-5.0/vtkDataSetWriter.h
%{root}/include/vtk-5.0/vtkIdFilter.h
%{root}/include/vtk-5.0/vtkAlgorithmOutput.h
%{root}/include/vtk-5.0/vtkOutputStream.h
%{root}/include/vtk-5.0/vtkInterpolateDataSetAttributes.h
%{root}/include/vtk-5.0/vtkScalarBarActor.h
%{root}/include/vtk-5.0/vtkInterpolatedVelocityField.h
%{root}/include/vtk-5.0/vtkOrientationMarkerWidget.h
%{root}/include/vtk-5.0/vtkXRenderWindowInteractor.h
%{root}/include/vtk-5.0/vtkCommand.h
%{root}/include/vtk-5.0/vtkLongArray.h
%{root}/include/vtk-5.0/vtkTensorGlyph.h
%{root}/include/vtk-5.0/vtkVectorDot.h
%{root}/include/vtk-5.0/vtkMultiPartExtentTranslator.h
%{root}/include/vtk-5.0/vtkDataSetCollection.h
%{root}/include/vtk-5.0/vtkFilteringInstantiator.h
%{root}/include/vtk-5.0/vtkWarpLens.h
%{root}/include/vtk-5.0/vtkPStreamTracer.h
%{root}/include/vtk-5.0/vtkGenericPointIterator.h
%{root}/include/vtk-5.0/vtkMultiProcessController.h
%{root}/include/vtk-5.0/vtkImageToStructuredPoints.h
%{root}/include/vtk-5.0/vtkRuledSurfaceFilter.h
%{root}/include/vtk-5.0/vtkCutter.h
%{root}/include/vtk-5.0/vtkMapper.h
%{root}/include/vtk-5.0/vtkInformation.h
%{root}/include/vtk-5.0/vtkUnstructuredGridLinearRayIntegrator.h
%{root}/include/vtk-5.0/vtkParametricKlein.h
%{root}/include/vtk-5.0/vtkImageShiftScale.h
%{root}/include/vtk-5.0/vtkOpenGLImageMapper.h
%{root}/include/vtk-5.0/vtkStructuredVisibilityConstraint.h
%{root}/include/vtk-5.0/vtkTestUtilities.h
%{root}/include/vtk-5.0/internal/stdio_core.h
%{root}/include/vtk-5.0/vtkExodusReader.h
%{root}/include/vtk-5.0/vtkDelaunay2D.h
%{root}/include/vtk-5.0/vtkDelaunay3D.h
%{root}/include/vtk-5.0/vtkInformationIntegerVectorKey.h
%{root}/include/vtk-5.0/vtkSmartPointer.h
%{root}/include/vtk-5.0/vtkOpenGLPolyDataMapper.h
%{root}/include/vtk-5.0/vtkLinearExtrusionFilter.h
%{root}/include/vtk-5.0/vtkTypeUInt16Array.h

# Bullet Physics Detection Library Files
%files -n bullet-bin
%defattr(755, root, root)
%dir %{root}/include/bullet
%dir %{root}/include/bullet/BulletDynamics
%dir %{root}/include/bullet/BulletDynamics/Vehicle
%dir %{root}/include/bullet/BulletDynamics/Dynamics
%dir %{root}/include/bullet/BulletDynamics/ConstraintSolver
%dir %{root}/include/bullet/BulletCollision
%dir %{root}/include/bullet/BulletCollision/CollisionShapes
%dir %{root}/include/bullet/BulletCollision/NarrowPhaseCollision
%dir %{root}/include/bullet/BulletCollision/BroadphaseCollision
%dir %{root}/include/bullet/BulletCollision/CollisionDispatch
%dir %{root}/include/bullet/LinearMath
%{root}/lib/libbulletmath.a
%{root}/lib/libbulletcollision.a
%{root}/lib/libbulletdynamics.a
%{root}/lib/libboxbox.a
%{root}/lib/libbulletopenglsupport.a
%{root}/lib/libconvexdecomposition.a
%{root}/lib/libGIMPACTBullet.a
%{root}/lib/libquickstep.a
%{root}/lib/libcolladadom.a
%{root}/lib/libGIMPACT.a
%{root}/lib/liblibxml.a

%defattr(644, root, root)
%{_libdir}/pkgconfig/bullet.pc
%{root}/include/bullet/BulletDynamics/Vehicle/btRaycastVehicle.h
%{root}/include/bullet/BulletDynamics/Vehicle/btWheelInfo.h
%{root}/include/bullet/BulletDynamics/Vehicle/btVehicleRaycaster.h
%{root}/include/bullet/BulletDynamics/Dynamics/btRigidBody.h
%{root}/include/bullet/BulletDynamics/Dynamics/btDynamicsWorld.h
%{root}/include/bullet/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h
%{root}/include/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btTypedConstraint.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btConstraintSolver.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btContactConstraint.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btContactSolverInfo.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btJacobianEntry.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h
%{root}/include/bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btConcaveShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btCollisionMargin.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btCompoundShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btConvexHullShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btCylinderShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btTriangleMesh.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btTetrahedronShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btSphereShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btMultiSphereShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btStridingMeshInterface.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btEmptyShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btOptimizedBvh.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btTriangleCallback.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btTriangleBuffer.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btConvexShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btStaticPlaneShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btConeShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btCollisionShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btTriangleShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btBoxShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btMinkowskiSumShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btTriangleMeshShape.h
%{root}/include/bullet/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btConvexCast.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btGjkEpa.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btPointCollector.h
%{root}/include/bullet/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h
%{root}/include/bullet/BulletCollision/BroadphaseCollision/btDispatcher.h
%{root}/include/bullet/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h
%{root}/include/bullet/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h
%{root}/include/bullet/BulletCollision/BroadphaseCollision/btAxisSweep3.h
%{root}/include/bullet/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h
%{root}/include/bullet/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h
%{root}/include/bullet/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btUnionFind.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btCollisionDispatcher.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/SphereTriangleDetector.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btCollisionObject.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btSimulationIslandManager.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h
%{root}/include/bullet/BulletCollision/CollisionDispatch/btManifoldResult.h
%{root}/include/bullet/LinearMath/btGeometryUtil.h
%{root}/include/bullet/LinearMath/btSimdMinMax.h
%{root}/include/bullet/LinearMath/btList.h
%{root}/include/bullet/LinearMath/btMatrix3x3.h
%{root}/include/bullet/LinearMath/btVector3.h
%{root}/include/bullet/LinearMath/btScalar.h
%{root}/include/bullet/LinearMath/btDefaultMotionState.h
%{root}/include/bullet/LinearMath/btPoint3.h
%{root}/include/bullet/LinearMath/btTransform.h
%{root}/include/bullet/LinearMath/btQuadWord.h
%{root}/include/bullet/LinearMath/btAabbUtil2.h
%{root}/include/bullet/LinearMath/btTransformUtil.h
%{root}/include/bullet/LinearMath/btRandom.h
%{root}/include/bullet/LinearMath/btQuaternion.h
%{root}/include/bullet/LinearMath/btMinMax.h
%{root}/include/bullet/LinearMath/btMotionState.h
%{root}/include/bullet/LinearMath/btIDebugDraw.h
%{root}/include/bullet/LinearMath/btAlignedAllocator.h
%{root}/include/bullet/LinearMath/btStackAlloc.h
%{root}/include/bullet/LinearMath/btAlignedObjectArray.h
%{root}/include/bullet/LinearMath/btQuickprof.h
%{root}/include/bullet/btBulletDynamicsCommon.h
%{root}/include/bullet/btBulletCollisionCommon.h

%files -n wx28-bin
%defattr(755, root, root)
%dir %{root}/lib/wx
%dir %{root}/lib/wx/config
%dir %{root}/lib/wx/include
%dir %{root}/lib/wx/include/gtk2-ansi-release-2.8
%dir %{root}/lib/wx/include/gtk2-ansi-release-2.8/wx
%dir %{root}/share/bakefile
%dir %{root}/share/bakefile/presets
%dir %{root}/include/wx-2.8
%dir %{root}/include/wx-2.8/wx
%dir %{root}/include/wx-2.8/wx/aui
%dir %{root}/include/wx-2.8/wx/gtk
%dir %{root}/include/wx-2.8/wx/gtk/gnome
%dir %{root}/include/wx-2.8/wx/xml
%dir %{root}/include/wx-2.8/wx/xrc
%dir %{root}/include/wx-2.8/wx/html
%dir %{root}/include/wx-2.8/wx/unix
%dir %{root}/include/wx-2.8/wx/generic
%dir %{root}/include/wx-2.8/wx/richtext
%dir %{root}/include/wx-2.8/wx/protocol

%defattr(755, root, root)
%{root}/bin/wxrc
%{root}/bin/wx-config
%{root}/bin/wxrc-2.8
%{root}/lib/wx/config/gtk2-ansi-release-2.8
%{root}/lib/wx/include/gtk2-ansi-release-2.8/wx/setup.h
%{root}/lib/libwx_base-2.8.so
%{root}/lib/libwx_gtk2_html-2.8.so
%{root}/lib/libwx_gtk2_richtext-2.8.so
%{root}/lib/libwx_base_net-2.8.so.0
%{root}/lib/libwx_base_net-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_aui-2.8.so
%{root}/lib/libwx_base_net-2.8.so
%{root}/lib/libwx_gtk2_core-2.8.so.0
%{root}/lib/libwx_gtk2_xrc-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_adv-2.8.so
%{root}/lib/libwx_gtk2_qa-2.8.so.0
%{root}/lib/libwx_gtk2_gl-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_gl-2.8.so
%{root}/lib/libwx_gtk2_adv-2.8.so.0
%{root}/lib/libwx_gtk2_adv-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_aui-2.8.so.0.0.0
%{root}/lib/libwx_base_xml-2.8.so
%{root}/lib/libwx_gtk2_core-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_aui-2.8.so.0
%{root}/lib/libwx_base_xml-2.8.so.0
%{root}/lib/libwx_base-2.8.so.0
%{root}/lib/libwx_gtk2_qa-2.8.so.0.0.0
%{root}/lib/libwx_base_xml-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_qa-2.8.so
%{root}/lib/libwx_gtk2_richtext-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_html-2.8.so.0
%{root}/lib/libwx_gtk2_xrc-2.8.so
%{root}/lib/libwx_base-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_html-2.8.so.0.0.0
%{root}/lib/libwx_gtk2_gl-2.8.so.0
%{root}/lib/libwx_gtk2_core-2.8.so
%{root}/lib/libwx_gtk2_xrc-2.8.so.0
%{root}/lib/libwx_gtk2_richtext-2.8.so.0
%defattr(644, root, root)
%{root}/share/aclocal/wxwin.m4
%{root}/share/bakefile/presets/wx_win32.bkl
%{root}/share/bakefile/presets/wx.bkl
%{root}/share/bakefile/presets/wx_unix.bkl
%{root}/include/wx-2.8/wx/artprov.h
%{root}/include/wx-2.8/wx/debugrpt.h
%{root}/include/wx-2.8/wx/aui/aui.h
%{root}/include/wx-2.8/wx/aui/dockart.h
%{root}/include/wx-2.8/wx/aui/framemanager.h
%{root}/include/wx-2.8/wx/aui/floatpane.h
%{root}/include/wx-2.8/wx/aui/tabmdi.h
%{root}/include/wx-2.8/wx/aui/auibook.h
%{root}/include/wx-2.8/wx/gtk/win_gtk.h
%{root}/include/wx-2.8/wx/gtk/dc.h
%{root}/include/wx-2.8/wx/gtk/fontpicker.h
%{root}/include/wx-2.8/wx/gtk/filedlg.h
%{root}/include/wx-2.8/wx/gtk/dialog.h
%{root}/include/wx-2.8/wx/gtk/bitmap.h
%{root}/include/wx-2.8/wx/gtk/textctrl.h
%{root}/include/wx-2.8/wx/gtk/fontdlg.h
%{root}/include/wx-2.8/wx/gtk/app.h
%{root}/include/wx-2.8/wx/gtk/dnd.h
%{root}/include/wx-2.8/wx/gtk/gnome/gprint.h
%{root}/include/wx-2.8/wx/gtk/gnome/gvfs.h
%{root}/include/wx-2.8/wx/gtk/mdi.h
%{root}/include/wx-2.8/wx/gtk/pen.h
%{root}/include/wx-2.8/wx/gtk/dcclient.h
%{root}/include/wx-2.8/wx/gtk/dcmemory.h
%{root}/include/wx-2.8/wx/gtk/collpane.h
%{root}/include/wx-2.8/wx/gtk/tooltip.h
%{root}/include/wx-2.8/wx/gtk/dataobj.h
%{root}/include/wx-2.8/wx/gtk/spinbutt.h
%{root}/include/wx-2.8/wx/gtk/dirdlg.h
%{root}/include/wx-2.8/wx/gtk/spinctrl.h
%{root}/include/wx-2.8/wx/gtk/clrpicker.h
%{root}/include/wx-2.8/wx/gtk/combobox.h
%{root}/include/wx-2.8/wx/gtk/popupwin.h
%{root}/include/wx-2.8/wx/gtk/assertdlg_gtk.h
%{root}/include/wx-2.8/wx/gtk/control.h
%{root}/include/wx-2.8/wx/gtk/cursor.h
%{root}/include/wx-2.8/wx/gtk/menuitem.h
%{root}/include/wx-2.8/wx/gtk/timer.h
%{root}/include/wx-2.8/wx/gtk/gauge.h
%{root}/include/wx-2.8/wx/gtk/colour.h
%{root}/include/wx-2.8/wx/gtk/choice.h
%{root}/include/wx-2.8/wx/gtk/tbargtk.h
%{root}/include/wx-2.8/wx/gtk/filepicker.h
%{root}/include/wx-2.8/wx/gtk/scrolbar.h
%{root}/include/wx-2.8/wx/gtk/treeentry_gtk.h
%{root}/include/wx-2.8/wx/gtk/font.h
%{root}/include/wx-2.8/wx/gtk/glcanvas.h
%{root}/include/wx-2.8/wx/gtk/frame.h
%{root}/include/wx-2.8/wx/gtk/scrolwin.h
%{root}/include/wx-2.8/wx/gtk/tglbtn.h
%{root}/include/wx-2.8/wx/gtk/menu.h
%{root}/include/wx-2.8/wx/gtk/accel.h
%{root}/include/wx-2.8/wx/gtk/notebook.h
%{root}/include/wx-2.8/wx/gtk/dcscreen.h
%{root}/include/wx-2.8/wx/gtk/slider.h
%{root}/include/wx-2.8/wx/gtk/window.h
%{root}/include/wx-2.8/wx/gtk/dataform.h
%{root}/include/wx-2.8/wx/gtk/colordlg.h
%{root}/include/wx-2.8/wx/gtk/checkbox.h
%{root}/include/wx-2.8/wx/gtk/listbox.h
%{root}/include/wx-2.8/wx/gtk/checklst.h
%{root}/include/wx-2.8/wx/gtk/statline.h
%{root}/include/wx-2.8/wx/gtk/dataobj2.h
%{root}/include/wx-2.8/wx/gtk/statbmp.h
%{root}/include/wx-2.8/wx/gtk/statbox.h
%{root}/include/wx-2.8/wx/gtk/radiobox.h
%{root}/include/wx-2.8/wx/gtk/radiobut.h
%{root}/include/wx-2.8/wx/gtk/clipbrd.h
%{root}/include/wx-2.8/wx/gtk/animate.h
%{root}/include/wx-2.8/wx/gtk/stattext.h
%{root}/include/wx-2.8/wx/gtk/button.h
%{root}/include/wx-2.8/wx/gtk/toplevel.h
%{root}/include/wx-2.8/wx/gtk/minifram.h
%{root}/include/wx-2.8/wx/gtk/bmpbuttn.h
%{root}/include/wx-2.8/wx/gtk/msgdlg.h
%{root}/include/wx-2.8/wx/gtk/brush.h
%{root}/include/wx-2.8/wx/gtk/treectrl.h
%{root}/include/wx-2.8/wx/gtk/region.h
%{root}/include/wx-2.8/wx/xml/xml.h
%{root}/include/wx-2.8/wx/xrc/xh_filepicker.h
%{root}/include/wx-2.8/wx/xrc/xh_panel.h
%{root}/include/wx-2.8/wx/xrc/xh_spin.h
%{root}/include/wx-2.8/wx/xrc/xh_text.h
%{root}/include/wx-2.8/wx/xrc/xh_tree.h
%{root}/include/wx-2.8/wx/xrc/xh_dirpicker.h
%{root}/include/wx-2.8/wx/xrc/xh_clrpicker.h
%{root}/include/wx-2.8/wx/xrc/xh_collpane.h
%{root}/include/wx-2.8/wx/xrc/xh_bmpbt.h
%{root}/include/wx-2.8/wx/xrc/xh_datectrl.h
%{root}/include/wx-2.8/wx/xrc/xh_wizrd.h
%{root}/include/wx-2.8/wx/xrc/xh_chckb.h
%{root}/include/wx-2.8/wx/xrc/xh_chckl.h
%{root}/include/wx-2.8/wx/xrc/xh_choic.h
%{root}/include/wx-2.8/wx/xrc/xh_radbt.h
%{root}/include/wx-2.8/wx/xrc/xh_radbx.h
%{root}/include/wx-2.8/wx/xrc/xh_combo.h
%{root}/include/wx-2.8/wx/xrc/xh_bmpcbox.h
%{root}/include/wx-2.8/wx/xrc/xh_treebk.h
%{root}/include/wx-2.8/wx/xrc/xh_listbk.h
%{root}/include/wx-2.8/wx/xrc/xh_statbar.h
%{root}/include/wx-2.8/wx/xrc/xh_animatctrl.h
%{root}/include/wx-2.8/wx/xrc/xh_scrol.h
%{root}/include/wx-2.8/wx/xrc/xh_scwin.h
%{root}/include/wx-2.8/wx/xrc/xh_fontpicker.h
%{root}/include/wx-2.8/wx/xrc/xh_listb.h
%{root}/include/wx-2.8/wx/xrc/xh_listc.h
%{root}/include/wx-2.8/wx/xrc/xh_sizer.h
%{root}/include/wx-2.8/wx/xrc/xh_odcombo.h
%{root}/include/wx-2.8/wx/xrc/xh_slidr.h
%{root}/include/wx-2.8/wx/xrc/xh_split.h
%{root}/include/wx-2.8/wx/xrc/xh_stbmp.h
%{root}/include/wx-2.8/wx/xrc/xh_stbox.h
%{root}/include/wx-2.8/wx/xrc/xh_stlin.h
%{root}/include/wx-2.8/wx/xrc/xh_gauge.h
%{root}/include/wx-2.8/wx/xrc/xh_sttxt.h
%{root}/include/wx-2.8/wx/xrc/xh_gdctl.h
%{root}/include/wx-2.8/wx/xrc/xh_hyperlink.h
%{root}/include/wx-2.8/wx/xrc/xh_frame.h
%{root}/include/wx-2.8/wx/xrc/xmlres.h
%{root}/include/wx-2.8/wx/xrc/xh_toolb.h
%{root}/include/wx-2.8/wx/xrc/xh_cald.h
%{root}/include/wx-2.8/wx/xrc/xh_bttn.h
%{root}/include/wx-2.8/wx/xrc/xh_choicbk.h
%{root}/include/wx-2.8/wx/xrc/xh_tglbtn.h
%{root}/include/wx-2.8/wx/xrc/xh_all.h
%{root}/include/wx-2.8/wx/xrc/xh_bmp.h
%{root}/include/wx-2.8/wx/xrc/xh_dlg.h
%{root}/include/wx-2.8/wx/xrc/xh_htmllbox.h
%{root}/include/wx-2.8/wx/xrc/xh_grid.h
%{root}/include/wx-2.8/wx/xrc/xh_mdi.h
%{root}/include/wx-2.8/wx/xrc/xh_html.h
%{root}/include/wx-2.8/wx/xrc/xh_notbk.h
%{root}/include/wx-2.8/wx/xrc/xh_unkwn.h
%{root}/include/wx-2.8/wx/xrc/xh_menu.h
%{root}/include/wx-2.8/wx/db.h
%{root}/include/wx-2.8/wx/dc.h
%{root}/include/wx-2.8/wx/html/htmltag.h
%{root}/include/wx-2.8/wx/html/htmlwin.h
%{root}/include/wx-2.8/wx/html/m_templ.h
%{root}/include/wx-2.8/wx/html/forcelnk.h
%{root}/include/wx-2.8/wx/html/helpdata.h
%{root}/include/wx-2.8/wx/html/helpctrl.h
%{root}/include/wx-2.8/wx/html/winpars.h
%{root}/include/wx-2.8/wx/html/htmprint.h
%{root}/include/wx-2.8/wx/html/htmlcell.h
%{root}/include/wx-2.8/wx/html/htmldefs.h
%{root}/include/wx-2.8/wx/html/htmlfilt.h
%{root}/include/wx-2.8/wx/html/helpdlg.h
%{root}/include/wx-2.8/wx/html/helpfrm.h
%{root}/include/wx-2.8/wx/html/helpwnd.h
%{root}/include/wx-2.8/wx/html/htmlpars.h
%{root}/include/wx-2.8/wx/html/htmlproc.h
%{root}/include/wx-2.8/wx/unix/apptrait.h
%{root}/include/wx-2.8/wx/unix/private.h
%{root}/include/wx-2.8/wx/unix/sound.h
%{root}/include/wx-2.8/wx/unix/fontutil.h
%{root}/include/wx-2.8/wx/unix/taskbarx11.h
%{root}/include/wx-2.8/wx/unix/execute.h
%{root}/include/wx-2.8/wx/unix/pipe.h
%{root}/include/wx-2.8/wx/unix/stdpaths.h
%{root}/include/wx-2.8/wx/unix/apptbase.h
%{root}/include/wx-2.8/wx/unix/joystick.h
%{root}/include/wx-2.8/wx/unix/mimetype.h
%{root}/include/wx-2.8/wx/unix/stackwalk.h
%{root}/include/wx-2.8/wx/unix/utilsx11.h
%{root}/include/wx-2.8/wx/unix/gsockunx.h
%{root}/include/wx-2.8/wx/wx.h
%{root}/include/wx-2.8/wx/ownerdrw.h
%{root}/include/wx-2.8/wx/anidecod.h
%{root}/include/wx-2.8/wx/fontpicker.h
%{root}/include/wx-2.8/wx/filedlg.h
%{root}/include/wx-2.8/wx/dialog.h
%{root}/include/wx-2.8/wx/wupdlock.h
%{root}/include/wx-2.8/wx/dialup.h
%{root}/include/wx-2.8/wx/apptrait.h
%{root}/include/wx-2.8/wx/quantize.h
%{root}/include/wx-2.8/wx/combo.h
%{root}/include/wx-2.8/wx/debug.h
%{root}/include/wx-2.8/wx/strconv.h
%{root}/include/wx-2.8/wx/filesys.h
%{root}/include/wx-2.8/wx/palette.h
%{root}/include/wx-2.8/wx/display.h
%{root}/include/wx-2.8/wx/listimpl.cpp
%{root}/include/wx-2.8/wx/dcprint.h
%{root}/include/wx-2.8/wx/gsocket.h
%{root}/include/wx-2.8/wx/regex.h
%{root}/include/wx-2.8/wx/dlimpexp.h
%{root}/include/wx-2.8/wx/bitmap.h
%{root}/include/wx-2.8/wx/textctrl.h
%{root}/include/wx-2.8/wx/fontdlg.h
%{root}/include/wx-2.8/wx/fontenc.h
%{root}/include/wx-2.8/wx/dbgrid.h
%{root}/include/wx-2.8/wx/fontmap.h
%{root}/include/wx-2.8/wx/toolbook.h
%{root}/include/wx-2.8/wx/textfile.h
%{root}/include/wx-2.8/wx/app.h
%{root}/include/wx-2.8/wx/encconv.h
%{root}/include/wx-2.8/wx/dde.h
%{root}/include/wx-2.8/wx/cpp.h
%{root}/include/wx-2.8/wx/dir.h
%{root}/include/wx-2.8/wx/dnd.h
%{root}/include/wx-2.8/wx/ipc.h
%{root}/include/wx-2.8/wx/log.h
%{root}/include/wx-2.8/wx/mdi.h
%{root}/include/wx-2.8/wx/dbkeyg.h
%{root}/include/wx-2.8/wx/pen.h
%{root}/include/wx-2.8/wx/metafile.h
%{root}/include/wx-2.8/wx/tab.h
%{root}/include/wx-2.8/wx/helpbase.h
%{root}/include/wx-2.8/wx/uri.h
%{root}/include/wx-2.8/wx/url.h
%{root}/include/wx-2.8/wx/dcclient.h
%{root}/include/wx-2.8/wx/xti.h
%{root}/include/wx-2.8/wx/thrimpl.cpp
%{root}/include/wx-2.8/wx/fontenum.h
%{root}/include/wx-2.8/wx/vscroll.h
%{root}/include/wx-2.8/wx/overlay.h
%{root}/include/wx-2.8/wx/dcmemory.h
%{root}/include/wx-2.8/wx/vidmode.h
%{root}/include/wx-2.8/wx/collpane.h
%{root}/include/wx-2.8/wx/imagjpeg.h
%{root}/include/wx-2.8/wx/toolbar.h
%{root}/include/wx-2.8/wx/datectrl.h
%{root}/include/wx-2.8/wx/gdicmn.h
%{root}/include/wx-2.8/wx/iosfwrap.h
%{root}/include/wx-2.8/wx/imaglist.h
%{root}/include/wx-2.8/wx/encinfo.h
%{root}/include/wx-2.8/wx/gdiobj.h
%{root}/include/wx-2.8/wx/tooltip.h
%{root}/include/wx-2.8/wx/renderer.h
%{root}/include/wx-2.8/wx/tbarbase.h
%{root}/include/wx-2.8/wx/stopwatch.h
%{root}/include/wx-2.8/wx/dataobj.h
%{root}/include/wx-2.8/wx/spinbutt.h
%{root}/include/wx-2.8/wx/splash.h
%{root}/include/wx-2.8/wx/dirdlg.h
%{root}/include/wx-2.8/wx/helphtml.h
%{root}/include/wx-2.8/wx/spinctrl.h
%{root}/include/wx-2.8/wx/ptr_scpd.h
%{root}/include/wx-2.8/wx/fs_inet.h
%{root}/include/wx-2.8/wx/platform.h
%{root}/include/wx-2.8/wx/listbase.h
%{root}/include/wx-2.8/wx/recguard.h
%{root}/include/wx-2.8/wx/zipstrm.h
%{root}/include/wx-2.8/wx/dateevt.h
%{root}/include/wx-2.8/wx/clrpicker.h
%{root}/include/wx-2.8/wx/listbook.h
%{root}/include/wx-2.8/wx/sizer.h
%{root}/include/wx-2.8/wx/imagtiff.h
%{root}/include/wx-2.8/wx/geometry.h
%{root}/include/wx-2.8/wx/listctrl.h
%{root}/include/wx-2.8/wx/combobox.h
%{root}/include/wx-2.8/wx/platinfo.h
%{root}/include/wx-2.8/wx/confbase.h
%{root}/include/wx-2.8/wx/popupwin.h
%{root}/include/wx-2.8/wx/module.h
%{root}/include/wx-2.8/wx/vector.h
%{root}/include/wx-2.8/wx/scopeguard.h
%{root}/include/wx-2.8/wx/sckipc.h
%{root}/include/wx-2.8/wx/fileconf.h
%{root}/include/wx-2.8/wx/fdrepdlg.h
%{root}/include/wx-2.8/wx/ffile.h
%{root}/include/wx-2.8/wx/containr.h
%{root}/include/wx-2.8/wx/filefn.h
%{root}/include/wx-2.8/wx/variant.h
%{root}/include/wx-2.8/wx/sound.h
%{root}/include/wx-2.8/wx/fontutil.h
%{root}/include/wx-2.8/wx/access.h
%{root}/include/wx-2.8/wx/tarstrm.h
%{root}/include/wx-2.8/wx/fs_filter.h
%{root}/include/wx-2.8/wx/choicdlg.h
%{root}/include/wx-2.8/wx/choicebk.h
%{root}/include/wx-2.8/wx/docview.h
%{root}/include/wx-2.8/wx/datetime.h
%{root}/include/wx-2.8/wx/archive.h
%{root}/include/wx-2.8/wx/taskbar.h
%{root}/include/wx-2.8/wx/event.h
%{root}/include/wx-2.8/wx/control.h
%{root}/include/wx-2.8/wx/mstream.h
%{root}/include/wx-2.8/wx/cursor.h
%{root}/include/wx-2.8/wx/stack.h
%{root}/include/wx-2.8/wx/menuitem.h
%{root}/include/wx-2.8/wx/bookctrl.h
%{root}/include/wx-2.8/wx/timer.h
%{root}/include/wx-2.8/wx/validate.h
%{root}/include/wx-2.8/wx/mediactrl.h
%{root}/include/wx-2.8/wx/gauge.h
%{root}/include/wx-2.8/wx/xpmdecod.h
%{root}/include/wx-2.8/wx/dcps.h
%{root}/include/wx-2.8/wx/defs.h
%{root}/include/wx-2.8/wx/colour.h
%{root}/include/wx-2.8/wx/aboutdlg.h
%{root}/include/wx-2.8/wx/hashmap.h
%{root}/include/wx-2.8/wx/choice.h
%{root}/include/wx-2.8/wx/config.h
%{root}/include/wx-2.8/wx/hashset.h
%{root}/include/wx-2.8/wx/filename.h
%{root}/include/wx-2.8/wx/prntbase.h
%{root}/include/wx-2.8/wx/afterstd.h
%{root}/include/wx-2.8/wx/filepicker.h
%{root}/include/wx-2.8/wx/file.h
%{root}/include/wx-2.8/wx/generic/dcpsg.h
%{root}/include/wx-2.8/wx/generic/combo.h
%{root}/include/wx-2.8/wx/generic/collpaneg.h
%{root}/include/wx-2.8/wx/generic/textdlgg.h
%{root}/include/wx-2.8/wx/generic/aboutdlgg.h
%{root}/include/wx-2.8/wx/generic/fontdlgg.h
%{root}/include/wx-2.8/wx/generic/datectrl.h
%{root}/include/wx-2.8/wx/generic/imaglist.h
%{root}/include/wx-2.8/wx/generic/progdlgg.h
%{root}/include/wx-2.8/wx/generic/clrpickerg.h
%{root}/include/wx-2.8/wx/generic/splash.h
%{root}/include/wx-2.8/wx/generic/spinctlg.h
%{root}/include/wx-2.8/wx/generic/panelg.h
%{root}/include/wx-2.8/wx/generic/listctrl.h
%{root}/include/wx-2.8/wx/generic/fontpickerg.h
%{root}/include/wx-2.8/wx/generic/msgdlgg.h
%{root}/include/wx-2.8/wx/generic/fdrepdlg.h
%{root}/include/wx-2.8/wx/generic/filedlgg.h
%{root}/include/wx-2.8/wx/generic/filepickerg.h
%{root}/include/wx-2.8/wx/generic/choicdgg.h
%{root}/include/wx-2.8/wx/generic/buttonbar.h
%{root}/include/wx-2.8/wx/generic/timer.h
%{root}/include/wx-2.8/wx/generic/dirctrlg.h
%{root}/include/wx-2.8/wx/generic/grid.h
%{root}/include/wx-2.8/wx/generic/scrolwin.h
%{root}/include/wx-2.8/wx/generic/prntdlgg.h
%{root}/include/wx-2.8/wx/generic/icon.h
%{root}/include/wx-2.8/wx/generic/busyinfo.h
%{root}/include/wx-2.8/wx/generic/calctrl.h
%{root}/include/wx-2.8/wx/generic/splitter.h
%{root}/include/wx-2.8/wx/generic/logg.h
%{root}/include/wx-2.8/wx/generic/accel.h
%{root}/include/wx-2.8/wx/generic/paletteg.h
%{root}/include/wx-2.8/wx/generic/notebook.h
%{root}/include/wx-2.8/wx/generic/gridsel.h
%{root}/include/wx-2.8/wx/generic/tabg.h
%{root}/include/wx-2.8/wx/generic/bmpcbox.h
%{root}/include/wx-2.8/wx/generic/dirdlgg.h
%{root}/include/wx-2.8/wx/generic/wizard.h
%{root}/include/wx-2.8/wx/generic/sashwin.h
%{root}/include/wx-2.8/wx/generic/animate.h
%{root}/include/wx-2.8/wx/generic/dataview.h
%{root}/include/wx-2.8/wx/generic/caret.h
%{root}/include/wx-2.8/wx/generic/dragimgg.h
%{root}/include/wx-2.8/wx/generic/propdlg.h
%{root}/include/wx-2.8/wx/generic/statusbr.h
%{root}/include/wx-2.8/wx/generic/gridctrl.h
%{root}/include/wx-2.8/wx/generic/colrdlgg.h
%{root}/include/wx-2.8/wx/generic/helpext.h
%{root}/include/wx-2.8/wx/generic/treectlg.h
%{root}/include/wx-2.8/wx/generic/laywin.h
%{root}/include/wx-2.8/wx/generic/numdlgg.h
%{root}/include/wx-2.8/wx/generic/printps.h
%{root}/include/wx-2.8/wx/scrolbar.h
%{root}/include/wx-2.8/wx/datstrm.h
%{root}/include/wx-2.8/wx/font.h
%{root}/include/wx-2.8/wx/glcanvas.h
%{root}/include/wx-2.8/wx/frame.h
%{root}/include/wx-2.8/wx/animdecod.h
%{root}/include/wx-2.8/wx/matrix.h
%{root}/include/wx-2.8/wx/hash.h
%{root}/include/wx-2.8/wx/help.h
%{root}/include/wx-2.8/wx/grid.h
%{root}/include/wx-2.8/wx/txtstrm.h
%{root}/include/wx-2.8/wx/richtext/richtextbuffer.h
%{root}/include/wx-2.8/wx/richtext/richtextstyles.h
%{root}/include/wx-2.8/wx/richtext/richtextsymboldlg.h
%{root}/include/wx-2.8/wx/richtext/richtextxml.h
%{root}/include/wx-2.8/wx/richtext/richtextctrl.h
%{root}/include/wx-2.8/wx/richtext/richtextprint.h
%{root}/include/wx-2.8/wx/richtext/richtextstyledlg.h
%{root}/include/wx-2.8/wx/richtext/richtextformatdlg.h
%{root}/include/wx-2.8/wx/scrolwin.h
%{root}/include/wx-2.8/wx/icon.h
%{root}/include/wx-2.8/wx/gbsizer.h
%{root}/include/wx-2.8/wx/tglbtn.h
%{root}/include/wx-2.8/wx/settings.h
%{root}/include/wx-2.8/wx/tokenzr.h
%{root}/include/wx-2.8/wx/init.h
%{root}/include/wx-2.8/wx/intl.h
%{root}/include/wx-2.8/wx/dynlib.h
%{root}/include/wx-2.8/wx/busyinfo.h
%{root}/include/wx-2.8/wx/isql.h
%{root}/include/wx-2.8/wx/calctrl.h
%{root}/include/wx-2.8/wx/splitter.h
%{root}/include/wx-2.8/wx/imagbmp.h
%{root}/include/wx-2.8/wx/beforestd.h
%{root}/include/wx-2.8/wx/imaggif.h
%{root}/include/wx-2.8/wx/imagiff.h
%{root}/include/wx-2.8/wx/imagpcx.h
%{root}/include/wx-2.8/wx/imagpng.h
%{root}/include/wx-2.8/wx/imagpnm.h
%{root}/include/wx-2.8/wx/link.h
%{root}/include/wx-2.8/wx/list.h
%{root}/include/wx-2.8/wx/chkconf.h
%{root}/include/wx-2.8/wx/imagtga.h
%{root}/include/wx-2.8/wx/math.h
%{root}/include/wx-2.8/wx/menu.h
%{root}/include/wx-2.8/wx/imagxpm.h
%{root}/include/wx-2.8/wx/accel.h
%{root}/include/wx-2.8/wx/ioswrap.h
%{root}/include/wx-2.8/wx/evtloop.h
%{root}/include/wx-2.8/wx/wfstream.h
%{root}/include/wx-2.8/wx/rawbmp.h
%{root}/include/wx-2.8/wx/notebook.h
%{root}/include/wx-2.8/wx/snglinst.h
%{root}/include/wx-2.8/wx/dcscreen.h
%{root}/include/wx-2.8/wx/slider.h
%{root}/include/wx-2.8/wx/display_impl.h
%{root}/include/wx-2.8/wx/isqlext.h
%{root}/include/wx-2.8/wx/window.h
%{root}/include/wx-2.8/wx/textbuf.h
%{root}/include/wx-2.8/wx/valtext.h
%{root}/include/wx-2.8/wx/textdlg.h
%{root}/include/wx-2.8/wx/colordlg.h
%{root}/include/wx-2.8/wx/buffer.h
%{root}/include/wx-2.8/wx/fs_arc.h
%{root}/include/wx-2.8/wx/cmdline.h
%{root}/include/wx-2.8/wx/types.h
%{root}/include/wx-2.8/wx/checkbox.h
%{root}/include/wx-2.8/wx/selstore.h
%{root}/include/wx-2.8/wx/listbox.h
%{root}/include/wx-2.8/wx/fs_mem.h
%{root}/include/wx-2.8/wx/convauto.h
%{root}/include/wx-2.8/wx/ipcbase.h
%{root}/include/wx-2.8/wx/sysopt.h
%{root}/include/wx-2.8/wx/checklst.h
%{root}/include/wx-2.8/wx/fs_zip.h
%{root}/include/wx-2.8/wx/clntdata.h
%{root}/include/wx-2.8/wx/wxchar.h
%{root}/include/wx-2.8/wx/process.h
%{root}/include/wx-2.8/wx/object.h
%{root}/include/wx-2.8/wx/wave.h
%{root}/include/wx-2.8/wx/bmpcbox.h
%{root}/include/wx-2.8/wx/cmdproc.h
%{root}/include/wx-2.8/wx/iconloc.h
%{root}/include/wx-2.8/wx/utils.h
%{root}/include/wx-2.8/wx/sckaddr.h
%{root}/include/wx-2.8/wx/stockitem.h
%{root}/include/wx-2.8/wx/statline.h
%{root}/include/wx-2.8/wx/progdlg.h
%{root}/include/wx-2.8/wx/memconf.h
%{root}/include/wx-2.8/wx/panel.h
%{root}/include/wx-2.8/wx/paper.h
%{root}/include/wx-2.8/wx/dcgraph.h
%{root}/include/wx-2.8/wx/vlbox.h
%{root}/include/wx-2.8/wx/thread.h
%{root}/include/wx-2.8/wx/vms_x_fix.h
%{root}/include/wx-2.8/wx/wxhtml.h
%{root}/include/wx-2.8/wx/dirctrl.h
%{root}/include/wx-2.8/wx/iconbndl.h
%{root}/include/wx-2.8/wx/statbmp.h
%{root}/include/wx-2.8/wx/statbox.h
%{root}/include/wx-2.8/wx/xtistrm.h
%{root}/include/wx-2.8/wx/arrstr.h
%{root}/include/wx-2.8/wx/wizard.h
%{root}/include/wx-2.8/wx/effects.h
%{root}/include/wx-2.8/wx/xtixml.h
%{root}/include/wx-2.8/wx/protocol/ftp.h
%{root}/include/wx-2.8/wx/protocol/protocol.h
%{root}/include/wx-2.8/wx/protocol/file.h
%{root}/include/wx-2.8/wx/protocol/http.h
%{root}/include/wx-2.8/wx/xpmhand.h
%{root}/include/wx-2.8/wx/radiobox.h
%{root}/include/wx-2.8/wx/radiobut.h
%{root}/include/wx-2.8/wx/stdpaths.h
%{root}/include/wx-2.8/wx/sashwin.h
%{root}/include/wx-2.8/wx/dcmirror.h
%{root}/include/wx-2.8/wx/clipbrd.h
%{root}/include/wx-2.8/wx/dbtable.h
%{root}/include/wx-2.8/wx/dcbuffer.h
%{root}/include/wx-2.8/wx/fmappriv.h
%{root}/include/wx-2.8/wx/except.h
%{root}/include/wx-2.8/wx/animate.h
%{root}/include/wx-2.8/wx/stattext.h
%{root}/include/wx-2.8/wx/tabctrl.h
%{root}/include/wx-2.8/wx/dataview.h
%{root}/include/wx-2.8/wx/button.h
%{root}/include/wx-2.8/wx/dynarray.h
%{root}/include/wx-2.8/wx/printdlg.h
%{root}/include/wx-2.8/wx/longlong.h
%{root}/include/wx-2.8/wx/arrimpl.cpp
%{root}/include/wx-2.8/wx/pickerbase.h
%{root}/include/wx-2.8/wx/valgen.h
%{root}/include/wx-2.8/wx/toplevel.h
%{root}/include/wx-2.8/wx/dragimag.h
%{root}/include/wx-2.8/wx/caret.h
%{root}/include/wx-2.8/wx/propdlg.h
%{root}/include/wx-2.8/wx/image.h
%{root}/include/wx-2.8/wx/wxprec.h
%{root}/include/wx-2.8/wx/statusbr.h
%{root}/include/wx-2.8/wx/joystick.h
%{root}/include/wx-2.8/wx/tipdlg.h
%{root}/include/wx-2.8/wx/gifdecod.h
%{root}/include/wx-2.8/wx/tipwin.h
%{root}/include/wx-2.8/wx/version.h
%{root}/include/wx-2.8/wx/zstream.h
%{root}/include/wx-2.8/wx/numdlg.h
%{root}/include/wx-2.8/wx/graphics.h
%{root}/include/wx-2.8/wx/volume.h
%{root}/include/wx-2.8/wx/minifram.h
%{root}/include/wx-2.8/wx/htmllbox.h
%{root}/include/wx-2.8/wx/stream.h
%{root}/include/wx-2.8/wx/treebase.h
%{root}/include/wx-2.8/wx/string.h
%{root}/include/wx-2.8/wx/hyperlink.h
%{root}/include/wx-2.8/wx/bmpbuttn.h
%{root}/include/wx-2.8/wx/mimetype.h
%{root}/include/wx-2.8/wx/sstream.h
%{root}/include/wx-2.8/wx/treebook.h
%{root}/include/wx-2.8/wx/docmdi.h
%{root}/include/wx-2.8/wx/features.h
%{root}/include/wx-2.8/wx/msgdlg.h
%{root}/include/wx-2.8/wx/dynload.h
%{root}/include/wx-2.8/wx/brush.h
%{root}/include/wx-2.8/wx/stackwalk.h
%{root}/include/wx-2.8/wx/helpwin.h
%{root}/include/wx-2.8/wx/power.h
%{root}/include/wx-2.8/wx/treectrl.h
%{root}/include/wx-2.8/wx/msgout.h
%{root}/include/wx-2.8/wx/memtext.h
%{root}/include/wx-2.8/wx/build.h
%{root}/include/wx-2.8/wx/layout.h
%{root}/include/wx-2.8/wx/print.h
%{root}/include/wx-2.8/wx/laywin.h
%{root}/include/wx-2.8/wx/cshelp.h
%{root}/include/wx-2.8/wx/ctrlsub.h
%{root}/include/wx-2.8/wx/socket.h
%{root}/include/wx-2.8/wx/region.h
%{root}/include/wx-2.8/wx/cmndata.h
%{root}/include/wx-2.8/wx/memory.h
%{root}/include/wx-2.8/wx/sckstrm.h
%{root}/include/wx-2.8/wx/odcombo.h
