##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform poco_options' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'TankPlugin' ) )
TankPluginDir = pj( RootDir, 'share', 'examples', 'TankPlugin' )

iveFile = sca_util.getFilesRecursiveByExt( TankPluginDir, [ '.ive' ] )
vsFile = sca_util.getFilesRecursiveByExt( TankPluginDir, [ '.vs' ] )
fsFile = sca_util.getFilesRecursiveByExt( TankPluginDir, [ '.fs' ] )
fileBundle.addFiles( iveFile )
fileBundle.addFiles( vsFile )
fileBundle.addFiles( fsFile )

TankPluginSubdirs = Split("""
    UserInterface
    GraphicalPlugin
""")

##Run SConscript files in all of these folders.
for d in TankPluginSubdirs:
   SConscript( dirs = d )
