##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform poco_options' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'dynamic_vehicle_sim_tool' ) )
WarrantyToolDir = pj( RootDir, 'share', 'examples', 'dynamic_vehicle_sim_tool' )

#fileBundle.addFiles( [ 'warrantytool.ves' ] )
#iveFile = sca_util.getFilesRecursiveByExt( WarrantyToolDir, [ '.ive' ] )
#fileBundle.addFiles( iveFile )

WarrantyToolSubdirs = Split("""
    UserInterface
    GraphicalPlugin
    test
""")

##Run SConscript files in all of these folders.
for d in WarrantyToolSubdirs:
   SConscript( dirs = d )
