##Install aspen libraries, apps, and icons

Import( 'GetPlatform' )

aspenSubdirs = Split("""
    3DIcons
""")

if GetPlatform() == 'win32':
   aspenSubdirs += Split("""    
      CASILib
      VE_AspenUnit
   """)


##Run SConscript files in all of those folders.
for d in aspenSubdirs:
   SConscript( dirs = d )
