##Builds VE-Suite Libraries
#import os
#pj = os.path.join

aspenSubdirs = Split("""
    CASILib
    VE_AspenUnit
""")

##Run SConscript files in all of those folders.
for d in aspenSubdirs:
   SConscript( dirs = d )
