import os, sys, string
#import xerces
pj = os.path.join

Import('baseEnv')
Import('libPath')
Import('xerces')


srcs = Split("""
   interface.cpp 
   package.cpp 
   string_ops.cpp 
   GeometryDataBuffer.cpp
""")

srcs = map(lambda s: pj('#', 'VE_Conductor', 'Network', s), srcs)

##srcs = list()
##srcs.extend(srcs)

env = baseEnv.Copy()
#env.Append(CPPPATH = [os.getcwd()])
env.Append(CPPPATH = ['#'])
env.Append(LIBPATH = libPath,
              LIBS = 'VE_XMLLib')
for lib in xerces:
   env.Append(LIBS = lib)
targetLib = pj(libPath, 'VE_ConductorLib')
env.SharedLibrary(target = targetLib, source = srcs)

#env.Program(pj('#','bin',Platform,'VE_CE'), source = srcs)




