##Builds VE_ConductorLib
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR buildDir xerces_options')

sources = Split("""
   string_ops.cxx 
""")

headers = Split("""
   string_ops.h 
""")

##srcs = map(lambda s: pj('#', 'VE_Conductor', 'Network', s), srcs)

lib_env = ves_pkg.getEnv().Copy()
#lib_env.Append(LIBS = 'VE_XML')
#lib_env.Append(LIBPATH = [pj('#', buildDir, 'VE_Open','XML')])
xerces_options.apply( lib_env )

if baseEnv['StaticOnly'] == "no":
   lib = ves_pkg.createStaticAndSharedLibrary('VE_ConductorLib',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createStaticLibrary('VE_ConductorLib', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Conductor', 'Network'))
lib.build()



