##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform poco_options' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'constraint_demo' ) )
ConstraintDemoDir = pj( RootDir, 'share', 'examples', 'constraint_demo' )

fileBundle.addFiles( [ 'constraint_demo.db' ] )
fileBundle.addFiles( [ 'constraint_demo.ves' ] )
iveFile = sca_util.getFilesRecursiveByExt( ConstraintDemoDir, [ '.ive' ] )
fileBundle.addFiles( iveFile )

ConstraintDemoSubdirs = Split("""
    UserInterface
    GraphicalPlugin
""")

##Run SConscript files in all of these folders.
for d in ConstraintDemoSubdirs:
   SConscript( dirs = d )
