##Builds InteractiveStove Graphical Plugin
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import('RootDir ves_pkg buildDir GetPlatform vtk_options vrjuggler_options boost_options bullet_options osg_options xerces_options')

srcs = Split("""
   VEIntStovemod.cxx
""")

headers = Split("""
   VEIntStovemod.h
""")

lib_env = ves_pkg.getEnv().Copy()
lib_env. AppendUnique( LIBS = [ 'ves_xplorer',
                         'ves_xplorer_scenegraph' ] )
lib_env.AppendUnique( LIBPATH = [ pj('#', buildDir, 'src','ves','xplorer'),
		            pj('#', buildDir, 'src','ves','xplorer','scenegraph') ] )
lib_env.Append( CPPDEFINES = [ 'VE_USER_PLUGIN_LIBRARY' ] )


vtk_options.apply( lib_env )
osg_options.apply( lib_env )
xerces_options.apply( lib_env )
vrjuggler_options.apply( lib_env )
boost_options.apply( lib_env )
bullet_options.apply( lib_env )

if GetPlatform() == 'darwin':
   lib_env['SHLINKFLAGS'] = '$LINKFLAGS -bundle -flat_namespace'
   lib_env['SHLIBSUFFIX'] = '.dylib'

lib = ves_pkg.createSharedLibrary( 'InteractiveStoveGP', lib_env,
    installPrefix = pj( 'share', 'vesuite', 'examples', 'InteractiveStove', 'Plugins', 'GE', host_type ) ) 

lib.addSources(srcs)
lib.build()
