##Builds idl skeleton files for veopen
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg', 'RootDir')
env = ves_pkg.getEnv().Copy()

launcherBundle = ves_pkg.createFileBundle( 'bin' )
pyFile = sca_util.getFilesRecursiveByExt( '.', ['.py'] )
pyFile += sca_util.getFilesRecursiveByExt( '.', ['.xpm'] )
pyFile += sca_util.getFilesRecursiveByExt( '.', ['.bmp'] )
pyFile += sca_util.getFilesRecursiveByExt( '.', ['.png'] )
runScripts = ['vesuiteReboot.sh',
              'vesuiteWake.sh',
              'vesuiteShutdown.sh',
              'velauncher.sh',
              'clearCluster.sh', ]
iconScripts = ['vesuiteConfig.sh',
               'vesuiteGnomeConfig.sh',
               'vesuiteKdeConfig.sh' ]

launcherBundle.addFiles( runScripts )
launcherBundle.addFiles( pyFile )

linuxDClick = ves_pkg.createFileBundle( pj('share','vesuite','misc' ) )
dclickFiles = sca_util.getFilesRecursiveByExt( pj(RootDir,'VE_Installer','installer','LinuxConfig'), ['.xml'] )
dclickFiles += sca_util.getFilesRecursiveByExt( pj(RootDir,'VE_Installer','installer','LinuxConfig'), ['.desktop'] )
dclickFiles += sca_util.getFilesRecursiveByExt( pj(RootDir,'VE_Installer','installer','LinuxConfig'), ['.sh'] )
dclickFiles += sca_util.getFilesRecursiveByExt( pj(RootDir,'VE_Installer','installer','LinuxConfig'), ['.png'] )

dclickFiles = map(lambda s: pj('LinuxConfig', s), dclickFiles)

linuxDClick.addFiles( dclickFiles )
linuxDClick.addFiles( iconScripts )
