##Builds idl skeleton files for veopen
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg')

launcherBundle = ves_pkg.createFileBundle( 'bin' )
pyFile = sca_util.getFilesRecursiveByExt( '.', ['.py'] )
pyFile += sca_util.getFilesRecursiveByExt( '.', ['.xpm'] )
pyFile += sca_util.getFilesRecursiveByExt( '.', ['.bmp'] )
pyFile += sca_util.getFilesRecursiveByExt( '.', ['.png'] )
launcherBundle.addFiles( pyFile )

linuxDClick = ves_pkg.createFileBundle( pj('share','vesuite','misc' ) )
dclickFiles = ['vesuiteGnomeConfig.sh',
		'VE-Suite.xml',
		'vesuite.desktop',
		pj('installerImages','gnome-mime-application-x-vesuite.png'),
		'vesuiteKdeConfig.sh',
		'ves.desktop']
linuxDClick.addFiles( dclickFiles )
