#!/bin/sh
#Soften: Corrects the paths for the libraries made for
#VE-Launcher's Linux self-executable.

cd dist
for i in *.so
do
	if chrpath $i 2>/dev/null | grep = >/dev/null
	then
		echo "Fixing $i"
		chrpath -d $i
	fi
done
cd ..
