/* cmn_io.h -- index + size for cmn variables used by the IECM interface */
/* Generated from 'd:\CMU\Models\Archive\IECM\Source\402 CS\c\veggy\interface\interface_igcc.cfg' on 03/19/04 12:02:26. */
/* Version IECM Interface 4.0.1 */

/* Output Variables */
#define CMN_SZ_OUT 12
#define CMN_IDX_OUT_HOURS_YR 0
#define CMN_SZ_OUT_HOURS_YR 1
#define CMN_IDX_OUT_MW_GROSS 1
#define CMN_SZ_OUT_MW_GROSS 1
#define CMN_IDX_OUT_MW_NET 2
#define CMN_SZ_OUT_MW_NET 1
#define CMN_IDX_OUT_NET_EFF 3
#define CMN_SZ_OUT_NET_EFF 1
#define CMN_IDX_OUT_MWH_YR 4
#define CMN_SZ_OUT_MWH_YR 1
#define CMN_IDX_OUT_BKWH_YR 5
#define CMN_SZ_OUT_BKWH_YR 1
#define CMN_IDX_OUT_ELEC_TOT 6
#define CMN_SZ_OUT_ELEC_TOT 1
#define CMN_IDX_OUT_FUELTYPE_CTL 7
#define CMN_SZ_OUT_FUELTYPE_CTL 1
#define CMN_IDX_OUT_FCF 8
#define CMN_SZ_OUT_FCF 1
#define CMN_IDX_OUT_VCLF 9
#define CMN_SZ_OUT_VCLF 1
#define CMN_IDX_OUT_BOOK_LIFE 10
#define CMN_SZ_OUT_BOOK_LIFE 1
#define CMN_IDX_OUT_COST_YR 11
#define CMN_SZ_OUT_COST_YR 1

/* Input Variables */
#define CMN_SZ_IN 132
#define CMN_IDX_IN_TAX_PROP 0
#define CMN_SZ_IN_TAX_PROP 1
#define CMN_IDX_IN_BOOK_LIFE 1
#define CMN_SZ_IN_BOOK_LIFE 1
#define CMN_IDX_IN_DEBT_RATIO 2
#define CMN_SZ_IN_DEBT_RATIO 1
#define CMN_IDX_IN_TAX_FED 3
#define CMN_SZ_IN_TAX_FED 1
#define CMN_IDX_IN_ITC 4
#define CMN_SZ_IN_ITC 1
#define CMN_IDX_IN_PREF_RATIO 5
#define CMN_SZ_IN_PREF_RATIO 1
#define CMN_IDX_IN_REAL_BOND 6
#define CMN_SZ_IN_REAL_BOND 1
#define CMN_IDX_IN_COM_STOCK 7
#define CMN_SZ_IN_COM_STOCK 1
#define CMN_IDX_IN_REAL_ESC 8
#define CMN_SZ_IN_REAL_ESC 1
#define CMN_IDX_IN_PREF_STOCK 9
#define CMN_SZ_IN_PREF_STOCK 1
#define CMN_IDX_IN_TAX_STATE 10
#define CMN_SZ_IN_TAX_STATE 1
#define CMN_IDX_IN_COM_RATIO 11
#define CMN_SZ_IN_COM_RATIO 3
#define CMN_IDX_IN_FCF 14
#define CMN_SZ_IN_FCF 3
#define CMN_IDX_IN_INF 17
#define CMN_SZ_IN_INF 3
#define CMN_IDX_IN_COST_YR 20
#define CMN_SZ_IN_COST_YR 1
#define CMN_IDX_IN_INFLAT_CTL 21
#define CMN_SZ_IN_INFLAT_CTL 1
#define CMN_IDX_IN_COAL_IDX 22
#define CMN_SZ_IN_COAL_IDX 1
#define CMN_IDX_IN_COAL_COST 23
#define CMN_SZ_IN_COAL_COST 1
#define CMN_IDX_IN_COAL_HHV 24
#define CMN_SZ_IN_COAL_HHV 1
#define CMN_IDX_IN_COAL_C 25
#define CMN_SZ_IN_COAL_C 1
#define CMN_IDX_IN_COAL_H 26
#define CMN_SZ_IN_COAL_H 1
#define CMN_IDX_IN_COAL_O 27
#define CMN_SZ_IN_COAL_O 1
#define CMN_IDX_IN_COAL_CL 28
#define CMN_SZ_IN_COAL_CL 1
#define CMN_IDX_IN_COAL_S 29
#define CMN_SZ_IN_COAL_S 1
#define CMN_IDX_IN_COAL_N 30
#define CMN_SZ_IN_COAL_N 1
#define CMN_IDX_IN_COAL_ASH 31
#define CMN_SZ_IN_COAL_ASH 1
#define CMN_IDX_IN_COAL_H2O 32
#define CMN_SZ_IN_COAL_H2O 1
#define CMN_IDX_IN_ASH_SIO2 33
#define CMN_SZ_IN_ASH_SIO2 1
#define CMN_IDX_IN_ASH_AL2O3 34
#define CMN_SZ_IN_ASH_AL2O3 1
#define CMN_IDX_IN_ASH_FE2O3 35
#define CMN_SZ_IN_ASH_FE2O3 1
#define CMN_IDX_IN_ASH_CAO 36
#define CMN_SZ_IN_ASH_CAO 1
#define CMN_IDX_IN_ASH_MGO 37
#define CMN_SZ_IN_ASH_MGO 1
#define CMN_IDX_IN_ASH_NA2O 38
#define CMN_SZ_IN_ASH_NA2O 1
#define CMN_IDX_IN_ASH_K2O 39
#define CMN_SZ_IN_ASH_K2O 1
#define CMN_IDX_IN_ASH_TIO2 40
#define CMN_SZ_IN_ASH_TIO2 1
#define CMN_IDX_IN_ASH_P2O5 41
#define CMN_SZ_IN_ASH_P2O5 1
#define CMN_IDX_IN_ASH_SO3 42
#define CMN_SZ_IN_ASH_SO3 1
#define CMN_IDX_IN_ASH_MNO2 43
#define CMN_SZ_IN_ASH_MNO2 1
#define CMN_IDX_IN_DISCOUNT 44
#define CMN_SZ_IN_DISCOUNT 3
#define CMN_IDX_IN_WAGES 47
#define CMN_SZ_IN_WAGES 1
#define CMN_IDX_IN_NGAS_CST 48
#define CMN_SZ_IN_NGAS_CST 3
#define CMN_IDX_IN_H2O_CST 51
#define CMN_SZ_IN_H2O_CST 3
#define CMN_IDX_IN_CARBON_CST 54
#define CMN_SZ_IN_CARBON_CST 3
#define CMN_IDX_IN_NH3_CST 57
#define CMN_SZ_IN_NH3_CST 3
#define CMN_IDX_IN_LIME_CST 60
#define CMN_SZ_IN_LIME_CST 3
#define CMN_IDX_IN_LS_CST 63
#define CMN_SZ_IN_LS_CST 3
#define CMN_IDX_IN_UREA_CST 66
#define CMN_SZ_IN_UREA_CST 3
#define CMN_IDX_IN_LOX_CST 69
#define CMN_SZ_IN_LOX_CST 3
#define CMN_IDX_IN_OIL2_CST 72
#define CMN_SZ_IN_OIL2_CST 3
#define CMN_IDX_IN_OIL6_CST 75
#define CMN_SZ_IN_OIL6_CST 3
#define CMN_IDX_IN_MIBC_CST 78
#define CMN_SZ_IN_MIBC_CST 3
#define CMN_IDX_IN_SACID_CST 81
#define CMN_SZ_IN_SACID_CST 3
#define CMN_IDX_IN_S_CST 84
#define CMN_SZ_IN_S_CST 3
#define CMN_IDX_IN_CO2_CST 87
#define CMN_SZ_IN_CO2_CST 3
#define CMN_IDX_IN_MEA_CST 90
#define CMN_SZ_IN_MEA_CST 3
#define CMN_IDX_IN_NAOH_CST 93
#define CMN_SZ_IN_NAOH_CST 3
#define CMN_IDX_IN_PRES_AIR 96
#define CMN_SZ_IN_PRES_AIR 1
#define CMN_IDX_IN_TMP_AIR 97
#define CMN_SZ_IN_TMP_AIR 1
#define CMN_IDX_IN_CF 98
#define CMN_SZ_IN_CF 1
#define CMN_IDX_IN_MW_GROSS 99
#define CMN_SZ_IN_MW_GROSS 3
#define CMN_IDX_IN_FUELTYPE_MENU 102
#define CMN_SZ_IN_FUELTYPE_MENU 1
#define CMN_IDX_IN_OIL_IDX 103
#define CMN_SZ_IN_OIL_IDX 1
#define CMN_IDX_IN_OIL_HHV 104
#define CMN_SZ_IN_OIL_HHV 1
#define CMN_IDX_IN_OIL_C 105
#define CMN_SZ_IN_OIL_C 1
#define CMN_IDX_IN_OIL_H 106
#define CMN_SZ_IN_OIL_H 1
#define CMN_IDX_IN_OIL_O 107
#define CMN_SZ_IN_OIL_O 1
#define CMN_IDX_IN_OIL_CL 108
#define CMN_SZ_IN_OIL_CL 1
#define CMN_IDX_IN_OIL_S 109
#define CMN_SZ_IN_OIL_S 1
#define CMN_IDX_IN_OIL_N 110
#define CMN_SZ_IN_OIL_N 1
#define CMN_IDX_IN_OIL_ASH 111
#define CMN_SZ_IN_OIL_ASH 1
#define CMN_IDX_IN_OIL_H2O 112
#define CMN_SZ_IN_OIL_H2O 1
#define CMN_IDX_IN_GAS_IDX 113
#define CMN_SZ_IN_GAS_IDX 1
#define CMN_IDX_IN_GAS_HHV 114
#define CMN_SZ_IN_GAS_HHV 1
#define CMN_IDX_IN_GAS_C 115
#define CMN_SZ_IN_GAS_C 1
#define CMN_IDX_IN_GAS_H 116
#define CMN_SZ_IN_GAS_H 1
#define CMN_IDX_IN_GAS_O 117
#define CMN_SZ_IN_GAS_O 1
#define CMN_IDX_IN_GAS_CL 118
#define CMN_SZ_IN_GAS_CL 1
#define CMN_IDX_IN_GAS_S 119
#define CMN_SZ_IN_GAS_S 1
#define CMN_IDX_IN_GAS_N 120
#define CMN_SZ_IN_GAS_N 1
#define CMN_IDX_IN_GAS_ASH 121
#define CMN_SZ_IN_GAS_ASH 1
#define CMN_IDX_IN_GAS_H2O 122
#define CMN_SZ_IN_GAS_H2O 1
#define CMN_IDX_IN_FUELTYPE_CTL 123
#define CMN_SZ_IN_FUELTYPE_CTL 3
#define CMN_IDX_IN_NGAS_DENS 126
#define CMN_SZ_IN_NGAS_DENS 3
#define CMN_IDX_IN_MW_NET 129
#define CMN_SZ_IN_MW_NET 3

/* Calculated Variables */
#define CMN_SZ_CALC 24
#define CMN_IDX_CALC_COM_RATIO 0
#define CMN_SZ_CALC_COM_RATIO 1
#define CMN_IDX_CALC_FCF 1
#define CMN_SZ_CALC_FCF 1
#define CMN_IDX_CALC_INF 2
#define CMN_SZ_CALC_INF 1
#define CMN_IDX_CALC_DISCOUNT 3
#define CMN_SZ_CALC_DISCOUNT 1
#define CMN_IDX_CALC_NGAS_CST 4
#define CMN_SZ_CALC_NGAS_CST 1
#define CMN_IDX_CALC_H2O_CST 5
#define CMN_SZ_CALC_H2O_CST 1
#define CMN_IDX_CALC_CARBON_CST 6
#define CMN_SZ_CALC_CARBON_CST 1
#define CMN_IDX_CALC_NH3_CST 7
#define CMN_SZ_CALC_NH3_CST 1
#define CMN_IDX_CALC_LIME_CST 8
#define CMN_SZ_CALC_LIME_CST 1
#define CMN_IDX_CALC_LS_CST 9
#define CMN_SZ_CALC_LS_CST 1
#define CMN_IDX_CALC_UREA_CST 10
#define CMN_SZ_CALC_UREA_CST 1
#define CMN_IDX_CALC_LOX_CST 11
#define CMN_SZ_CALC_LOX_CST 1
#define CMN_IDX_CALC_OIL2_CST 12
#define CMN_SZ_CALC_OIL2_CST 1
#define CMN_IDX_CALC_OIL6_CST 13
#define CMN_SZ_CALC_OIL6_CST 1
#define CMN_IDX_CALC_MIBC_CST 14
#define CMN_SZ_CALC_MIBC_CST 1
#define CMN_IDX_CALC_SACID_CST 15
#define CMN_SZ_CALC_SACID_CST 1
#define CMN_IDX_CALC_S_CST 16
#define CMN_SZ_CALC_S_CST 1
#define CMN_IDX_CALC_CO2_CST 17
#define CMN_SZ_CALC_CO2_CST 1
#define CMN_IDX_CALC_MEA_CST 18
#define CMN_SZ_CALC_MEA_CST 1
#define CMN_IDX_CALC_NAOH_CST 19
#define CMN_SZ_CALC_NAOH_CST 1
#define CMN_IDX_CALC_MW_GROSS 20
#define CMN_SZ_CALC_MW_GROSS 1
#define CMN_IDX_CALC_FUELTYPE_CTL 21
#define CMN_SZ_CALC_FUELTYPE_CTL 1
#define CMN_IDX_CALC_NGAS_DENS 22
#define CMN_SZ_CALC_NGAS_DENS 1
#define CMN_IDX_CALC_MW_NET 23
#define CMN_SZ_CALC_MW_NET 1
