/* gts_io.h -- index + size for gts variables used by the IECM interface */
/* Generated from 'd:\CMU\Models\DOE\c\veggy\interface\interface_igcc.cfg' on 12/09/03 13:02:01. */
/* Version IECM Interface 4.0.1 */

/* Output Variables */
#define GTS_SZ_OUT 172
#define GTS_IDX_OUT_MW 0
#define GTS_SZ_OUT_MW 1
#define GTS_IDX_OUT_MW_GEN 1
#define GTS_SZ_OUT_MW_GEN 1
#define GTS_IDX_OUT_MW_COMP 2
#define GTS_SZ_OUT_MW_COMP 1
#define GTS_IDX_OUT_MW_TURB 3
#define GTS_SZ_OUT_MW_TURB 1
#define GTS_IDX_OUT_MW_HRSG 4
#define GTS_SZ_OUT_MW_HRSG 1
#define GTS_IDX_OUT_MW_LOSS 5
#define GTS_SZ_OUT_MW_LOSS 1
#define GTS_IDX_OUT_SCYC_EFF 6
#define GTS_SZ_OUT_SCYC_EFF 1
#define GTS_IDX_OUT_CCYC_EFF 7
#define GTS_SZ_OUT_CCYC_EFF 1
#define GTS_IDX_OUT_PFC 8
#define GTS_SZ_OUT_PFC 1
#define GTS_IDX_OUT_GFC 9
#define GTS_SZ_OUT_GFC 1
#define GTS_IDX_OUT_EHO 10
#define GTS_SZ_OUT_EHO 1
#define GTS_IDX_OUT_PROJCONT 11
#define GTS_SZ_OUT_PROJCONT 1
#define GTS_IDX_OUT_PROCCONT 12
#define GTS_SZ_OUT_PROCCONT 1
#define GTS_IDX_OUT_INT 13
#define GTS_SZ_OUT_INT 1
#define GTS_IDX_OUT_ROYALTY 14
#define GTS_SZ_OUT_ROYALTY 1
#define GTS_IDX_OUT_PREPROD 15
#define GTS_SZ_OUT_PREPROD 1
#define GTS_IDX_OUT_INV 16
#define GTS_SZ_OUT_INV 1
#define GTS_IDX_OUT_TCR 17
#define GTS_SZ_OUT_TCR 1
#define GTS_IDX_OUT_TCR_EFF 18
#define GTS_SZ_OUT_TCR_EFF 1
#define GTS_IDX_OUT_OPLAB 19
#define GTS_SZ_OUT_OPLAB 1
#define GTS_IDX_OUT_MNTLAB 20
#define GTS_SZ_OUT_MNTLAB 1
#define GTS_IDX_OUT_MNTMATL 21
#define GTS_SZ_OUT_MNTMATL 1
#define GTS_IDX_OUT_ADMIN 22
#define GTS_SZ_OUT_ADMIN 1
#define GTS_IDX_OUT_OM_FIX 23
#define GTS_SZ_OUT_OM_FIX 1
#define GTS_IDX_OUT_UTIL 24
#define GTS_SZ_OUT_UTIL 1
#define GTS_IDX_OUT_NGAS_CST 25
#define GTS_SZ_OUT_NGAS_CST 1
#define GTS_IDX_OUT_OM_VAR 26
#define GTS_SZ_OUT_OM_VAR 1
#define GTS_IDX_OUT_OM 27
#define GTS_SZ_OUT_OM 1
#define GTS_IDX_OUT_1 28
#define GTS_SZ_OUT_1 1
#define GTS_IDX_OUT_2 29
#define GTS_SZ_OUT_2 1
#define GTS_IDX_OUT_3 30
#define GTS_SZ_OUT_3 1
#define GTS_IDX_OUT_4 31
#define GTS_SZ_OUT_4 1
#define GTS_IDX_OUT_5 32
#define GTS_SZ_OUT_5 1
#define GTS_IDX_OUT_6 33
#define GTS_SZ_OUT_6 1
#define GTS_IDX_OUT_7 34
#define GTS_SZ_OUT_7 1
#define GTS_IDX_OUT_8 35
#define GTS_SZ_OUT_8 1
#define GTS_IDX_OUT_9 36
#define GTS_SZ_OUT_9 1
#define GTS_IDX_OUT_10 37
#define GTS_SZ_OUT_10 1
#define GTS_IDX_OUT_11 38
#define GTS_SZ_OUT_11 1
#define GTS_IDX_OUT_12 39
#define GTS_SZ_OUT_12 1
#define GTS_IDX_OUT_13 40
#define GTS_SZ_OUT_13 1
#define GTS_IDX_OUT_14 41
#define GTS_SZ_OUT_14 1
#define GTS_IDX_OUT_15 42
#define GTS_SZ_OUT_15 1
#define GTS_IDX_OUT_18 43
#define GTS_SZ_OUT_18 1
#define GTS_IDX_OUT_20 44
#define GTS_SZ_OUT_20 1
#define GTS_IDX_OUT_21 45
#define GTS_SZ_OUT_21 1
#define GTS_IDX_OUT_GAS_1 46
#define GTS_SZ_OUT_GAS_1 13
#define GTS_IDX_OUT_GAS_2 59
#define GTS_SZ_OUT_GAS_2 13
#define GTS_IDX_OUT_GAS_3 72
#define GTS_SZ_OUT_GAS_3 13
#define GTS_IDX_OUT_GAS_4 85
#define GTS_SZ_OUT_GAS_4 13
#define GTS_IDX_OUT_SYNGAS_1 98
#define GTS_SZ_OUT_SYNGAS_1 13
#define GTS_IDX_OUT_SYNGAS_2 111
#define GTS_SZ_OUT_SYNGAS_2 13
#define GTS_IDX_OUT_SYNGAS_3 124
#define GTS_SZ_OUT_SYNGAS_3 13
#define GTS_IDX_OUT_SYNGAS_4 137
#define GTS_SZ_OUT_SYNGAS_4 13
#define GTS_IDX_OUT_C10 150
#define GTS_SZ_OUT_C10 1
#define GTS_IDX_OUT_C20 151
#define GTS_SZ_OUT_C20 1
#define GTS_IDX_OUT_C30 152
#define GTS_SZ_OUT_C30 1
#define GTS_IDX_OUT_C40 153
#define GTS_SZ_OUT_C40 1
#define GTS_IDX_OUT_POLL_YR 154
#define GTS_SZ_OUT_POLL_YR 1
#define GTS_IDX_OUT_CST_YR_TBL 155
#define GTS_SZ_OUT_CST_YR_TBL 5
#define GTS_IDX_OUT_CST_MWH_TBL 160
#define GTS_SZ_OUT_CST_MWH_TBL 5
#define GTS_IDX_OUT_CST_PCT_TBL 165
#define GTS_SZ_OUT_CST_PCT_TBL 5
#define GTS_IDX_OUT_GASIF_TEMP 170
#define GTS_SZ_OUT_GASIF_TEMP 1
#define GTS_IDX_OUT_GASIF_PRESS 171
#define GTS_SZ_OUT_GASIF_PRESS 1

/* Input Variables */
#define GTS_SZ_IN 68
#define GTS_IDX_IN_DEV_CTL 0
#define GTS_SZ_IN_DEV_CTL 1
#define GTS_IDX_IN_COMP_EFF 1
#define GTS_SZ_IN_COMP_EFF 1
#define GTS_IDX_IN_PRES_COMB 2
#define GTS_SZ_IN_PRES_COMB 1
#define GTS_IDX_IN_PRES_DROP_COMB 3
#define GTS_SZ_IN_PRES_DROP_COMB 1
#define GTS_IDX_IN_PRES_BACK_TURB 4
#define GTS_SZ_IN_PRES_BACK_TURB 1
#define GTS_IDX_IN_PRES_RATIO_COMP 5
#define GTS_SZ_IN_PRES_RATIO_COMP 1
#define GTS_IDX_IN_TMP_TURB 6
#define GTS_SZ_IN_TMP_TURB 3
#define GTS_IDX_IN_MW_TURB 9
#define GTS_SZ_IN_MW_TURB 3
#define GTS_IDX_IN_NTURB 12
#define GTS_SZ_IN_NTURB 1
#define GTS_IDX_IN_EXAIR 13
#define GTS_SZ_IN_EXAIR 3
#define GTS_IDX_IN_HG_EFF_EL 16
#define GTS_SZ_IN_HG_EFF_EL 3
#define GTS_IDX_IN_HG_EFF_OX 19
#define GTS_SZ_IN_HG_EFF_OX 3
#define GTS_IDX_IN_HG_EFF_TSP 22
#define GTS_SZ_IN_HG_EFF_TSP 3
#define GTS_IDX_IN_CST_YR 25
#define GTS_SZ_IN_CST_YR 1
#define GTS_IDX_IN_GFC 26
#define GTS_SZ_IN_GFC 1
#define GTS_IDX_IN_EHO 27
#define GTS_SZ_IN_EHO 1
#define GTS_IDX_IN_PROJCONT 28
#define GTS_SZ_IN_PROJCONT 1
#define GTS_IDX_IN_PROCCONT 29
#define GTS_SZ_IN_PROCCONT 3
#define GTS_IDX_IN_ROYALTY 32
#define GTS_SZ_IN_ROYALTY 1
#define GTS_IDX_IN_FIXTIME 33
#define GTS_SZ_IN_FIXTIME 1
#define GTS_IDX_IN_VARTIME 34
#define GTS_SZ_IN_VARTIME 1
#define GTS_IDX_IN_MISCCAP 35
#define GTS_SZ_IN_MISCCAP 1
#define GTS_IDX_IN_INV 36
#define GTS_SZ_IN_INV 1
#define GTS_IDX_IN_C10_FIT 37
#define GTS_SZ_IN_C10_FIT 1
#define GTS_IDX_IN_C20_FIT 38
#define GTS_SZ_IN_C20_FIT 1
#define GTS_IDX_IN_C30_FIT 39
#define GTS_SZ_IN_C30_FIT 1
#define GTS_IDX_IN_C40_FIT 40
#define GTS_SZ_IN_C40_FIT 1
#define GTS_IDX_IN_TCR_FACTOR 41
#define GTS_SZ_IN_TCR_FACTOR 1
#define GTS_IDX_IN_NJOBS 42
#define GTS_SZ_IN_NJOBS 1
#define GTS_IDX_IN_NSHIFTS 43
#define GTS_SZ_IN_NSHIFTS 1
#define GTS_IDX_IN_MNT 44
#define GTS_SZ_IN_MNT 3
#define GTS_IDX_IN_MNTLAB 47
#define GTS_SZ_IN_MNTLAB 1
#define GTS_IDX_IN_ADMIN 48
#define GTS_SZ_IN_ADMIN 1
#define GTS_IDX_IN_TURB_EFF 49
#define GTS_SZ_IN_TURB_EFF 1
#define GTS_IDX_IN_GEN_EFF 50
#define GTS_SZ_IN_GEN_EFF 1
#define GTS_IDX_IN_TMP_HRSG_OUT 51
#define GTS_SZ_IN_TMP_HRSG_OUT 1
#define GTS_IDX_IN_HR_STEAM 52
#define GTS_SZ_IN_HR_STEAM 1
#define GTS_IDX_IN_MW_HRSG 53
#define GTS_SZ_IN_MW_HRSG 3
#define GTS_IDX_IN_ELEC_CST 56
#define GTS_SZ_IN_ELEC_CST 3
#define GTS_IDX_IN_H2O_PCT 59
#define GTS_SZ_IN_H2O_PCT 3
#define GTS_IDX_IN_CONSTTIME 62
#define GTS_SZ_IN_CONSTTIME 3
#define GTS_IDX_IN_PENALTY 65
#define GTS_SZ_IN_PENALTY 3

/* Calculated Variables */
#define GTS_SZ_CALC 13
#define GTS_IDX_CALC_TMP_TURB 0
#define GTS_SZ_CALC_TMP_TURB 1
#define GTS_IDX_CALC_MW_TURB 1
#define GTS_SZ_CALC_MW_TURB 1
#define GTS_IDX_CALC_EXAIR 2
#define GTS_SZ_CALC_EXAIR 1
#define GTS_IDX_CALC_HG_EFF_EL 3
#define GTS_SZ_CALC_HG_EFF_EL 1
#define GTS_IDX_CALC_HG_EFF_OX 4
#define GTS_SZ_CALC_HG_EFF_OX 1
#define GTS_IDX_CALC_HG_EFF_TSP 5
#define GTS_SZ_CALC_HG_EFF_TSP 1
#define GTS_IDX_CALC_PROCCONT 6
#define GTS_SZ_CALC_PROCCONT 1
#define GTS_IDX_CALC_MNT 7
#define GTS_SZ_CALC_MNT 1
#define GTS_IDX_CALC_MW_HRSG 8
#define GTS_SZ_CALC_MW_HRSG 1
#define GTS_IDX_CALC_ELEC_CST 9
#define GTS_SZ_CALC_ELEC_CST 1
#define GTS_IDX_CALC_H2O_PCT 10
#define GTS_SZ_CALC_H2O_PCT 1
#define GTS_IDX_CALC_CONSTTIME 11
#define GTS_SZ_CALC_CONSTTIME 1
#define GTS_IDX_CALC_PENALTY 12
#define GTS_SZ_CALC_PENALTY 1
