##Builds GUIPluginLib
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR buildDir xerces_options wxwidgets_options RootDir')

srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'conductor') )
sources = sca_util.getSourcesRecursive( srcDir )
headers = sca_util.getHeadersRecursive( srcDir )

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['VE_ConductorLib', 'VE_XML','VE_OpenModuleLib', 'VE_Conductor_Utilities'])
lib_env.Append(LIBPATH = [#pj('#', buildDir, 'VE_Conductor','Utilities'),
                          #pj('#', buildDir, 'VE_Conductor','Network'),
                          pj('#', buildDir, 'src', 'open','skel'),
                        pj('#', buildDir, 'src', 'open','xml')])
lib_env.ParseConfig('flagpoll TAO ACE TAO_IORInterceptor TAO_ObjRefTemplate TAO_Valuetype \
                              TAO_CosNaming TAO_Svc_Utils TAO_IORTable TAO_Messaging \
                              TAO_PortableServer TAO_BiDirGIOP TAO_AnyTypeCode vpr --libs --cflags')

xerces_options.apply( lib_env )
wxwidgets_options.apply( lib_env )
if baseEnv['StaticOnly'] == "no":
   lib = ves_pkg.createStaticAndSharedLibrary('GUIPlugin',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createStaticLibrary('GUIPlugin', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Conductor', 'GUIPlugin'))
lib.build()
