import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')
Import('xerces')

model_srcs = Split("""
   Point.cxx
   Port.cxx
   Link.cxx
   Network.cxx
   Model.cxx
   Tag.cxx
   ModelCreator.cxx 
""")

model_srcs = map(lambda s: pj('#', 'VE_Open', 'XML', 'Model', s), model_srcs)

env = baseEnv.Copy()
#env.Append(CPPPATH = [os.getcwd()])
env.Append(CPPPATH = ['#'])
env.Append(CPPPATH = pj( os.getenv('XERCESCROOT',''), 'include') )
env.Append(LIBPATH = libPath,
              LIBS = 'VE_XMLLib')
for lib in xerces:
   env.Append(LIBS = lib)

targetLib = pj(libPath, 'VE_ModelLib')
env.SharedLibrary(target = targetLib, source = model_srcs)
#env.Program(pj('#','bin',Platform,'VE_Open','VE_XML'), source = model_srcs)
