##Builds VE_UtilLib
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR vtk_options boost_options RootDir')

srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'xplorer', 'util') )
sources = sca_util.getSourcesRecursive( srcDir )
headers = sca_util.getHeadersRecursive( srcDir )

index = sources.index(pj('Logo_Maker','binaryMaker.cxx') )
sources.pop(index)
index = sources.index(pj('Logo_Maker','logoMaker.cxx') )
sources.pop(index)
index = sources.index(pj('Logo_Maker','xpmMaker.cxx') )
sources.pop(index)

lib_env = ves_pkg.getEnv().Clone()

vtk_options.apply( lib_env )
boost_options.apply( lib_env )

lib_env.Append( CPPDEFINES = ['VE_UTIL_LIBRARY'] )

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_xplorer_util',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_xplorer_util', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves', 'xplorer', 'util'))
lib.build()
