##Builds VE_UtilLib
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR execOsgPatTag vtk_options RootDir')

srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'xplorer', 'util') )
sources = sca_util.getSourcesRecursive( srcDir )
headers = sca_util.getHeadersRecursive( srcDir )

index = sources.index(pj('Logo_Maker','binaryMaker.cxx') )
sources.pop(index)
index = sources.index(pj('Logo_Maker','logoMaker.cxx') )
sources.pop(index)
index = sources.index(pj('Logo_Maker','xpmMaker.cxx') )
sources.pop(index)

##srcs = map(lambda s: pj('#', 'VE_Xplorer', 'Utilities', s), util_srcs)

lib_env = ves_pkg.getEnv().Copy()
lib_env.ParseConfig('flagpoll Boost.Filesystem --atleast-version=%s --cflags --libs'%lib_env['BoostVersion'])
vtk_options.apply( lib_env )
if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_xplorer_util',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_xplorer_util', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves', 'xplorer', 'util'))
lib.build()
