#
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'ves_pkg buildDir RootDir GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share','vesuite','logo' ) )

osgFile = sca_util.getFilesRecursiveByExt( pj( RootDir, 'share', 'logo' ), [ '.osg' ] )
iveFile = sca_util.getFilesRecursiveByExt( pj( RootDir, 'share', 'logo' ), [ '.ive' ] )

fileBundle.addFiles( osgFile )
fileBundle.addFiles( iveFile )
