##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'ConstructionBots' ) )
ConstructionBotsDemoDir = pj( RootDir, 'share', 'examples', 'ConstructionBots' )

iveFile = sca_util.getFilesRecursiveByExt( ConstructionBotsDemoDir, [ '.ive' ] )
jpgFile = sca_util.getFilesRecursiveByExt( ConstructionBotsDemoDir, [ '.jpg' ] )
wavFile = sca_util.getFilesRecursiveByExt( ConstructionBotsDemoDir, [ '.wav' ] )

fileBundle.addFiles( iveFile )
fileBundle.addFiles( jpgFile )
fileBundle.addFiles( wavFile )
fileBundle.addFiles( [ 'constructionbots.ves' ] )

ConstructionBotsSubdirs = Split("""
    ConstructionBotsGP
    ConstructionBotsUI
""")

##Run SConscript files in all of these folders.
for d in ConstructionBotsSubdirs:
   SConscript( dirs = d )
