##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform poco_options' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'AtomProbe' ) )
AtomProbeDir = pj( RootDir, 'share', 'examples', 'AtomProbe' )

iveFile = sca_util.getFilesRecursiveByExt( AtomProbeDir, [ '.ive' ] )
vsFile = sca_util.getFilesRecursiveByExt( AtomProbeDir, [ '.vs' ] )
fsFile = sca_util.getFilesRecursiveByExt( AtomProbeDir, [ '.fsh' ] )
fileBundle.addFiles( iveFile )
fileBundle.addFiles( vsFile )
fileBundle.addFiles( fsFile )

AtomProbeSubdirs = Split("""
    UserInterface
    GraphicalPlugin
""")

##Run SConscript files in all of these folders.
for d in AtomProbeSubdirs:
   SConscript( dirs = d )
