import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('Platform')

srcs = Split("""
   multiPlaneVtkOutput.cxx
   preprocessor.cxx
""")

srcs = map(lambda s: pj('#', 'VE_Builder', 'Preprocessor', s), srcs)

env = baseEnv.Copy()
env.Append(CPPPATH = [os.getcwd()])
env.Append(LIBPATH = '#',
              LIBS = 'Shared_Library')
env.Program(pj('#','bin',Platform,'Preprocessor'), source = srcs)
