#dev/src/plugins/PDU/PDURealm/SConscript
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'ParallaxMapping' ) )
parallaxMappingDir = pj( RootDir, 'share', 'examples', 'ParallaxMapping' )

iveFile = sca_util.getFilesRecursiveByExt( parallaxMappingDir, [ '.ive' ] )
pngFile = sca_util.getFilesRecursiveByExt( parallaxMappingDir, [ '.png' ] )

fileBundle.addFiles( iveFile )
fileBundle.addFiles( pngFile )

parallaxMappingSubdirs= Split("""
    GraphicalPlugin
	UserInterface
""")

#Run SConscript files in all of these folders
for d in parallaxMappingSubdirs:
    SConscript( dirs = d )
