##Builds a multitude of utilities
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('cfdHostType')

addNormals2Poly = Split("""
   addNormals2Poly.cpp
""")

appendVTK = Split("""
   appendVTK.cpp
""")

combineFluentParticleFile = Split("""
   CombinePartFiles.cpp
""")

compareScalars = Split("""
    compareScalars.cpp
""")

convertCellDataToPointData = Split("""
   convertCellDataToPointData.cpp
""")

convertSurfaceFileToStl = Split("""
   convertSurfaceFileToStl.cpp 
""")

convertVTK2Ascii = Split("""
   convertVTK2Ascii.cpp
""")

convertVTK2Binary = Split("""
   convertVTK2Binary.cpp
""")

createMiniFlowdata = Split("""
   createMiniFlowdata.cpp
""")

makeVtkSurface = Split("""
   makeVtkSurface.cpp
   setScalarAndVector.cpp
   ../Translator/viewCells.cpp""")

mergeVertices = Split("""
   mergeVertices.cpp
""")

meshViewer = Split("""
   meshViewer.cpp
   setScalarAndVector.cpp
   ../Translator/viewCells.cpp""")

moveFieldToPointData = Split("""
   moveFieldToPointData.cpp
""")

removeVtkCellsOutsideBox = Split("""
   removeVtkCellsOutsideBox.cpp
""")

removeVtkPointData = Split("""
   removeVtkPointData.cpp
""")

scaleVTK = Split("""
   scaleVTK.cpp
""")

transformVTK = Split("""
   transformVTK.cpp 
""")

whatIsScalarRange = Split("""
   whatIsScalarRange.cpp
""")

env = baseEnv.Copy()
env.Append(CPPPATH = [os.getcwd()])
env.Append(LIBS = ['VE_UtilLib'])
env.Append(CPPPATH = [pj('#', 'VE_Builder', 'Translator')])
env.ParseConfig('flagpoll vtk --libs --cflags')
env.ParseConfig('flagpoll boost --libs --cflags')
env.ParseConfig( 'vpr-config --libs --extra-libs --includes' )
env.ParseConfig( 'vrjuggler-config --libs --extra-libs --includes' )

env.Program(pj('#','bin',cfdHostType,'addNormals2Poly'), source = addNormals2Poly)
env.Program(pj('#','bin',cfdHostType,'appendVTK'), source = appendVTK)
env.Program(pj('#','bin',cfdHostType,'combineFluentParticleFile'), source = combineFluentParticleFile)
env.Program(pj('#','bin',cfdHostType,'compareScalars'), source = compareScalars)
env.Program(pj('#','bin',cfdHostType,'convertCellDataToPointData'), source = convertCellDataToPointData)
env.Program(pj('#','bin',cfdHostType,'convertSurfaceFileToStl'), source = convertSurfaceFileToStl)
env.Program(pj('#','bin',cfdHostType,'convertVTK2Ascii'), source = convertVTK2Ascii)
env.Program(pj('#','bin',cfdHostType,'convertVTK2Binary'), source = convertVTK2Binary)
env.Program(pj('#','bin',cfdHostType,'createMiniFlowdata'), source = createMiniFlowdata)
env.Program(pj('#','bin',cfdHostType,'makeVtkSurface'), source = makeVtkSurface)
env.Program(pj('#','bin',cfdHostType,'mergeVertices'), source = mergeVertices)
env.Program(pj('#','bin',cfdHostType,'meshViewer'), source = meshViewer)
env.Program(pj('#','bin',cfdHostType,'moveFieldToPointData'), source = moveFieldToPointData)
env.Program(pj('#','bin',cfdHostType,'removeVtkCellsOutsideBox'), source = removeVtkCellsOutsideBox)
env.Program(pj('#','bin',cfdHostType,'removeVtkPointData'), source = removeVtkPointData)
env.Program(pj('#','bin',cfdHostType,'scaleVTK'), source = scaleVTK)
env.Program(pj('#','bin',cfdHostType,'transformVTK'), source = transformVTK)
env.Program(pj('#','bin',cfdHostType,'whatIsScalarRange'), source = whatIsScalarRange)
