##Builds VE-Builder translator base class
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR vtk_options buildDir')

sources = Split("""
   cfdTranslatorToVTK.cxx 
""")

headers = Split("""
   cfdTranslatorToVTK.h 
""")
##srcs = map(lambda s: pj('#', 'VE_CE', 'Utilities', s), srcs)

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBPATH = [pj('#', buildDir, 'src', 'xplorer','util')],
               LIBS = ['ves_xplorer_util'])
lib_env.ParseConfig('flagpoll Boost.Filesystem --atleast-version=%s --libs --cflags'%lib_env['BoostVersion'])
vtk_options.apply( lib_env )

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_builder_translator_base',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_builder_translator_base', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves', 'builder', 'cfdTranslatorToVTK'))
lib.build()
