// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// .\be\be_codegen.cpp:1063

#include "stdafx.h"
#include "VEPSI_i.h"
#include "VE_PSI.h"
#include <ves/open/xml/model/Network.h>
#include <ves/open/xml/model/Link.h>
#include <ves/open/xml/model/Model.h>
#include <ves/open/xml/DataValuePair.h>
#include <ves/open/xml/XMLReaderWriter.h>
#include <ves/open/xml/model/Point.h>
#include <ves/open/xml/model/Port.h>
#include <ves/open/xml/Command.h>
#include <ves/open/xml/XMLObjectFactory.h>
#include <ves/open/xml/XMLCreator.h>
#include <ves/open/xml/shader/ShaderCreator.h>
#include <ves/open/xml/model/ModelCreator.h>
#include <ves/open/xml/cad/CADCreator.h>
#include <fstream>
#include <iostream>

#include <vpr/vpr.h>
#include <vpr/System.h>
#include <boost/bind.hpp>

// Implementation skeleton constructor
VEPSI_i::VEPSI_i( std::string name, VE_PSIDlg * dialog, 
                         CorbaUnitManager* parent, std::string dir )
    :
    AspenLog( 0 ),
    theParent( parent ),
    theDialog( dialog ),
    return_state( 0 ),
    cur_id_( 0 ),
    UnitName_( name ),
    mWorkingDir( dir ),
    dyn(NULL),
    bkp(NULL),
    dynSim(NULL),
    mQuerying(false)
{
    /*ves::open::xml::XMLObjectFactory::Instance()->
        RegisterObjectCreator( "XML",new ves::open::xml::XMLCreator() );
    ves::open::xml::XMLObjectFactory::Instance()->
        RegisterObjectCreator(
        "Shader",new ves::open::xml::shader::ShaderCreator() );
    ves::open::xml::XMLObjectFactory::Instance()->
        RegisterObjectCreator(
        "Model",new ves::open::xml::model::ModelCreator() );
    ves::open::xml::XMLObjectFactory::Instance()->
        RegisterObjectCreator( "CAD",new ves::open::xml::cad::CADCreator() );
*/
    AspenLog = reinterpret_cast<CEdit *>(theDialog->GetDlgItem(IDC_EDIT1));

    mQueryCommandNames.insert( "getNetwork");
    mQueryCommandNames.insert( "openSimulation");
    mQueryCommandNames.insert( "runNetwork");
    mQueryCommandNames.insert( "reinitNetwork");
    mQueryCommandNames.insert( "reinitBlock");
    mQueryCommandNames.insert( "stepNetwork");
    mQueryCommandNames.insert( "showSimulation");
    mQueryCommandNames.insert( "hideSimulation");
    mQueryCommandNames.insert( "closeSimulation");
    mQueryCommandNames.insert( "saveSimulation");
    mQueryCommandNames.insert( "saveAsSimulation");
    mQueryCommandNames.insert( "getModuleParamList");
    mQueryCommandNames.insert( "getInputModuleParamList");
    mQueryCommandNames.insert( "getInputModuleProperties");
    mQueryCommandNames.insert( "getOutputModuleParamList");
    mQueryCommandNames.insert( "getOutputModuleProperties");
    mQueryCommandNames.insert( "getStreamModuleParamList");
    mQueryCommandNames.insert( "getStreamInputModuleParamList");
    mQueryCommandNames.insert( "getStreamInputModuleProperties");
    mQueryCommandNames.insert( "getStreamOutputModuleParamList");
    mQueryCommandNames.insert( "getStreamOutputModuleProperties");
    mQueryCommandNames.insert( "setParam");
    mQueryCommandNames.insert( "setLinkParam");
    mQueryCommandNames.insert( "addVariable");

    mQueryCommandNames.insert( "getOPCValue");
    mQueryCommandNames.insert( "getOPCValues");
    mQueryCommandNames.insert( "setOPCValues");
    mQueryCommandNames.insert( "connectToOPC");
    mQueryCommandNames.insert( "getAllOPCVariables");

    dynFlag = false;
    bkpFlag = false;
}
////////////////////////////////////////////////////////////////////////////////
// Implementation skeleton destructor
VEPSI_i::~VEPSI_i( void )
{
    if( bkpFlag )
    {
        delete bkp;
    }
    
    if( dynFlag )
    {
        delete dyn;
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::ShowAspen()
{
    if( bkpFlag )
    {
        bkp->showAspen( true );
    }
    
    if( dynFlag )
    {
        dyn->SetVisibility( true );
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::HideAspen()
{
    if( bkpFlag )
    {
        bkp->showAspen(false);
    }
    
    if( dynFlag )
    {
        dyn->SetVisibility(false);
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::CloseAspen()
{
    if( bkpFlag )
    {
        bkp->closeFile();
    }
    
    if( dynFlag )
    {
        dyn->CloseFile();
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::SaveAspen( std::string filename)
{
    if( bkpFlag )
    {
        bkp->saveAs(( mWorkingDir + filename + ".apw" ).c_str());
        bkp->saveAs(( mWorkingDir + filename + ".bkp" ).c_str());
    }
    
    if( dynFlag )
    {
        dyn->SaveAs(( mWorkingDir + filename + ".dynf" ).c_str());
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::StepSim()
{
    if( bkpFlag )
    {
        bkp->step();
    }
    
    if( dynFlag )
    {
        //dyn->Step();
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::ReinitializeAspen()
{
    try
    {
        if( bkpFlag )
        {
            bkp->ReinitAspen();
        }
        
        if( dynFlag )
        {
            dyn->ReinitDynamics();
        }
    }
    catch(...)
    {
        AspenLog->SetSel(-1, -1);
        AspenLog->ReplaceSel("Reinitialize Failed.\r\n");
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::StartCalc (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
      if( bkpFlag )
    {
        bkp->aspendoc->runSolver( false );
    }
    
    if( dynFlag )
    {
        dyn->dyndoc->RunSolver( );
    }
    AspenLog->SetSel( -1, -1 );
    AspenLog->ReplaceSel( "Simulation Complete\r\n" );
    //executive_->SetModuleMessage(cur_id_,"Simulation completed.\n");
    return_state=0;
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::StopCalc (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
    std::string msg;
    msg = UnitName_+" : Instant calculation, already finished\n";
    //executive_->SetModuleMessage(cur_id_,msg.c_str());

}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::PauseCalc (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
    std::string msg;
    msg = UnitName_+" : Instant calculation, already finished\n";
    //executive_->SetModuleMessage(cur_id_,msg.c_str());
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::Resume (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
    std::string msg;
    msg = UnitName_+" : Instant calculation, already finished\n";
    //executive_->SetModuleMessage(cur_id_,msg.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char * VEPSI_i::GetStatusMessage (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
    ves::open::xml::CommandPtr returnState( new ves::open::xml::Command() );

    returnState->SetCommandName( "statusmessage" );
    ves::open::xml::DataValuePairPtr
        data( new ves::open::xml::DataValuePair() );
    data->SetDataName( "RETURN_STATE" );
    data->SetDataType( "UNSIGNED INT" );
    data->SetDataValue( return_state );
    returnState->AddDataValuePair( data );
    
    std::vector< std::pair< ves::open::xml::XMLObjectPtr, std::string > >
        nodes;

    nodes.push_back( 
        std::pair< ves::open::xml::XMLObjectPtr, std::string >( 
        returnState, "vecommand" ) );
    ves::open::xml::XMLReaderWriter commandWriter;
    std::string status = "returnString";
    commandWriter.UseStandaloneDOMDocumentManager();
    commandWriter.WriteXMLDocument( nodes, status, "Command" );
    return CORBA::string_dup( status.c_str() );
}
////////////////////////////////////////////////////////////////////////////////
char * VEPSI_i::GetUserData (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
    char * result = 0;
    return result;
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::SetID (
    ::CORBA::Long id
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
  // no need to implement this
  std::cout << "This not implemented for the Aspen Unit" << std::endl;
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::SetCurID (
    ::CORBA::Long id
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    cur_id_ = id;
}
////////////////////////////////////////////////////////////////////////////////
::Types::ArrayLong* VEPSI_i::GetID (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    return &ids_;
}
////////////////////////////////////////////////////////////////////////////////
CORBA::Long VEPSI_i::GetCurID (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    return cur_id_;
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::DeleteModuleInstance(CORBA::Long id) 
ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    return; //do nothing;
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::SetName (
    const char * name
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
    UnitName_ = std::string(name);
}
////////////////////////////////////////////////////////////////////////////////
char * VEPSI_i::GetName (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    return CORBA::string_dup(UnitName_.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char * VEPSI_i::Query ( const char * query_str
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    mQuerying = true;
    AspenLog->SetSel( -1, -1 );
    AspenLog->ReplaceSel( "Query\r\n" );
    _mutex.acquire();
    ves::open::xml::XMLReaderWriter networkWriter;
    networkWriter.UseStandaloneDOMDocumentManager();
    networkWriter.ReadFromString();
    networkWriter.ReadXMLData( query_str, "Command", "vecommand" );

    std::vector< ves::open::xml::XMLObjectPtr > objectVector =
        networkWriter.GetLoadedXMLObjects();

    ves::open::xml::CommandPtr cmd;    
    std::string cmdname;
    
    cmd = boost::dynamic_pointer_cast<ves::open::xml::Command>
        ( objectVector.at( 0 ) );
    cmdname = cmd->GetCommandName();
    
    std::set< std::string >::const_iterator commandItr
        = mQueryCommandNames.find( cmdname );
    
    //If the command is not processed here - do not bother doing anything more
    if( commandItr == mQueryCommandNames.end() )
    {
        _mutex.release();
        mQuerying = false;
        return CORBA::string_dup("NULL");
    }
    
    AspenLog->SetSel( -1, -1 );
    AspenLog->ReplaceSel( ("Command: "+cmdname+"\r\n").c_str() );
    char* returnValue = "empty";

    if ( cmdname == "getNetwork" )
    {
        returnValue = handleGetNetwork( cmd );
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if( cmdname == "openSimulation" )
    {
        returnValue = handleOpenSimulation( cmd );
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "runNetwork" )
    {
        StartCalc();
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "networkRun" );
    }
    else if ( cmdname == "stepNetwork" )
    {
        StepSim();
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "networkRun" );
    }
    else if ( cmdname == "showSimulation" )
    {
        ShowAspen();
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "Simulation Shown." );
    }
    else if ( cmdname == "hideSimulation" )
    {
        HideAspen();
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "Simulation hidden." );
    }
    else if ( cmdname == "closeSimulation" )
    {
        AspenLog->SetSel( -1, -1 );
        AspenLog->ReplaceSel( "closing...\r\n" );
        CloseAspen();
        AspenLog->SetSel( -1, -1 );
        AspenLog->ReplaceSel( "closed.\r\n" );
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "Simulation closed." );
    }
    else if ( cmdname == "saveSimulation" )
    {
        AspenLog->SetSel(-1, -1);
        AspenLog->ReplaceSel( "saving...\r\n" );
        try
        {
            SaveAspen( mFileName );
            AspenLog->SetSel( -1, -1 );
            AspenLog->ReplaceSel( "saved.\r\n" );
        }
        catch(...)
        {
            AspenLog->SetSel(-1, -1);
            AspenLog->ReplaceSel( "messed up save.\r\n" );
            mQuerying = false;
            _mutex.release();
        }
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "Simulation Saved." );
    }
    else if ( cmdname == "saveAsSimulation" )
    {
        returnValue = handleSaveAs( cmd );
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if( cmdname == "reinitNetwork" )
    {
        ReinitializeAspen();
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "Simulation reinitialized." );
    }
    else if( cmdname == "reinitBlock" )
    {
        ReinitializeBlock( cmd );
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "Block reinitialized." );
    }

    //Blocks
    else if ( cmdname == "getModuleParamList" )
    {
        //executive_->SetModuleMessage(cur_id_,"Querying inputs...\n");
        returnValue = handleGetModuleParamList( cmd );
        //executive_->SetModuleMessage(cur_id_,"Querying completed.\n");
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "getInputModuleParamList" )
    {
        //executive_->SetModuleMessage(cur_id_,"Querying inputs...\n");
        returnValue = handleGetInputModuleParamList( cmd );
        //executive_->SetModuleMessage(cur_id_,"Querying completed.\n");
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "getInputModuleProperties" )
    {
        returnValue = handleGetInputModuleProperties( cmd );
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "getOutputModuleParamList" )
    {
        //executive_->SetModuleMessage(cur_id_,"Querying outputs...\n");
        returnValue = handleGetOutputModuleParamList( cmd );
        //executive_->SetModuleMessage(cur_id_,"Querying completed.\n");
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "getOutputModuleProperties" )
    {
        returnValue = handleGetOutputModuleProperties( cmd );
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }

    //Streams
    else if ( cmdname == "getStreamModuleParamList" )
    {
        //executive_->SetModuleMessage(cur_id_,"Querying inputs...\n");
        returnValue = handleGetStreamModuleParamList( cmd );
        //executive_->SetModuleMessage(cur_id_,"Querying completed.\n");
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "getStreamInputModuleParamList" )
    {
        //executive_->SetModuleMessage(cur_id_,"Querying link inputs...\n");
        returnValue = handleGetStreamInputModuleParamList( cmd );
        //executive_->SetModuleMessage(cur_id_,"Querying link completed.\n");
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "getStreamInputModuleProperties" )
    {
        returnValue = handleGetStreamInputModuleProperties( cmd );
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "getStreamOutputModuleParamList" )
    {
        //executive_->SetModuleMessage(cur_id_,"Querying link outputs...\n");
        returnValue = handleGetStreamOutputModuleParamList( cmd );
        //executive_->SetModuleMessage(cur_id_,"Querying link completed.\n");
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }
    else if ( cmdname == "getStreamOutputModuleProperties" )
    {
        returnValue = handleGetStreamOutputModuleProperties( cmd );
        mQuerying = false;
        _mutex.release();
        return returnValue;
    }

    //Params
    else if ( cmdname == "setParam" )
    {
        SetParam( cmd );
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "Param Set" );
    }
    else if ( cmdname == "setLinkParam" )
    {
        SetLinkParam( cmd );
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "Param Set" );
    }
    else if ( cmdname == "addVariable" )
    {
        addVariable( cmd );
        mQuerying = false;
        _mutex.release();
        return( "NULL" );
    }

    //DynSim
    else if ( cmdname == "getOPCValues" )
    {
        returnValue = getOPCValues( cmd );
        _mutex.release();
        mQuerying = false;
        return returnValue;
    }
    else if ( cmdname == "setOPCValues" )
    {
        returnValue = setOPCValues( cmd );
        _mutex.release();
        mQuerying = false;
        return returnValue;
    }
    else if ( cmdname == "connectToOPC" )
    {
        connectToOPC( cmd );
        _mutex.release();
        mQuerying = false;
        return( "NULL" );
    }
    else if ( cmdname == "addVariable" )
    {
        addVariable( cmd );
        _mutex.release();
        mQuerying = false;
        return( "NULL" );
    }
    else if ( cmdname == "getAllOPCVariables" )
    {
        returnValue = getAllOPCVariables( cmd );
        _mutex.release();
        mQuerying = false;
        return returnValue;
    }

    else
    {
        mQuerying = false;
        _mutex.release();
        return CORBA::string_dup( "NULL" );
    }
}
///////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetNetwork(ves::open::xml::CommandPtr cmd)
{
    CEdit *Display;
    Display = reinterpret_cast<CEdit *>(theDialog->GetDlgItem(IDC_EDIT2));

    //this command has no params
    bool firsttime=true;

    std::string filename = cmd->GetDataValuePair(1)->GetDataString();

    std::string extension = filename.substr( filename.size() - 4, 4 );
 
    if( extension.find( "bkp" ) != std::string::npos )
    {
        bkpFlag = true;
        dynFlag = false;
        dynSimFlag = false;
        filename.resize( filename.size() - 4 );
        bkp = new AspenPlus();
        bkp->SetWorkingDir( mWorkingDir );
    }
    else if( extension.find( "dynf" ) != std::string::npos )
    {
        bkpFlag = false;
        dynFlag = true;
        dynSimFlag = false;
        filename.resize( filename.size() - 5 );
        dyn = new AspenDynamics();
        dyn->SetWorkingDir( mWorkingDir );
    }
    else if( extension.find( "xml" ) != std::string::npos )
    {
        bkpFlag = false;
        dynFlag = false;
        dynSimFlag = true;
        filename.resize( filename.size() - 4 );
        dynSim = new DynSim();
    }
    
    if( bkpFlag )
    {
        if (firsttime)
        {
            //make sure bkp file exists
            std::ifstream bkpFile( ( mWorkingDir + filename + ".bkp" ).c_str(),
                std::ios::binary);
            if( !bkpFile.is_open() )
            {
                //no bkp file
                AspenLog->SetSel(-1, -1);
                AspenLog->ReplaceSel("BKP File Does NOT exist.\r\n");
                return CORBA::string_dup( "BKPDNE" );
            }
            bkpFile.close();

            //make sure apw file exists
            std::ifstream apwFile( ( mWorkingDir + filename + ".apw" ).c_str(),
                std::ios::binary);
            if( !apwFile.is_open() )
            {
                //no apw file
                AspenLog->SetSel(-1, -1);
                AspenLog->ReplaceSel("APW File Does NOT exist.\r\n");
                return CORBA::string_dup( "APWDNE" );
            }
            apwFile.close();

            //Display->SetWindowText( ( mWorkingDir + filename ).c_str());
            Display->SetWindowText( ( filename ).c_str());
            //go through bkp parsing procedure
            bkp->OpenSimAndParse( filename.c_str() );
            mFileName = filename;
            firsttime=false;
        }
           
        //Display->SetWindowText(filename.c_str());

        std::string network;
        try
        {
            network = bkp->CreateNetwork( );
        }
        catch(...)
        {
            std::cout << "GetNetwork Exception Aspen Unit" << std::endl;
            return NULL;
        }

        return CORBA::string_dup( network.c_str() );
    }
    
    if( dynFlag )
    {
        if (firsttime)
        {
            //make sure bkp file exists
            std::ifstream dynFile( ( mWorkingDir + filename + ".dynf" ).c_str(),
                std::ios::binary);
            if( !dynFile.is_open() )
            {
                //no dyn file
                AspenLog->SetSel(-1, -1);
                AspenLog->ReplaceSel("Dynf File Does NOT exist.\r\n");
                return CORBA::string_dup( "DYNDNE" );
            }
            dynFile.close();

            //Display->SetWindowText( ( mWorkingDir + filename ).c_str());
            Display->SetWindowText( ( filename ).c_str());
            //go through dyn parsing procedure
            dyn->OpenFile( filename.c_str() );
            m_thread = new vpr::Thread( boost::bind( &VEPSI_i::Monitor, this ) );
            //dyn->ParseFile((mWorkingDir + filename + ".dynf" ).c_str());
            //Monitor(  );
            mFileName = filename;
            firsttime=false;
        }
           
        //Display->SetWindowText(filename.c_str());

        std::string network;
        try
        {
            network = dyn->CreateNetwork();
        }
        catch(...)
        {
            std::cout << "GetNetwork Exception Dynamics Unit" << std::endl;
            return NULL;
        }
        return CORBA::string_dup(network.c_str());
    }

    if( dynSimFlag )
    {
        std::string network;
        if (firsttime)
        {
            //make sure bkp file exists
            std::ifstream xmlFile( ( mWorkingDir + filename + ".xml" ).c_str(),
                std::ios::binary);
            if( !xmlFile.is_open() )
            {
                //no bkp file
                AspenLog->SetSel(-1, -1);
                AspenLog->ReplaceSel("XML File Does NOT exist.\r\n");
                return CORBA::string_dup( "XMLDNE" );
            }
            xmlFile.close();

            //make sure apw file exists
            std::ifstream s4mFile( ( mWorkingDir + filename + ".s4m" ).c_str(),
                std::ios::binary);
            if( !s4mFile.is_open() )
            {
                //no apw file
                AspenLog->SetSel(-1, -1);
                AspenLog->ReplaceSel("S4M File Does NOT exist.\r\n");
                return CORBA::string_dup( "S4MDNE" );
            }
            s4mFile.close();

            Display->SetWindowText( ( filename ).c_str());
            //go through bkp parsing procedure
            network = dynSim->CreateNetwork( filename );

            mFileName = filename;
            firsttime=false;
        }
        return CORBA::string_dup( network.c_str() );
    }

    return NULL;
}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleOpenSimulation(ves::open::xml::CommandPtr cmd)
{
    CEdit *Display;
    Display = reinterpret_cast<CEdit *>(theDialog->GetDlgItem(IDC_EDIT2));

    //this command has no params
    std::string filename = cmd->GetDataValuePair(1)->GetDataString();

    std::string extension = filename.substr( filename.size() - 4, 4 );
 
    if( extension.find( "bkp" ) != std::string::npos )
    {
        filename.resize( filename.size() - 4 );
        //make sure bkp file exists
        std::ifstream bkpFile( ( mWorkingDir + filename + ".bkp" ).c_str(),
            std::ios::binary);
        if( !bkpFile.is_open() )
        {
            //no bkp file
            AspenLog->SetSel(-1, -1);
            AspenLog->ReplaceSel("BKP File Does NOT exist.\r\n");
            return CORBA::string_dup( "BKPDNE" );
        }
        bkpFile.close();

        //make sure apw file exists
        std::ifstream apwFile( ( mWorkingDir + filename + ".apw" ).c_str(),
            std::ios::binary);
        if( !apwFile.is_open() )
        {
            //no apw file
            AspenLog->SetSel(-1, -1);
            AspenLog->ReplaceSel("APW File Does NOT exist.\r\n");
            return CORBA::string_dup( "APWDNE" );
        }
        apwFile.close();

        bkpFlag = true;
        dynFlag = false;
        Display->SetWindowText(filename.c_str());
        bkp = new AspenPlus();
        bkp->SetWorkingDir( mWorkingDir );
        bkp->OpenSim(filename.c_str());
    }
    else if( extension.find( "dynf" ) != std::string::npos )
    {   
        filename.resize( filename.size() - 5 );
        //make sure dynf file exists
        std::ifstream dynFile( ( mWorkingDir + filename + ".dynf" ).c_str(),
            std::ios::binary);
        if( !dynFile.is_open() )
        {
            //no dyn file
            AspenLog->SetSel(-1, -1);
            AspenLog->ReplaceSel("Dynf File Does NOT exist.\r\n");
            return CORBA::string_dup( "DYNDNE" );
        }
        dynFile.close();
        
        bkpFlag = false;
        dynFlag = true;
        Display->SetWindowText(filename.c_str());
        dyn = new AspenDynamics();
        dyn->SetWorkingDir( mWorkingDir );
        dyn->OpenFile(filename.c_str());
    }
    return CORBA::string_dup("Simulation Opened.");
}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleSaveAs(ves::open::xml::CommandPtr cmd)
{
    AspenLog->SetSel(-1, -1);
    AspenLog->ReplaceSel("saving...\r\n");
    std::string filename = cmd->GetDataValuePair(1)->GetDataString();
    mFileName = filename;
    SaveAspen( mFileName );
    AspenLog->SetSel(-1, -1);
    AspenLog->ReplaceSel("saved.\r\n");
    return CORBA::string_dup("Simulation Saved.");
}
////////////////////////////////////////////////////////////////////////////////
//no reinitialize of block in dynamics
void VEPSI_i::ReinitializeBlock(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname;
    unsigned int modId;

    for( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        
        if (curPair->GetDataName()=="ModuleName")
            modname=curPair->GetDataString();
        else if (curPair->GetDataName()=="ModuleId")
            curPair->GetData(modId);
    }
    bkp->ReinitBlock(modname);
}

////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetModuleParamList(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname;
    unsigned int modId;

    for( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        
        if (curPair->GetDataName()=="ModuleName")
            modname=curPair->GetDataString();
        else if (curPair->GetDataName()=="ModuleId")
            curPair->GetData(modId);
    }

    //There shouldn't be two intances of an Dynamics framework. so discard the 
    //moduleId
    //the returned string will be a well formated XML within "vecommand" element
    std::string netPak = dyn->GetModuleParams( modname, true );

    return CORBA::string_dup(netPak.c_str());
}

////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetInputModuleParamList(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname;
    unsigned int modId;

    for( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        
        if (curPair->GetDataName()=="ModuleName")
            modname=curPair->GetDataString();
        else if (curPair->GetDataName()=="ModuleId")
            curPair->GetData(modId);
    }

    //There shouldn't be two intances of an Aspen framework. so discard the moduleId
    //the returned string will be a well formated XML within "vecommand" element
    std::string netPak = bkp->GetInputModuleParams(modname);

    //std::ofstream output("inputList.txt");
    //output<<netPak;
    //output.close();  

    return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetInputModuleProperties(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname,paramName;
    unsigned int modId;

    for ( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        if (curPair->GetDataName()=="ModuleName")
            modname=curPair->GetDataString();
        else if (curPair->GetDataName()=="moduleId")
            curPair->GetData(modId); //modId is discarded because of the same reason as before
        else if (curPair->GetDataName()=="ParamName")
            paramName=curPair->GetDataString();
    }
    std::string netPak = bkp->GetInputModuleParamProperties(modname, paramName);
    return CORBA::string_dup(netPak.c_str());

}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetOutputModuleParamList(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname;
    unsigned int modId;

    for( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        
        if (curPair->GetDataName()=="ModuleName")
            modname=curPair->GetDataString();
        else if (curPair->GetDataName()=="ModuleId")
            curPair->GetData(modId);
    }

    //There shouldn't be two intances of an Aspen framework. so discard the
    //moduleId
    //the returned string will be a well formated XML within "vecommand" element
    std::string netPak = bkp->GetOutputModuleParams(modname);
    return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetOutputModuleProperties(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname,paramName;
    unsigned int modId;

    for ( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        if (curPair->GetDataName()=="ModuleName")
        {
            modname=curPair->GetDataString();
        }
        else if (curPair->GetDataName()=="moduleId")
        {
            //modId is discarded because of the same reason as before
            curPair->GetData(modId); 
        }
        else if (curPair->GetDataName()=="ParamName")
        {
        paramName=curPair->GetDataString();
        }
    }
    std::string netPak = bkp->GetOutputModuleParamProperties(modname, paramName);
    return CORBA::string_dup(netPak.c_str());

}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetStreamModuleParamList(ves::open::xml::CommandPtr cmd)
{    
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname;
    unsigned int modId;

    for( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        
        if (curPair->GetDataName()=="ModuleName")
        {
            modname=curPair->GetDataString();
        }
        else if (curPair->GetDataName()=="ModuleId")
        {
            curPair->GetData(modId);
        }
    }

    //There shouldn't be two intances of an Dynamics framework. so discard the 
    //moduleId
    //the returned string will be a well formated XML within "vecommand" element
    std::string netPak = dyn->GetModuleParams( modname, false );

    return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetStreamInputModuleParamList(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname;
    unsigned int modId;

    for ( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        
        if (curPair->GetDataName()=="ModuleName")
        {
            modname=curPair->GetDataString();
        }
        else if (curPair->GetDataName()=="ModuleId")
        {
            curPair->GetData(modId);
        }
    }

    //There shouldn't be two intances of an Aspen framework. so discard the moduleId
    //the returned string will be a well formated XML within "vecommand" element
    std::string netPak = bkp->GetStreamInputModuleParams(modname);
    return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetStreamInputModuleProperties(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname,paramName;
    unsigned int modId;

    for ( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        if (curPair->GetDataName()=="ModuleName")
        {
            modname=curPair->GetDataString();
        }
        else if (curPair->GetDataName()=="moduleId")
        {
            curPair->GetData(modId); //modId is discarded because of the same reason as before
        }
        else if (curPair->GetDataName()=="ParamName")
        {
            paramName=curPair->GetDataString();
        }
    }
    std::string netPak = bkp->GetStreamInputModuleParamProperties(modname, paramName);
    return CORBA::string_dup(netPak.c_str());

}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetStreamOutputModuleParamList(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname;
    unsigned int modId;

    for( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        
        if (curPair->GetDataName()=="ModuleName")
        {
            modname=curPair->GetDataString();
        }
        else if (curPair->GetDataName()=="ModuleId")
        {
            curPair->GetData(modId);
        }
    }

    //There shouldn't be two intances of an Aspen framework. so discard the moduleId
    //the returned string will be a well formated XML within "vecommand" element
    std::string netPak = bkp->GetStreamOutputModuleParams(modname);
    return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::handleGetStreamOutputModuleProperties(ves::open::xml::CommandPtr cmd)
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname,paramName;
    unsigned int modId;

    for( size_t i=0; i < num; i++)
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        if (curPair->GetDataName()=="ModuleName")
        {
            modname=curPair->GetDataString();
        }
        else if (curPair->GetDataName()=="moduleId")
        {
            curPair->GetData(modId); //modId is discarded because of the same reason as before
        }
        else if (curPair->GetDataName()=="ParamName")
        {
            paramName=curPair->GetDataString();
        }
    }
    std::string netPak = bkp->GetStreamOutputModuleParamProperties(modname, paramName);
    return CORBA::string_dup(netPak.c_str());

}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::SetParams (CORBA::Long id,
    const char * param)
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    //discard the id, it is not used;
    ves::open::xml::XMLReaderWriter networkWriter;
    networkWriter.UseStandaloneDOMDocumentManager();
    networkWriter.ReadFromString();
    networkWriter.ReadXMLData( param, "Command", "vecommand" );
    std::vector< ves::open::xml::XMLObjectPtr > objectVector = 
        networkWriter.GetLoadedXMLObjects();

    //this part would need rewrite later
    for( size_t i = 0; i < objectVector.size(); ++i )
    {
        ves::open::xml::CommandPtr paramCmd = 
            boost::dynamic_pointer_cast<ves::open::xml::Command>( 
            objectVector.at( i ) );
        std::string paramName = paramCmd->GetCommandName();

        //insert code here to resolve how upwind data is passed to aspen unit
        //when it is included in a network
        size_t numDVP = boost::dynamic_pointer_cast< ves::open::xml::Command >(
            paramCmd->GetDataValuePair( "setParam" )->GetDataXMLObject())->
            GetNumberOfDataValuePairs();
 
        for( size_t j = 0; j < numDVP; ++j )
        {
            ves::open::xml::DataValuePairPtr tempDVP =
                boost::dynamic_pointer_cast< ves::open::xml::Command >(
                paramCmd->GetDataValuePair( "setParam" )->GetDataXMLObject())->
                GetDataValuePair( j );
           
            ves::open::xml::CommandPtr tempCmd =
                boost::dynamic_pointer_cast< ves::open::xml::Command >(
                tempDVP->GetDataXMLObject());

            SetParam( tempCmd );
        }
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::SetParam( ves::open::xml::CommandPtr cmd )
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname,paramName, paramValue;

    if( bkpFlag )
    {
        for( size_t i = 0; i < num; i++)
        {
            ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
            if (curPair->GetDataName()=="ModuleName")
            {
                modname=curPair->GetDataString();
            }
            else if (curPair->GetDataName()=="ParamName")
            {
                paramName=curPair->GetDataString();
            }
            else if (curPair->GetDataName()=="ParamValue")
            {
                paramValue=curPair->GetDataString();
            }
        }
        
        CASI::CASIObj cur_block = bkp->aspendoc->getBlockByName(modname.c_str());
        CASI::Variable tempvar = cur_block.getInputVarByName(paramName.c_str());
        CASI::Variable cur_var = bkp->aspendoc->getVarByNodePath(tempvar.getNodePath());
        CString newValue;
        newValue = paramValue.c_str();
        bool success = cur_var.setValue(newValue);
    }
    
    if( dynFlag )
    {
        for( size_t i = 0; i < num; i++)
        {
            ves::open::xml::DataValuePairPtr pair = cmd->GetDataValuePair( i );
            std::vector< std::string > temp_vector;
            pair->GetData( temp_vector );
            dyn->SetValue( temp_vector[0], temp_vector[1], temp_vector[2], true );
        }
    }
}
////////////////////////////////////////////////////////////////////////////////
void VEPSI_i::SetLinkParam( ves::open::xml::CommandPtr cmd )
{
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::string modname,paramName, paramValue;

    if( dynFlag )
    {
        for( size_t i = 0; i < num; i++)
        {
            ves::open::xml::DataValuePairPtr pair = cmd->GetDataValuePair( i );
            std::vector< std::string > temp_vector;
            pair->GetData( temp_vector );
            dyn->SetValue( temp_vector[0].c_str(), temp_vector[1].c_str(),
                temp_vector[2].c_str(), false );
        }
    }
}
///////////////////////////////////////////////////////////////////////////////
void VEPSI_i::addVariable( ves::open::xml::CommandPtr cmd )
{
    ves::open::xml::DataValuePairPtr pair = cmd->GetDataValuePair( 0 );
    std::string var;
    pair->GetData( var );
    if( dynFlag )
    {
        dyn->AddADVariable( var );
    }
    else if( dynSimFlag )
    {
        dynSim->AddOPCVariable( var.c_str() );
    }
}
///////////////////////////////////////////////////////////////////////////////
void VEPSI_i::Monitor(  )
{
    HRESULT hr = CoInitializeEx(NULL, COINIT_MULTITHREADED);
    while (true)
    {
        //Aspen Dynamics
        if( dynFlag )
        {
            int temp = dyn->NumADVars();
            bool tempBool = dyn->IsADVarsEmpty();
            if( !tempBool && dyn && !mQuerying )
            {
                _mutex.acquire();
                std::string netPak = dyn->GetADValues( );
                theParent->GetExecutive()->SetParams(0, 0, CORBA::string_dup( netPak.c_str( ) ) );     
                _mutex.release();
            }
        }

        //DynSim
        if( dynSimFlag )
        {
            if( connected && !dynSim->IsOPCVarsEmpty()&& !mQuerying && dynSim )
            {
                _mutex.acquire();
                //dynsim->AddOPCVariable( "MY_SWITCH" );
                std::string netPak = dynSim->GetOPCValues( );
                theParent->GetExecutive()->SetParams(0, 0, CORBA::string_dup( netPak.c_str( ) ) );            
                _mutex.release();
            }
        }
        vpr::System::msleep( 5 );
    }
    CoUninitialize();
}

///////////////////////////////////////////////////////////////////////////////
void VEPSI_i::UpdateVars( )
{
    if( connected )
    {
        std::vector< std::pair< std::string, std::string > > vars =
            dynSim->ReadVars();
        //std::map< std::string, std::pair< std::string, VARTYPE > > vars =
        //    dynsim->ReadVars();

        if( !vars.empty() )
        {
            //dump results to aspen log
            for( int i = 0; i < vars.size(); i++)
            {
                std::string temp = vars[i].first + " " + vars[i].second +"\n";
                AspenLog->SetSel(-1, -1);
                AspenLog->ReplaceSel( temp.c_str() );
            }

            //dump results to aspen log
            //std::map< std::string, std::pair< std::string, VARTYPE > >::iterator iter;
            //for( iter = vars.begin(); iter != vars.end(); ++iter)
            //{
            //    std::string temp = iter->first + " " + iter->second.first +"\n";
            //    AspenLog->SetSel(-1, -1);
            //    AspenLog->ReplaceSel( temp.c_str() );
            //}
        }
    }
}
///////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::getOPCValues( ves::open::xml::CommandPtr cmd )
{
    std::string netPak = dynSim->GetOPCValues( );
    return CORBA::string_dup( netPak.c_str( ) );
}
///////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::setOPCValues( ves::open::xml::CommandPtr cmd )
{
    //read and parse command into map of var name and value
    size_t num = cmd->GetNumberOfDataValuePairs();
    std::vector< std::pair< std::string, std::string > > varsAndValues;
    for ( size_t i=0; i < num; i++ )
    {
        ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
        std::pair< std::string, std::string > temp;
        temp.first = curPair->GetDataName();
        temp.second = curPair->GetDataString();
        varsAndValues.push_back( temp );
    }
    dynSim->SetOPCValues( varsAndValues );
    return CORBA::string_dup( "NULL" );
}
///////////////////////////////////////////////////////////////////////////////
void VEPSI_i::connectWithList( ves::open::xml::CommandPtr cmd )
{
        //create variable list
        //ves::open::xml::DataValuePairPtr pair = cmd->GetDataValuePair( 0 );
        //std::vector< std::string > list;
        //pair->GetData( list );
        //dynSim->ConnectWithList( list );
}
///////////////////////////////////////////////////////////////////////////////
void VEPSI_i::connectToOPC( ves::open::xml::CommandPtr cmd )
{
    connected = dynSim->ConnectToOPCServer();
    m_thread = new vpr::Thread( boost::bind( &VEPSI_i::Monitor,
            this ) );
    //m_Thread = AfxBeginThread( ThreadFunc, this);
}
///////////////////////////////////////////////////////////////////////////////
char* VEPSI_i::getAllOPCVariables( ves::open::xml::CommandPtr cmd )
{
    ves::open::xml::DataValuePairPtr curPair = cmd->GetDataValuePair( 0 );
    std::string modname = curPair->GetDataString( );
    std::string netPak = dynSim->GetAllOPCVariables( modname.c_str() );
    return CORBA::string_dup( netPak.c_str( ) );
}
