##Builds DefaultPlugin_UI_Dialog
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

srcs = Split("""
    DefaultPlugin.cxx
    DefaultPlugin_UI_Dialog.cxx
""")

env = baseEnv.Copy()
env.Append(CPPPATH = pj('#', 'VE_Conductor', 'Framework') )
env.Append(LIBS = ['VE_ConductorLib', 'VE_XMLLib', 'VE_ModelLib',
                   'VE_CADLib', 'VE_ShaderLib', 'GUIPluginLib',
                   'VE_OpenModuleLib'])
env.ParseConfig( 'wx-config --cxxflags --libs' )
env.ParseConfig('flagpoll tao --cflags --libs')
env.ParseConfig('flagpoll xerces --libs')

targetLib = pj(libPath, 'DefaultPlugin_UI_Dialog')
env.SharedLibrary(targetLib, source = srcs)
