##Builds WinClient program
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('baseEnv ves_pkg RootDir buildDir vtk_options osg_options xerces_options')
openDir = os.path.abspath( pj( RootDir, 'ConstructionBotsGP' ) )

sources = sca_util.getSourcesRecursive( openDir )
headers = sca_util.getHeadersRecursive( openDir )

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append( LIBS = [ 'loki.0.1.6' ])
lib_env.Append( LIBPATH = [ pj( os.getenv( 'VE_INSTALL_DIR' ), 'lib' ) ] )
lib_env.Append( CPPPATH = [ pj( os.getenv( 'VE_INSTALL_DIR' ), 'include' ) ] )

lib_env.ParseConfig( 'flagpoll vrjuggler --libs --cflags' )
lib_env.ParseConfig( 'flagpoll Boost.Filesystem --libs --cflags' )
lib_env.ParseConfig( 'flagpoll bullet --libs --cflags' )

vtk_options.apply( lib_env )
osg_options.apply( lib_env )
xerces_options.apply( lib_env )

lib = ves_pkg.createStaticAndSharedLibrary( 'ConstructionBotsGP', lib_env, pj( RootDir, 'Plugins', 'GE', 'linux-i686' ) )   
lib.addSources( sources )
#lib.addHeaders( headers, pj( 'Plugins', 'GE' ) )
lib.build()
