##Builds VE_XMLLib
import os, sys, string 
import SConsAddons.Util as sca_util
##import practice
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR xerces_options apr_options apu_options RootDir GetPlatform boost_options')
openDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'open', 'xml') )
sources = sca_util.getSourcesRecursive( openDir )
headers = sca_util.getHeadersRecursive( openDir )

lib_env = ves_pkg.getEnv().Clone()

xerces_options.apply( lib_env )
apr_options.apply( lib_env )
apu_options.apply( lib_env )

lib_env.Append( CPPDEFINES = ['VE_XML_LIBRARY'])

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_open_xml',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_open_xml', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources( sources )
lib.addHeaders( headers,  pj( 'ves', 'open', 'xml') )
lib.build()
