##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform poco_options kibitz_options' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'hyper_lab_ice' ) )
ConstraintDemoDir = pj( RootDir, 'share', 'examples', 'hyper_lab_ice' )

#fileBundle.addFiles( [ 'constraint_demo.db' ] )
#fileBundle.addFiles( [ 'constraint_demo.ves' ] )
#iveFile = sca_util.getFilesRecursiveByExt( ConstraintDemoDir, [ '.ive' ] )
#fileBundle.addFiles( iveFile )

hyper_lab_subdirs = Split("""
    UserInterface
    GraphicalPlugin
""")

if kibitz_options.isAvailable() and GetPlatform() == 'win32':
    hyper_lab_subdirs.append( 'opc_client' )

##Run SConscript files in all of these folders.
for d in hyper_lab_subdirs:
   SConscript( dirs = d )
