##Builds VE_ShaderLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

shader_srcs = Split("""
   TextureImage.cxx
   Uniform.cxx
   Program.cxx
   Shader.cxx 
   ShaderCreator.cxx 
""")

srcs = map(lambda s: pj('#', 'VE_Open', 'XML', 'Shader', s), shader_srcs)

env = baseEnv.Copy()
env.Append(LIBS = 'VE_XMLLib')
env.ParseConfig('flagpoll xerces --libs')

targetLib = pj(libPath, 'VE_ShaderLib')
env.SharedLibrary(target = targetLib, source = srcs)
