// This file is generated by omniidl (C++ backend)- omniORB_4_0. Do not edit.

#include "VjObs.h"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_0;



VjObs_ptr VjObs_Helper::_nil() {
  return ::VjObs::_nil();
}

CORBA::Boolean VjObs_Helper::is_nil(::VjObs_ptr p) {
  return CORBA::is_nil(p);

}

void VjObs_Helper::release(::VjObs_ptr p) {
  CORBA::release(p);
}

void VjObs_Helper::duplicate(::VjObs_ptr p) {
  if( p && !p->_NP_is_nil() )  omni::duplicateObjRef(p);
}

void VjObs_Helper::marshalObjRef(::VjObs_ptr obj, cdrStream& s) {
  ::VjObs::_marshalObjRef(obj, s);
}

VjObs_ptr VjObs_Helper::unmarshalObjRef(cdrStream& s) {
  return ::VjObs::_unmarshalObjRef(s);
}

VjObs_ptr
VjObs::_duplicate(::VjObs_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);

  return obj;
}


VjObs_ptr
VjObs::_narrow(CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


VjObs_ptr
VjObs::_unchecked_narrow(CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}


VjObs_ptr
VjObs::_nil()
{
  static _objref_VjObs* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_VjObs;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
}

const char* VjObs::_PD_repoId = "IDL:VjObs:1.0";


_objref_VjObs::~_objref_VjObs() {}


_objref_VjObs::_objref_VjObs(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::VjObs::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_VjObs::_ptrToObjRef(const char* id)
{
  if( id == ::VjObs::_PD_repoId )
    return (::VjObs_ptr) this;
  
  if( id == CORBA::Object::_PD_repoId )
    return (CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::VjObs::_PD_repoId) )
    return (::VjObs_ptr) this;
  
  if( omni::strMatch(id, CORBA::Object::_PD_repoId) )
    return (CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void
class _0RL_cd_FA7BFB3749925F90_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  
    
  
  
};

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->update();


}

void _objref_VjObs::update()
{
  _0RL_cd_FA7BFB3749925F90_00000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_10000000, "update", 7);


  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  _cVjObs_mscalar__p
class _0RL_cd_FA7BFB3749925F90_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  VjObs::scalar_p_var result;
};

void _0RL_cd_FA7BFB3749925F90_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const VjObs::scalar_p&) result >>= _n;

}

void _0RL_cd_FA7BFB3749925F90_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VjObs::scalar_p;
  (VjObs::scalar_p&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_20000000* tcd = (_0RL_cd_FA7BFB3749925F90_20000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->update_scalar();


}

VjObs::scalar_p* _objref_VjObs::update_scalar()
{
  _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_30000000, "update_scalar", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_20000000* tcd = (_0RL_cd_FA7BFB3749925F90_20000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->update_vector();


}

VjObs::scalar_p* _objref_VjObs::update_vector()
{
  _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_40000000, "update_vector", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_20000000* tcd = (_0RL_cd_FA7BFB3749925F90_20000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_geo_name();


}

VjObs::scalar_p* _objref_VjObs::get_geo_name()
{
  _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_50000000, "get_geo_name", 13);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_60000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_20000000* tcd = (_0RL_cd_FA7BFB3749925F90_20000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_teacher_name();


}

VjObs::scalar_p* _objref_VjObs::get_teacher_name()
{
  _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_60000000, "get_teacher_name", 17);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cshort
class _0RL_cd_FA7BFB3749925F90_70000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_70000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  CORBA::Short result;
};

void _0RL_cd_FA7BFB3749925F90_70000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_FA7BFB3749925F90_70000000::unmarshalReturnedValues(cdrStream& _n)
{
  (CORBA::Short&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_80000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_sc_num();


}

CORBA::Short _objref_VjObs::get_sc_num()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_80000000, "get_sc_num", 11);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_geo_num();


}

CORBA::Short _objref_VjObs::get_geo_num()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_90000000, "get_geo_num", 12);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_teacher_num();


}

CORBA::Short _objref_VjObs::get_teacher_num()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_a0000000, "get_teacher_num", 16);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cstring
class _0RL_cd_FA7BFB3749925F90_b0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_b0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  CORBA::String_var result;
};

void _0RL_cd_FA7BFB3749925F90_b0000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_FA7BFB3749925F90_b0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_b0000000* tcd = (_0RL_cd_FA7BFB3749925F90_b0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_perf();


}

char* _objref_VjObs::get_perf()
{
  _0RL_cd_FA7BFB3749925F90_b0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_c0000000, "get_perf", 9);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  void_i_cshort
class _0RL_cd_FA7BFB3749925F90_d0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_d0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  CORBA::Short arg_0;
};

void _0RL_cd_FA7BFB3749925F90_d0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_FA7BFB3749925F90_d0000000::unmarshalArguments(cdrStream& _n)
{
  (CORBA::Short&)arg_0 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_e0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->SetClientInfoFlag(tcd->arg_0);


}

void _objref_VjObs::SetClientInfoFlag(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_e0000000, "SetClientInfoFlag", 18);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  void_i_cVjObs_mobj__p
class _0RL_cd_FA7BFB3749925F90_f0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_f0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  VjObs::obj_p_var arg_0_;
  const VjObs::obj_p* arg_0;
};

void _0RL_cd_FA7BFB3749925F90_f0000000::marshalArguments(cdrStream& _n)
{
  (const VjObs::obj_p&) *arg_0 >>= _n;

}

void _0RL_cd_FA7BFB3749925F90_f0000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new VjObs::obj_p;
  (VjObs::obj_p&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_f0000000* tcd = (_0RL_cd_FA7BFB3749925F90_f0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->SetClientInfoData(*tcd->arg_0);


}

void _objref_VjObs::SetClientInfoData(const VjObs::obj_p& o)
{
  _0RL_cd_FA7BFB3749925F90_f0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_01000000, "SetClientInfoData", 18);
  _call_desc.arg_0 = &(VjObs::obj_p&) o;

  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  _cVjObs_mobj__p
class _0RL_cd_FA7BFB3749925F90_11000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_11000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  VjObs::obj_p_var result;
};

void _0RL_cd_FA7BFB3749925F90_11000000::marshalReturnedValues(cdrStream& _n)
{
  (const VjObs::obj_p&) result >>= _n;

}

void _0RL_cd_FA7BFB3749925F90_11000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new VjObs::obj_p;
  (VjObs::obj_p&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_21000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_11000000* tcd = (_0RL_cd_FA7BFB3749925F90_11000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->GetClientInfoData();


}

VjObs::obj_p* _objref_VjObs::GetClientInfoData()
{
  _0RL_cd_FA7BFB3749925F90_11000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_21000000, "GetClientInfoData", 18);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_31000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->GetNumberOfSounds();


}

CORBA::Short _objref_VjObs::GetNumberOfSounds()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_31000000, "GetNumberOfSounds", 18);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_41000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_20000000* tcd = (_0RL_cd_FA7BFB3749925F90_20000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->GetSoundNameArray();


}

VjObs::scalar_p* _objref_VjObs::GetSoundNameArray()
{
  _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_41000000, "GetSoundNameArray", 18);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_51000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_20000000* tcd = (_0RL_cd_FA7BFB3749925F90_20000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_dataset_names();


}

VjObs::scalar_p* _objref_VjObs::get_dataset_names()
{
  _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_51000000, "get_dataset_names", 18);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_61000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_11000000* tcd = (_0RL_cd_FA7BFB3749925F90_11000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_dataset_types();


}

VjObs::obj_p* _objref_VjObs::get_dataset_types()
{
  _0RL_cd_FA7BFB3749925F90_11000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_61000000, "get_dataset_types", 18);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_71000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_11000000* tcd = (_0RL_cd_FA7BFB3749925F90_11000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_num_scalars_per_dataset();


}

VjObs::obj_p* _objref_VjObs::get_num_scalars_per_dataset()
{
  _0RL_cd_FA7BFB3749925F90_11000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_71000000, "get_num_scalars_per_dataset", 28);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_81000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_11000000* tcd = (_0RL_cd_FA7BFB3749925F90_11000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->get_num_vectors_per_dataset();


}

VjObs::obj_p* _objref_VjObs::get_num_vectors_per_dataset()
{
  _0RL_cd_FA7BFB3749925F90_11000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_81000000, "get_num_vectors_per_dataset", 28);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_91000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setNumDatasets(tcd->arg_0);


}

void _objref_VjObs::setNumDatasets(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_91000000, "setNumDatasets", 15);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_a1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getNumDatasets();


}

CORBA::Short _objref_VjObs::getNumDatasets()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_a1000000, "getNumDatasets", 15);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_b1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getTotalNumberOfScalars();


}

CORBA::Short _objref_VjObs::getTotalNumberOfScalars()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_b1000000, "getTotalNumberOfScalars", 24);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_c1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setNumVectors(tcd->arg_0);


}

void _objref_VjObs::setNumVectors(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_c1000000, "setNumVectors", 14);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_d1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getNumVectors();


}

CORBA::Short _objref_VjObs::getNumVectors()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_d1000000, "getNumVectors", 14);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_e1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setNumGeoArrays(tcd->arg_0);


}

void _objref_VjObs::setNumGeoArrays(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_e1000000, "setNumGeoArrays", 16);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_f1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getNumGeoArrays();


}

CORBA::Short _objref_VjObs::getNumGeoArrays()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_f1000000, "getNumGeoArrays", 16);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  void_i_clong
class _0RL_cd_FA7BFB3749925F90_02000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_02000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  CORBA::Long arg_0;
};

void _0RL_cd_FA7BFB3749925F90_02000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_FA7BFB3749925F90_02000000::unmarshalArguments(cdrStream& _n)
{
  (CORBA::Long&)arg_0 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_12000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_02000000* tcd = (_0RL_cd_FA7BFB3749925F90_02000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setClients(tcd->arg_0);


}

void _objref_VjObs::setClients(CORBA::Long value)
{
  _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_12000000, "setClients", 11);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  _clong
class _0RL_cd_FA7BFB3749925F90_22000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_FA7BFB3749925F90_22000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall) {}
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  CORBA::Long result;
};

void _0RL_cd_FA7BFB3749925F90_22000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_FA7BFB3749925F90_22000000::unmarshalReturnedValues(cdrStream& _n)
{
  (CORBA::Long&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_32000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_22000000* tcd = (_0RL_cd_FA7BFB3749925F90_22000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getClients();


}

CORBA::Long _objref_VjObs::getClients()
{
  _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_32000000, "getClients", 11);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_42000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_02000000* tcd = (_0RL_cd_FA7BFB3749925F90_02000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setIsoValue(tcd->arg_0);


}

void _objref_VjObs::setIsoValue(CORBA::Long value)
{
  _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_42000000, "setIsoValue", 12);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_52000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_22000000* tcd = (_0RL_cd_FA7BFB3749925F90_22000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getIsoValue();


}

CORBA::Long _objref_VjObs::getIsoValue()
{
  _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_52000000, "getIsoValue", 12);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_62000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_02000000* tcd = (_0RL_cd_FA7BFB3749925F90_02000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setSc(tcd->arg_0);


}

void _objref_VjObs::setSc(CORBA::Long value)
{
  _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_62000000, "setSc", 6);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_72000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_22000000* tcd = (_0RL_cd_FA7BFB3749925F90_22000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getSc();


}

CORBA::Long _objref_VjObs::getSc()
{
  _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_72000000, "getSc", 6);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_82000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_02000000* tcd = (_0RL_cd_FA7BFB3749925F90_02000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setMin(tcd->arg_0);


}

void _objref_VjObs::setMin(CORBA::Long value)
{
  _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_82000000, "setMin", 7);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_92000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_22000000* tcd = (_0RL_cd_FA7BFB3749925F90_22000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getMin();


}

CORBA::Long _objref_VjObs::getMin()
{
  _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_92000000, "getMin", 7);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_a2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_02000000* tcd = (_0RL_cd_FA7BFB3749925F90_02000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setMax(tcd->arg_0);


}

void _objref_VjObs::setMax(CORBA::Long value)
{
  _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_a2000000, "setMax", 7);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_b2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_22000000* tcd = (_0RL_cd_FA7BFB3749925F90_22000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getMax();


}

CORBA::Long _objref_VjObs::getMax()
{
  _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_b2000000, "getMax", 7);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_c2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_02000000* tcd = (_0RL_cd_FA7BFB3749925F90_02000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setId(tcd->arg_0);


}

void _objref_VjObs::setId(CORBA::Long value)
{
  _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_c2000000, "setId", 6);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_d2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_22000000* tcd = (_0RL_cd_FA7BFB3749925F90_22000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getId();


}

CORBA::Long _objref_VjObs::getId()
{
  _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_d2000000, "getId", 6);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_e2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_02000000* tcd = (_0RL_cd_FA7BFB3749925F90_02000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setGeoState(tcd->arg_0);


}

void _objref_VjObs::setGeoState(CORBA::Long value)
{
  _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_e2000000, "setGeoState", 12);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_f2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_22000000* tcd = (_0RL_cd_FA7BFB3749925F90_22000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getGeoState();


}

CORBA::Long _objref_VjObs::getGeoState()
{
  _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_f2000000, "getGeoState", 12);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_03000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setPostdataState(tcd->arg_0);


}

void _objref_VjObs::setPostdataState(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_03000000, "setPostdataState", 17);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_13000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getPostdataState();


}

CORBA::Short _objref_VjObs::getPostdataState()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_13000000, "getPostdataState", 17);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_23000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setPreState(tcd->arg_0);


}

void _objref_VjObs::setPreState(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_23000000, "setPreState", 12);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_33000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getPreState();


}

CORBA::Short _objref_VjObs::getPreState()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_33000000, "getPreState", 12);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_43000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setTimesteps(tcd->arg_0);


}

void _objref_VjObs::setTimesteps(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_43000000, "setTimesteps", 13);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_53000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getTimesteps();


}

CORBA::Short _objref_VjObs::getTimesteps()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_53000000, "getTimesteps", 13);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_63000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setNumTeacherArrays(tcd->arg_0);


}

void _objref_VjObs::setNumTeacherArrays(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_63000000, "setNumTeacherArrays", 20);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_73000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getNumTeacherArrays();


}

CORBA::Short _objref_VjObs::getNumTeacherArrays()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_73000000, "getNumTeacherArrays", 20);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_83000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_d0000000* tcd = (_0RL_cd_FA7BFB3749925F90_d0000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  impl->setTeacherState(tcd->arg_0);


}

void _objref_VjObs::setTeacherState(CORBA::Short value)
{
  _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_83000000, "setTeacherState", 16);
  _call_desc.arg_0 = value;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_FA7BFB3749925F90_93000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_FA7BFB3749925F90_70000000* tcd = (_0RL_cd_FA7BFB3749925F90_70000000*)cd;
  _impl_VjObs* impl = (_impl_VjObs*) svnt->_ptrToInterface(VjObs::_PD_repoId);
  tcd->result = impl->getTeacherState();


}

CORBA::Short _objref_VjObs::getTeacherState()
{
  _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_93000000, "getTeacherState", 16);


  _invoke(_call_desc);
  return _call_desc.result;


}
_pof_VjObs::~_pof_VjObs() {}


omniObjRef*
_pof_VjObs::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_VjObs(ior, id);
}


CORBA::Boolean
_pof_VjObs::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::VjObs::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_VjObs _the_pof_VjObs;

_impl_VjObs::~_impl_VjObs() {}


CORBA::Boolean
_impl_VjObs::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "update") ) {

    _0RL_cd_FA7BFB3749925F90_00000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_10000000, "update", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "update_scalar") ) {

    _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_30000000, "update_scalar", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "update_vector") ) {

    _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_40000000, "update_vector", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_geo_name") ) {

    _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_50000000, "get_geo_name", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_teacher_name") ) {

    _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_60000000, "get_teacher_name", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_sc_num") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_80000000, "get_sc_num", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_geo_num") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_90000000, "get_geo_num", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_teacher_num") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_a0000000, "get_teacher_num", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_perf") ) {

    _0RL_cd_FA7BFB3749925F90_b0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_c0000000, "get_perf", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "SetClientInfoFlag") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_e0000000, "SetClientInfoFlag", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "SetClientInfoData") ) {

    _0RL_cd_FA7BFB3749925F90_f0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_01000000, "SetClientInfoData", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "GetClientInfoData") ) {

    _0RL_cd_FA7BFB3749925F90_11000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_21000000, "GetClientInfoData", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "GetNumberOfSounds") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_31000000, "GetNumberOfSounds", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "GetSoundNameArray") ) {

    _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_41000000, "GetSoundNameArray", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_dataset_names") ) {

    _0RL_cd_FA7BFB3749925F90_20000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_51000000, "get_dataset_names", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_dataset_types") ) {

    _0RL_cd_FA7BFB3749925F90_11000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_61000000, "get_dataset_types", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_num_scalars_per_dataset") ) {

    _0RL_cd_FA7BFB3749925F90_11000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_71000000, "get_num_scalars_per_dataset", 28, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_num_vectors_per_dataset") ) {

    _0RL_cd_FA7BFB3749925F90_11000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_81000000, "get_num_vectors_per_dataset", 28, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setNumDatasets") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_91000000, "setNumDatasets", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getNumDatasets") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_a1000000, "getNumDatasets", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getTotalNumberOfScalars") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_b1000000, "getTotalNumberOfScalars", 24, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setNumVectors") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_c1000000, "setNumVectors", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getNumVectors") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_d1000000, "getNumVectors", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setNumGeoArrays") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_e1000000, "setNumGeoArrays", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getNumGeoArrays") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_f1000000, "getNumGeoArrays", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setClients") ) {

    _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_12000000, "setClients", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getClients") ) {

    _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_32000000, "getClients", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setIsoValue") ) {

    _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_42000000, "setIsoValue", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getIsoValue") ) {

    _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_52000000, "getIsoValue", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setSc") ) {

    _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_62000000, "setSc", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getSc") ) {

    _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_72000000, "getSc", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setMin") ) {

    _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_82000000, "setMin", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getMin") ) {

    _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_92000000, "getMin", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setMax") ) {

    _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_a2000000, "setMax", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getMax") ) {

    _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_b2000000, "getMax", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setId") ) {

    _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_c2000000, "setId", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getId") ) {

    _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_d2000000, "getId", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setGeoState") ) {

    _0RL_cd_FA7BFB3749925F90_02000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_e2000000, "setGeoState", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getGeoState") ) {

    _0RL_cd_FA7BFB3749925F90_22000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_f2000000, "getGeoState", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setPostdataState") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_03000000, "setPostdataState", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getPostdataState") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_13000000, "getPostdataState", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setPreState") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_23000000, "setPreState", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getPreState") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_33000000, "getPreState", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setTimesteps") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_43000000, "setTimesteps", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getTimesteps") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_53000000, "getTimesteps", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setNumTeacherArrays") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_63000000, "setNumTeacherArrays", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getNumTeacherArrays") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_73000000, "getNumTeacherArrays", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setTeacherState") ) {

    _0RL_cd_FA7BFB3749925F90_d0000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_83000000, "setTeacherState", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getTeacherState") ) {

    _0RL_cd_FA7BFB3749925F90_70000000 _call_desc(_0RL_lcfn_FA7BFB3749925F90_93000000, "getTeacherState", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_VjObs::_ptrToInterface(const char* id)
{
  if( id == ::VjObs::_PD_repoId )
    return (_impl_VjObs*) this;
  
  if( id == CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::VjObs::_PD_repoId) )
    return (_impl_VjObs*) this;
  
  if( omni::strMatch(id, CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_VjObs::_mostDerivedRepoId()
{
  return ::VjObs::_PD_repoId;
}

POA_VjObs::~POA_VjObs() {}

