##Builds VE_OpenModuleLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

srcs = Split("""
   moduleS.cpp
   moduleC.cpp
   VjObsC.cpp
   VjObsS.cpp
""")
##srcs = map(lambda s: pj('#', 'VE_Open', 'skel', s), srcs)

env = baseEnv.Copy()
env.ParseConfig('flagpoll TAO ACE TAO_IORInterceptor TAO_ObjRefTemplate TAO_Valuetype \
                              TAO_CosNaming TAO_Svc_Utils TAO_IORTable TAO_Messaging \
                              TAO_PortableServer TAO_BiDirGIOP TAO_AnyTypeCode --cflags --libs')

targetLib = pj(env[ 'LIBDIR' ], 'VE_OpenModuleLib')
env.SharedLibrary(target = targetLib, source = srcs)
