##Builds VE_OpenModuleLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

srcs = Split("""
   moduleS.cpp
   moduleC.cpp
   VjObsC.cpp
   VjObsS.cpp
""")
srcs = map(lambda s: pj('#', 'VE_Open', 'skel', s), srcs)

env = baseEnv.Copy()
env.Append(LIBS = ['VE_XMLLib', 'VE_ShaderLib'])
env.ParseConfig('flagpoll tao --cflags --libs')

targetLib = pj(libPath, 'VE_OpenModuleLib')
env.SharedLibrary(target = targetLib, source = srcs)
