import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')
Import('ace_tao')

skel_srcs = Split("""
   moduleS.cpp
   moduleC.cpp
   VjObsC.cpp
   VjObsS.cpp
""")
skel_srcs = map(lambda s: pj('#', 'VE_Open', 'skel', s), skel_srcs)

env = baseEnv.Copy()
#env.Append(CPPPATH = [os.getcwd()])
env.Append(CPPPATH = ['#'])
##env.Append(CPPPATH = pj( env['TAO_HOME'], 'include') )
##env.Append(CPPPATH = pj( '/home/vr/Applications/TSVEG/Libraries/Release/Opt/ACE-TAO-5.4/Linux-RHEL_4', 'include') )
env.ParseConfig('flagpoll tao --cflags')
env.Append(LIBPATH = libPath,
              LIBS = ['VE_XMLLib', 'VE_ShaderLib'])
for lib in ace_tao:
   env.Append(LIBS = lib)

targetLib = pj(libPath, 'VE_OpenModuleLib')
env.SharedLibrary(target = targetLib, source = skel_srcs)
#env.Program(pj('#','bin',Platform,'VE_Open','VE_XML'), source = skel_srcs)
