#Builds db
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import( 'baseEnv ves_pkg LIBDIR RootDir buildDir GetPlatform' )
Import( 'xerces_options tao_options wxwidgets_options mysqlpp_options' )
openDir = os.path.abspath( pj( RootDir, 'share', 'tools', 'db' ) )
sources = sca_util.getSourcesRecursive( openDir )
headers = sca_util.getHeadersRecursive( openDir )

env = ves_pkg.getEnv().Clone()
env.Append( LIBS = [ 'ves_open_module',
                     'ves_open_xml' ] )
env.Append( LIBPATH = [ pj( '#', buildDir, 'src', 'ves', 'open' ),
                        pj( '#', buildDir, 'src', 'ves', 'open','xml' ) ] )
#env.Append( CPPPATH = [ pj( RootDir, 'external', 'osgEphemeris', 'include' ) ] )
#env.Append( CPPDEFINES = [ 'VE_USER_PLUGIN_LIBRARY' ] )
  
xerces_options.apply( env )
tao_options.apply( env )
wxwidgets_options.apply( env )
mysqlpp_options.apply( env )

prog = ves_pkg.createProgram( 'ves_db' + env[ "PROGSUFFIX" ], env, 'bin' )
prog.addSources( sources )
prog.addHeaders( headers )
prog.build()
