##Builds loaderToVtk program
import os, sys, string
pj = os.path.join

Import('baseEnv libPath ves_pkg LIBDIR GetPlatform buildDir')

srcs = Split("""
   main.cxx
""")
srcs = map(lambda s: pj('#', buildDir, 'VE_Builder', 'Translator', 'DataLoader', s), srcs)

env = ves_pkg.getEnv().Copy()
env.Append(LIBS = ['VE_UtilLib', 'DataLoaderLib', 'TranslatorToVTKLib'])

env.ParseConfig('flagpoll Boost.Filesystem vtk --cflags --libs')

prog = ves_pkg.createProgram('loaderToVtk', env, 'bin')
prog.addSources( srcs )
prog.build()


