##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'VirtualLab' ) )
virtuallabDemoDir = pj( RootDir, 'share', 'examples', 'VirtualLab' )
iveFile = sca_util.getFilesRecursiveByExt( virtuallabDemoDir, [ '.ive' ] )

virtuallabSubdirs = Split("""
    VirtualLabGP
    VirtualLabUI
""")

##Run SConscript files in all of these folders.
for d in virtuallabSubdirs:
   SConscript( dirs = d )
