##Builds vtkTo3DTexture
import os, sys, string
pj = os.path.join

Import('baseEnv libPath ves_pkg LIBDIR GetPlatform')

srcs = Split("""
   flowTexture.cpp 
   tcApp.cpp
   tcFrame.cpp 
   textureCreator.cpp
""")
##srcs = map(lambda s: pj('#', 'VE_Builder', 'vtkTo3DTexture', 'tcGUI', s), srcs)

env = ves_pkg.getEnv().Copy()
env.Append(LIBS = ['VE_UtilLib'])
env.ParseConfig('flagpoll vtk Boost.Filesystem --libs --cflags')
env.ParseConfig('wx-config --cxxflags --libs')

prog = ves_pkg.createProgram('vtkTo3DTexture', env, 'bin')
prog.addSources( srcs )
prog.build()
