##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'CameraPlacementTool' ) )
CameraPlacementToolDir = pj( RootDir, 'share', 'examples', 'CameraPlacementTool' )

iveFile = sca_util.getFilesRecursiveByExt( CameraPlacementToolDir, [ '.ive' ] )
#jpgFile = sca_util.getFilesRecursiveByExt( CameraPlacementToolDir, [ '.jpg' ] )
tgaFile = sca_util.getFilesRecursiveByExt( CameraPlacementToolDir, [ '.tga' ] )
#wavFile = sca_util.getFilesRecursiveByExt( CameraPlacementToolDir, [ '.wav' ] )

fileBundle.addFiles( iveFile )
#fileBundle.addFiles( jpgFile )
fileBundle.addFiles( tgaFile )
#fileBundle.addFiles( wavFile )
fileBundle.addFiles( [ 'cameraplacementtool.ves' ] )

CameraPlacementToolSubdirs = Split("""
    GraphicalPlugin
    UserInterface
""")

##Run SConscript files in all of these folders.
for d in CameraPlacementToolSubdirs:
   SConscript( dirs = d )
