##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'CameraPlacementTool' ) )
CameraPlacementToolDir = pj( RootDir, 'share', 'examples', 'CameraPlacementTool' )

#iveFile = sca_util.getFilesRecursiveByExt( CameraPlacementToolDir, [ '.ive' ] )
#xpmFile = sca_util.getFilesRecursiveByExt( CameraPlacementToolDir, [ '.xpm' ] )
jpgFile = sca_util.getFilesRecursiveByExt( CameraPlacementToolDir, [ '.jpg' ] )
#wavFile = sca_util.getFilesRecursiveByExt( CameraPlacementToolDir, [ '.wav' ] )

#fileBundle.addFiles( iveFile )
#fileBundle.addFiles( xpmFile )
fileBundle.addFiles( jpgFile )
#fileBundle.addFiles( wavFile )
#fileBundle.addFiles( [ '.ves' ] )

CameraPlacementToolSubdirs = Split("""
    GraphicalPlugin
    UserInterfacePlugin
""")

##Run SConscript files in all of these folders.
for d in CameraPlacementToolSubdirs:
   SConscript( dirs = d )
