import os, sys, string
pj = os.path.join

Import('baseEnv')

sources = Split("""
   avgVariables.cpp
   converter.cpp
   dump.cpp
   fluentCase.cpp
   fluentIO.cpp
   fluentObjects.cpp
   FluentTranslator.cpp
   fluentVtkFactory.cpp
   FormatSelector.cpp
   mFixTranslator.cpp
   parseFluent.cpp
   reorder.cpp
   setOperators.cpp
   setOperators.hpp
   setOperators_stl.hpp
   toVTK.cpp
   UnstructuredGridWriter.cpp
""")
env = baseEnv.Copy()
env.Append(CPPPATH = [os.getcwd()])
env.Program('vexplorer', source = sources)
