##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'VascularSimViewer' ) )
VascularSimViewerDir = pj( RootDir, 'share', 'examples', 'VascularSimViewer' )

#fileBundle.addFiles( [ 'vascularsimviewer.ves' ] )
iveFile = sca_util.getFilesRecursiveByExt( VascularSimViewerDir, [ '.ive' ] )
fileBundle.addFiles( iveFile )

VascularSimViewerSubdirs = Split("""
    GraphicalPlugin
    UserInterface
""")

##Run SConscript files in all of these folders.
for d in VascularSimViewerSubdirs:
   SConscript( dirs = d )
