##Builds VE_NURBSLib<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('Platform')
Import('libPath')
Import('execOsgPatTag')

srcs = Split("""
   ControlPoint.cxx
   KnotVector.cxx
   NCurve.cxx
   NSurface.cxx
   NURBSNode.cxx
   NURBSObject.cxx
""")

env = baseEnv.Copy()
##env.Append(CPPPATH = [os.getcwd()])
env.ParseConfig('flagpoll osg --libs --cflags')

targetLib = pj(env[ 'LIBDIR' ], 'VE_NURBSLib%s' %(execOsgPatTag))
env.SharedLibrary(target = targetLib, source = srcs)
