#ifndef _VE_UI_CONTROL_IDS_H_
#define _VE_UI_CONTROL_IDS_H_

enum UI_GLOBAL_IDS{
//the notebook control id
   ID_UI_TABS = wxID_HIGHEST
};

//Visualizaton tab control ids
/*enum VIS_TAB_IDS{
   CATEGORY_RAD_BOX,
   CONTOUR_RAD_BOX,
   DIRECTION_RBOX,
   PRE_COMP_SURF_BUTTON,
   SINGLE_PLANE_BUTTON,
   CYCLE_CHECK_BOX,
   NEAREST_PLANE_CHECK_BOX,
   VIS_SLIDER,
   UPDATE_BUTTON,
   BLUE_MENU_CHECK_BOX,
   SCALAR_BAR_CHECK_BOX,
   RECORD_BUTTON,
   CLEAR_BUTTON,
   EXIT_BUTTON
//end vis tab control ids
};
*/
//Scalars tab control ids
/*enum SCALAR_TAB_IDS{
   SCALAR_RAD_BOX,
   SCALAR_UPDATE_BUTTON,
   MIN_PER_SLIDER,
   MAX_PER_SLIDER
};
*/
//Vector tab control ids
/*enum VECTOR_TAB_IDS{
   VECTOR_UPDATE_BUTTON,
   SCALE_VEC_MAG_CHK,
   MIN_THRESH_SLIDER,
   MAX_THRESH_SLIDER,
   RATIO_SLIDER,
   SCALE_SLIDER,
   VECTOR_RAD_BOX

};
*/
/*enum STREAMLINE_TAB_IDS{
   CURSOR_SELECT_RBOX,
   DIR_RBOX,
   INTEGRATE_DIR_RBOX,
   COMP_STREAMLINE_BUTTON,
   PARTICLE_TRACK_BUTTON,
   SEED_POINTS_CHK,
   NUM_PTS_SLIDER,
   SIZE_SLIDER,
   PROP_SLIDER,
   INT_STEP_SLIDER,
   STEP_SLIDER
};

enum DATASETS_TAB_IDS{
   RBOX_3D,
   VERTEX_RBOX,
   POLYDATA_RBOX,
   SCALAR_1_RBOX,
   SCALAR_2_RBOX,
   SCALAR_3_RBOX
};

enum SOUNDS_TAB_IDS{
   SOUND_RBOX,
   SOUND_UPDATE_BUTTON
};
enum TEACHER_TAB_IDS{
   TEACHER_RBOX
};
enum GEOMETRY_TAB_IDS{
   GEOMETRY_RBOX,
   GEOMETRY_UPDATE_BUTTON
};*/
#endif // _VE_UI_CONTROL_IDS_H_
