##Builds a multitude of utilities
import os, sys, string
pj = os.path.join

Import('baseEnv RootDir ves_pkg LIBDIR GetPlatform buildDir vtk_options')

srcs = Split("""
   fluentmulti.c2p.cpp
""")


#env = ves_pkg.getEnv().Clone()
env = baseEnv.Clone()
vtk_options.apply( env )

multiblock = ves_pkg.createProgram('multiblockTest' + env["PROGSUFFIX"], env, 'bin')
multiblock.addSources( srcs )
multiblock.build()


srcs1 = Split("""
   polyhedral_test.cpp
""")

poly = ves_pkg.createProgram('polyhedralTest' + env["PROGSUFFIX"], env, 'bin')
poly.addSources( srcs1 )
poly.build()

SConscript( dirs = ['vector_field'] )
