##Builds BaffleUnit program
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import('ves_pkg buildDir RootDir osg_options xerces_options GetPlatform vpr_options vrjuggler_options')

lib_env = ves_pkg.getEnv().Clone()

vrjuggler_options.apply( lib_env )

srcs = Split("""
    main.cpp
""")

prog1 = ves_pkg.createProgram('matrix_test' + lib_env["PROGSUFFIX"], lib_env,
          installPrefix = pj( 'share', 'vesuite', 'examples', 'dynamic_vehicle_sim_tool', 'bird_test' ))

prog1.addSources(srcs)
prog1.build()
