##Builds BaffleUnit program
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join
env=Environment(CPPPATH='/Users/adams/mySoftware/plplot5.9.5/include/plplot')
host_type = distutils.util.get_platform()

Import('ves_pkg buildDir RootDir osg_options xerces_options tao_options GetPlatform')

srcs = Split("""
	sensor_overlayUNIT_server.cxx
	sensor_overlayUNIT_i.cxx
	Sensor_DataC.cpp
	Sensor_DataI.cpp
	Sensor_DataS.cpp
	
""")

headers = Split("""
	sensor_overlayUNIT_i.h
	Sensor_DataC.h
	Sensor_DataI.h
	Senosr_DataS.h
""")

lib_env = ves_pkg.getEnv().Clone()
lib_env.Append(LIBS = ['ves_open_xml', 'ves_ce_unitwrapper', 'ves_open_module'])
lib_env.Append(LIBPATH = [pj(RootDir, buildDir, 'src', 'ves', 'open'),
			                 pj(RootDir, buildDir, 'src', 'ves', 'open', 'xml'),
			                 pj(RootDir, buildDir, 'src', 'ves', 'ce', 'unitwrapper')])

#lib_env.Append(LIBPATH='/Users/adams/mySoftware/plplot5.9.5/lib')
lib_env.Append(LIBPATH='./')
lib_env.Append(LIBS = ['csirocsa.0.0.1', 'plplotcxxd.9.3.0', 'plplotd.9.7.0', 'qsastime.0.0.1'])
lib_env.Append(CPPPATH= '/Users/adams/mySoftware/plplot5.9.5/include/plplot')

if GetPlatform() == 'win32':
   lib_env.Append( CPPDEFINES = ['_WIN32_WINNT=0x400'] )

tao_options.apply( lib_env )
osg_options.apply( lib_env )
xerces_options.apply( lib_env )

prog = ves_pkg.createProgram('sensor_overlayUNIT' + lib_env["PROGSUFFIX"], lib_env,
          installPrefix = pj( 'share', 'vesuite', 'examples', 'sensor_overlay', 'Plugins', 'Unit', host_type ))

prog.addSources(srcs)
prog.build()
