// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:381


#include "Sensor_DataC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "Sensor_DataC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for Sensor_Data.

Sensor_Data_ptr
TAO::Objref_Traits<Sensor_Data>::duplicate (
    Sensor_Data_ptr p)
{
  return Sensor_Data::_duplicate (p);
}

void
TAO::Objref_Traits<Sensor_Data>::release (
    Sensor_Data_ptr p)
{
  ::CORBA::release (p);
}

Sensor_Data_ptr
TAO::Objref_Traits<Sensor_Data>::nil (void)
{
  return Sensor_Data::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Sensor_Data>::marshal (
    const Sensor_Data_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*_TAO_Sensor_Data_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Short Sensor_Data::setup_files (
    const char * node_name)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Sensor_Data_Proxy_Broker_ == 0)
    {
      Sensor_Data_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Short>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_node_name (node_name);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_node_name
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setup_files",
      11,
      this->the_TAO_Sensor_Data_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Short Sensor_Data::write_temperature_to_file (
    const char * node_name,
    ::CORBA::Short DAQBox,
    ::CORBA::Short channel,
    ::CORBA::Double temperature,
    ::CORBA::Double time)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Sensor_Data_Proxy_Broker_ == 0)
    {
      Sensor_Data_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Short>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_node_name (node_name);
  TAO::Arg_Traits< ::CORBA::Short>::in_arg_val _tao_DAQBox (DAQBox);
  TAO::Arg_Traits< ::CORBA::Short>::in_arg_val _tao_channel (channel);
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_temperature (temperature);
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_time (time);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_node_name,
      &_tao_DAQBox,
      &_tao_channel,
      &_tao_temperature,
      &_tao_time
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      6,
      "write_temperature_to_file",
      25,
      this->the_TAO_Sensor_Data_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:78

::CORBA::Double Sensor_Data::send_temperature (
    const char * node_name,
    ::CORBA::Short DAQBox,
    ::CORBA::Short channel,
    ::CORBA::Double temperature,
    ::CORBA::Double time)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Sensor_Data_Proxy_Broker_ == 0)
    {
      Sensor_Data_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::CORBA::Double>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_node_name (node_name);
  TAO::Arg_Traits< ::CORBA::Short>::in_arg_val _tao_DAQBox (DAQBox);
  TAO::Arg_Traits< ::CORBA::Short>::in_arg_val _tao_channel (channel);
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_temperature (temperature);
  TAO::Arg_Traits< ::CORBA::Double>::in_arg_val _tao_time (time);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_node_name,
      &_tao_DAQBox,
      &_tao_channel,
      &_tao_temperature,
      &_tao_time
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      6,
      "send_temperature",
      16,
      this->the_TAO_Sensor_Data_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_operation/operation_cs.cpp:78

void Sensor_Data::createPLPLOT (
    const char * node_name,
    ::CORBA::Short channel,
    ::CORBA::Short numberOfChannels)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_Sensor_Data_Proxy_Broker_ == 0)
    {
      Sensor_Data_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_node_name (node_name);
  TAO::Arg_Traits< ::CORBA::Short>::in_arg_val _tao_channel (channel);
  TAO::Arg_Traits< ::CORBA::Short>::in_arg_val _tao_numberOfChannels (numberOfChannels);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_node_name,
      &_tao_channel,
      &_tao_numberOfChannels
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      4,
      "createPLPLOT",
      12,
      this->the_TAO_Sensor_Data_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

Sensor_Data::Sensor_Data (void)
 : the_TAO_Sensor_Data_Proxy_Broker_ (0)
{
  this->Sensor_Data_setup_collocation ();
}

void
Sensor_Data::Sensor_Data_setup_collocation ()
{
  if (::_TAO_Sensor_Data_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_Sensor_Data_Proxy_Broker_ =
        ::_TAO_Sensor_Data_Proxy_Broker_Factory_function_pointer (this);
    }
}

Sensor_Data::~Sensor_Data (void)
{}

void 
Sensor_Data::_tao_any_destructor (void *_tao_void_pointer)
{
  Sensor_Data *_tao_tmp_pointer =
    static_cast<Sensor_Data *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Sensor_Data_ptr
Sensor_Data::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Sensor_Data>::narrow (
        _tao_objref,
        "IDL:Sensor_Data:1.0",
        _TAO_Sensor_Data_Proxy_Broker_Factory_function_pointer
      );
}

Sensor_Data_ptr
Sensor_Data::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<Sensor_Data>::unchecked_narrow (
        _tao_objref,
        "IDL:Sensor_Data:1.0",
        _TAO_Sensor_Data_Proxy_Broker_Factory_function_pointer
      );
}

Sensor_Data_ptr
Sensor_Data::_duplicate (Sensor_Data_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
Sensor_Data::_tao_release (Sensor_Data_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Sensor_Data::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:Sensor_Data:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Sensor_Data::_interface_repository_id (void) const
{
  return "IDL:Sensor_Data:1.0";
}

::CORBA::Boolean
Sensor_Data::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Sensor_Data (
    ::CORBA::tk_objref,
    "IDL:Sensor_Data:1.0",
    "Sensor_Data");
  
::CORBA::TypeCode_ptr const _tc_Sensor_Data =
  &_tao_tc_Sensor_Data;

// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Sensor_Data>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Sensor_Data_ptr _tao_elem)
{
  Sensor_Data_ptr _tao_objptr =
    Sensor_Data::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Sensor_Data_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Sensor_Data>::insert (
      _tao_any,
      Sensor_Data::_tao_any_destructor,
      _tc_Sensor_Data,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Sensor_Data_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Sensor_Data>::extract (
        _tao_any,
        Sensor_Data::_tao_any_destructor,
        _tc_Sensor_Data,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// ../../../TAO/TAO_IDL/be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Sensor_Data_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Sensor_Data_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::Sensor_Data RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        _TAO_Sensor_Data_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



