// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// ../../../TAO/TAO_IDL/be/be_codegen.cpp:1135

#ifndef SENSOR_DATAI_H_
#define SENSOR_DATAI_H_

#include "Sensor_DataS.h"
#include "ace/Task.h"
#include <string>
//#include "plc++demos.h"
#include "plstream.h"
//#include "pngPlotClass.h"
#include <string>
#include <vector>
#ifdef USE_NAMESPACE
using namespace std;
#endif 


#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  Sensor_Data_i
: public virtual POA_Sensor_Data
{
public:
	
	std::vector<std::string> node;
	std::vector<int> daq;
	std::vector<int> channel;
	std::vector<double> temperature;
	std::vector<double> dataTime;
	
	// Constructor 
	Sensor_Data_i (void);
	
	// Destructor 
	virtual ~Sensor_Data_i (void);
	
	virtual
	::CORBA::Short setup_files (
								const char * node_name);
	
	virtual
	::CORBA::Short write_temperature_to_file (
											  const char * node_name,
											  ::CORBA::Short DAQBox,
											  ::CORBA::Short channel,
											  ::CORBA::Double temperature,
											  ::CORBA::Double time);
	
	virtual
	::CORBA::Double send_temperature (
									  const char * node_name,
									  ::CORBA::Short DAQBox,
									  ::CORBA::Short channel,
									  ::CORBA::Double temperature,
									  ::CORBA::Double time);
	
	
	
	virtual
	void createPLPLOT (
					   const char * node_name,
					   ::CORBA::Short channel,
					   ::CORBA::Short numberOfChannels);
	
	
	void readData(std::string filenametoread);  //reads data...not available to client???
	void deleteVectors();
	
	
	
};

#endif /* SENSOR_DATAI_H_  */

