##Builds the ChangeLog files
import os, sys
import doxygen
from SCons.Util import WhereIs
pj = os.path.join

Import('ves_pkg')
env = ves_pkg.getEnv().Copy()

sys.stdout.write("Generating doxygen files....\n")
# Find doxygen
sys.stdout.write("searching for doxygen...\n")
doxygen_cmd = WhereIs('doxygen')

if None == doxygen_cmd:
    sys.stdout.write("Could not find doxygen. Please make sure doxygen is in your PATH.\n")
    sys.exit(0)

else:
    sys.stdout.write("Found doxygen\n")

os.system(doxygen_cmd)


sys.stdout.write("Done creating documentation\n")
