##Builds the ChangeLog files
import os, sys
from SCons.Util import WhereIs
pj = os.path.join

Import('ves_pkg')
env = ves_pkg.getEnv().Clone()

# Find doxygen
sys.stdout.write("searching for doxygen...\n")
doxygen_cmd = WhereIs('doxygen')

if None == doxygen_cmd:
    sys.stdout.write("Could not find doxygen. Please make sure doxygen is in your PATH.\n")
    sys.exit(0)
else:
    sys.stdout.write("Found doxygen\n")
    sys.stdout.write("Generating doxygen files....\n")

#os.popen(doxygen_cmd)

doxyAction = doxygen_cmd

doxyBuilder = Builder(action = doxyAction, single_source = True,
                            suffix = ".html")

env.Append(BUILDERS = {'doxyResolve': doxyBuilder})

#env.doxyResolve(target = pdfTargets, source = foedSrcs)

sys.stdout.write("Done generating documentation\n")
