##Builds VE_DataLib
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR vtk_options boost_options RootDir vpr_options')

srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'xplorer', 'data') )
sources = sca_util.getSourcesRecursive( srcDir )
headers = sca_util.getHeadersRecursive( srcDir )

lib_env = ves_pkg.getEnv().Clone()

lib_env.Append( LIBS = ['PocoSQLite'])

vtk_options.apply( lib_env )
boost_options.apply( lib_env )
# Hack to get boost_signals-mt added to link line without specifying it directly
vpr_options.apply( lib_env )

lib_env.Append( CPPDEFINES = ['VE_DATA_LIBRARY'] )

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_xplorer_data',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_xplorer_data', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves', 'xplorer', 'data'))
lib.build()
