##Builds Exe_server
import os, sys, string
pj = os.path.join

Import('ves_pkg LIBDIR PREFIX')

srcs = Split("""
   Exe_server.cpp 
   Executive_i.cpp 
   Execute_Thread.cpp
   QueryThread.cxx
""")

env = ves_pkg.getEnv().Copy()
env.Append(LIBS = ['VE_ConductorLib', 'VE_XMLLib', 'VE_ModelLib', 'VE_CADLib',
                   'VE_ShaderLib', 'VE_CE_UtilitiesLib', 'VE_OpenModuleLib'])
env.Append(LIBPATH = [pj( PREFIX, LIBDIR)])

env.ParseConfig('flagpoll TAO apr-1 apr-util-1 xerces TAO_IORInterceptor TAO_ObjRefTemplate TAO_Valuetype \
                              TAO_CosNaming TAO_Svc_Utils TAO_IORTable TAO_Messaging \
                              TAO_PortableServer TAO_BiDirGIOP TAO_AnyTypeCode --libs --cflags')

ce_prog = ves_pkg.createProgram('Exe_server', env, 'bin')
ce_prog.addSources( srcs )
ce_prog.build()
