##Builds CE Libraries
openSubdirs = Split("""
    cfdTranslatorToVTK
    DataLoader
""")

##Run SConscript files in all of those folders.
for d in openSubdirs:
   #print " dir ", d
   SConscript( dirs = d )
