##Builds VE_TextureBasedLib<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')
Import('execOsgPatTag')

srcs = Split("""
   cfd3DTextureCullCallback.cxx
   cfdAdvectionSubGraph.cxx
   cfdCopyTo3DTextureStage.cxx
   cfdOSGAdvectionShaderManager.cxx
   cfdOSGPingPongTexture3d.cxx
   cfdOSGShaderManager.cxx
   cfdOSGTransferShaderManager.cxx
   cfdPBufferManager.cxx
   cfdPBufferQuad.cxx
   cfdScalarShaderManager.cxx
   cfdScalarVolumeVisHandler.cxx
   cfdSimpleTextureCallback.cxx
   cfdTextureDataSet.cxx
   cfdTextureManager.cxx
   cfdTextureMatrixCallback.cxx
   cfdUpdateableOSGNoiseTexture3d.cxx
   cfdUpdateableOSGTexture1d.cxx
   cfdUpdateParameterCallback.cxx
   cfdUpdateTextureCallback.cxx
   cfdVectorVolumeVisHandler.cxx
   cfdVolumeBillboard.cxx
   cfdVolumeCenterCallback.cxx
   cfdVolumeVisNodeHandler.cxx
   cfdVolumeVisualization.cxx
""")

##srcs = map(lambda s: pj('#', 'VE_Xplorer', 'TextureBased', s), srcs)

env = baseEnv.Copy()
env.Append(LIBS = 'VE_UtilLib')
env.ParseConfig('flagpoll vtk osg vrjuggler Boost.Filesystem --libs --cflags')
##env.ParseConfig('wx-config --cxxflags --libs')
##For non-64-bit systems: (64-bits need 'lib64')
##env.Append(LIBPATH = [pj('usr', 'X11R6', 'lib')])
##env.Append(LIBS = ['X11', 'GL'])


targetLib = pj(libPath, 'VE_TextureBasedLib%s' %(execOsgPatTag))
env.SharedLibrary(target = targetLib, source = srcs)
