# $Id: Makefile 16737 2005-02-03 19:47:26Z patrickh $

default: all

XML_FILES=\
 vesuite.xml

XSLT_TOOL?=Saxon 
#XSLT_TOOL?=Xalan
#FO_VERSION=XEP

include $(VE_SUITE_HOME)/VE_Installer/mk/docbook.mk
