##sets up jconf files for stereo_desktop
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg')

veaBundle = ves_pkg.createFileBundle( pj('share','vesuite','shaders') )
veaFile = sca_util.getFilesRecursiveByExt( '.', ['.vea'] )
veaBundle.addFiles( veaFile )
