##Builds VE_UtilLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

srcs = Split("""
   cfdAccessoryFunctions.cxx
   cfdGrid2Surface.cxx
   cfdVTKFileHandler.cxx
   cleanVtk.cxx
   fileIO.cxx
   readWriteVtkThings.cxx
""")

srcs = map(lambda s: pj('#', 'VE_Xplorer', 'Utilities', s), srcs)

env = baseEnv.Copy()
env.ParseConfig('flagpoll vtk --cflags --libs')
env.ParseConfig('flagpoll boost --cflags --libs')
env.ParseConfig('wx-config --cxxflags --libs')
env.ParseConfig('vrjuggler-config --libs --extra-libs --includes')

targetLib = pj(libPath, 'VE_UtilLib')
env.SharedLibrary(target = targetLib, source = srcs)
