import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('Platform')
Import('boost')
Import('vtk')
Import('libPath')

srcs = Split("""
   cfdAccessoryFunctions.cxx
   cfdGrid2Surface.cxx
   cfdVTKFileHandler.cxx
   cleanVtk.cxx
   fileIO.cxx
   readWriteVtkThings.cxx
""")

srcs = map(lambda s: pj('#', 'VE_Xplorer', 'Utilities', s), srcs)

env = baseEnv.Copy()
env.Append(CPPPATH = ['#'])
env.Append(CPPPATH = pj( os.getenv('VTK_BASE_DIR',''), 'include', 'vtk') )
env.Append(CPPPATH = pj( os.getenv('VJ_DEPS_DIR',''), 'include') )
env.Append(LIBPATH = libPath)
for lib in boost:
    env.Append(LIBS = lib)
##for lib in vtk:
##    env.Append(LIBS = lib)
env.ParseConfig('flagpoll vtk --cflags --libs') ##FIX
##env.ParseConfig('flagpoll boost --cflags --libs') ##FIX
env.ParseConfig('wx-config --cxxflags --libs')
env.ParseConfig('vrjuggler-config --libs --extra-libs --includes')

targetLib = pj(libPath, 'VE_UtilLib')
env.SharedLibrary(target = targetLib, source = srcs)
