##Builds VE_UtilLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

util_srcs = Split("""
   cfdAccessoryFunctions.cxx
   cfdGrid2Surface.cxx
   cfdVTKFileHandler.cxx
   cleanVtk.cxx
   fileIO.cxx
   readWriteVtkThings.cxx
""")

srcs = map(lambda s: pj('#', 'VE_Xplorer', 'Utilities', s), util_srcs)

env = baseEnv.Copy()
env.ParseConfig('flagpoll Boost.Filesystem vtk --cflags --libs')

targetLib = pj(libPath, 'VE_UtilLib')
env.SharedLibrary(target = targetLib, source = srcs)
