##installs launcher python files into bin
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg', 'RootDir')
#env = ves_pkg.getEnv().Copy()

launcherBundle = ves_pkg.createFileBundle( 'bin' )
pyFile = sca_util.getFilesRecursiveByExt( '.', ['.py'] )

launcherBundle.addFiles( pyFile )

