#ifndef CFD_VE_ENUM_H
#define CFD_VE_ENUM_H

#include <string>

enum cfdIDEnum
{
   UPDATE_INTERACTIVE_DISPLAY,
   UPDATE_INTERACTIVE_DESIGN,
   UPDATE_INTERACTIVE_INITIAL_SEARCH,
   UPDATE_INTERACTIVE_GA,
   INTERACTIVE_DESIGN_SAVE,
   INTERACTIVE_DESIGN_DISPLAY,
   INTERACTIVE_GA_INFO_UPDATE,
   INTERACTIVE_GA_GENE_CHECK,
  
};

std::string IDEnumToString(int value);
#endif
