interface VjDesignObs
{
   typedef sequence <double> floatarray;
   typedef sequence <short> active_flag;
   typedef sequence <string>  name;

   void update();
   
   void setClientInfoFlag( in short value ); 
   short getClientInfoFlag();
     
   void setInteractiveState_UI( in short value );
   short getInteractiveState_cfd();

   void setInteractiveGA(in short value);
   short getInteractiveGA();

   void setDesignParams(in design_params o);
   design_params getDesignParams();

   void setNumDesignParams(in short value);

   void setStateBuffer(in active_flag o);
   active_flag getStateBuffer();

   void setNewVtkFileName(in filename value);
   filename getNewVtkFileName();
   
   
};

