##sets up jconf files for stereo_desktop
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg')

launcherBundle = ves_pkg.createFileBundle( pj('share','vesuite','examples','garage') )
iveFile = sca_util.getFilesRecursiveByExt( '.', ['.ive'] )
vesFile = sca_util.getFilesRecursiveByExt( '.', ['.ves'] )
launcherBundle.addFiles( iveFile )
launcherBundle.addFiles( vesFile )


