##Builds VE_CE_UtilitiesLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')


srcs = Split("""
   Connection.cxx
   Module.cxx
   node_base.cxx
   node_module.cxx
   Port.cxx
   IPort.cxx
   Network.cxx
   node_loop.cxx
   OPort.cxx
   Scheduler.cxx  
""")
srcs = map(lambda s: pj('#', 'VE_CE', 'Utilities', s), srcs)

env = baseEnv.Copy()
env.Append(LIBS = ['VE_ModelLib', 'VE_XMLLib', 'VE_OpenModuleLib'])
env.ParseConfig('flagpoll xerces --libs')
env.ParseConfig('flagpoll tao --libs --cflags')

targetLib = pj(libPath, 'VE_CE_UtilitiesLib')
env.SharedLibrary(target = targetLib, source = srcs)
