##Builds VE_ShaderLib
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR buildDir xerces_options')

sources = Split("""
   TextureImage.cxx
   Uniform.cxx
   Program.cxx
   Shader.cxx 
   ShaderCreator.cxx 
""")

headers = Split("""
   TextureImage.h
   Uniform.h
   Program.h
   Shader.h 
   TextureImagePtr.h
   UniformPtr.h
   ProgramPtr.h
   ShaderPtr.h 
   ShaderCreator.h 
""")

##srcs = map(lambda s: pj('#', 'VE_Open', 'XML', 'Shader', s), shader_srcs)

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = 'VE_XMLLib')
lib_env.Append(LIBPATH = [  pj('#', buildDir, 'VE_Open','XML')])
##lib_env.ParseConfig('flagpoll xerces --libs --cflags')
xerces_options.apply( lib_env )

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('VE_ShaderLib',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('VE_ShaderLib', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Open', 'XML', 'Shader'))
lib.build()
