##Builds VE_CADLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

srcs = Split("""
   CADAssembly.cxx
   CADAttribute.cxx
   CADClone.cxx
   CADCreator.cxx
   CADMaterial.cxx
   CADNode.cxx
   CADNodeTraverser.cxx
   CADPart.cxx
   CADNodeAnimation.cxx
""")

srcs = map(lambda s: pj('#', 'VE_Open', 'XML', 'CAD', s), srcs)

env = baseEnv.Copy()
env.Append(LIBS = ['VE_XMLLib', 'VE_ShaderLib'])

targetLib = pj(libPath, 'VE_CADLib')
env.SharedLibrary(target = targetLib, source = srcs)
