##Builds idl skeleton files for veopen
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg', 'RootDir')
env = ves_pkg.getEnv().Copy()

launcherBundle = ves_pkg.createFileBundle( 'bin' )

vessetupScripts = [ 'ves.setup.csh',
                 'ves.setup.sh' ]

#vessetupScripts = map(lambda s: pj(RootDir,'VE_Installer', s), vessetupScripts)

launcherBundle.addFiles( vessetupScripts )
