
BuildRequires: aaa_base acl attr bash bison bzip2 coreutils cpio cpp devs diffutils e2fsprogs file filesystem findutils gawk glibc glibc-devel glibc-locale grep gzip info klogd libacl libattr libgcc libstdc++ m4 make man mktemp module-init-tools patch permissions popt procinfo procps psmisc pwdutils readline sed sysvinit tar timezone unzip util-linux zlib zlib-devel autoconf automake binutils doxygen gcc gettext graphviz libpng libtool rpm python python-devel wxGTK wxGTK-devel wxGTK-compat wxGTK-gl python-wxGTK

Name:         VE-Suite-Dependencies
License:      LGPL
Group:        System/Libraries
Autoreqprov:  on
Version:      1.0.2
Release:      1
Summary:      All third party packages necessary to build and run VE-Suite applications.
Source0:      VE-Suite-Dependencies-%{version}.tar.bz2
URL:          http://www.vesuite.org
Provides:     ve-suite-dependencies
BuildRoot:    %{_tmppath}/%{name}-%{version}-build

%description

This package contains all third party packages necessary to build and run 
VE-Suite applications bundled into one distribution.  This includes:
   * VR Juggler               http://www.vrjuggler.org
   * WxWidgets                http://www.wxwidgets.org
   * ACE+TAO                  http://www.dre.vanderbilt.edu
   * OpenSceneGraph           http://www.openscenegraph.org
   * VTK                      http://www.kitware.com/vtk/index.html
   * Xerces                   http://xerces.apache.org

Authors:
--------
   Kenneth Mark Bryden, Ph.D <kmbryden@iastate.edu>

#
## Define some generally useful macros
## Macros that begin with an underscore, '_', are defined by the system in the
## rpm macro files; these are usually located in /usr/lib/rpm.
#

# The root macro defines the root location of the ve-suite installation.
# Changing this will change where ALL files go.
%define root %{_prefix}/ve-suite-%{version}/dependencies

# This is a standard rpm macro that untars the source ball into the build 
# directory.
%prep

%setup -q -n VE-Suite-Dependencies-%{version}

%build

# Since this is a binary RPM, do nothing for the build.

%install

# Copy files around to their proper locations.

# Clean the directory structure out if it exists.
if [ -d $RPM_BUILD_ROOT ]
then
   rm -rf $RPM_BUILD_ROOT
fi

# Create the directory structure.
mkdir $RPM_BUILD_ROOT
mkdir $RPM_BUILD_ROOT%{_prefix}
mkdir $RPM_BUILD_ROOT%{_prefix}/ve-suite-%{version}

# Copy the binaries over 
cp -a $RPM_BUILD_DIR/* $RPM_BUILD_ROOT%{_prefix}/ve-suite-%{version}/dependencies


%files
# Use wildcards since the contents of the directory can change; it should be
# safe since the build root was deleted first, and the install root is a non
# standard directory that is created based on the version of the RPM.
%dir %{_prefix}/ve-suite-%{version}/dependencies/bin
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_HTBP.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_HTBP.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_HTBP.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_HTBP.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_RMCast.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_RMCast.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_RMCast.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_RMCast.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_SSL.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_SSL.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_SSL.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_SSL.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_TMCast.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_TMCast.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_TMCast.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACE_TMCast.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML_Parser.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML_Parser.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML_Parser.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML_Parser.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML_XML_Svc_Conf_Parser.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML_XML_Svc_Conf_Parser.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML_XML_Svc_Conf_Parser.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libACEXML_XML_Svc_Conf_Parser.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libKokyu.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libKokyu.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libKokyu.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libKokyu.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libnetsvcs.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libnetsvcs.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libnetsvcs.so.5
%{_prefix}/ve-suite-%{version}/dependencies/bin/libnetsvcs.so.5.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libOpenThreads.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosgDB.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosgFX.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosgGA.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosgParticle.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosgProducer.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosgSim.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosg.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosgText.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libosgUtil.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libProducer.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_AnyTypeCode.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_AnyTypeCode.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_AnyTypeCode.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_AnyTypeCode.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_AV.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_AV.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_AV.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_AV.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_BiDirGIOP.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_BiDirGIOP.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_BiDirGIOP.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_BiDirGIOP.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CodecFactory.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CodecFactory.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CodecFactory.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CodecFactory.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Codeset.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Codeset.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Codeset.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Codeset.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosConcurrency.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosEvent.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosLifeCycle.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosLifeCycle.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosLifeCycle.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosLifeCycle.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosLoadBalancing.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosLoadBalancing.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosLoadBalancing.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosLoadBalancing.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNaming.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Persist.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Persist.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Persist.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Persist.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosNotification.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosProperty.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTime.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTime.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTime.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTime.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CosTrading.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CSD_Framework.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CSD_Framework.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CSD_Framework.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CSD_Framework.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CSD_ThreadPool.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CSD_ThreadPool.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CSD_ThreadPool.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_CSD_ThreadPool.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Domain.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Domain.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Domain.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Domain.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DsLogAdmin.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DynamicAny.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DynamicAny.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DynamicAny.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DynamicAny.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DynamicInterface.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DynamicInterface.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DynamicInterface.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_DynamicInterface.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ETCL.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ETCL.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ETCL.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ETCL.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FaultTolerance.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FaultTolerance.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FaultTolerance.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FaultTolerance.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FT_ClientORB.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FT_ClientORB.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FT_ClientORB.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FT_ClientORB.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTORB_Utils.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTORB_Utils.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTORB_Utils.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTORB_Utils.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTRT_ClientORB.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTRT_ClientORB.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTRT_ClientORB.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTRT_ClientORB.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTRT_EventChannel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTRT_EventChannel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTRT_EventChannel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FTRT_EventChannel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FtRtEvent.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FtRtEvent.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FtRtEvent.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FtRtEvent.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FT_ServerORB.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FT_ServerORB.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FT_ServerORB.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_FT_ServerORB.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_HTIOP.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_HTIOP.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_HTIOP.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_HTIOP.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IFR_Client.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IFR_Client.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IFR_Client.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IFR_Client.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IFRService.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IFRService.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IFRService.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IFRService.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ImR_Client.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ImR_Client.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ImR_Client.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ImR_Client.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORInterceptor.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORInterceptor.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORInterceptor.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORInterceptor.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORManip.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORManip.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORManip.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORManip.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORTable.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORTable.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORTable.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_IORTable.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Messaging.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Messaging.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Messaging.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Messaging.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ObjRefTemplate.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ObjRefTemplate.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ObjRefTemplate.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_ObjRefTemplate.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PI.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PI_Server.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PI_Server.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PI_Server.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PI_Server.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PI.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PI.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PI.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PortableGroup.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PortableGroup.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PortableGroup.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PortableGroup.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PortableServer.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PortableServer.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PortableServer.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_PortableServer.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTCORBAEvent.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTCORBAEvent.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTCORBAEvent.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTCORBAEvent.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTCORBA.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTCORBA.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTCORBA.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTCORBA.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEventLogAdmin.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent_Serv.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent_Serv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent_Serv.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent_Serv.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent_Skel.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent_Skel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent_Skel.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent_Skel.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTEvent.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTKokyuEvent.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTKokyuEvent.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTKokyuEvent.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTKokyuEvent.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RT_Notification.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RT_Notification.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RT_Notification.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RT_Notification.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTPortableServer.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTPortableServer.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTPortableServer.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTPortableServer.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTSchedEvent.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTSchedEvent.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTSchedEvent.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTSchedEvent.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTSched.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTSched.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTSched.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTSched.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTScheduler.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTScheduler.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTScheduler.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_RTScheduler.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Security.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Security.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Security.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Security.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_SmartProxies.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_SmartProxies.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_SmartProxies.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_SmartProxies.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_SSLIOP.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_SSLIOP.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_SSLIOP.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_SSLIOP.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Strategies.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Strategies.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Strategies.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Strategies.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Svc_Utils.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Svc_Utils.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Svc_Utils.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Svc_Utils.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_TypeCodeFactory.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_TypeCodeFactory.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_TypeCodeFactory.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_TypeCodeFactory.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Utils.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Utils.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Utils.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Utils.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Valuetype.la
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Valuetype.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Valuetype.so.1
%{_prefix}/ve-suite-%{version}/dependencies/bin/libTAO_Valuetype.so.1.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkCommon.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkCommon.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkCommon.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkDICOMParser.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkDICOMParser.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkDICOMParser.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkexoIIc.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkexoIIc.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkexoIIc.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkexpat.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkexpat.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkexpat.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkFiltering.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkFiltering.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkFiltering.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkfreetype.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkfreetype.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkfreetype.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkftgl.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkftgl.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkftgl.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkGenericFiltering.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkGenericFiltering.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkGenericFiltering.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkGraphics.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkGraphics.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkGraphics.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkHybrid.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkHybrid.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkHybrid.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkImaging.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkImaging.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkImaging.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkIO.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkIO.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkIO.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkjpeg.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkjpeg.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkjpeg.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkMPEG2Encode.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkMPEG2Encode.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkMPEG2Encode.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkNetCDF.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkNetCDF.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkNetCDF.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkParallel.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkParallel.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkParallel.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkpng.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkpng.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkpng.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkRendering.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkRendering.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkRendering.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtksys.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtksys.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtksys.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtktiff.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtktiff.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtktiff.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkVolumeRendering.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkVolumeRendering.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkVolumeRendering.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkWidgets.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkWidgets.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkWidgets.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkzlib.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkzlib.so.5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libvtkzlib.so.5.0.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base_net-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base_net-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base_net-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base_xml-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base_xml-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_base_xml-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_adv-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_adv-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_adv-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_core-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_core-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_core-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_gl-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_gl-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_gl-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_html-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_html-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_html-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_media-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_media-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_media-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_qa-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_qa-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_qa-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_xrc-2.6.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_xrc-2.6.so.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libwx_gtk2_xrc-2.6.so.0.2.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libxerces-c.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libxerces-c.so.27
%{_prefix}/ve-suite-%{version}/dependencies/bin/libxerces-c.so.27.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/libxerces-depdom.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/libxerces-depdom.so.27
%{_prefix}/ve-suite-%{version}/dependencies/bin/libxerces-depdom.so.27.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/Naming_Service
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_3dc.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_3ds.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_ac.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_bmp.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_bsp.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_dds.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_dw.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_dxf.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_flt.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_freetype.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_geo.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_gif.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_hdr.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_ive.so
#%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_iv.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_jpeg.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_logo.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_lwo.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_lws.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_md2.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_net.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_normals.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_obj.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_OpenFlight.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_osga.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_osgFX.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_osgParticle.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_osgSim.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_osg.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_osgText.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_osgtgz.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_pfb.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_pic.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_png.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_pnm.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_rgb.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_rot.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_scale.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_shp.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_stl.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_tga.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_tgz.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_tiff.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_trans.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_txp.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_x.so
%{_prefix}/ve-suite-%{version}/dependencies/bin/osgdb_zip.so
%dir %{_prefix}/ve-suite-%{version}/dependencies/bin/wx
%dir %{_prefix}/ve-suite-%{version}/dependencies/bin/wx/config
%{_prefix}/ve-suite-%{version}/dependencies/bin/wx/config/gtk2-ansi-release-2.6
%dir %{_prefix}/ve-suite-%{version}/dependencies/bin/wx/include
%dir %{_prefix}/ve-suite-%{version}/dependencies/bin/wx/include/gtk2-ansi-release-2.6
%dir %{_prefix}/ve-suite-%{version}/dependencies/bin/wx/include/gtk2-ansi-release-2.6/wx
%{_prefix}/ve-suite-%{version}/dependencies/bin/wx/include/gtk2-ansi-release-2.6/wx/setup.h
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/UseVTK.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/VTKBuildSettings.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkCommonKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/VTKConfig.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkFilteringKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkGenericFilteringKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkGraphicsKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkHybridKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkImagingKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkIOKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/VTKLibraryDepends.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkParallelKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkRenderingKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkVolumeRenderingKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/vtkWidgetsKit.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/CMake/vtkLoadCMakeExtensions.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/CMake/vtkMakeInstantiator.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/CMake/vtkMakeInstantiator.cxx.in
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/CMake/vtkMakeInstantiator.h.in
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/CMake/vtkTclTkMacros.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/CMake/vtkWrapJava.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/CMake/vtkWrapPython.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/CMake/vtkWrapTcl.cmake
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/authors.txt
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_class2example.pl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_cleanhtml.pl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_codematch.pl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_contributors.pl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_header2doxygen.pl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_index.pl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_index.stop
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_readme.txt
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_rmpath.pl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/doc_version.pl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/paper-clip.gif
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/pic.gif
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/doxygen/vtk-logo.gif
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/testing/FindString.tcl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/testing/HeaderTesting.py
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/testing/PrintSelfCheck.tcl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/testing/prtImageTest.tcl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/testing/rtImageTest.tcl
%{_prefix}/ve-suite-%{version}/dependencies/bin/vtk-5.0/testing/TestSetGet.tcl
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/ACE_HTBP.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/ACE.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/ACE_RMCast.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/ACE_SSL.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/ACE_TMCast.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/ACEXML_Parser.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/ACEXML.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/ACEXML_XML_Svc_Conf_Parser.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/Kokyu.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_AnyTypeCode.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_BiDirGIOP.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CodecFactory.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosConcurrency.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosConcurrency_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosConcurrency_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosEvent.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosEvent_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosEvent_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosLifeCycle.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosLoadBalancing.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosNaming.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosNaming_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosNaming_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosNotification.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosNotification_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosNotification_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosProperty.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosProperty_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosProperty_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosTime.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosTrading.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosTrading_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CosTrading_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CSD_Framework.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_CSD_ThreadPool.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_Domain.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsEventLogAdmin.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsEventLogAdmin_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsEventLogAdmin_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsLogAdmin.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsLogAdmin_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsLogAdmin_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsNotifyLogAdmin.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsNotifyLogAdmin_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DsNotifyLogAdmin_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DynamicAny.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_DynamicInterface.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_ETCL.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_FaultTolerance.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_FT_ClientORB.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_FTORB_Utils.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_FT_ServerORB.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_IFR_Client.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_ImR_Client.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_IORInterceptor.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_IORManip.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_IORTable.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_Messaging.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_ObjRefTemplate.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_PI.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_PI_Server.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_PortableGroup.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_PortableServer.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTCORBA.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTEventLogAdmin.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTEventLogAdmin_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTEventLogAdmin_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTEvent.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTEvent_Serv.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTEvent_Skel.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTPortableServer.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_RTScheduler.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_SmartProxies.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_Strategies.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_Svc_Utils.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_TypeCodeFactory.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_Utils.pc
%{_prefix}/ve-suite-%{version}/dependencies/bin/pkgconfig/TAO_Valuetype.pc
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/bin
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/bin/cppdom-config
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/bin/gmtl-config
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/C4.base.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/C4.closed.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/C4.closed.mono.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/C4.displays.closed.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/C4.displays.closed.mono.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/C4.mstar.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/C4.rfwand.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.directx_joystick.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.flock.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.intersense_api.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.intersense.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.linux_joydev.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.mstar.1pack.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.mstar.2pack.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.multiview.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/example.vrpn.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/hmd.displays.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/pinch.mixin.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/powerwall_18x8.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/ptah.cluster.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.analog.mixin.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.analog.wandmixin.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.base.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.c6displays.mixin.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.c6viewports.mixin.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.digital.glove.mixin.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.glove.mixin.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/simstandalone.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.trackd.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sim.wand.mixin.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/sonixOpenAL.jconf
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/configFiles/standalone.jconf
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/alias.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/analog_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/analog_proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/application_data.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/cluster_manager.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/cluster_node.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/command_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/command_proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/corba_performance_monitor.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/corba_remote_reconfig.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/cyber_glove.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/data_glove.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/default_simulator.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/digital_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/digital_proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/directx_joystick.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/display_system.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/display_window.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/dtk.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/dtk_segment.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/fastrak.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/flock.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/gadget_logger.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/gesture_proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/glove_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/glove_proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/ibox.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/input_area.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/input_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/input_manager.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/input_window.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/intersense_api.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/intersense.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/intersense_station.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/keyboard_mouse_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/keyboard_mouse_proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/key_modifier_pair.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/linux_joydev.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/motion_star.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/msft_speech_recog_digital.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/msft_speech_recog_string.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/opengl_frame_buffer_config.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/pinch_glove.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/positional_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/position_calibration_filter.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/position_proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/position_transform_filter.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/puck_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/serial_encoder.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulated_analog_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulated_digital_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulated_digital_glove.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulated_glove_gesture.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulated_positional_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulated_relative_position.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulated_setable_position.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulator_plugin.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/simulator_viewport.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/sound.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/sound_manager_sonix.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/start_barrier_plugin.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/string_device.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/string_proxy.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/surface_viewport.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/swap_lock_tcp_plugin.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/swap_lock_wired_plugin.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/three_d_mouse.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/trackd_api_controller.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/trackd_api_sensor.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/trackd_controller.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/trackd_sensor.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/user.jdef
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/definitions/vrpn.jdef
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libaudiere-1.9.3.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libaudiere.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libaudiere.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-1_33.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-1_33.so.1.33.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-d-1_33.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-d-1_33.so.1.33.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-mt-1_33.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-mt-1_33.so.1.33.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-mt-d-1_33.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-mt-d-1_33.so.1.33.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-mt-d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc-mt.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libboost_filesystem-gcc.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libcppdom.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libcppdom.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libgadget.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libgadget.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libgadget.so.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libgadget.so.1.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libgadget.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libjccl.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libjccl.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libjccl.so.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libjccl.so.1.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libjccl.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libnspr4.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libopenal.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libopenal.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libopenal.so.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libopenal.so.0.0.8
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libplc4.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libplds4.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libsonix.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libsonix.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libsonix.so.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libsonix.so.1.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libsonix.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvpr.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvpr.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvpr.so.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvpr.so.1.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvpr.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_ogl.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_ogl.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_ogl.so.2
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_ogl.so.2.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_ogl.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_pf.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_pf.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_pf.so.2
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_pf.so.2.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj_pf.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj.so.2
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj.so.2.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/libvrj.so.2.0.1
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/DataGlove_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/DataGlove_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/Fastrak_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/Fastrak_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/Flock_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/Flock_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/IBox_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/IBox_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/IntersenseAPI_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/IntersenseAPI_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/IS900_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/IS900_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/LinuxJoydev_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/LinuxJoydev_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/MotionStar_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/MotionStar_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/PinchGlove_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/PinchGlove_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/SerialEncoder_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/SerialEncoder_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/SpaceBall_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/SpaceBall_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/ThreeDMouse_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/ThreeDMouse_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/Trackd_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/Trackd_drv.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/VRPN_drv_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/drivers/VRPN_drv.so
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/ApplicationDataManager_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/ApplicationDataManager.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/RIMPlugin_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/RIMPlugin.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/StartBarrierPlugin_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/StartBarrierPlugin.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/SwapLockTCPPlugin_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/SwapLockTCPPlugin.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/SwapLockWiredPlugin_d.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/gadgeteer/plugins/SwapLockWiredPlugin.so
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libgadget.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libgadget.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libgadget.so.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libgadget.so.1.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libgadget.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libjccl.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libjccl.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libjccl.so.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libjccl.so.1.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libjccl.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libsonix.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libsonix.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libsonix.so.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libsonix.so.1.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libsonix.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvpr.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvpr.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvpr.so.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvpr.so.1.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvpr.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_ogl.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_ogl.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_ogl.so.2
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_ogl.so.2.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_ogl.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_pf.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_pf.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_pf.so.2
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_pf.so.2.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj_pf.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj.so.2
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj.so.2.0
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/libvrj.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libgadget.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libgadget.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libgadget.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libjccl.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libjccl.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libjccl.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libsonix.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libsonix.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libsonix.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvpr.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvpr.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvpr.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj_ogl.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj_ogl.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj_ogl.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj_pf.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj_pf.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj_pf.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/debug/libvrj.so.2.0.1
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libgadget.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libgadget.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libgadget.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libjccl.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libjccl.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libjccl.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libsonix.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libsonix.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libsonix.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvpr.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvpr.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvpr.so.1.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj_ogl.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj_ogl.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj_ogl.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj_pf.a
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj_pf.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj_pf.so.2.0.1
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/opt/libvrj.so.2.0.1
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/i686/profiled
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/jccl
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/jccl/plugins
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/snx
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/snx/plugins
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/snx/plugins/dbg
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/snx/plugins/dbg/Audiere_snd.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/snx/plugins/dbg/OpenAL_snd.so
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/snx/plugins/opt
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/snx/plugins/opt/Audiere_snd.so
%{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/snx/plugins/opt/OpenAL_snd.so
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/vrjuggler
%dir %{_prefix}/ve-suite-%{version}/dependencies/vrJuggler2.0.1/lib/vrjuggler/plugins
