##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'Fermentor' ) )
fermentorDemoDir = pj( RootDir, 'share', 'examples', 'Fermentor' )
iveFile = sca_util.getFilesRecursiveByExt( fermentorDemoDir, [ '.ive' ] )

fileBundle.addFiles( iveFile )
fileBundle.addFiles( [ 'Icons/fermentor.jpg' ] )
fileBundle.addFiles( [ 'fermentor.ves' ] )
fermentorSubdirs = Split("""
    FermentorGP
    FermentorUI
""")

##Run SConscript files in all of these folders.
for d in fermentorSubdirs:
   SConscript( dirs = d )
