##Builds QtUILib
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('poco_options baseEnv ves_pkg LIBDIR buildDir RootDir osg_options vpr_options vrjuggler_options GetPlatform xerces_options tao_options')
Import('minerva_options')
Import('tao_options')

srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'conductor', 'qt') )
buildSrcDir = pj('#',buildDir,'src','ves','conductor','qt')

lib_env = ves_pkg.getEnv().Clone()

##### Moc section must come before uic section to prevent issues with undefined
##### symbols and vtables
### moc files

source = [pj(buildSrcDir,'MoveFrame.h')]
cppSources = lib_env.qt_moc(source)

source = [pj(buildSrcDir,'IconStack.h')]
cppSources += lib_env.qt_moc(source)

source = [pj(buildSrcDir,'TreeTab.h')]
cppSources += lib_env.qt_moc(source)

source = [pj(buildSrcDir,'MainWindow.h')]
cppSources += lib_env.qt_moc(source)

source = [pj(buildSrcDir,'UIElementQt.h')]
cppSources += lib_env.qt_moc(source)

source = [pj(buildSrcDir,'propertyBrowser','PropertyBrowser.h')]
cppSources += lib_env.qt_moc(source)

source = [pj(buildSrcDir,'propertyBrowser','Visualization.h')]
cppSources += lib_env.qt_moc(source)

source = [pj(buildSrcDir,'propertyBrowser','GenericPropertyBrowser.h')]
cppSources += lib_env.qt_moc(source)
###

### rcc files
source = [pj(buildSrcDir,'propertyBrowser','icons.qrc')]
cppSources += lib_env.qt_rcc(source)
###

### uic files
source = [pj(buildSrcDir,'titlebar.ui')]
cppHeaders = lib_env.qt_uic(source)

source = [pj(buildSrcDir,'TreeTab.ui')]
cppHeaders += lib_env.qt_uic(source)

source = [pj(buildSrcDir,'MainWindow.ui')]
cppHeaders += lib_env.qt_uic(source)

source = [pj(buildSrcDir,'propertyBrowser','Visualization.ui')]
cppHeaders += lib_env.qt_uic(source)
####

lib_env.Depends( cppSources, cppHeaders)

openDir = os.path.abspath( pj(RootDir,buildDir,'src','ves','conductor','qt') )
cppSources1 = map(lambda s: pj(openDir, '%s' ) %(s), cppSources)
cppHeaders1 = map(lambda s: pj(openDir, '%s' ) %(s), cppHeaders)
    
headers = cppHeaders1
headers += sca_util.getHeadersRecursive( srcDir )
sources = cppSources1
sources += sca_util.getSourcesRecursive( srcDir )

lib_env.Append(LIBS = ['ves_open_xml',
                       'ves_xplorer',
                       'ves_xplorer_data',
                       'ves_xplorer_command',
                       'ves_xplorer_eventmanager',
					   'ves_xplorer_scenegraph',
                       'QtSolutions_PropertyBrowser-2.5',
                       'osgQtTree'
                      ])
lib_env.Append(LIBPATH = [
                           pj('#', buildDir, 'src', 'ves', 'open', 'xml'),
                           pj('#', buildDir, 'src', 'ves', 'xplorer'),
                           pj('#', buildDir, 'src', 'ves', 'xplorer', 'data'),
                           pj('#', buildDir, 'src', 'ves', 'xplorer', 'command'),
                           pj('#', buildDir, 'src', 'ves', 'xplorer', 'eventmanager'),
						   pj('#', buildDir, 'src', 'ves', 'xplorer', 'scenegraph'),
                           pj('#', buildDir, 'external', 'qtpropertybrowser-2.5_1-opensource', 'src'),
                           pj('#', buildDir, 'external', 'osgQtTree' )
                         ])

if GetPlatform() != 'darwin':
    Import('qt_options')
    qt_options.apply(lib_env)
    lib_env.AppendUnique( CPPDEFINES = ['QT_ON','QT_QTPROPERTYBROWSER_IMPORT'] )
else:
    import qt46
    qt46.applyQtBuildFlags(lib_env)

#lib_env.AppendUnique( CPPDEFINES = ['QT_RENDER_DEBUG'])

if GetPlatform() == 'win32':
    lib_env.AppendUnique(CXXFLAGS = ['/Zc:wchar_t-'])

osg_options.apply( lib_env )
vpr_options.apply( lib_env )
vrjuggler_options.apply( lib_env )
poco_options.apply( lib_env )
xerces_options.apply(lib_env)
tao_options.apply(lib_env)

if minerva_options.isAvailable():
	lib_env.AppendUnique( CPPDEFINES = ['MINERVA_GIS_SUPPORT'] )
	lib_env.AppendUnique( CPPDEFINES = ['NOMINMAX'] )
	srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'conductor', 'qt' ,'minerva') )
	base_plugin_srcs = sca_util.getSourcesRecursive( srcDir )
	base_header_srcs = sca_util.getHeadersRecursive( srcDir )
	sources += map(lambda s: pj('minerva', s), base_plugin_srcs)
	headers += map(lambda s: pj('minerva', s), base_header_srcs)
	minerva_options.apply( lib_env )
	
lib_env.Append( CPPDEFINES = ['VE_CONDUCTOR_QTUI_LIBRARY'])
lib_env.AppendUnique( CPPPATH = [ pj(RootDir,'external','qtpropertybrowser-2.5_1-opensource','src') ] )
lib_env.AppendUnique( CPPPATH = [ pj(RootDir,'external') ] )

if lib_env['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_conductor_qtui',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_conductor_qtui', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves', 'conductor','qt'))
lib.build()
