//#include "Observer.idl"

interface VjObs
{
   typedef sequence< string > scalar_p;
   typedef sequence< short > obj_p;
   typedef sequence< double > obj_pd;

   struct Scalar
   {
      string scalarnames;
      obj_pd scalarrange;
   };

   typedef sequence< Scalar > Scalars;

   struct Dataset
   {
      string datasetname;
      scalar_p vectornames;
      Scalars scalarVector;
   };

   typedef sequence< Dataset > Datasets;

   struct Model
   {
      scalar_p geometrynames;
      Datasets dataVector;

      obj_p datasettypes;
      obj_p num_scalars_per_dataset;
      obj_p num_vectors_per_dataset;
   };

   typedef sequence< Model > Models;
   Models GetModels();

   //void attach(in Observer o);
   //void detach(in Observer o);
   //void update();
   //scalar_p update_scalar();
   //scalar_p update_vector();
   //scalar_p get_geo_name();
   scalar_p get_teacher_name();
   //short get_sc_num();
   //short get_geo_num();
   short get_teacher_num();
   //short get_postdata();
   string get_perf();
   //short get_timesteps();
   
   void SetClientInfoFlag( in short value );   
   void SetClientInfoData( in obj_pd o);   
   obj_pd GetClientInfoData();   

   // Used For Sound Files
   short GetNumberOfSounds();
   scalar_p GetSoundNameArray();

   // New Stuff
   // used as a generic way to pull data across
   obj_pd getDouble1D( in string input );
   //void setNumGeoArrays(in short value);
   //short getNumGeoArrays();

   void setIsoValue(in long value);
   long getIsoValue();

   void setSc(in long value);
   long getSc();

   void setMin(in long value);
   long getMin();

   void setMax(in long value);
   long getMax();

   void setId(in long value);
   long getId();

   void setGeoState(in long value);
   long getGeoState();

   void setPostdataState(in short value);
   short getPostdataState();

   void setPreState(in short value);
   short getPreState();

   void setTimesteps(in short value);
   short getTimesteps();

   void setNumTeacherArrays(in short value);
   short getNumTeacherArrays();

   void setTeacherState(in short value);
   short getTeacherState();
   
};
