#!python
import os, sys, string
pj = os.path.join
Import('baseEnv buildDir')

xplorerSubdirs = Split("""
    Utilities  
    SceneGraph
    TextureBased
    XplorerHandlers
    GraphicalPlugin
    XplorerNetwork
    GE
""")
##    DefaultGraphicalPlugin
##    SceneGraph/NURBS
##    SceneGraph/NURBS/Utilities
##    SceneGraph/Utilities

##Run SConscript files in all of those folders.
#for d in xplorerSubdirs:
#   #print " dir ", d
#   SConscript( dirs = d )

#baseEnv[ 'cluster' ] = 'yes'
#SConscript( dirs = "GE", build_dir=pj(buildDir,'VE_Xplorer','GE','cluster'))