#!python
import os, sys, string
pj = os.path.join
Import('baseEnv buildDir')

xplorerSubdirs = Split("""
    scenegraph
""")


##Run SConscript files in all of those folders.
for d in xplorerSubdirs:
   #print " dir ", d
   SConscript( dirs = d )
