##Builds VE_Xplorer<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv libPath ves_pkg LIBDIR GetPlatform execOsgPatTag')

srcs = Split("""
   cfdApp.cxx
   cfdAppWrapper.cxx
   cfdVEXplorer.cxx
   cfdVjObsWrapper.cxx
   VjObs_i.cxx 
""")

env = ves_pkg.getEnv().Copy()
env.Append(LIBS = ['VE_XMLLib', 'VE_CADLib', 'VE_ModelLib', 'VE_ShaderLib',
                   'VE_SceneGraph_UtilitiesLib', 
                   'VE_SceneGraphLib%s' %(execOsgPatTag),
                   'VE_UtilLib',
                   'VE_TextureBasedLib%s' %(execOsgPatTag),
                   'VE_OpenModuleLib',
                   'VE_XplorerLib%s' %(execOsgPatTag),
                   'VE_XplorerNetworkLib%s' %(execOsgPatTag),
                   'GraphicalPlugin%s' %(execOsgPatTag)])

env.ParseConfig('flagpoll Boost.Filesystem --libs --cflags')
env.ParseConfig('flagpoll vtk xerces osg vrjuggler TAO \
                          ACE TAO_IORInterceptor TAO_ObjRefTemplate TAO_Valuetype \
                          TAO_CosNaming TAO_Svc_Utils TAO_IORTable TAO_Messaging \
                          TAO_PortableServer TAO_BiDirGIOP TAO_AnyTypeCode \
                          apr-1 apr-util-1 --libs --cflags')
env.ParseConfig('flagpoll vrjuggler --get-vrj-ogl-libs')

prog = ves_pkg.createProgram('project%s' %(execOsgPatTag), env, 'bin')
prog.addSources( srcs )
prog.build()

