##Builds tao skel files
import os, sys, string, glob
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR buildDir RootDir tao_options')

sources = Split("""
   moduleS.cpp
   moduleC.cpp
   VjObsC.cpp
   VjObsS.cpp
""")

sources.append( pj('idl','Body_AMI_UIHandler_i.cxx') )

headers  = glob.glob(pj(RootDir, buildDir, 'src','ves','open','*.cpp'))
headers += glob.glob(pj(RootDir, buildDir, 'src','ves','open','*.h'))
headers += glob.glob(pj(RootDir, buildDir, 'src','ves','open','*.inl'))
headers.append( pj( 'idl','Body_AMI_UIHandler_i.h') )

lib_env = ves_pkg.getEnv().Clone()

tao_options.apply( lib_env )

lib_env.Append( CPPDEFINES = ['VE_OPEN_MODULE_LIBRARY'])
   
if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_open_module',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_open_module', lib_env,
                                               installPrefix = LIBDIR)

lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves','open') )
lib.build()

openSubdirs = Split("""
    idl
    xml
""")

##Run SConscript files in all of those folders.
for d in openSubdirs:
   SConscript( dirs = d )
