##Builds tao skel files
import os, sys, string, glob
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR buildDir')

openSubdirs = Split("""
    idl
    xml
""")

##Run SConscript files in all of those folders.
for d in openSubdirs:
   #print " dir ", d
   SConscript( dirs = d )

sources = Split("""
   moduleS.cpp
   moduleC.cpp
   VjObsC.cpp
   VjObsS.cpp
""")
##srcs = map(lambda s: pj('#', 'VE_Open', 'skel', s), srcs)
headers  = glob.glob(pj('#', buildDir, 'src','ves','open','*.cpp'))
headers += glob.glob(pj('#', buildDir, 'src','ves','open','*.h'))
headers += glob.glob(pj('#', buildDir, 'src','ves','open','*.inl'))

lib_env = ves_pkg.getEnv().Copy()
lib_env.ParseConfig('flagpoll TAO ACE TAO_IORInterceptor TAO_ObjRefTemplate TAO_Valuetype \
                              TAO_CosNaming TAO_Svc_Utils TAO_IORTable TAO_Messaging \
                              TAO_PortableServer TAO_BiDirGIOP TAO_AnyTypeCode --cflags --libs')

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_open_module',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_open_module', lib_env,
                                               installPrefix = LIBDIR)

lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves','open') )
lib.build()
