##Builds tao skel files
openSubdirs = Split("""
    idl
    skel
    XML
""")
##    XML/Shader
##    XML/CAD
##    XML/Model

##Run SConscript files in all of those folders.
for d in openSubdirs:
   #print " dir ", d
   SConscript( dirs = d )
