##Builds ???
import os, sys, string
pj = os.path.join

Import('baseEnv')

env = baseEnv.Copy()
env.Append(CPPPATH = [os.getcwd()])

env.Append(CPPPATH = ['idl'])

target = ['module.h', 'VjObs.h']

idlCmd = 'tao_idl -o ./VE_Open/skel -GI -I./VE_Open/idl ./VE_Open/idl/'
srcs = ['module.idl', 'VjObs.idl']
idlFile = [idlCmd + srcs[0], idlCmd + srcs[1]]
for i in range(len(idlFile)):
    bld = Builder(action = idlFile[i])
    env.Append(BUILDERS = {'tao_idl': bld})
    env.tao_idl(target[i], list())
