##Builds Unit Wrapper for ce units
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('baseEnv ves_pkg LIBDIR buildDir xerces_options RootDir tao_options')

srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'ce', 'unitwrapper') )
sources = sca_util.getSourcesRecursive( srcDir )
headers = sca_util.getHeadersRecursive( srcDir )

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['ves_open_xml', 'ves_open_module'])
lib_env.Append(LIBPATH = [ pj('#', buildDir, 'src','ves','open'),
                        pj('#', buildDir, 'src','ves','open','xml')])

xerces_options.apply( lib_env )
tao_options.apply( lib_env )

if GetPlatform() == 'win32':
   lib_env.Append( CPPDEFINES = ['LOKI_DLL'])
   
lib_env.Append( CPPDEFINES = ['VE_CE_UNIT_WRAPPER_LIBRARY'])

if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('ves_ce_unitwrapper',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('ves_ce_unitwrapper', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'ves', 'ce', 'unitwrapper'))
lib.build()
