#ifndef __DataSetDataArrayChoiceDialog__
#define __DataSetDataArrayChoiceDialog__

/**
@file
Subclass of DataArrayChoiceDialog, which is generated by wxFormBuilder.
*/

#include <ves/conductor/util/DataArrayChoiceDialog.h>

#include <vector>
#include <string>

/** Implementing DataArrayChoiceDialog */
class DataSetDataArrayChoiceDialog : public DataArrayChoiceDialog
{
public:
	/** Constructor */
	DataSetDataArrayChoiceDialog( wxWindow* parent );
    
    ///
    void SetDataArrays( std::vector< std::string > activeArrays );
    ///
    std::vector< std::string > GetUserActiveArrays();
    
protected:
    std::vector< std::string > m_activeArrays;
    std::vector< std::string > m_usersDataArrays;
};

#endif // __DataSetDataArrayChoiceDialog__
