##Builds Exe_server
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg buildDir xerces_options boost_options')
Import('RootDir tao_options GetPlatform')

srcDir = os.path.abspath( pj(RootDir, 'src', 'apps', 'ce') )
srcs = sca_util.getSourcesRecursive( srcDir )
headers = sca_util.getHeadersRecursive( srcDir )

srcs.remove( "Executive_i.cxx" )
headers.remove( "Executive_i.h" )

env = ves_pkg.getEnv().Clone()
env.Append(LIBS = ['ves_open_xml', 'ves_ce_util', 'ves_open_module','ves_ce'])
env.Append(LIBPATH = [
                        pj('#', buildDir, 'src','ves','ce'),
                        pj('#', buildDir, 'src','ves','ce','util'),
                        pj('#', buildDir, 'src','ves','open'),
                        pj('#', buildDir, 'src','ves','open','xml')
                     ])
                     
xerces_options.apply( env )
boost_options.apply( env )
tao_options.apply( env )
   
ce_prog = ves_pkg.createProgram('ves_ce' + env["PROGSUFFIX"], env, 'bin')
ce_prog.addSources( srcs )
ce_prog.addHeaders( headers )
ce_prog.build()

