##Builds Exe_server
import os, sys, string
pj = os.path.join

Import('ves_pkg LIBDIR PREFIX buildDir xerces_options boost_options tao_options GetPlatform')

srcs = Split("""
   Exe_server.cxx 
   Executive_i.cxx 
   Execute_Thread.cxx
   QueryThread.cxx
""")

headers = Split("""
   Executive_i.h
   Execute_Thread.h
   QueryThread.h
""")

env = ves_pkg.getEnv().Copy()
env.Append(LIBS = ['ves_open_xml', 'ves_ce_util', 'ves_open_module'])
env.Append(LIBPATH = [
                        pj('#', buildDir, 'src','ves','ce','util'),
                        pj('#', buildDir, 'src','ves','open'),
                        pj('#', buildDir, 'src','ves','open','xml')
                     ])
                     
xerces_options.apply( env )
boost_options.apply( env )
tao_options.apply( env )
   
ce_prog = ves_pkg.createProgram('ves_ce' + env["PROGSUFFIX"], env, 'bin')
ce_prog.addSources( srcs )
ce_prog.addHeaders( headers )
ce_prog.build()

