##Builds Exe_server
import os, sys, string
pj = os.path.join

Import('ves_pkg LIBDIR PREFIX buildDir xerces_options')

srcs = Split("""
   Exe_server.cxx 
   Executive_i.cxx 
   Execute_Thread.cxx
   QueryThread.cxx
""")

env = ves_pkg.getEnv().Copy()
env.Append(LIBS = ['VE_ConductorLib', 'VE_XML', 'VE_CE_UtilitiesLib', 'VE_OpenModuleLib'])
env.Append(LIBPATH = [pj('#', buildDir, 'VE_Conductor','Network'),
                        pj('#', buildDir, 'VE_CE','Utilities'),
                        pj('#', buildDir, 'VE_Open','skel'),
                        pj('#', buildDir, 'VE_Open','XML')])

env.ParseConfig('flagpoll TAO TAO_IORInterceptor TAO_ObjRefTemplate TAO_Valuetype \
                              TAO_CosNaming TAO_Svc_Utils TAO_IORTable TAO_Messaging \
                              TAO_PortableServer TAO_BiDirGIOP TAO_AnyTypeCode --libs --cflags')

xerces_options.apply( env )
ce_prog = ves_pkg.createProgram('Exe_server', env, 'bin')
ce_prog.addSources( srcs )
ce_prog.build()

ceSubdirs = Split("""
   Utilities
   UnitWrapper
""")

##Run SConscript files in all of those folders.
for d in ceSubdirs:
   SConscript( dirs = d )
