/* asu_io.h -- index + size for asu variables used by the IECM interface */
/* Generated from 'd:\CMU\Models\DOE\c\veggy\interface\interface_igcc.cfg' on 12/09/03 13:02:01. */
/* Version IECM Interface 4.0.1 */

/* Output Variables */
#define ASU_SZ_OUT 120
#define ASU_IDX_OUT_MW 0
#define ASU_SZ_OUT_MW 1
#define ASU_IDX_OUT_PFC 1
#define ASU_SZ_OUT_PFC 1
#define ASU_IDX_OUT_GFC 2
#define ASU_SZ_OUT_GFC 1
#define ASU_IDX_OUT_EHO 3
#define ASU_SZ_OUT_EHO 1
#define ASU_IDX_OUT_PROJCONT 4
#define ASU_SZ_OUT_PROJCONT 1
#define ASU_IDX_OUT_PROCCONT 5
#define ASU_SZ_OUT_PROCCONT 1
#define ASU_IDX_OUT_INT 6
#define ASU_SZ_OUT_INT 1
#define ASU_IDX_OUT_ROYALTY 7
#define ASU_SZ_OUT_ROYALTY 1
#define ASU_IDX_OUT_PREPROD 8
#define ASU_SZ_OUT_PREPROD 1
#define ASU_IDX_OUT_INV 9
#define ASU_SZ_OUT_INV 1
#define ASU_IDX_OUT_TCR 10
#define ASU_SZ_OUT_TCR 1
#define ASU_IDX_OUT_TCR_EFF 11
#define ASU_SZ_OUT_TCR_EFF 1
#define ASU_IDX_OUT_OPLAB 12
#define ASU_SZ_OUT_OPLAB 1
#define ASU_IDX_OUT_MNTLAB 13
#define ASU_SZ_OUT_MNTLAB 1
#define ASU_IDX_OUT_MNTMATL 14
#define ASU_SZ_OUT_MNTMATL 1
#define ASU_IDX_OUT_ADMIN 15
#define ASU_SZ_OUT_ADMIN 1
#define ASU_IDX_OUT_OM_FIX 16
#define ASU_SZ_OUT_OM_FIX 1
#define ASU_IDX_OUT_UTIL 17
#define ASU_SZ_OUT_UTIL 1
#define ASU_IDX_OUT_MW_CST 18
#define ASU_SZ_OUT_MW_CST 1
#define ASU_IDX_OUT_OM_VAR 19
#define ASU_SZ_OUT_OM_VAR 1
#define ASU_IDX_OUT_OM 20
#define ASU_SZ_OUT_OM 1
#define ASU_IDX_OUT_1 21
#define ASU_SZ_OUT_1 1
#define ASU_IDX_OUT_2 22
#define ASU_SZ_OUT_2 1
#define ASU_IDX_OUT_3 23
#define ASU_SZ_OUT_3 1
#define ASU_IDX_OUT_4 24
#define ASU_SZ_OUT_4 1
#define ASU_IDX_OUT_5 25
#define ASU_SZ_OUT_5 1
#define ASU_IDX_OUT_SYNGAS_1 26
#define ASU_SZ_OUT_SYNGAS_1 13
#define ASU_IDX_OUT_SYNGAS_2 39
#define ASU_SZ_OUT_SYNGAS_2 13
#define ASU_IDX_OUT_SYNGAS_3 52
#define ASU_SZ_OUT_SYNGAS_3 13
#define ASU_IDX_OUT_SYNGAS_4 65
#define ASU_SZ_OUT_SYNGAS_4 13
#define ASU_IDX_OUT_SYNGAS_5 78
#define ASU_SZ_OUT_SYNGAS_5 13
#define ASU_IDX_OUT_SYNGAS_6 91
#define ASU_SZ_OUT_SYNGAS_6 13
#define ASU_IDX_OUT_C10 104
#define ASU_SZ_OUT_C10 1
#define ASU_IDX_OUT_CST_YR_TBL 105
#define ASU_SZ_OUT_CST_YR_TBL 5
#define ASU_IDX_OUT_CST_MWH_TBL 110
#define ASU_SZ_OUT_CST_MWH_TBL 5
#define ASU_IDX_OUT_CST_PCT_TBL 115
#define ASU_SZ_OUT_CST_PCT_TBL 5

/* Input Variables */
#define ASU_SZ_IN 35
#define ASU_IDX_IN_PENALTY 0
#define ASU_SZ_IN_PENALTY 3
#define ASU_IDX_IN_CST_YR 3
#define ASU_SZ_IN_CST_YR 1
#define ASU_IDX_IN_CONSTTIME 4
#define ASU_SZ_IN_CONSTTIME 1
#define ASU_IDX_IN_GFC 5
#define ASU_SZ_IN_GFC 1
#define ASU_IDX_IN_EHO 6
#define ASU_SZ_IN_EHO 1
#define ASU_IDX_IN_PROJCONT 7
#define ASU_SZ_IN_PROJCONT 1
#define ASU_IDX_IN_PROCCONT 8
#define ASU_SZ_IN_PROCCONT 1
#define ASU_IDX_IN_ROYALTY 9
#define ASU_SZ_IN_ROYALTY 1
#define ASU_IDX_IN_FIXTIME 10
#define ASU_SZ_IN_FIXTIME 1
#define ASU_IDX_IN_VARTIME 11
#define ASU_SZ_IN_VARTIME 1
#define ASU_IDX_IN_MISCCAP 12
#define ASU_SZ_IN_MISCCAP 1
#define ASU_IDX_IN_INV 13
#define ASU_SZ_IN_INV 1
#define ASU_IDX_IN_C10_FIT 14
#define ASU_SZ_IN_C10_FIT 1
#define ASU_IDX_IN_TCR_FACTOR 15
#define ASU_SZ_IN_TCR_FACTOR 1
#define ASU_IDX_IN_NJOBS 16
#define ASU_SZ_IN_NJOBS 1
#define ASU_IDX_IN_NSHIFTS 17
#define ASU_SZ_IN_NSHIFTS 1
#define ASU_IDX_IN_MNT 18
#define ASU_SZ_IN_MNT 1
#define ASU_IDX_IN_MNTLAB 19
#define ASU_SZ_IN_MNTLAB 1
#define ASU_IDX_IN_ADMIN 20
#define ASU_SZ_IN_ADMIN 1
#define ASU_IDX_IN_OXID_O2_PCT 21
#define ASU_SZ_IN_OXID_O2_PCT 1
#define ASU_IDX_IN_OXID_N2_PCT 22
#define ASU_SZ_IN_OXID_N2_PCT 3
#define ASU_IDX_IN_OXID_AR_PCT 25
#define ASU_SZ_IN_OXID_AR_PCT 3
#define ASU_IDX_IN_NTRAINS 28
#define ASU_SZ_IN_NTRAINS 3
#define ASU_IDX_IN_NSPARES 31
#define ASU_SZ_IN_NSPARES 1
#define ASU_IDX_IN_ELEC_CST 32
#define ASU_SZ_IN_ELEC_CST 3

/* Calculated Variables */
#define ASU_SZ_CALC 5
#define ASU_IDX_CALC_PENALTY 0
#define ASU_SZ_CALC_PENALTY 1
#define ASU_IDX_CALC_OXID_N2_PCT 1
#define ASU_SZ_CALC_OXID_N2_PCT 1
#define ASU_IDX_CALC_OXID_AR_PCT 2
#define ASU_SZ_CALC_OXID_AR_PCT 1
#define ASU_IDX_CALC_NTRAINS 3
#define ASU_SZ_CALC_NTRAINS 1
#define ASU_IDX_CALC_ELEC_CST 4
#define ASU_SZ_CALC_ELEC_CST 1
