/* stk_io.h -- index + size for stk variables used by the IECM interface */
/* Generated from 'd:\CMU\Models\DOE\c\veggy\interface\interface_igcc.cfg' on 12/09/03 13:02:01. */
/* Version IECM Interface 4.0.1 */

/* Output Variables */
#define STK_SZ_OUT 181
#define STK_IDX_OUT_OX_CST_TBL 0
#define STK_SZ_OUT_OX_CST_TBL 4
#define STK_IDX_OUT_N_CST_TBL 4
#define STK_SZ_OUT_N_CST_TBL 4
#define STK_IDX_OUT_BOIL_N_CST_TBL 8
#define STK_SZ_OUT_BOIL_N_CST_TBL 4
#define STK_IDX_OUT_TSP_CST_TBL 12
#define STK_SZ_OUT_TSP_CST_TBL 4
#define STK_IDX_OUT_S_CST_TBL 16
#define STK_SZ_OUT_S_CST_TBL 4
#define STK_IDX_OUT_S_N_CST_TBL 20
#define STK_SZ_OUT_S_N_CST_TBL 4
#define STK_IDX_OUT_CO2_CST_TBL 24
#define STK_SZ_OUT_CO2_CST_TBL 4
#define STK_IDX_OUT_SUB_CST_TBL 28
#define STK_SZ_OUT_SUB_CST_TBL 4
#define STK_IDX_OUT_PLT_CST_TBL 32
#define STK_SZ_OUT_PLT_CST_TBL 4
#define STK_IDX_OUT_POWER_CST_TBL 36
#define STK_SZ_OUT_POWER_CST_TBL 4
#define STK_IDX_OUT_TRC_CST_TBL 40
#define STK_SZ_OUT_TRC_CST_TBL 4
#define STK_IDX_OUT_TOT_CST_TBL 44
#define STK_SZ_OUT_TOT_CST_TBL 4
#define STK_IDX_OUT_STACK_1 48
#define STK_SZ_OUT_STACK_1 1
#define STK_IDX_OUT_STACK_2 49
#define STK_SZ_OUT_STACK_2 1
#define STK_IDX_OUT_STACK_3 50
#define STK_SZ_OUT_STACK_3 1
#define STK_IDX_OUT_STACK_4 51
#define STK_SZ_OUT_STACK_4 1
#define STK_IDX_OUT_STACK_5 52
#define STK_SZ_OUT_STACK_5 1
#define STK_IDX_OUT_STACK_6 53
#define STK_SZ_OUT_STACK_6 1
#define STK_IDX_OUT_STACK_7 54
#define STK_SZ_OUT_STACK_7 1
#define STK_IDX_OUT_STACK_8 55
#define STK_SZ_OUT_STACK_8 1
#define STK_IDX_OUT_STACK_9 56
#define STK_SZ_OUT_STACK_9 1
#define STK_IDX_OUT_STACK_10 57
#define STK_SZ_OUT_STACK_10 1
#define STK_IDX_OUT_STACK_11 58
#define STK_SZ_OUT_STACK_11 1
#define STK_IDX_OUT_STACK_12 59
#define STK_SZ_OUT_STACK_12 1
#define STK_IDX_OUT_STACK_13 60
#define STK_SZ_OUT_STACK_13 1
#define STK_IDX_OUT_STACK_14 61
#define STK_SZ_OUT_STACK_14 1
#define STK_IDX_OUT_STACK_15 62
#define STK_SZ_OUT_STACK_15 1
#define STK_IDX_OUT_STACK_N2 63
#define STK_SZ_OUT_STACK_N2 1
#define STK_IDX_OUT_STACK_O2 64
#define STK_SZ_OUT_STACK_O2 1
#define STK_IDX_OUT_STACK_H2O 65
#define STK_SZ_OUT_STACK_H2O 1
#define STK_IDX_OUT_STACK_CO2 66
#define STK_SZ_OUT_STACK_CO2 1
#define STK_IDX_OUT_STACK_CO 67
#define STK_SZ_OUT_STACK_CO 1
#define STK_IDX_OUT_STACK_HCL 68
#define STK_SZ_OUT_STACK_HCL 1
#define STK_IDX_OUT_STACK_SO2 69
#define STK_SZ_OUT_STACK_SO2 1
#define STK_IDX_OUT_STACK_SO3 70
#define STK_SZ_OUT_STACK_SO3 1
#define STK_IDX_OUT_STACK_NO 71
#define STK_SZ_OUT_STACK_NO 1
#define STK_IDX_OUT_STACK_NO2 72
#define STK_SZ_OUT_STACK_NO2 1
#define STK_IDX_OUT_STACK_ASH 73
#define STK_SZ_OUT_STACK_ASH 1
#define STK_IDX_OUT_STACK_TOTAL 74
#define STK_SZ_OUT_STACK_TOTAL 1
#define STK_IDX_OUT_STACK_SOX 75
#define STK_SZ_OUT_STACK_SOX 1
#define STK_IDX_OUT_STACK_NOX 76
#define STK_SZ_OUT_STACK_NOX 1
#define STK_IDX_OUT_STACK_NH3 77
#define STK_SZ_OUT_STACK_NH3 1
#define STK_IDX_OUT_FUEL 78
#define STK_SZ_OUT_FUEL 1
#define STK_IDX_OUT_COAL 79
#define STK_SZ_OUT_COAL 1
#define STK_IDX_OUT_OIL 80
#define STK_SZ_OUT_OIL 1
#define STK_IDX_OUT_NGAS 81
#define STK_SZ_OUT_NGAS 1
#define STK_IDX_OUT_PETCOKE 82
#define STK_SZ_OUT_PETCOKE 1
#define STK_IDX_OUT_FUEL_OTHER 83
#define STK_SZ_OUT_FUEL_OTHER 1
#define STK_IDX_OUT_WATER 84
#define STK_SZ_OUT_WATER 1
#define STK_IDX_OUT_REAG 85
#define STK_SZ_OUT_REAG 1
#define STK_IDX_OUT_SORB 86
#define STK_SZ_OUT_SORB 1
#define STK_IDX_OUT_NH3 87
#define STK_SZ_OUT_NH3 1
#define STK_IDX_OUT_CARBON 88
#define STK_SZ_OUT_CARBON 1
#define STK_IDX_OUT_CHEM 89
#define STK_SZ_OUT_CHEM 1
#define STK_IDX_OUT_H2O 90
#define STK_SZ_OUT_H2O 1
#define STK_IDX_OUT_BASH 91
#define STK_SZ_OUT_BASH 1
#define STK_IDX_OUT_FASH 92
#define STK_SZ_OUT_FASH 1
#define STK_IDX_OUT_FGT 93
#define STK_SZ_OUT_FGT 1
#define STK_IDX_OUT_TRC_WST_YR 94
#define STK_SZ_OUT_TRC_WST_YR 1
#define STK_IDX_OUT_ASH_BP 95
#define STK_SZ_OUT_ASH_BP 1
#define STK_IDX_OUT_GYP_BP 96
#define STK_SZ_OUT_GYP_BP 1
#define STK_IDX_OUT_S_BP 97
#define STK_SZ_OUT_S_BP 1
#define STK_IDX_OUT_ACID_BP 98
#define STK_SZ_OUT_ACID_BP 1
#define STK_IDX_OUT_CO2_SEQ 99
#define STK_SZ_OUT_CO2_SEQ 1
#define STK_IDX_OUT_SOL_IN 100
#define STK_SZ_OUT_SOL_IN 1
#define STK_IDX_OUT_SOL_OUT 101
#define STK_SZ_OUT_SOL_OUT 1
#define STK_IDX_OUT_GAS_1 102
#define STK_SZ_OUT_GAS_1 13
#define STK_IDX_OUT_GAS_2 115
#define STK_SZ_OUT_GAS_2 13
#define STK_IDX_OUT_GAS_3 128
#define STK_SZ_OUT_GAS_3 13
#define STK_IDX_OUT_GAS_4 141
#define STK_SZ_OUT_GAS_4 13
#define STK_IDX_OUT_GAS_5 154
#define STK_SZ_OUT_GAS_5 13
#define STK_IDX_OUT_GAS_6 167
#define STK_SZ_OUT_GAS_6 13
#define STK_IDX_OUT_STACK_AR 180
#define STK_SZ_OUT_STACK_AR 1

/* Input Variables */
#define STK_SZ_IN 0

/* Calculated Variables */
#define STK_SZ_CALC 0
