/////////////////////////////////////////////////////////////////////////////
// Name:        DataSetLoaderUI.h
// Purpose:     
// Author:      
// Modified by: 
// Created:     11/04/2006 20:56:53
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 11/04/2006 20:56:53

#ifndef _DATASETLOADERUI_H_
#define _DATASETLOADERUI_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "DataSetLoaderUI.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include <wx/string.h>
#include <wx/gdicmn.h>
#include <wx/dialog.h>
#include <wx/intl.h>

#include <set>
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxComboBox;
class wxTextCtrl;
class wxButton;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10000
#define SYMBOL_DATASETLOADERUI_STYLE wxDEFAULT_DIALOG_STYLE|wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxSTAY_ON_TOP|wxCLOSE_BOX|wxMAXIMIZE_BOX|wxMINIMIZE_BOX
#define SYMBOL_DATASETLOADERUI_TITLE _("DataSetLoader")
#define SYMBOL_DATASETLOADERUI_IDNAME ID_DIALOG
#define SYMBOL_DATASETLOADERUI_SIZE wxSize(-1, 500)
#define SYMBOL_DATASETLOADERUI_POSITION wxDefaultPosition
enum
{
   ID_SCROLLEDWINDOW=10001,
   ID_COMBOBOX,
   ID_TEXTCTRL,
   ID_BUTTON,
   ID_TEXTCTRL2,
   ID_BUTTON3,
   ID_TEXTCTRL3,
   ID_BUTTON4,
   ID_BUTTON6,
   ID_BUTTON5,
   ID_TEXTCTRL1,
   ID_BUTTON2,
   ID_SCROLLEDWINDOW1,
   ID_LISTBOX,
   ID_INFORMATION_PACKET_LIST,
   ID_INFORMATION_PACKET_CHANGE_NAME,
   ID_INFORMATION_PACKET_ADD_NAME
};

////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * DataSetLoaderUI class declaration
 */

class DataSetLoaderUI: public wxDialog
{    
    //DECLARE_DYNAMIC_CLASS( DataSetLoaderUI )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    DataSetLoaderUI( );
    DataSetLoaderUI( wxWindow* parent, wxWindowID id = SYMBOL_DATASETLOADERUI_IDNAME, const wxString& caption = SYMBOL_DATASETLOADERUI_TITLE, const wxPoint& pos = SYMBOL_DATASETLOADERUI_POSITION, const wxSize& size = SYMBOL_DATASETLOADERUI_SIZE, long style = SYMBOL_DATASETLOADERUI_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DATASETLOADERUI_IDNAME, const wxString& caption = SYMBOL_DATASETLOADERUI_TITLE, const wxPoint& pos = SYMBOL_DATASETLOADERUI_POSITION, const wxSize& size = SYMBOL_DATASETLOADERUI_SIZE, long style = SYMBOL_DATASETLOADERUI_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin DataSetLoaderUI event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
    void OnButtonClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON3
    void OnButton3Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON4
    void OnButton4Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON6
    void OnButton6Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON2
    void OnButton2Click( wxCommandEvent& event );

    /// wxEVT_COMMAND_LISTBOX_SELECTED event handler for ID_LISTBOX
    void OnListboxSelected( wxCommandEvent& event );

    /// wxEVT_COMMAND_COMBOBOX_SELECTED event handler for ID_INFORMATION_PACKET_LIST
    void OnInformationPacketChange( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_ENTER event handler for ID_INFORMATION_PACKET_CHANGE_NAME
    void OnInformationPacketAdd( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_INFORMATION_PACKET_ADD_NAME
    void OnInformationPacketChangeName( wxCommandEvent& event );

////@end DataSetLoaderUI event handler declarations

////@begin DataSetLoaderUI member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end DataSetLoaderUI member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin DataSetLoaderUI member variables
    wxComboBox* dataSetList;
    wxTextCtrl* dataSetTextEntry;
    wxButton* dataSetOpenButton;
    wxTextCtrl* preComputDirTextEntry;
    wxButton* preComputeOpenButton;
    wxTextCtrl* surfaceDataText;
    wxButton* surfaceDataOpenButton;
    wxButton* transformButton;
    wxButton* scalarButton;

   std::set< wxString > textureDirs;
////@end DataSetLoaderUI member variables
};

#endif
    // _DATASETLOADERUI_H_
