##Builds VE-Suite Libraries
#import os
#pj = os.path.join

tbetSubdirs = Split("""
    vti_texture_decompose
""")

##Run SConscript files in all of those folders.
for d in tbetSubdirs:
   SConscript( dirs = d )
