#!python
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('ves_pkg RootDir')

conductorSubdirs = Split("""
    Network
    GUIPlugin
    Utilities
    Framework
""")
##    DefaultPlugin

##Run SConscript files in all of those folders.
for d in conductorSubdirs:
   #print " dir ", d
   SConscript( dirs = d )

# install the xpms for conductor in the proper location
# sp that plugins and other apps can use them
xpmDir = os.path.abspath( pj(RootDir, 'VE_Conductor','xpm') )
xpmBundle = ves_pkg.createFileBundle( pj('include','VE_Conductor') )
xpms = sca_util.getFilesRecursiveByExt( xpmDir, ['.xpm'] )
xpms = map(lambda s: pj('xpm', s), xpms)
xpmBundle.addFiles( xpms )
