#!python
conductorSubdirs = Split("""
    Network
    GUIPlugin
    Utilities
    Framework
    DefaultPlugin
""")

##Run SConscript files in all of those folders.
for d in conductorSubdirs:
   #print " dir ", d
   SConscript( dirs = d )
