##sets up jconf files for stereo_desktop
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg buildDir RootDir GetPlatform')

shareBundle = ves_pkg.createFileBundle( pj('share','vesuite') )

fontFile = sca_util.getFilesRecursiveByExt( pj(RootDir, 'share'), ['.ttf'] )
shareBundle.addFiles( fontFile )

shareBundle.addFiles( ['ptconfigfile.txt'] )
shareBundle.addFiles( ['Draft2.png'] )
shareBundle.addFiles( ['Info_Panel.png'] )
shareBundle.addFiles( ['Info_Panel-No_Title.png'] )
shareBundle.addFiles( ['splotch.png'] )

wavFiles = sca_util.getFilesRecursiveByExt( pj(sca_util.getFullRootPath(), 'share','audio'), ['.wav'] )
wavFiles = map(lambda s: pj('audio', s), wavFiles)
shareBundle.addFiles(wavFiles,"",False)

shareSubdirs = Split("""
    glsl
    shaders
    vrj_configs
    examples
    tools
    scripts
    osg-textures
    osg-data
    logo
""")

if GetPlatform() != 'win32':
  shareSubdirs.append( pj('fpc') )

##Set the Sconscript files to build.
if 'docs' in COMMAND_LINE_TARGETS:
  ves_pkg.getEnv().Alias('docs', pj(RootDir, 'share', 'docs'))
  shareSubdirs.append(pj('docs'))
#elif 'changelog' in COMMAND_LINE_TARGETS:
#  ves_dirs = [ chlogSubdirs ]
#  baseEnv.Alias('changelog', chlogSubdirs)
#elif 'doxygen' in  COMMAND_LINE_TARGETS:
#  ves_dirs = [ doxySubdirs ]
#  baseEnv.Alias('doxygen', doxySubdirs)

##Run SConscript files in all of those folders.
for d in shareSubdirs:
   SConscript( dirs = d )
