##sets up jconf files for stereo_desktop
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg')

launcherBundle = ves_pkg.createFileBundle( 'share' )
jconfFile = sca_util.getFilesRecursiveByExt( '.', ['.jconf'] )
launcherBundle.addFiles( jconfFile )
   
#SConscript(dirs = "docs")
