##sets up jconf files for stereo_desktop
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg buildDir RootDir GetPlatform')

fontBundle = ves_pkg.createFileBundle( pj('share','vesuite') )
fontFile = sca_util.getFilesRecursiveByExt( pj(RootDir, 'share'), ['.ttf'] )
fontBundle.addFiles( fontFile )

ptConfigFile = ves_pkg.createFileBundle( pj('share','vesuite') )
ptConfigFile.addFiles( ['ptconfigfile.txt'] )

shareSubdirs = Split("""
    glsl
    shaders
    vrj_configs
    examples
    tools
    scripts
    osg-textures
    osg-data
""")

if GetPlatform() != 'win32':
  shareSubdirs.append( pj('fpc') )

##Set the Sconscript files to build.
if 'docs' in COMMAND_LINE_TARGETS:
  ves_pkg.getEnv().Alias('docs', pj(RootDir, 'share', 'docs'))
  shareSubdirs.append(pj('docs'))
#elif 'changelog' in COMMAND_LINE_TARGETS:
#  ves_dirs = [ chlogSubdirs ]
#  baseEnv.Alias('changelog', chlogSubdirs)
#elif 'doxygen' in  COMMAND_LINE_TARGETS:
#  ves_dirs = [ doxySubdirs ]
#  baseEnv.Alias('doxygen', doxySubdirs)

##Run SConscript files in all of those folders.
for d in shareSubdirs:
   SConscript( dirs = d )
