#Builds lemon converter
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import( 'baseEnv ves_pkg LIBDIR RootDir buildDir GetPlatform boost_options' )
Import( 'xerces_options lemon_options poco_options' )
openDir = os.path.abspath( pj( RootDir, 'share', 'tools', 'lemon', 'simple' ) )
sources = sca_util.getSourcesRecursive( openDir )
headers = sca_util.getHeadersRecursive( openDir )

env = ves_pkg.getEnv().Clone()

lemon_options.apply( env )

prog = ves_pkg.createProgram( 'ves_hello_lemon' + env[ "PROGSUFFIX" ], env, 'bin' )
prog.addSources( sources )
prog.addHeaders( headers )
prog.build()
