##Builds VE_NURBSLib<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR osg_options')

sources = Split("""
   ControlPoint.cxx
   KnotVector.cxx
   NCurve.cxx
   NSurface.cxx
   NURBSNode.cxx
   NURBSObject.cxx
""")

headers = Split("""
   ControlPoint.h
   KnotVector.h
   NCurve.h
   NSurface.h
   NURBSNode.h
   NURBSObject.h
""")

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['GLU','GL'])
#lib_env.ParseConfig('flagpoll vrjuggler --get-extra_libs')
lib_env.ParseConfig('flagpoll vrjuggler --require-Version=%s --get-extra_libs'%lib_env['VRJugglerVersion'])
osg_options.apply( lib_env )
if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('VE_NURBSLib%s' %(execOsgPatTag),
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('VE_NURBSLib%s' %(execOsgPatTag), lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Xplorer', 'SceneGraph', 'NURBS'))
lib.build()
