##Builds WinClient program
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('baseEnv ves_pkg RootDir buildDir wxwidgets_options osg_options xerces_options')
openDir = os.path.abspath( pj( RootDir, 'ConstructionBotsUI' ) )

sources = sca_util.getSourcesRecursive( openDir )
headers = sca_util.getHeadersRecursive( openDir )

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append( LIBS = [ 'loki.0.1.6' ])
lib_env.Append( LIBPATH = [ pj( os.getenv( 'VE_INSTALL_DIR' ), 'lib' ) ] )
lib_env.Append( CPPPATH = [ pj( os.getenv( 'VE_INSTALL_DIR' ), 'include' ), 
                            pj( os.getenv( 'VE_SUITE_HOME' ), 'src' ) ] )

lib_env.ParseConfig( 'flagpoll vrjuggler --libs --cflags' )
lib_env.ParseConfig( 'flagpoll Boost.Filesystem --libs --cflags' )

lib_env.ParseConfig( 'flagpoll TAO ACE TAO_IORInterceptor TAO_ObjRefTemplate TAO_Valuetype \
                         TAO_CosNaming TAO_Svc_Utils TAO_IORTable TAO_Messaging \
                         TAO_PortableServer TAO_BiDirGIOP TAO_AnyTypeCode \
                         --libs --cflags' )

osg_options.apply( lib_env )
xerces_options.apply( lib_env )
wxwidgets_options.apply( lib_env )

lib = ves_pkg.createStaticAndSharedLibrary( 'ConstructionBotsUI', lib_env, pj( RootDir, 'Plugins', 'UI', 'linux-i686' ) )   
lib.addSources( sources )
#lib.addHeaders( headers,  pj( 'Plugins', 'UI' ) )
lib.build()
