##Builds DefaultGraphicalPlugin<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR execOsgPatTag buildDir vtk_options osg_options xerces_options GetPlatform')

sources = Split("""
    DefaultGraphicalPlugin.cxx
""")

headers = Split("""
    DefaultGraphicalPlugin.h
""")

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['VE_SceneGraphLib%s' %(execOsgPatTag),
                   'VE_XplorerLib%s' %(execOsgPatTag),
                   'GraphicalPlugin%s' %(execOsgPatTag),
                   'VE_TextureBasedLib%s' %(execOsgPatTag),
                   'VE_UtilLib', 'VE_ModelLib', 'VE_XMLLib', 'VE_CADLib'])
lib_env.Append(LIBPATH = [pj('#', buildDir, 'VE_Xplorer','SceneGraph'),
                        pj('#', buildDir, 'VE_Xplorer','XplorerHandlers'),
                        pj('#', buildDir, 'VE_Xplorer','Utilities'),
                        pj('#', buildDir, 'VE_Xplorer','TextureBased'),
                        pj('#', buildDir, 'VE_Xplorer','GraphicalPlugin'),
                        pj('#', buildDir, 'VE_Open','XML'),
                        pj('#', buildDir, 'VE_Open','XML','Model'),
                        pj('#', buildDir, 'VE_Open','XML','CAD'),
                        pj('#', buildDir, 'VE_Open','XML','Shader')])
lib_env.ParseConfig('flagpoll vrjuggler --require-Version=%s --libs --cflags'%lib_env['VRJugglerVersion'])
lib_env.ParseConfig('flagpoll Boost.Filesystem --require-Version=%s --libs --cflags'%lib_env['BoostVersion'])
vtk_options.apply( lib_env )
osg_options.apply( lib_env )
xerces_options.apply( lib_env )

if GetPlatform() == 'darwin':
   lib_env['SHLINKFLAGS'] = '$LINKFLAGS -bundle -flat_namespace -undefined suppress'
   lib_env['SHLIBSUFFIX'] = '.dylib'

lib = ves_pkg.createSharedLibrary('DefaultGraphicalPlugin%s' %(execOsgPatTag),
                                                        lib_env,
                                                        installPrefix = pj('bin','Plugins','GE'))
##else:
##   lib = ves_pkg.createStaticLibrary('DefaultGraphicalPlugin%s' %(execOsgPatTag), lib_env,
##                                               installPrefix = pj('bin','Plugins','GE'))
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Xplorer', 'DefaultGraphicalPlugin'))
lib.build()
