##Build all the osg test apps
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg buildDir RootDir GetPlatform')

shareSubdirs = Split("""
   multi_viewport_lighting
   streamlines
   vectors
   rtt
   geometry_opt
   geometry_drawarray_conversion
   warp_surface
   vtk_osg_vectors
   vtk_osg_streamlines
   vtk_osg_warp_surface
""")

##Run SConscript files in all of those folders.
for d in shareSubdirs:
   SConscript( dirs = d )
