##sets up jconf files for stereo_desktop
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg buildDir RootDir GetPlatform')

shareSubdirs = Split("""
   multi_viewport_lighting
   streamlines
   vectors
""")

##Run SConscript files in all of those folders.
for d in shareSubdirs:
   SConscript( dirs = d )
