##install basic physics demo
import os, sys, string
pj = os.path.join
import SConsAddons.Util as sca_util

Import('ves_pkg')

launcherBundle = ves_pkg.createFileBundle( pj('share','vesuite','examples','simple_physics') )
osgFile = sca_util.getFilesRecursiveByExt( '.', ['.ive'] )
vesFile = sca_util.getFilesRecursiveByExt( '.', ['.ves'] )
launcherBundle.addFiles( osgFile )
launcherBundle.addFiles( vesFile )


