#
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'ves_pkg buildDir RootDir GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share','vesuite','osg-data' ) )
osgFile = sca_util.getFilesRecursiveByExt( pj( RootDir, 'share', 'osg-data' ), [ '.osg' ] )
iveFile = sca_util.getFilesRecursiveByExt( pj( RootDir, 'share', 'osg-data' ), [ '.ive' ] )
fileBundle.addFiles( osgFile )
fileBundle.addFiles( iveFile )

vesBundle = ves_pkg.createFileBundle( pj('share','vesuite') )
pngFile = sca_util.getFilesRecursiveByExt( pj( RootDir, 'share', 'osg-data' ), [ '.png' ] )
handFile = pj('hand-r-v3.osg')
vesBundle.addFiles( pngFile )
vesBundle.addFiles( handFile )
