#
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'ves_pkg buildDir RootDir GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share','vesuite','osg-data' ) )

osgFile = sca_util.getFilesRecursiveByExt( pj( RootDir, 'share', 'osg-data' ), [ '.osg' ] )
iveFile = sca_util.getFilesRecursiveByExt( pj( RootDir, 'share', 'osg-data' ), [ '.ive' ] )
jpgFile = sca_util.getFilesRecursiveByExt( pj( RootDir, 'share', 'osg-data' ), [ '.jpg' ] )

fileBundle.addFiles( osgFile )
fileBundle.addFiles( iveFile )
fileBundle.addFiles( jpgFile )
