##Builds BaffleUnit program
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import('ves_pkg buildDir RootDir vtk_options osg_options xerces_options tao_options')

srcs = Split("""
   IntStoveUnit_client.cpp
   IntStoveUnit_i.cpp
   baffle.cpp
   create_stove.cpp
   inlet.cpp
   stove.cpp
""")

headers = Split("""
   IntStoveUnit_i.h
   baffle.h
   create_stove.h
   inlet.h
   stove.h
""")

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['ves_open_xml', 'ves_ce_unitwrapper', 'ves_open_module'])
lib_env.Append(LIBPATH = [pj(RootDir, buildDir, 'src', 'ves', 'open'),
			                 pj(RootDir, buildDir, 'src', 'ves', 'open', 'xml'),
			                 pj(RootDir, buildDir, 'src', 'ves', 'ce', 'unitwrapper'),
                          pj(RootDir, buildDir, 'external', 'loki-0.1.6')])

lib_env.Append(CPPPATH = [pj(RootDir, 'external', 'loki-0.1.6', 'include')])

tao_options.apply( lib_env )
osg_options.apply( lib_env )
xerces_options.apply( lib_env )
vtk_options.apply( lib_env )

prog = ves_pkg.createProgram('IntStoveUnit' + lib_env["PROGSUFFIX"], lib_env,
          installPrefix = pj( 'share', 'vesuite', 'examples', 'InteractiveStove', 'Plugins', 'Unit', host_type ))

prog.addSources(srcs)
prog.build()
