##Build Default Plugins
openSubdirs = Split("""
    aspen_dynamics
    aspen_dynamics_unit_operation
    aspen_plus
    aspen_plus_unit_operation
    powersim
    sim
    sim_unit_operation
""")
#    opc_unit_operation


##Run SConscript files in all of those folders.
for d in openSubdirs:
   SConscript( dirs = d )
