#Builds VE-Suite plugin utilies for simulators
Import( 'GetPlatform baseEnv ves_pkg' )

toolsSubdirs = Split("""
    builder
    vea
""")
# not needed anymore since we have screen capture working in xplorer
#desktop_wallpaper

if GetPlatform() == 'win32':
    #Should Aspen support be built
    if baseEnv[ 'MakeAspenSupport' ] != 'no':
        toolsSubdirs.append( "aspen" )

    #Should DynSim support be built
    if baseEnv[ 'MakeDynSimSupport' ] != 'no':
        toolsSubdirs.append( "DynSimUnit" )

    #Should Powersim support be built
    if baseEnv[ 'MakePowersimSupport' ] != 'no':
        toolsSubdirs.append( "powersim" )

#Should db support be built
#if mysqlpp_options.isAvailable():
#    toolsSubdirs.append( "db" )

#Run SConscript files in all of those folders.
for d in toolsSubdirs:
    SConscript( dirs = d )
