#Builds VE-Suite Libraries
#import os
#pj = os.path.join

Import( 'GetPlatform baseEnv ves_pkg mysqlpp_options' )

toolsSubdirs = Split("""
    builder
    vea
""")

#Should Aspen support be built
if GetPlatform() == 'win32':
    if baseEnv[ 'MakeAspenSupport' ] != 'no':
        toolsSubdirs = Split("""
            aspen
        """)

#Should db support be built
if mysqlpp_options.isAvailable():
    toolsSubdirs = Split("""
        db
    """)
        
#Run SConscript files in all of those folders.
for d in toolsSubdirs:
    SConscript( dirs = d )
