##Builds VE-Suite Libraries
#import os
#pj = os.path.join

Import( 'GetPlatform' )

toolsSubdirs = Split("""
    builder
    vea
""")

if GetPlatform() == 'win32':
   toolsSubdirs += Split("""aspen""")

##Run SConscript files in all of those folders.
for d in toolsSubdirs:
   #print " dir ", d
   SConscript( dirs = d )
