import os, sys, string
pj = os.path.join

Import('baseEnv')

sources = Split("""
   main.cxx
   transient.cxx
""")
env = baseEnv.Copy()
env.Append(CPPPATH = [os.getcwd()])
env.Program('vexplorer', source = sources)
