##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'WarrantyTool' ) )
CameraPlacementToolDir = pj( RootDir, 'share', 'examples', 'WarrantyTool' )

#fileBundle.addFiles( [ 'warrantytool.ves' ] )

CameraPlacementToolSubdirs = Split("""
    GraphicalPlugin
    UserInterface
""")

##Run SConscript files in all of these folders.
for d in CameraPlacementToolSubdirs:
   SConscript( dirs = d )
