##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'HyperLab' ) )
HyperLabDemoDir = pj( RootDir, 'share', 'examples', 'HyperLab' )

iveFile = sca_util.getFilesRecursiveByExt( HyperLabDemoDir, [ '.ive' ] )
xpmFile = sca_util.getFilesRecursiveByExt( HyperLabDemoDir, [ '.xpm' ] )
icoFile = sca_util.getFilesRecursiveByExt( HyperLabDemoDir, [ '.ico' ] )
tgaFile = sca_util.getFilesRecursiveByExt( HyperLabDemoDir, [ '.tga' ] )

fileBundle.addFiles( iveFile )
fileBundle.addFiles( xpmFile )
fileBundle.addFiles( icoFile )
fileBundle.addFiles( tgaFile )
fileBundle.addFiles( [ 'hyperlab.ves' ] )

HyperLabSubdirs = Split("""
    HyperLabGP
    HyperLabUI
""")

if GetPlatform() == 'win32':
   HyperLabSubdirs += Split("""HyperLabUnit""")

##Run SConscript files in all of these folders.
for d in HyperLabSubdirs:
   SConscript( dirs = d )
