##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'HyperLab' ) )
coinDemoDir = pj( RootDir, 'share', 'examples', 'HyperLab' )
xpmFile = sca_util.getFilesRecursiveByExt( coinDemoDir, [ '.xpm' ] )
iveFile = sca_util.getFilesRecursiveByExt( coinDemoDir, [ '.ive' ] )
wavFile = sca_util.getFilesRecursiveByExt( coinDemoDir, [ '.wav' ] )
jpgFile = sca_util.getFilesRecursiveByExt( coinDemoDir, [ '.jpg' ] )
tgaFile = sca_util.getFilesRecursiveByExt( coinDemoDir, [ '.tga' ] )
ddsFile = sca_util.getFilesRecursiveByExt( coinDemoDir, [ '.dds' ] )

fileBundle.addFiles( xpmFile )
fileBundle.addFiles( iveFile )
fileBundle.addFiles( wavFile )
fileBundle.addFiles( jpgFile )
fileBundle.addFiles( tgaFile )
fileBundle.addFiles( ddsFile )
fileBundle.addFiles( [ 'hyperlab.ves' ] )
HyperLabSubdirs = Split("""
    HyperLabGP
    HyperLabUI
""")

##Run SConscript files in all of these folders.
for d in HyperLabSubdirs:
   SConscript( dirs = d )
