#!python
EnsureSConsVersion(0,96)
SConsignFile()

import sys, string
import os, string, platform
#import distultils.util
import SCons.Script
import commands

#pj = os.path.join

#try:
#  import SConsAddons
#except:
#  sys.path.append(pj(os.getcwd(), 'Tools', 'scons-addons', 'src'))
#  sys.path.append(pj(os.getcwd(), 'Tools', 'scons-addons', 'templates'))


#def run(cmd):
#    """Run a command and decipher the return code. Exit by default."""
#    res = os.system(cmd)
#    # Assumes that if a process doesn't call exit, it was successful
#     if (os.WIFEXITED(res)):
#         code = os.WEXITSTATUS(res)
#       if code != 0:
#            print "Error: return code: " + str(code)
#            if SCons.Script.keep_going_on_error == 0:
#               sys.exit(code)


#cmd = "svn log --xml --verbose -r'{'2007-06-01'}':'HEAD' > ChangeLog.xml"
#dox = "doxygen"
#os.system(cmd)

#os.system(dox)
import SConsAddons.Util as sca_util


from_date = "2007-05-31"
to_date = "HEAD"
os.system("svn log --xml --verbose -r'{'%s'}':'%s' > ChangeLog.xml" % (from_date, to_date))