##Builds VE-Suite Libraries
#import os
#pj = os.path.join

lemonSubdirs = Split("""
    converter
    simple
    gis_scheduler
    test_scheduler
""")

##Run SConscript files in all of those folders.
for d in lemonSubdirs:
   SConscript( dirs = d )
