##Builds InteractiveStove Graphical Plugin
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import('baseEnv ves_pkg LIBDIR buildDir vtk_options osg_options xerces_options')

srcs = Split("""
   VEIntStovemod.cxx
""")

headers = Split("""
   VEIntStovemod.h
""")

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['ves_xplorer'])
lib_env.Append(LIBPATH = [pj(os.getenv('VE_SUITE_HOME'), buildDir, 'src', 'ves', 'xplorer'),
                          pj(os.getenv('VE_SUITE_HOME'), buildDir, 'external', 'loki-0.1.6')])

lib_env.Append(CPPPATH = [pj(os.getenv('VE_SUITE_HOME'), 'src'),
			                 pj(os.getenv('VE_SUITE_HOME'), 'external', 'loki-0.1.6', 'include'),
                          pj(os.getenv('VE_SUITE_HOME'), 'external', 'osgOQ', 'include')])

lib_env.ParseConfig('flagpoll vrjuggler --libs --cflags')
lib_env.ParseConfig('flagpoll Boost.Filesystem --libs --cflags')
lib_env.ParseConfig('flagpoll bullet --libs --cflags')

vtk_options.apply( lib_env )
osg_options.apply( lib_env )
xerces_options.apply( lib_env )

lib = ves_pkg.createSharedLibrary( 'InteractiveStoveGP', lib_env,
    installPrefix = pj( 'share', 'vesuite', 'examples', 'InteractiveStove', 'Plugins', 'GE', host_type ) ) 

lib.addSources(srcs)
lib.addHeaders(headers,  pj( 'Plugins', 'GE'))
lib.build()
