// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:151

#ifndef _TAO_IDL___SKEL_VJOBSC_H_
#define _TAO_IDL___SKEL_VJOBSC_H_


#include "tao/corba.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

#if defined (TAO_EXPORT_NESTED_CLASSES)
#  if defined (TAO_EXPORT_NESTED_MACRO)
#    undef TAO_EXPORT_NESTED_MACRO
#  endif /* defined (TAO_EXPORT_NESTED_MACRO) */
#  define TAO_EXPORT_NESTED_MACRO 
#endif /* TAO_EXPORT_NESTED_CLASSES */

#if defined(_MSC_VER)
#if (_MSC_VER >= 1200)
#pragma warning(push)
#endif /* _MSC_VER >= 1200 */
#pragma warning(disable:4250)
#endif /* _MSC_VER */

#if defined (__BORLANDC__)
#pragma option push -w-rvl -w-rch -w-ccc -w-inl
#endif /* __BORLANDC__ */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ch.cpp:52

#if !defined (_VJOBS___PTR_CH_)
#define _VJOBS___PTR_CH_

class VjObs;
typedef VjObs *VjObs_ptr;

#endif /* end #if !defined */

#if !defined (_VJOBS___VAR_CH_)
#define _VJOBS___VAR_CH_

// TAO_IDL - Generated from
// be/be_interface.cpp:571

class  VjObs_var : public TAO_Base_var
{
public:
  VjObs_var (void); // default constructor
  VjObs_var (VjObs_ptr p) : ptr_ (p) {} 
  VjObs_var (const VjObs_var &); // copy constructor
  ~VjObs_var (void); // destructor
  
  VjObs_var &operator= (VjObs_ptr);
  VjObs_var &operator= (const VjObs_var &);
  VjObs_ptr operator-> (void) const;
  
  operator const VjObs_ptr &() const;
  operator VjObs_ptr &();
  // in, inout, out, _retn 
  VjObs_ptr in (void) const;
  VjObs_ptr &inout (void);
  VjObs_ptr &out (void);
  VjObs_ptr _retn (void);
  VjObs_ptr ptr (void) const;
  
  // Hooks used by template sequence and object manager classes
  // for non-defined forward declared interfaces.
  static VjObs_ptr tao_duplicate (VjObs_ptr);
  static void tao_release (VjObs_ptr);
  static VjObs_ptr tao_nil (void);
  static VjObs_ptr tao_narrow (
      CORBA::Object *
      ACE_ENV_ARG_DECL_NOT_USED
    );
  static CORBA::Object * tao_upcast (void *);

private:
  VjObs_ptr ptr_;
  // Unimplemented - prevents widening assignment.
  VjObs_var (const TAO_Base_var &rhs);
  VjObs_var &operator= (const TAO_Base_var &rhs);
};

#endif /* end #if !defined */

#if !defined (_VJOBS___OUT_CH_)
#define _VJOBS___OUT_CH_

// TAO_IDL - Generated from
// be/be_interface.cpp:946

class  VjObs_out
{
public:
  VjObs_out (VjObs_ptr &);
  VjObs_out (VjObs_var &);
  VjObs_out (const VjObs_out &);
  VjObs_out &operator= (const VjObs_out &);
  VjObs_out &operator= (const VjObs_var &);
  VjObs_out &operator= (VjObs_ptr);
  operator VjObs_ptr &();
  VjObs_ptr &ptr (void);
  VjObs_ptr operator-> (void);

private:
  VjObs_ptr &ptr_;
};

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ch.cpp:110

#if !defined (_VJOBS_CH_)
#define _VJOBS_CH_

class _TAO_VjObs_Proxy_Impl;
class _TAO_VjObs_Remote_Proxy_Impl;
class _TAO_VjObs_Proxy_Broker;
class _TAO_VjObs_Remote_Proxy_Broker;

class  VjObs
  : public virtual CORBA::Object
{
public:
  typedef VjObs_ptr _ptr_type;
  typedef VjObs_var _var_type;
  static int _tao_class_id;
  
  // The static operations.
  static VjObs_ptr _duplicate (VjObs_ptr obj);
  
  static VjObs_ptr _narrow (
      CORBA::Object_ptr obj
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static VjObs_ptr _unchecked_narrow (
      CORBA::Object_ptr obj
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  static VjObs_ptr _nil (void)
    {
      return (VjObs_ptr)0;
    }
  
  static void _tao_any_destructor (void *);

#if !defined (_VJOBS_SCALAR_P_CH_)
#define _VJOBS_SCALAR_P_CH_
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:371
  
  class scalar_p;
  class scalar_p_var;
  
  // *************************************************************
  // VjObs::scalar_p
  // *************************************************************
  
  class  scalar_p : public 
  
  // TAO_IDL - Generated from 
  // be/be_visitor_sequence/sequence_ch.cpp:51

#if !defined (TAO_USE_SEQUENCE_TEMPLATES)
  TAO_Unbounded_String_Sequence
#else /* TAO_USE_SEQUENCE_TEMPLATES */
  TAO_Unbounded_String_Sequence

#endif /* !TAO_USE_SEQUENCE_TEMPLATES */ 
  {
  public:
    scalar_p (void);
    scalar_p (CORBA::ULong max);
    scalar_p (
        CORBA::ULong max, 
        CORBA::ULong length, 
        char * *buffer, 
        CORBA::Boolean release = 0
      );
    scalar_p (const scalar_p &);
    ~scalar_p (void);
    
    static void _tao_any_destructor (void*);
    
    typedef scalar_p_var _var_type;
  };

#endif /* end #if !defined */

#if !defined (_VJOBS_SCALAR_P___VAR_CH_)
#define _VJOBS_SCALAR_P___VAR_CH_
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:549
  
  // *************************************************************
  // class VjObs::scalar_p_var
  // *************************************************************
  
  class  scalar_p_var
  {
  public:
    scalar_p_var (void);
    scalar_p_var (scalar_p *);
    scalar_p_var (const scalar_p_var &);
    ~scalar_p_var (void);
    
    scalar_p_var &operator= (scalar_p *);
    scalar_p_var &operator= (const scalar_p_var &);
    scalar_p *operator-> (void);
    const scalar_p *operator-> (void) const;
    
    operator const scalar_p &() const;
    operator scalar_p &();
    operator scalar_p &() const;
    
    // Variable-size base types only.
    operator scalar_p *&();
    
    TAO_SeqElem_String_Manager operator[] (CORBA::ULong index);
    
    // in, inout, out, _retn 
    const scalar_p &in (void) const;
    scalar_p &inout (void);
    scalar_p *&out (void);
    scalar_p *_retn (void);
    scalar_p *ptr (void) const;
  
  private:
    scalar_p *ptr_;
  };

#endif /* end #if !defined */

#if !defined (_VJOBS_SCALAR_P___OUT_CH_)
#define _VJOBS_SCALAR_P___OUT_CH_
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:753
  
  class  scalar_p_out
  {
  public:
    scalar_p_out (scalar_p *&);
    scalar_p_out (scalar_p_var &);
    scalar_p_out (const scalar_p_out &);
    scalar_p_out &operator= (const scalar_p_out &);
    scalar_p_out &operator= (scalar_p *);
    operator scalar_p *&();
    scalar_p *&ptr (void);
    scalar_p *operator-> (void);
    TAO_SeqElem_String_Manager operator[] (CORBA::ULong index);
  
  private:
    scalar_p *&ptr_;
    // Assignment from T_var not allowed.
    void operator= (const scalar_p_var &);
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:44
  
  static ::CORBA::TypeCode_ptr _tc_scalar_p;
  
  // TAO_IDL - Generated from 
  // be/be_visitor_sequence/gen_unbounded_sequence_ch.cpp:65

#if !defined (TAO_USE_SEQUENCE_TEMPLATES)

#if !defined (__TAO_UNBOUNDED_SEQUENCE_VJOBS_OBJ_P_CH_)
#define __TAO_UNBOUNDED_SEQUENCE_VJOBS_OBJ_P_CH_
  
  class  _TAO_Unbounded_Sequence_VjObs_obj_p
    : public TAO_Unbounded_Base_Sequence
  {
  public:
    _TAO_Unbounded_Sequence_VjObs_obj_p (void);
    _TAO_Unbounded_Sequence_VjObs_obj_p (CORBA::ULong maximum); 
    _TAO_Unbounded_Sequence_VjObs_obj_p (
        CORBA::ULong maximum,
        CORBA::ULong length,
        CORBA::Short *data,
        CORBA::Boolean release = 0
      );
    _TAO_Unbounded_Sequence_VjObs_obj_p (
        const _TAO_Unbounded_Sequence_VjObs_obj_p &rhs
      );
    _TAO_Unbounded_Sequence_VjObs_obj_p &operator= (
        const _TAO_Unbounded_Sequence_VjObs_obj_p &rhs
      );
    virtual ~_TAO_Unbounded_Sequence_VjObs_obj_p (void);
    
    // = Accessors.
    CORBA::Short &operator[] (CORBA::ULong i);
    const CORBA::Short &operator[] (CORBA::ULong i) const;
    
    // = Static operations.
    static CORBA::Short *allocbuf (CORBA::ULong size);
    static void freebuf (CORBA::Short *buffer);
    
    // Implement the TAO_Base_Sequence methods (see Sequence.h)
    virtual void _allocate_buffer (CORBA::ULong length);
    virtual void _deallocate_buffer (void);
    CORBA::Short *get_buffer (CORBA::Boolean orphan = 0);
    const CORBA::Short *get_buffer (void) const;
    void replace (
        CORBA::ULong max,
        CORBA::ULong length,
        CORBA::Short *data,
        CORBA::Boolean release
      );
  };

#endif /* end #if !defined */

#endif /* !TAO_USE_SEQUENCE_TEMPLATES */ 

#if !defined (_VJOBS_OBJ_P_CH_)
#define _VJOBS_OBJ_P_CH_
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:371
  
  class obj_p;
  class obj_p_var;
  
  // *************************************************************
  // VjObs::obj_p
  // *************************************************************
  
  class  obj_p : public 
  
  // TAO_IDL - Generated from 
  // be/be_visitor_sequence/sequence_ch.cpp:51

#if !defined (TAO_USE_SEQUENCE_TEMPLATES)
  _TAO_Unbounded_Sequence_VjObs_obj_p
#else /* TAO_USE_SEQUENCE_TEMPLATES */
  TAO_Unbounded_Sequence<CORBA::Short>

#endif /* !TAO_USE_SEQUENCE_TEMPLATES */ 
  {
  public:
    obj_p (void);
    obj_p (CORBA::ULong max);
    obj_p (
        CORBA::ULong max, 
        CORBA::ULong length, 
        CORBA::Short *buffer, 
        CORBA::Boolean release = 0
      );
    obj_p (const obj_p &);
    ~obj_p (void);
    
    static void _tao_any_destructor (void*);
    
    typedef obj_p_var _var_type;
  };

#endif /* end #if !defined */

#if !defined (_VJOBS_OBJ_P___VAR_CH_)
#define _VJOBS_OBJ_P___VAR_CH_
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:549
  
  // *************************************************************
  // class VjObs::obj_p_var
  // *************************************************************
  
  class  obj_p_var
  {
  public:
    obj_p_var (void);
    obj_p_var (obj_p *);
    obj_p_var (const obj_p_var &);
    
    // Fixed-size base types only.
    obj_p_var (const obj_p &);
    
    ~obj_p_var (void);
    
    obj_p_var &operator= (obj_p *);
    obj_p_var &operator= (const obj_p_var &);
    
    // Fixed-size base types only.
    obj_p_var &operator= (const obj_p &);
    
    obj_p *operator-> (void);
    const obj_p *operator-> (void) const;
    
    operator const obj_p &() const;
    operator obj_p &();
    operator obj_p &() const;
    CORBA::Short & operator[] (CORBA::ULong index);
    const CORBA::Short & operator[] (CORBA::ULong index) const;
    
    // in, inout, out, _retn 
    const obj_p &in (void) const;
    obj_p &inout (void);
    obj_p *&out (void);
    obj_p *_retn (void);
    obj_p *ptr (void) const;
  
  private:
    obj_p *ptr_;
  };

#endif /* end #if !defined */

#if !defined (_VJOBS_OBJ_P___OUT_CH_)
#define _VJOBS_OBJ_P___OUT_CH_
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:753
  
  class  obj_p_out
  {
  public:
    obj_p_out (obj_p *&);
    obj_p_out (obj_p_var &);
    obj_p_out (const obj_p_out &);
    obj_p_out &operator= (const obj_p_out &);
    obj_p_out &operator= (obj_p *);
    operator obj_p *&();
    obj_p *&ptr (void);
    obj_p *operator-> (void);
    CORBA::Short & operator[] (CORBA::ULong index);
  
  private:
    obj_p *&ptr_;
    // Assignment from T_var not allowed.
    void operator= (const obj_p_var &);
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:44
  
  static ::CORBA::TypeCode_ptr _tc_obj_p;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void update (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::VjObs::scalar_p * update_scalar (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::VjObs::scalar_p * get_geo_name (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::VjObs::scalar_p * get_teacher_name (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short get_sc_num (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short get_geo_num (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short get_teacher_num (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual char * get_perf (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void SetClientInfoFlag (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void SetClientInfoData (
      const VjObs::obj_p & o
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::VjObs::obj_p * GetClientInfoData (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short GetNumberOfSounds (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::VjObs::scalar_p * GetSoundNameArray (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::VjObs::scalar_p * get_dataset_names (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::VjObs::obj_p * get_dataset_types (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual ::VjObs::obj_p * get_num_scalars_per_dataset (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setNumDatasets (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getNumDatasets (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getTotalNumberOfScalars (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setNumVectors (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getNumVectors (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setNumGeoArrays (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getNumGeoArrays (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setClients (
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Long getClients (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setIsoValue (
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Long getIsoValue (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setSc (
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Long getSc (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setMin (
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Long getMin (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setMax (
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Long getMax (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setId (
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Long getId (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setGeoState (
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Long getGeoState (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setPostdataState (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getPostdataState (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setPreState (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getPreState (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setTimesteps (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getTimesteps (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setNumTeacherArrays (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getNumTeacherArrays (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual void setTeacherState (
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_ch.cpp:46
  
  virtual CORBA::Short getTeacherState (
      
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:267
  
  virtual CORBA::Boolean _is_a (
      const char *type_id
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    );
  
  virtual void *_tao_QueryInterface (ptr_arith_t type);
  
  virtual const char* _interface_repository_id (void) const;
private:
  _TAO_VjObs_Proxy_Broker *the_TAO_VjObs_Proxy_Broker_;

protected:
  VjObs (int collocated = 0);
  
  // These methods travese the inheritance tree and set the
  // parents piece of the given class in the right mode.
  virtual void VjObs_setup_collocation (int collocated);
  
  VjObs (
      TAO_Stub *objref, 
      CORBA::Boolean _tao_collocated = 0,
      TAO_Abstract_ServantBase *servant = 0
    );
  virtual ~VjObs (void);
  
  friend class _TAO_VjObs_Remote_Proxy_Impl;
  friend class _TAO_VjObs_ThruPOA_Proxy_Impl;
  friend class _TAO_VjObs_Direct_Proxy_Impl;

private:
  VjObs (const VjObs &);
  void operator= (const VjObs &);
};

// The Proxy Implementations are used by each interface to
// perform a call. Each different implementation encapsulates
// an invocation logic.


///////////////////////////////////////////////////////////////////////
//                    Base Proxy Impl. Declaration
//

// TAO_IDL - Generated from
// be/be_visitor_interface/base_proxy_impl_ch.cpp:35

class  _TAO_VjObs_Proxy_Impl
  : public virtual TAO_Object_Proxy_Impl
{
public:
  virtual ~_TAO_VjObs_Proxy_Impl (void) {}
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void update (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual ::VjObs::scalar_p * update_scalar (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual ::VjObs::scalar_p * get_geo_name (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual ::VjObs::scalar_p * get_teacher_name (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short get_sc_num (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short get_geo_num (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short get_teacher_num (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual char * get_perf (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void SetClientInfoFlag (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void SetClientInfoData (
      CORBA_Object *_collocated_tao_target_,
      const VjObs::obj_p & o
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual ::VjObs::obj_p * GetClientInfoData (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short GetNumberOfSounds (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual ::VjObs::scalar_p * GetSoundNameArray (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual ::VjObs::scalar_p * get_dataset_names (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual ::VjObs::obj_p * get_dataset_types (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual ::VjObs::obj_p * get_num_scalars_per_dataset (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setNumDatasets (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getNumDatasets (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getTotalNumberOfScalars (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setNumVectors (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getNumVectors (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setNumGeoArrays (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getNumGeoArrays (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setClients (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Long getClients (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setIsoValue (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Long getIsoValue (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setSc (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Long getSc (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setMin (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Long getMin (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setMax (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Long getMax (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setId (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Long getId (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setGeoState (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Long getGeoState (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setPostdataState (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getPostdataState (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setPreState (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getPreState (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setTimesteps (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getTimesteps (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setNumTeacherArrays (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getNumTeacherArrays (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual void setTeacherState (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/base_proxy_impl_ch.cpp:24
  
  virtual CORBA::Short getTeacherState (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    )) = 0;

protected:
  _TAO_VjObs_Proxy_Impl (void);
};

//
//               End Base Proxy Impl. Declaration
///////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////
//                Remote Proxy Impl. Declaration
//

// TAO_IDL - Generated from
// be/be_visitor_interface/remote_proxy_impl_ch.cpp:37

class  _TAO_VjObs_Remote_Proxy_Impl
  : public virtual _TAO_VjObs_Proxy_Impl,
    public virtual TAO_Remote_Object_Proxy_Impl
{
public:
  _TAO_VjObs_Remote_Proxy_Impl (void);
  
  virtual ~_TAO_VjObs_Remote_Proxy_Impl (void) {}
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void update (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual ::VjObs::scalar_p * update_scalar (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual ::VjObs::scalar_p * get_geo_name (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual ::VjObs::scalar_p * get_teacher_name (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short get_sc_num (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short get_geo_num (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short get_teacher_num (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual char * get_perf (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void SetClientInfoFlag (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void SetClientInfoData (
      CORBA_Object *_collocated_tao_target_,
      const VjObs::obj_p & o
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual ::VjObs::obj_p * GetClientInfoData (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short GetNumberOfSounds (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual ::VjObs::scalar_p * GetSoundNameArray (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual ::VjObs::scalar_p * get_dataset_names (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual ::VjObs::obj_p * get_dataset_types (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual ::VjObs::obj_p * get_num_scalars_per_dataset (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setNumDatasets (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getNumDatasets (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getTotalNumberOfScalars (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setNumVectors (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getNumVectors (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setNumGeoArrays (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getNumGeoArrays (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setClients (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Long getClients (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setIsoValue (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Long getIsoValue (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setSc (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Long getSc (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setMin (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Long getMin (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setMax (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Long getMax (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setId (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Long getId (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setGeoState (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Long value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Long getGeoState (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setPostdataState (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getPostdataState (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setPreState (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getPreState (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setTimesteps (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getTimesteps (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setNumTeacherArrays (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getNumTeacherArrays (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual void setTeacherState (
      CORBA_Object *_collocated_tao_target_,
      CORBA::Short value
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/proxy_impl_xh.cpp:24
  
  virtual CORBA::Short getTeacherState (
      CORBA_Object *_collocated_tao_target_
    )
    ACE_THROW_SPEC ((
      CORBA::SystemException
    ));
};

//
//             End Remote Proxy Impl. Declaration
///////////////////////////////////////////////////////////////////////

// The Proxy Brokers are used by each interface to get
// the right proxy for performing a call. In the new 
// collocation scheme, the proxy to be used can vary on
// a call by call basis.

///////////////////////////////////////////////////////////////////////
//                 Base Proxy Broker Declaration 
//

// TAO_IDL - Generated from
// be/be_visitor_interface/base_proxy_broker_ch.cpp:35

class  _TAO_VjObs_Proxy_Broker
{
public:
  virtual ~_TAO_VjObs_Proxy_Broker (void);
  virtual _TAO_VjObs_Proxy_Impl &select_proxy (
      VjObs *object
      ACE_ENV_ARG_DECL_WITH_DEFAULTS
    ) = 0;
  
protected:
  _TAO_VjObs_Proxy_Broker (void);
  
};

//
//              End Base Proxy Broker Declaration 
///////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////
//                 Remote Proxy Broker Declaration 
//

// TAO_IDL - Generated from
// be/be_visitor_interface/remote_proxy_broker_ch.cpp:40

class  _TAO_VjObs_Remote_Proxy_Broker
  : public virtual _TAO_VjObs_Proxy_Broker
{
public: 
  _TAO_VjObs_Remote_Proxy_Broker (void);
  
  virtual ~_TAO_VjObs_Remote_Proxy_Broker (void);
  
  virtual _TAO_VjObs_Proxy_Impl &select_proxy (
      VjObs *object
      ACE_ENV_ARG_DECL
    );
  
private:
  _TAO_VjObs_Remote_Proxy_Impl remote_proxy_impl_;

public:
  // This member function is used to get an handle to the unique instance
  // of the Remote Proxy Broker that is available for a given
  // interface.
  static _TAO_VjObs_Remote_Proxy_Broker *the_TAO_VjObs_Remote_Proxy_Broker (void);
};

//
//              End Remote Proxy Broker Declaration 
///////////////////////////////////////////////////////////////////////

#endif /* end #if !defined */

// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_decl.cpp:44

extern  ::CORBA::TypeCode_ptr  _tc_VjObs;

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root.cpp:80

extern 
_TAO_VjObs_Proxy_Broker *
(*_TAO_VjObs_Proxy_Broker_Factory_function_pointer) (
    CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:52

 void operator<<= (CORBA::Any &, VjObs_ptr); // copying
 void operator<<= (CORBA::Any &, VjObs_ptr *); // non-copying
 CORBA::Boolean operator>>= (const CORBA::Any &, VjObs_ptr &);

// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:52

 void operator<<= (CORBA::Any &, const VjObs::scalar_p &); // copying version
 void operator<<= (CORBA::Any &, VjObs::scalar_p*); // noncopying version
 CORBA::Boolean operator>>= (const CORBA::Any &, VjObs::scalar_p *&); // deprecated
 CORBA::Boolean operator>>= (const CORBA::Any &, const VjObs::scalar_p *&);

// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:52

 void operator<<= (CORBA::Any &, const VjObs::obj_p &); // copying version
 void operator<<= (CORBA::Any &, VjObs::obj_p*); // noncopying version
 CORBA::Boolean operator>>= (const CORBA::Any &, VjObs::obj_p *&); // deprecated
 CORBA::Boolean operator>>= (const CORBA::Any &, const VjObs::obj_p *&);

// TAO_IDL - Generated from
// be/be_visitor_root/cdr_op.cpp:48

#ifndef __ACE_INLINE__

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

 CORBA::Boolean operator<< (TAO_OutputCDR &, const VjObs_ptr );
 CORBA::Boolean operator>> (TAO_InputCDR &, VjObs_ptr &);

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:57

#if !defined _TAO_CDR_OP_VjObs_scalar_p_H_
#define _TAO_CDR_OP_VjObs_scalar_p_H_

 CORBA::Boolean operator<< (
    TAO_OutputCDR &,
    const VjObs::scalar_p &
  );
 CORBA::Boolean operator>> (
    TAO_InputCDR &,
    VjObs::scalar_p &
  );

#endif /* _TAO_CDR_OP_VjObs_scalar_p_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:57

#if !defined _TAO_CDR_OP_VjObs_obj_p_H_
#define _TAO_CDR_OP_VjObs_obj_p_H_

 CORBA::Boolean operator<< (
    TAO_OutputCDR &,
    const VjObs::obj_p &
  );
 CORBA::Boolean operator>> (
    TAO_InputCDR &,
    VjObs::obj_p &
  );

#endif /* _TAO_CDR_OP_VjObs_obj_p_H_ */

// TAO_IDL - Generated from
// be/be_visitor_root/cdr_op.cpp:64

#endif /* __ACE_INLINE__ */

// TAO_IDL - Generated from
// be/be_codegen.cpp:1016

#if defined (__ACE_INLINE__)
#include "VjObsC.i"
#endif /* defined INLINE */

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
#pragma warning(pop)
#endif /* _MSC_VER */

#if defined (__BORLANDC__)
#pragma option pop
#endif /* __BORLANDC__ */

#endif /* ifndef */

