#!python
Import('opts')

builderSubdirs = Split("""
    Translator/cfdTranslatorToVTK
    Translator/DataLoader
    Translator/DataLoader/TestLoader
    Preprocessor
    vtkTo3DTexture/tcGUI
    Utilities
""") 

if (opts.GetOption("HDF5BaseDir")):
   builderSubdirs.append('Translator/HDFtoVTK')

##Run SConscript files in all of those folders.
for d in builderSubdirs:
   #print " dir ", d
   SConscript( dirs = d )
