#!python
builderSubdirs = Split("""
    Translator/cfdTranslatorToVTK
    Translator/DataLoader
    Translator/DataLoader/TestLoader
    Preprocessor
    vtkTo3DTexture/tcGUI
    Utilities
""") 

##Run SConscript files in all of those folders.
for d in builderSubdirs:
   ##print " dir ", d
   SConscript( dirs = d )
