import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR GetPlatform buildDir vtk_options boost_options wxwidgets_options')
if not wxwidgets_options.isAvailable():
    Return()

sources = Split("""
   transient.cxx
   StarCDTransient.cxx
   StarCDTransientApp.cxx
""")
env = baseEnv.Clone()
env.Append(CPPPATH = [os.getcwd()])

wxwidgets_options.apply( env )

convertTransientStarCDData = ves_pkg.createProgram('convertTransientStarCDData' + env["PROGSUFFIX"], env, 'bin')
convertTransientStarCDData.addSources( sources )
convertTransientStarCDData.build()
