##Builds DataLoaderLib
import os, sys, string
import glob

pj = os.path.join
import SConsAddons.Util as sca_util

Import('baseEnv ves_pkg LIBDIR vtk_options buildDir RootDir boost_options')

#srcDir = os.path.abspath( pj(RootDir, 'src', 'ves', 'xplorer','plugin') )
#base_plugin_srcs = sca_util.getSources()
#base_header_srcs = sca_util.getHeaders()
#C:\dev\TSVEG\VE_Suite\src\ves\builder\DataLoader\tecplot
sources_list = glob.glob(pj(RootDir, 'src','ves','builder','DataLoader','tecplot','*.cxx'))
sources = map(lambda s: os.path.basename(s), sources_list)

#headers_list = glob.glob(pj(RootDir, 'src','ves','xplorer','*.h'))

lib_env = ves_pkg.getEnv().Clone()

# For windows with tecplot
TECSDKHOME = "C:\Program Files (x86)\Tecplot\TecSDK 1.1"
lib_env.Append( LIBPATH = [pj(TECSDKHOME,'lib','win32')],
                LIBS = ['tpsdkbase', 'tpsdkintegrationmanager','tptoolbox'],
                CPPPATH = [ pj(TECSDKHOME,'include'),
                    pj(TECSDKHOME,'include','sdk','integrationmanager','services'),
                    pj(TECSDKHOME,'include','sdk'),
                    pj(TECSDKHOME,'include','sdk','integrationmanager'),
                    pj(TECSDKHOME,'include','toolbox')],
                CPPDEFINES = ['ENGINE','VE_USER_BUILDER_LIBRARY']
              )

#boost_options.apply( lib_env )

vtk_options.apply( lib_env )

prog = ves_pkg.createProgram('tecplotReader' + lib_env["PROGSUFFIX"], lib_env, 'bin')
prog.addSources( sources )
prog.build()
