## Build CASIlib
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR RootDir')

sources = Split("""
   CASI.cxx
   CASI_CASIObj.cxx
   CASI_Document.cxx
   CASI_VAriable.cxx
   aspenplus_2004/happ.cxx
""")

headers = Split("""
   CASI.h
""")

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append( CPPPATH = [pj('#', 'share', 'tools', 'aspen','CASIlib', 'aspenplus_2004')] )
lib_env.Append( CPPDEFINES = ['_AFXDLL'])
lib_env.Append( CPPDEFINES = ['CASI_LIBRARY'])
lib = ves_pkg.createSharedLibrary('CASIlib', lib_env,
                                               installPrefix = LIBDIR)
lib.addSources(sources)
lib.addHeaders(headers)
lib.build()
