## Build CASIlib
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR RootDir')

sources = Split("""
   CASI.cxx
   CASI_CASIObj.cxx
   CASI_Document.cxx
   CASI_VAriable.cxx
""")

headers = Split("""
   CASI.h
""")

lib_env = ves_pkg.getEnv().Clone()
lib_env['MSVS_USE_MFC_DIRS'] = 1

lib_env.Append( CPPDEFINES = ['_AFXDLL'])
lib_env.Append( CPPDEFINES = ['CASI_LIBRARY'])
lib = ves_pkg.createSharedLibrary('CASIlib', lib_env,
                                               installPrefix = LIBDIR)
lib.addSources(sources)
lib.addHeaders(headers, pj('ves'))
lib.build()
