##Builds VE_XplorerLib<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR execOsgPatTag buildDir osg_options vtk_options xerces_options')

sources = Split("""
   cfd1DTextInput.cxx 
   cfdAnimatedImage.cxx 
   cfdAnimatedStreamlineCone.cxx 
   cfdCommandArray.cxx 
   cfdCommandObjects.cxx 
   cfdContour.cxx 
   cfdContourBase.cxx 
   cfdContours.cxx 
   cfdCursor.cxx 
   cfdCuttingPlane.cxx 
   cfdDataSet.cxx
   cfdDigitalAnalogGauge.cxx 
   cfdDisplaySettings.cxx 
   cfdEnvironmentHandler.cxx 
   cfdGlobalBase.cxx 
   cfdGraphicsObject.cxx 
   cfdImage.cxx 
   cfdIsosurface.cxx 
   cfdModel.cxx 
   cfdModelHandler.cxx 
   cfdMomentum.cxx 
   cfdMomentums.cxx
   cfdNavigate.cxx 
   cfdObjects.cxx 
   cfdPlanes.cxx 
   cfdPolyData.cxx 
   cfdPresetContour.cxx 
   cfdPresetMomentum.cxx 
   cfdPresetVector.cxx 
   cfdQuatCamHandler.cxx 
   cfdQuatCam.cxx 
   cfdReadParam.cxx 
   cfdScalarBarActor.cxx 
   cfdSound.cxx 
   cfdSoundHandler.cxx 
   cfdSteadyStateVizHandler.cxx 
   cfdStreamers.cxx 
   cfdTeacher.cxx 
   cfdTextOutput.cxx
   cfdTextureBasedVizHandler.cxx
   cfdThread.cxx 
   cfdVectorBase.cxx
   cfdVector.cxx 
   cfdVectors.cxx 
   cfdRawNodeWriteTraverser.cxx 
   ActiveModelEventHandler.cxx
   AddVTKDataSetEventHandler.cxx
   AttributeEventHandler.cxx 
   CADEventHandler.cxx 
   CADDeleteNodeEH.cxx
   CADRemoveAttributeEH.cxx
   CADAddNodeEH.cxx 
   CADAddAttributeEH.cxx 
   CADSetActiveAttributeEH.cxx 
   CADSetNameEH.cxx
   CADSetRootNodeEH.cxx
   CADToggleEH.cxx
   CADTransformEH.cxx
   Device.cxx
   DeviceHandler.cxx
   DeviceEH.cxx
   DeviceModeEH.cxx
   MaterialModeUpdateEH.cxx
   MaterialUpdateEH.cxx
   KeyboardMouse.cxx
   KeyboardMouseEH.cxx
   cfdObjectHandler.cxx
   CreateVisObjectEventHandler.cxx
   ClearVisObjectsEventHandler.cxx
   ChangeCursorEventHandler.cxx
   SPDimensionsEH.cxx
   SPBoundEH.cxx
   SeedPoints.cxx
   SeedPointActivateEH.cxx
   TBTransientModeUpdateEH.cxx
   TBTransientDurationUpdateEH.cxx
   TBIsosurfaceEnableEH.cxx
   TBIsosurfaceUpdateEH.cxx
   TBUpdateScalarRangeEH.cxx
   TBBBoxEH.cxx
   TBClipPlaneEH.cxx
   TextureBasedEventHandler.cxx
   TBActivateEH.cxx
   TBUpdateSolutionEH.cxx
   QCLoadFileEH.cxx
   StoredSceneEH.cxx
   ChangeWorkingDirectoryEventHandler.cxx
   ChangeBackgroundColorEventHandler.cxx
   DataSetAxis.cxx
   BBoxEventHandler.cxx
   WireframeEventHandler.cxx
   AxesEventHandler.cxx
   AxesLabelsEventHandler.cxx
   DataSetScalarBar.cxx
   ScalarBarEventHandler.cxx
   ViewEventHandler.cxx
   DisplayInformation.cxx
   DisplayEventHandler.cxx
   QCClearDataEH.cxx
   DataTransformEH.cxx
   Wand.cxx
   TBSliceNumberUpdateEH.cxx
   TBSetActiveShaderManagerEH.cxx
   TBPhongShadingEnableEH.cxx
   Tablet.cxx
   NavigationDataEventHandler.cxx
   TBPreIntegrateEH.cxx
   SoundAddNewEH.cxx
   SoundActivateEH.cxx

""")
##   DataSetFileEH.cxx
##   DataSetPrecomputeEH.cxx

headers = Split("""
   cfd1DTextInput.h 
   cfdAnimatedImage.h 
   cfdAnimatedStreamlineCone.h 
   cfdCommandArray.h 
   cfdCommandObjects.h 
   cfdContour.h 
   cfdContourBase.h 
   cfdContours.h 
   cfdCursor.h 
   cfdCuttingPlane.h 
   cfdDataSet.h
   cfdDigitalAnalogGauge.h 
   cfdDisplaySettings.h 
   cfdEnvironmentHandler.h 
   cfdGlobalBase.h 
   cfdGraphicsObject.h 
   cfdImage.h 
   cfdIsosurface.h 
   cfdModel.h 
   cfdModelHandler.h 
   cfdMomentum.h 
   cfdMomentums.h
   cfdNavigate.h 
   cfdObjects.h 
   cfdPlanes.h 
   cfdPolyData.h 
   cfdPresetContour.h 
   cfdPresetMomentum.h 
   cfdPresetVector.h 
   cfdQuatCamHandler.h 
   cfdQuatCam.h 
   cfdReadParam.h 
   cfdScalarBarActor.h 
   cfdSound.h 
   cfdSoundHandler.h 
   cfdSteadyStateVizHandler.h 
   cfdStreamers.h 
   cfdTeacher.h 
   cfdTextOutput.h
   cfdTextureBasedVizHandler.h
   cfdThread.h 
   cfdVectorBase.h
   cfdVector.h 
   cfdVectors.h 
   cfdRawNodeWriteTraverser.h 
   ActiveModelEventHandler.h
   AddVTKDataSetEventHandler.h
   AttributeEventHandler.h 
   CADEventHandler.h 
   CADDeleteNodeEH.h
   CADRemoveAttributeEH.h
   CADAddNodeEH.h 
   CADAddAttributeEH.h 
   CADSetActiveAttributeEH.h 
   CADSetNameEH.h
   CADSetRootNodeEH.h
   CADToggleEH.h
   CADTransformEH.h
   Device.h
   DeviceHandler.h
   DeviceEH.cxx
   DeviceModeEH.cxx
   MaterialModeUpdateEH.h
   MaterialUpdateEH.h
   KeyboardMouse.h
   KeyboardMouseEH.h
   cfdObjectHandler.h
   CreateVisObjectEventHandler.h
   ClearVisObjectsEventHandler.h
   ChangeCursorEventHandler.h
   SeedPoints.h
   SeedPointActivateEH.h
   SPBoundEH.h
   SPDimensionsEH.h
   TBTransientModeUpdateEH.h
   TBTransientDurationUpdateEH.h
   TBIsosurfaceEnableEH.h
   TBIsosurfaceUpdateEH.h
   TBUpdateScalarRangeEH.h
   TBBBoxEH.h
   TBClipPlaneEH.h
   TextureBasedEventHandler.h
   TBActivateEH.h
   TBUpdateSolutionEH.h
   QCLoadFileEH.h
   StoredSceneEH.h
   ChangeWorkingDirectoryEventHandler.h
   ChangeBackgroundColorEventHandler.h
   DataSetAxis.h
   BBoxEventHandler.h
   WireframeEventHandler.h
   AxesEventHandler.h
   AxesLabelsEventHandler.h
   DataSetScalarBar.h
   ScalarBarEventHandler.h
   ViewEventHandler.h
   DisplayInformation.h
   DisplayEventHandler.h
   QCClearDataEH.h
   DataTransformEH.h
   Wand.h
   TBSetActiveShaderManagerEH.h
   TBSliceNumberUpdateEH.h
   TBPhongShadingEnableEH.h
   Tablet.h
   NavigationDataEventHandler.h
   TBPreIntegrateEH.h
   SoundActivateEH.h
   SoundAddNewEH.h

""")
##   DataSetFileEH.h
##   DataSetPrecomputeEH.h

##srcs = map(lambda s: pj('#', 'VE_Xplorer', 'XplorerHandlers', s), xplorer_srcs)

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['VE_XMLLib', 'VE_CADLib', 'VE_ModelLib',
                   'VE_SceneGraph_UtilitiesLib', 
                   'VE_SceneGraphLib%s' %(execOsgPatTag),
                   'VE_UtilLib',
                   'VE_TextureBasedLib%s' %(execOsgPatTag)])
lib_env.Append(LIBPATH = [pj('#', buildDir, 'VE_Xplorer','SceneGraph'),
                        pj('#', buildDir, 'VE_Xplorer','SceneGraph','Utilities'),
                        pj('#', buildDir, 'VE_Xplorer','Utilities'),
                        pj('#', buildDir, 'VE_Xplorer','TextureBased'),
                        pj('#', buildDir, 'VE_Open','XML'),
                        pj('#', buildDir, 'VE_Open','XML','Model'),
                        pj('#', buildDir, 'VE_Open','XML','CAD')])
lib_env.ParseConfig('flagpoll vrjuggler --require-Version=%s --get-vrj-ogl-libs --libs --cflags'%lib_env['VRJugglerVersion'])
lib_env.ParseConfig('flagpoll bullet --libs --cflags')
lib_env.ParseConfig('flagpoll Boost.Filesystem --require-Version=%s --libs --cflags'%lib_env['BoostVersion'])
vtk_options.apply( lib_env )
osg_options.apply( lib_env )
xerces_options.apply( lib_env )
#ode_options.apply( lib_env )
#opal_options.apply( lib_env )
#lib_env.Append( CPPFLAGS = ['-ffriend-injection'] )
if baseEnv['StaticOnly'] == "no":
   lib = ves_pkg.createStaticAndSharedLibrary('VE_XplorerLib%s' %(execOsgPatTag),
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createStaticLibrary('VE_XplorerLib%s' %(execOsgPatTag), lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Xplorer', 'XplorerHandlers'))
lib.build()

