##Builds BaffleUnit program
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import('ves_pkg buildDir RootDir osg_options xerces_options tao_options GetPlatform vpr_options')

lib_env = ves_pkg.getEnv().Clone()

fileBundle = ves_pkg.createFileBundle( pj( 'share','vesuite','examples','dynamic_vehicle_sim_tool','test' ) )
fileBundle.addFiles( [ 'test_data_out6.txt' ] )

vpr_options.apply( lib_env )

srcs = Split("""
	udp_client.cpp
""")

prog1 = ves_pkg.createProgram('udp_client' + lib_env["PROGSUFFIX"], lib_env,
          installPrefix = pj( 'share', 'vesuite', 'examples', 'dynamic_vehicle_sim_tool', 'test' ))

prog1.addSources(srcs)
prog1.build()

srcs = Split("""
	udp_server.cpp
""")

prog2 = ves_pkg.createProgram('udp_server' + lib_env["PROGSUFFIX"], lib_env,
          installPrefix = pj( 'share', 'vesuite', 'examples', 'dynamic_vehicle_sim_tool', 'test' ))

prog2.addSources(srcs)
prog2.build()
