// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// .\be\be_codegen.cpp:1063

#include "stdafx.h"
#include "DynamicsUnit_i.h"
#include "VE_DynamicsUnit.h"
#include <ves/open/xml/model/Network.h>
#include <ves/open/xml/model/Link.h>
#include <ves/open/xml/model/Model.h>
#include <ves/open/xml/DataValuePair.h>
#include <ves/open/xml/XMLReaderWriter.h>
#include <ves/open/xml/model/Point.h>
#include <ves/open/xml/model/Port.h>
#include <ves/open/xml/Command.h>
#include <ves/open/xml/XMLObjectFactory.h>
#include <ves/open/xml/XMLCreator.h>
#include <ves/open/xml/shader/ShaderCreator.h>
#include <ves/open/xml/model/ModelCreator.h>
#include <ves/open/xml/cad/CADCreator.h>
#include <fstream>
#include <iostream>

// Implementation skeleton constructor
Body_Unit_i::Body_Unit_i( /*Body::Executive_ptr exec,*/ std::string name, 
    /*BKPParser* parser,*/ CVE_DynamicsUnitDlg * dialog, 
    CorbaUnitManager* parent, std::string dir )
    :
    dyn( new DynParser() ),
    DynamicsLog( 0 ),
    theParent( parent ),
    theDialog( dialog ),
    return_state( 0 ),
    cur_id_( 0 ),
    UnitName_( name ),
    mWorkingDir( dir )
{
    ves::open::xml::XMLObjectFactory::Instance()->
        RegisterObjectCreator( "XML",new ves::open::xml::XMLCreator() );
    ves::open::xml::XMLObjectFactory::Instance()->
        RegisterObjectCreator( "Shader",new ves::open::xml::shader::ShaderCreator() );
    ves::open::xml::XMLObjectFactory::Instance()->
        RegisterObjectCreator( "Model",new ves::open::xml::model::ModelCreator() );
    ves::open::xml::XMLObjectFactory::Instance()->
        RegisterObjectCreator( "CAD",new ves::open::xml::cad::CADCreator() );

	dyn->SetWorkingDir( mWorkingDir );

    DynamicsLog = reinterpret_cast<CEdit *>(theDialog->GetDlgItem(IDC_EDIT1));

    mQueryCommandNames.insert( "getNetwork");
    mQueryCommandNames.insert( "openSimulation");
    mQueryCommandNames.insert( "runNetwork");
	mQueryCommandNames.insert( "reinitNetwork");
	mQueryCommandNames.insert( "reinitBlock");
    mQueryCommandNames.insert( "stepNetwork");
    mQueryCommandNames.insert( "showSimulation");
    mQueryCommandNames.insert( "hideSimulation");
    mQueryCommandNames.insert( "closeSimulation");
    mQueryCommandNames.insert( "saveSimulation");
    mQueryCommandNames.insert( "saveAsSimulation");
    mQueryCommandNames.insert( "getModuleParamList");
    mQueryCommandNames.insert( "getInputModuleParamList");
    mQueryCommandNames.insert( "getInputModuleProperties");
    mQueryCommandNames.insert( "getOutputModuleParamList");
    mQueryCommandNames.insert( "getOutputModuleProperties");
    mQueryCommandNames.insert( "getStreamInputModuleParamList");
    mQueryCommandNames.insert( "getStreamInputModuleProperties");
    mQueryCommandNames.insert( "getStreamOutputModuleParamList");
    mQueryCommandNames.insert( "getStreamOutputModuleProperties");
    mQueryCommandNames.insert( "setParam");
}
////////////////////////////////////////////////////////////////////////////////
// Implementation skeleton destructor
Body_Unit_i::~Body_Unit_i( void )
{
    delete dyn;
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::ShowDynamics()
{
	dyn->SetVisibility(true);
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::HideDynamics()
{
	dyn->SetVisibility(false);
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::CloseDynamics()
{
	dyn->CloseFile();
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::SaveDynamics()
{
	dyn->SaveFile();
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::StepSim()
{
	//dyn->step();
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::ReinitializeDynamics()
{
    try
    {
	    dyn->ReinitDynamics();
    }
    catch(...)
    {
	    DynamicsLog->SetSel(-1, -1);
	    DynamicsLog->ReplaceSel("Reinitialize Failed.\r\n");
    }
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::StartCalc (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
	//executive_->SetModuleMessage(cur_id_,"Simulation running...\n");
	//dyn->dynamicsdoc->runSolver(false);
	dyn->dyndoc->RunSolver();
	DynamicsLog->SetSel(-1, -1);
	DynamicsLog->ReplaceSel("Simulation Complete\r\n");
	//executive_->SetModuleMessage(cur_id_,"Simulation completed.\n");
	return_state=0;
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::StopCalc (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
	std::string msg;
    msg = UnitName_+" : Instant calculation, already finished\n";
    //executive_->SetModuleMessage(cur_id_,msg.c_str());

}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::PauseCalc (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
	std::string msg;
    msg = UnitName_+" : Instant calculation, already finished\n";
    //executive_->SetModuleMessage(cur_id_,msg.c_str());
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::Resume (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
	std::string msg;
    msg = UnitName_+" : Instant calculation, already finished\n";
    //executive_->SetModuleMessage(cur_id_,msg.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char * Body_Unit_i::GetStatusMessage (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
	ves::open::xml::CommandPtr returnState( new ves::open::xml::Command() );

	returnState->SetCommandName("statusmessage");
	ves::open::xml::DataValuePairPtr data( new ves::open::xml::DataValuePair() );
	data->SetDataName("RETURN_STATE");
	data->SetDataType("UNSIGNED INT");
	data->SetDataValue(return_state);
    returnState->AddDataValuePair( data );
    
	std::vector< std::pair< ves::open::xml::XMLObjectPtr, std::string > > nodes;

	nodes.push_back( 
        std::pair< ves::open::xml::XMLObjectPtr, std::string >( 
        returnState, "vecommand" ) );
	ves::open::xml::XMLReaderWriter commandWriter;
	std::string status="returnString";
	commandWriter.UseStandaloneDOMDocumentManager();
	commandWriter.WriteXMLDocument( nodes, status, "Command" );
    return CORBA::string_dup(status.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char * Body_Unit_i::GetUserData (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
	char * result = 0;
	return result;
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::SetID (
    ::CORBA::Long id
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
  // no need to implement this
  std::cout << "This not implemented for the Dynamics Unit" << std::endl;
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::SetCurID (
    ::CORBA::Long id
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    cur_id_ = id;
}
////////////////////////////////////////////////////////////////////////////////
::Types::ArrayLong* Body_Unit_i::GetID (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
	return &ids_;
}
////////////////////////////////////////////////////////////////////////////////
CORBA::Long Body_Unit_i::GetCurID (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    return cur_id_;
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::DeleteModuleInstance(CORBA::Long id) 
ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
	return; //do nothing;
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::SetName (
    const char * name
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
  // Add your implementation here
	UnitName_ = std::string(name);
}
////////////////////////////////////////////////////////////////////////////////
char * Body_Unit_i::GetName (
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
    return CORBA::string_dup(UnitName_.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char * Body_Unit_i::Query ( const char * query_str
    
  )
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
	ves::open::xml::XMLReaderWriter networkWriter;
	networkWriter.UseStandaloneDOMDocumentManager();
	networkWriter.ReadFromString();
	networkWriter.ReadXMLData( query_str, "Command", "vecommand" );
	//std::ofstream packet("packet.txt");
	//packet << query_str;
	//packet.close();
	std::vector< ves::open::xml::XMLObjectPtr > objectVector = networkWriter.GetLoadedXMLObjects();

	ves::open::xml::CommandPtr cmd;	
	std::string cmdname;
	
	cmd = boost::dynamic_pointer_cast<ves::open::xml::Command>( objectVector.at( 0 ) );
	cmdname = cmd->GetCommandName();
    
    std::set< std::string >::const_iterator commandItr
        = mQueryCommandNames.find( cmdname );
    
    //If the command is not processed here then do not bother doing anything more
    if( commandItr == mQueryCommandNames.end() )
    {
        return CORBA::string_dup("NULL");
    }
    
	DynamicsLog->SetSel(-1, -1);
	DynamicsLog->ReplaceSel(("Command: "+cmdname+"\r\n").c_str());
	char* returnValue = "empty";

	if (cmdname=="getNetwork")
	{
		//bkp = theParent->CreateParser();
		//theParent->CreateParser();
		//bkp = new BKPParser();
		returnValue = handleGetNetwork( cmd );
		return returnValue;
	}
	else if(cmdname=="openSimulation")
	{
		returnValue = handleOpenSimulation(cmd);
		return returnValue;
	}
	else if (cmdname=="runNetwork")
	{
		StartCalc();
		return CORBA::string_dup("networkRun");
	}
	else if (cmdname=="stepNetwork")
	{
		StepSim();
		return CORBA::string_dup("networkRun");
	}
	else if (cmdname=="showSimulation")
	{
		ShowDynamics();
		return CORBA::string_dup("Simulation Shown.");
	}
	else if (cmdname=="hideSimulation")
	{
		HideDynamics();
		return CORBA::string_dup("Simulation hidden.");
	}
	else if (cmdname=="closeSimulation")
	{
		DynamicsLog->SetSel(-1, -1);
		DynamicsLog->ReplaceSel("closing...\r\n");
		CloseDynamics();
		DynamicsLog->SetSel(-1, -1);
		DynamicsLog->ReplaceSel("closed.\r\n");
		return CORBA::string_dup("Simulation closed.");
	}
	else if (cmdname=="saveSimulation")
	{
		DynamicsLog->SetSel(-1, -1);
		DynamicsLog->ReplaceSel("saving...\r\n");
		try
		{
			//SaveDynamics();
	        //dyn->saveAs(( mWorkingDir + mFilename + ".apw" ).c_str());
	        dyn->SaveAs(( mWorkingDir + mFilename + ".dynf" ).c_str());
		    DynamicsLog->SetSel(-1, -1);
		    DynamicsLog->ReplaceSel("saved.\r\n");
		}
		catch(...)
		{
			DynamicsLog->SetSel(-1, -1);
			DynamicsLog->ReplaceSel("messed up save.\r\n");
		}
		return CORBA::string_dup("Simulation Saved.");
	}
	else if (cmdname=="saveAsSimulation")
	{
		returnValue = handleSaveAs(cmd);
		return returnValue;
	}
	else if( cmdname == "reinitNetwork" )
	{
		ReinitializeDynamics();
		return CORBA::string_dup( "Simulation reinitialized." );
	}
	else if( cmdname == "reinitBlock" )
	{
		ReinitializeBlock(cmd);
		return CORBA::string_dup( "Block reinitialized." );
	}
    
    //Blocks
	else if (cmdname=="getModuleParamList")
	{
		//executive_->SetModuleMessage(cur_id_,"Querying inputs...\n");
		returnValue = handleGetModuleParamList(cmd);
		//executive_->SetModuleMessage(cur_id_,"Querying completed.\n");
		return returnValue;
	}
/*
	//Blocks
	else if (cmdname=="getInputModuleParamList")
	{
		//executive_->SetModuleMessage(cur_id_,"Querying inputs...\n");
		returnValue = handleGetInputModuleParamList(cmd);
		//executive_->SetModuleMessage(cur_id_,"Querying completed.\n");
		return returnValue;
	}
	else if (cmdname=="getInputModuleProperties")
	{
		returnValue = handleGetInputModuleProperties(cmd);
		return returnValue;
	}
	else if (cmdname=="getOutputModuleParamList")
	{
		//executive_->SetModuleMessage(cur_id_,"Querying outputs...\n");
		returnValue = handleGetOutputModuleParamList(cmd);
		//executive_->SetModuleMessage(cur_id_,"Querying completed.\n");
		return returnValue;
	}
	else if (cmdname=="getOutputModuleProperties")
	{
		returnValue = handleGetOutputModuleProperties(cmd);
		return returnValue;
	}

	//Streams
	else if (cmdname=="getStreamInputModuleParamList")
	{
		//executive_->SetModuleMessage(cur_id_,"Querying link inputs...\n");
		returnValue = handleGetStreamInputModuleParamList(cmd);
		//executive_->SetModuleMessage(cur_id_,"Querying link completed.\n");
		return returnValue;
	}
	else if (cmdname=="getStreamInputModuleProperties")
	{
		returnValue = handleGetStreamInputModuleProperties(cmd);
		return returnValue;
	}
	else if (cmdname=="getStreamOutputModuleParamList")
	{
		//executive_->SetModuleMessage(cur_id_,"Querying link outputs...\n");
		returnValue = handleGetStreamOutputModuleParamList(cmd);
		//executive_->SetModuleMessage(cur_id_,"Querying link completed.\n");
		return returnValue;
	}
	else if (cmdname=="getStreamOutputModuleProperties")
	{
		returnValue = handleGetStreamOutputModuleProperties(cmd);
		return returnValue;
	}
*/
	//Params
	else if (cmdname=="setParam")
	{
		SetParam(cmd);
		return CORBA::string_dup("Param Set");
	}
	else
		return CORBA::string_dup("NULL");

}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleGetNetwork(ves::open::xml::CommandPtr cmd)
{
    CEdit *Display;
    Display = reinterpret_cast<CEdit *>(theDialog->GetDlgItem(IDC_EDIT2));

	//this command has no params
	bool firsttime=true;

	std::string filename = cmd->GetDataValuePair(1)->GetDataString();
	if (firsttime)
	{
        //make sure bkp file exists
	    std::ifstream dynFile( ( mWorkingDir + filename + ".dynf" ).c_str() , std::ios::binary);
        if( !dynFile.is_open() )
        {
            //no dyn file
		    DynamicsLog->SetSel(-1, -1);
		    DynamicsLog->ReplaceSel("Dynf File Does NOT exist.\r\n");
	        return CORBA::string_dup( "DYNDNE" );
        }
        dynFile.close();

		//Display->SetWindowText( ( mWorkingDir + filename ).c_str());
		Display->SetWindowText( ( filename ).c_str());
        //go through dyn parsing procedure
		dyn->OpenFile(filename.c_str());
		//dyn->ParseFile((mWorkingDir + filename + ".dynf" ).c_str());
        mFilename = filename;
		firsttime=false;
	}
	   
    //Display->SetWindowText(filename.c_str());

	std::string network;
	try
    {
        network = dyn->CreateNetwork();
	}
	catch(...)
	{
		std::cout << "GetNetwork Exception Dynamics Unit" << std::endl;
        return NULL;
	}
	//std::ofstream output("returnString.txt");
	//output<<"Return String"<<std::endl;
	//output<<network<<std::endl;
	//output.close();   
	
	//Display = reinterpret_cast<CEdit *>(theDialog->GetDlgItem(IDC_EDIT1));
    //Display->set->SetWindowText(network.c_str());

		//DynamicsLog->SetSel(-1, -1);
		//DynamicsLog->ReplaceSel(network.c_str());
	return CORBA::string_dup(network.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleOpenSimulation(ves::open::xml::CommandPtr cmd)
{
    CEdit *Display;
    Display = reinterpret_cast<CEdit *>(theDialog->GetDlgItem(IDC_EDIT2));

	//this command has no params
	std::string filename = cmd->GetDataValuePair(1)->GetDataString();
	Display->SetWindowText(filename.c_str());
	dyn->OpenFile(filename.c_str());
	return CORBA::string_dup("Simulation Opened.");
}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleSaveAs(ves::open::xml::CommandPtr cmd)
{
	DynamicsLog->SetSel(-1, -1);
	DynamicsLog->ReplaceSel("saving...\r\n");
	std::string filename = cmd->GetDataValuePair(1)->GetDataString();
	mFilename = filename;
    dyn->SaveAs(( mWorkingDir + mFilename + ".dynf" ).c_str());
	//dyn->saveAs(( mWorkingDir + mFilename + ".dynf" ).c_str());
	DynamicsLog->SetSel(-1, -1);
	DynamicsLog->ReplaceSel("saved.\r\n");
	return CORBA::string_dup("Simulation Saved.");
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::ReinitializeBlock(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname;
	unsigned int modId;

	for( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="ModuleId")
			curPair->GetData(modId);
	}
	//dyn->ReinitBlock(modname);
}
////////////////////////////////////////////////////////////////////////////////
/*char* Body_Unit_i::handleGetInputModuleParamList(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname;
	unsigned int modId;

	for( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="ModuleId")
			curPair->GetData(modId);
	}

	//There shouldn't be two intances of an Dynamics framework. so discard the moduleId
	//the returned string will be a well formated XML within "vecommand" element
	std::string netPak;// = dyn->GetInputModuleParams(modname);

    //std::ofstream output("inputList.txt");
    //output<<netPak;
    //output.close();  

	return CORBA::string_dup(netPak.c_str());
}*/
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleGetModuleParamList(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname;
	unsigned int modId;

	for( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="ModuleId")
			curPair->GetData(modId);
	}

	//There shouldn't be two intances of an Dynamics framework. so discard the moduleId
	//the returned string will be a well formated XML within "vecommand" element
	std::string netPak = dyn->GetModuleParams(modname);

    //std::ofstream output("inputList.txt");
    //output<<netPak;
    //output.close();  

	return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
/*char* Body_Unit_i::handleGetInputModuleProperties(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname,paramName;
	unsigned int modId;

	for ( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="moduleId")
			curPair->GetData(modId); //modId is discarded because of the same reason as before
		else if (curPair->GetDataName()=="ParamName")
			paramName=curPair->GetDataString();
	}
	std::string netPak;// = dyn->GetInputModuleParamProperties(modname, paramName);
	return CORBA::string_dup(netPak.c_str());

}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleGetOutputModuleParamList(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname;
	unsigned int modId;

	for( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="ModuleId")
			curPair->GetData(modId);
	}

	//There shouldn't be two intances of an Dynamics framework. so discard the moduleId
	//the returned string will be a well formated XML within "vecommand" element
	std::string netPak; //= dyn->GetOutputModuleParams(modname);
	return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleGetOutputModuleProperties(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname,paramName;
	unsigned int modId;

	for ( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="moduleId")
			curPair->GetData(modId); //modId is discarded because of the same reason as before
		else if (curPair->GetDataName()=="ParamName")
			paramName=curPair->GetDataString();
	}
	std::string netPak; // = dyn->GetOutputModuleParamProperties(modname, paramName);
	return CORBA::string_dup(netPak.c_str());

}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleGetStreamInputModuleParamList(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname;
	unsigned int modId;

	for ( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="ModuleId")
			curPair->GetData(modId);
	}

	//There shouldn't be two intances of an Dynamics framework. so discard the moduleId
	//the returned string will be a well formated XML within "vecommand" element
	std::string netPak;// = dyn->GetStreamInputModuleParams(modname);
	return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleGetStreamInputModuleProperties(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname,paramName;
	unsigned int modId;

	for ( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="moduleId")
			curPair->GetData(modId); //modId is discarded because of the same reason as before
		else if (curPair->GetDataName()=="ParamName")
			paramName=curPair->GetDataString();
	}
	std::string netPak;// = dyn->GetStreamInputModuleParamProperties(modname, paramName);
	return CORBA::string_dup(netPak.c_str());

}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleGetStreamOutputModuleParamList(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname;
	unsigned int modId;

	for( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="ModuleId")
			curPair->GetData(modId);
	}

	//There shouldn't be two intances of an Dynamics framework. so discard the moduleId
	//the returned string will be a well formated XML within "vecommand" element
	std::string netPak;// = dyn->GetStreamOutputModuleParams(modname);
	return CORBA::string_dup(netPak.c_str());
}
////////////////////////////////////////////////////////////////////////////////
char* Body_Unit_i::handleGetStreamOutputModuleProperties(ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname,paramName;
	unsigned int modId;

	for( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="moduleId")
			curPair->GetData(modId); //modId is discarded because of the same reason as before
		else if (curPair->GetDataName()=="ParamName")
			paramName=curPair->GetDataString();
	}
	std::string netPak;// = dyn->GetStreamOutputModuleParamProperties(modname, paramName);
	return CORBA::string_dup(netPak.c_str());

}*/
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::SetParams (CORBA::Long id,
    const char * param)
  ACE_THROW_SPEC ((
    ::CORBA::SystemException,
    ::Error::EUnknown
  ))
{
   //discard the id, it is not used;
   ves::open::xml::XMLReaderWriter networkWriter;
   networkWriter.UseStandaloneDOMDocumentManager();
   networkWriter.ReadFromString();
   networkWriter.ReadXMLData( param, "Command", "vecommand" );
   std::vector< ves::open::xml::XMLObjectPtr > objectVector = networkWriter.GetLoadedXMLObjects();
  
   //this part would need rewrite later
   for( size_t i=0; i<objectVector.size(); i++)
   {
		ves::open::xml::CommandPtr param = boost::dynamic_pointer_cast<ves::open::xml::Command>( objectVector.at( i ) );
		std::string paramName = param->GetCommandName();
		
		size_t num = param->GetNumberOfDataValuePairs();
		for (size_t j=0; j<num; j++)
		{
			ves::open::xml::DataValuePairPtr curPair= param->GetDataValuePair("NodePath");
			CString nodepath = curPair->GetDataString().c_str();
			curPair = param->GetDataValuePair("Value");
			CString nodevalue = curPair->GetDataString().c_str();

			//CASI::Variable cur_var = dyn->Dynamicsdoc->getVarByNodePath(nodepath);
			//cur_var.setValue(nodevalue);
		}
   }
}
////////////////////////////////////////////////////////////////////////////////
void Body_Unit_i::SetParam (ves::open::xml::CommandPtr cmd)
{
	size_t num = cmd->GetNumberOfDataValuePairs();
	std::string modname,paramName, paramValue;

	for( size_t i=0; i < num; i++)
	{
		ves::open::xml::DataValuePairPtr curPair= cmd->GetDataValuePair(i);
		if (curPair->GetDataName()=="ModuleName")
			modname=curPair->GetDataString();
		else if (curPair->GetDataName()=="ParamName")
			paramName=curPair->GetDataString();
		else if (curPair->GetDataName()=="ParamValue")
			paramValue=curPair->GetDataString();
	}
	dyn->SetValue( modname, paramName, paramValue );
}
////////////////////////////////////////////////////////////////////////////////
