##Builds CoinFunnel Graphical Plugin
import os, sys, string
import SConsAddons.Util as sca_util
import distutils.util
pj = os.path.join

host_type = distutils.util.get_platform()

Import( 'baseEnv ves_pkg buildDir RootDir gmtl_options vpr_options osg_options osgal_options bullet_options xerces_options' )
openDir = os.path.abspath( pj( RootDir, 'share', 'examples', 'CoinFunnel', 'CoinFunnelGP' ) )
sources = sca_util.getSourcesRecursive( openDir )
headers = sca_util.getHeadersRecursive( openDir )

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append( LIBS = [ 'ves_xplorer',
                         'ves_xplorer_scenegraph' ] )
lib_env.Append( LIBPATH = [ pj('#', buildDir, 'src','ves','xplorer'),
		            pj('#', buildDir, 'src','ves','xplorer','scenegraph') ] )
#lib_env.Append( CPPPATH = [] )
lib_env.Append( CPPDEFINES = [ 'VE_USER_PLUGIN_LIBRARY' ] )

gmtl_options.apply( lib_env )
vpr_options.apply( lib_env )
osg_options.apply( lib_env )
osgal_options.apply( lib_env )
bullet_options.apply( lib_env )
xerces_options.apply( lib_env )

lib = ves_pkg.createSharedLibrary( 'CoinFunnelGP', lib_env,
    installPrefix = pj( 'share', 'vesuite', 'examples', 'CoinFunnel', 'Plugins', 'GE', host_type ) )  

lib.addSources( sources )
lib.build()
