##Builds VE_SceneGraphLib<tag>
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR execOsgPatTag osg_options buildDir')

sources = Split("""
   OCCNURBSFileReader.cxx
""")

headers = Split("""
   OCCNURBSFileReader.h
   IGES2VENURBS.h
   VENURBS2OCCNURBS.h
   OCCNURBS2VENURBS.h
""")

lib_env = ves_pkg.getEnv().Copy()
##env.Append(CPPPATH = [os.getcwd()])
lib_env.Append(LIBS = ['VE_NURBSLib%s' %(execOsgPatTag)])
lib_env.Append(LIBPATH = [pj('#', buildDir, 'VE_Xplorer','SceneGraph','NURBS')])
##lib_env.ParseConfig('flagpoll osg --libs --cflags')
osg_options.apply( lib_env )
if baseEnv['StaticOnly'] == "no":
   lib = ves_pkg.createStaticAndSharedLibrary('VE_NURBSUtilsLib%s' %(execOsgPatTag),
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createStaticLibrary('VE_NURBSUtilsLib%s' %(execOsgPatTag), lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Xplorer', 'SceneGraph', 'NURBS', 'Utilities'))
lib.build()
