## Build DASIlib
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR RootDir')

sources = Split("""
   AspenDynamicsInterface.cxx
""")

headers = Split("""
   AspenDynamicsInterface.h
""")

lib_env = ves_pkg.getEnv().Copy()
lib_env['MSVS_USE_MFC_DIRS'] = 1

lib_env.Append( CPPDEFINES = ['_AFXDLL'])
lib_env.Append( CPPDEFINES = ['ASPENDYNAMICSINTERFACE_LIBRARY'])
lib = ves_pkg.createSharedLibrary('AspenDynamicsInterface', lib_env,
                                               installPrefix = LIBDIR)
lib.addSources(sources)
lib.addHeaders(headers, pj('ves'))
lib.build()
