## Build DASIlib
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR RootDir')

sources = Split("""
   AspenPlusInterface.cxx
""")
#   DASI_VAriable.cxx
#   DASI_DASIObj.cxx
#   DASI.cxx

headers = Split("""
   AspenPlusInterface.h
""")

lib_env = ves_pkg.getEnv().Copy()
lib_env['MSVS_USE_MFC_DIRS'] = 1

lib_env.Append( CPPPATH = [pj('#', 'share', 'tools', 'aspen','DASIlib', 'aspendyn_2006.5')] )
lib_env.Append( CPPDEFINES = ['_AFXDLL'])
lib_env.Append( CPPDEFINES = ['ASPENPLUSINTERFACE_LIBRARY'])
lib = ves_pkg.createSharedLibrary('AspenPlusInterface', lib_env,
                                               installPrefix = LIBDIR)
lib.addSources(sources)
lib.addHeaders(headers, pj('ves'))
lib.build()
