##sets up jconf files for stereo_desktop
#import os, sys, string
#pj = os.path.join
#import SConsAddons.Util as sca_util

exampleSubdirs = Split("""
    CoinFunnel
    ConstructionBots
    Fermentor
    HyperLab
    InteractiveStove
    nurbs
    simple
    garage
    golf_game
""")
#     CameraPlacementTool

##Run SConscript files in all of those folders.
for d in exampleSubdirs:
   SConscript( dirs = d )
