##sets up jconf files for stereo_desktop
#import os, sys, string
#pj = os.path.join
#import SConsAddons.Util as sca_util
Import( 'poco_options' )

exampleSubdirs = Split("""
    CameraPlacementTool
    CoinFunnel
    ConstructionBots
    Fermentor
    HyperLab
    InteractiveStove
    nurbs
    ParallaxMapping
    simple
    garage
    golf_game
    SimpleNetwork
    simple_physics
    input_animation
""")
#VascularSimViewer
#    sensor_overlay

if poco_options.isAvailable():
    exampleSubdirs.append( 'WarrantyTool' )

##Run SConscript files in all of those folders.
for d in exampleSubdirs:
   SConscript( dirs = d )
