##sets up jconf files for stereo_desktop
#import os, sys, string
#pj = os.path.join
#import SConsAddons.Util as sca_util
Import( 'poco_options osgal_options' )

exampleSubdirs = Split("""
    CameraPlacementTool
    CoinFunnel
    HyperLab
    nurbs
    ParallaxMapping
    simple
    garage
    golf_game
    simple_physics
    input_animation
    dynamic_vehicle_sim_tool
    TankPlugin
    real_time_sensor
    Multiscale2
    constraint_demo
    hyper_lab_ice
""")
#InteractiveStove
#VascularSimViewer
#sensor_overlay
#VirtualLab
#Fermentor
#ConstructionBots
#SimpleNetwork

if poco_options.isAvailable():
    exampleSubdirs.append( 'WarrantyTool' )

if osgal_options.isAvailable():
    exampleSubdirs.append( 'audio_test' )

##Run SConscript files in all of those folders.
for d in exampleSubdirs:
   SConscript( dirs = d )
