#Builds tools for daycent
#http://www.nrel.colostate.edu/projects/daycent/index.html

Import( 'GetPlatform baseEnv ves_pkg poco_options' )

toolsSubdirs = Split("""
""")

if poco_options.isAvailable():
    toolsSubdirs.append('post_processor')

#Run SConscript files in all of those folders.
#for d in toolsSubdirs:
#    SConscript( dirs = d )
