##Builds Exe_server
import os, sys, string
pj = os.path.join

Import('ves_pkg LIBDIR PREFIX buildDir xerces_options')

srcs = Split("""
   veaMaker.cxx 
""")

env = ves_pkg.getEnv().Copy()
env.Append(LIBS = ['ves_open_xml'])
env.Append(LIBPATH = [ pj('#', buildDir,'src','ves', 'open', 'xml')])

xerces_options.apply( env )
ce_prog = ves_pkg.createProgram('veaMaker.exe', env, 'bin')
ce_prog.addSources( srcs )
ce_prog.build()

