##Builds VE-Suite Libraries
#import os
#pj = os.path.join

builderSubdirs = Split("""
    preprocessor
    util
    vtkto3dtexture
""")

##Run SConscript files in all of those folders.
for d in builderSubdirs:
   #print " dir ", d
   SConscript( dirs = d )
