##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg GetPlatform poco_options' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'audio_test' ) )
AudioTestDir = pj( RootDir, 'share', 'examples', 'audio_test' )

#fileBundle.addFiles( [ 'warrantytool.ves' ] )
#iveFile = sca_util.getFilesRecursiveByExt( AudioTestDir, [ '.ive' ] )
#fileBundle.addFiles( iveFile )

AudioTestSubdirs = Split("""
    GraphicalPlugin
""")

##Run SConscript files in all of these folders.
for d in AudioTestSubdirs:
   SConscript( dirs = d )
