##Builds VE_CADLib
import os, sys, string
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR buildDir xerces_options')

sources = Split("""
   CADAssembly.cxx
   CADAttribute.cxx
   CADCreator.cxx
   CADMaterial.cxx
   CADNode.cxx
   CADNodeTraverser.cxx
   CADPart.cxx
   CADNodeAnimation.cxx
""")

headers = Split("""
   CADAssembly.h
   CADAssemblyPtr.h
   CADAttribute.h
   CADAttributePtr.h
   CADCreator.h
   CADMaterial.h
   CADMaterialPtr.h
   CADNode.h
   CADNodeAnimation.h
   CADNodeAnimationPtr.h
   CADNodePtr.h
   CADNodeTraverser.h
   CADPart.h
   CADPartPtr.h
""")

##srcs = map(lambda s: pj('#', 'VE_Open', 'XML', 'CAD', s), srcs)

lib_env = ves_pkg.getEnv().Copy()
lib_env.Append(LIBS = ['VE_XMLLib', 'VE_ShaderLib'])
lib_env.Append(LIBPATH = [  pj('#', buildDir, 'VE_Open','XML'),
                        pj('#', buildDir, 'VE_Open','XML','Shader')])
xerces_options.apply( lib_env )
if baseEnv['StaticLibs'] == "yes":
   lib = ves_pkg.createStaticAndSharedLibrary('VE_CADLib',
                                                        lib_env,
                                                        installPrefix = LIBDIR)
else:
   lib = ves_pkg.createSharedLibrary('VE_CADLib', lib_env,
                                               installPrefix = LIBDIR)
   
lib.addSources(sources)
lib.addHeaders(headers,  pj( 'VE_Open', 'XML', 'CAD'))
lib.build()
