##Builds VE-Suite Libraries
import os
pj = os.path.join

Import( "ves_pkg" )

openSubdirs = Split("""
    builder
    ce
    conductor
    open
    util
    xplorer
""")

##Run SConscript files in all of those folders.
for d in openSubdirs:
   SConscript( dirs = d )

configHeader = ves_pkg.createFileBundle( pj( 'include', 'ves' ) )
configHeader.addFiles( pj( 'VEConfig.h' ) )
