##Builds CE Libraries
openSubdirs = Split("""
    builder
    ce
    conductor
    open
    util
    xplorer
""")

##Run SConscript files in all of those folders.
for d in openSubdirs:
   #print " dir ", d
   SConscript( dirs = d )
