##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'nurbs' ) )
nurbsDemoDir = pj( RootDir, 'share', 'examples', 'nurbs' )
venFile = sca_util.getFilesRecursiveByExt( nurbsDemoDir, [ '.ven' ] )
txtFile = sca_util.getFilesRecursiveByExt( nurbsDemoDir, [ '.txt' ] )
vesFile = sca_util.getFilesRecursiveByExt( nurbsDemoDir, [ '.ves' ] )

fileBundle.addFiles( venFile )
fileBundle.addFiles( txtFile )
fileBundle.addFiles( vesFile )