##Builds VE_SceneGraph_UtilitiesLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

srcs = Split("""
    Attribute.cxx
    MaterialHelper.cxx
    ShaderHelper.cxx
""")

srcs = map(lambda s: pj('#', 'VE_Xplorer', 'SceneGraph',
                        'Utilities', s), srcs)
env = baseEnv.Copy()
env.ParseConfig('flagpoll osg --libs --cflags')
env.ParseConfig('flagpoll xerces --libs')
env.ParseConfig('wx-config --cxxflags --libs')
env.ParseConfig('vrjuggler-config --libs --extra-libs --includes')

targetLib = pj(libPath, 'VE_SceneGraph_UtilitiesLib')
env.SharedLibrary(target = targetLib, source = srcs)
