##Builds VE_SceneGraph_UtilitiesLib
import os, sys, string
pj = os.path.join

Import('baseEnv')
Import('libPath')

srcs = Split("""
    Attribute.cxx
    MaterialHelper.cxx
    ShaderHelper.cxx
""")

##srcs = map(lambda s: pj('#', 'VE_Xplorer', 'SceneGraph',
##                        'Utilities', s), srcs)
env = baseEnv.Copy()
env.Append(LIBS = ['VE_CADLib', 'VE_ShaderLib', 'VE_XMLLib'])
env.ParseConfig('flagpoll osg xerces --libs --cflags')

targetLib = pj( env[ 'LIBDIR' ], 'VE_SceneGraph_UtilitiesLib')
env.SharedLibrary(target = targetLib, source = srcs)
