##Builds VE_Xplorer<tag>
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import('baseEnv ves_pkg LIBDIR GetPlatform execOsgPatTag buildDir osg_options vtk_options xerces_options vesSVNRevision RootDir')

srcDir = os.path.abspath( pj(RootDir, 'src', 'apps', 'xplorer') )
srcs = sca_util.getSourcesRecursive( srcDir )

env = ves_pkg.getEnv().Copy()
env.Append(
            LIBS = ['ves_open_xml',
                   'DataLoaderLib',
                   'TranslatorToVTKLib',
                   'ves_xplorer_scenegraph%s' %(execOsgPatTag),
                   'ves_xplorer_util',
                   'ves_xplorer_volume%s' %(execOsgPatTag),
                   'ves_open_module',
                   'ves_xplorer%s' %(execOsgPatTag)])#,
                   #'VE_XplorerNetworkLib%s' %(execOsgPatTag),
                   #'GraphicalPlugin%s' %(execOsgPatTag)])

env.Append(LIBPATH = [pj('#', buildDir, 'VE_Xplorer','SceneGraph'),
                        pj('#', buildDir, 'VE_Xplorer','XplorerHandlers'),
                        pj('#', buildDir, 'VE_Xplorer','Utilities'),
                        pj('#', buildDir, 'VE_Xplorer','TextureBased'),
                        pj('#', buildDir, 'VE_Xplorer','GraphicalPlugin'),
                        pj('#', buildDir, 'VE_Xplorer','XplorerNetwork'),
                        pj('#', buildDir, 'VE_Builder','Translator','DataLoader'),
                        pj('#', buildDir, 'VE_Builder','Translator','cfdTranslatorToVTK'),
                        pj('#', buildDir, 'VE_Open','skel'),
                        pj('#', buildDir, 'VE_Open','XML')])
#disable profiling by default
if env['VPRProfile'] == 'no':
   env.Append( CPPDEFINES = ['DISABLE_VPR_PROFILE'] )
env.Append( CPPDEFINES = [vesSVNRevision] )
env.Append(CPPPATH = [pj('#','external','osgOQ','include')])
env.Append(LIBS = ['osgOQ'])
env.Append(LIBPATH = [pj('#',buildDir,'external','osgOQ')])
vtk_options.apply( env )
osg_options.apply( env )
xerces_options.apply( env )
env.ParseConfig('flagpoll TAO \
                          ACE TAO_IORInterceptor TAO_ObjRefTemplate TAO_Valuetype \
                          TAO_CosNaming TAO_Svc_Utils TAO_IORTable TAO_Messaging \
                          TAO_PortableServer TAO_BiDirGIOP TAO_AnyTypeCode \
                          --libs --cflags')
env.ParseConfig('flagpoll vrjuggler --atleast-version=%s --get-vrj-ogl-libs --libs --cflags'%env['VRJugglerVersion'])
env.ParseConfig('flagpoll Boost.Filesystem --atleast-version=%s --libs --cflags'%env['BoostVersion'])
env.ParseConfig('flagpoll bullet --libs --cflags')

prog = ves_pkg.createProgram('project%s' %(execOsgPatTag), env, 'bin')
prog.addSources( srcs )
prog.build()

