##Builds a multitude of utilities
import os, sys, string
pj = os.path.join

Import('baseEnv RootDir ves_pkg LIBDIR GetPlatform buildDir vtk_options')

srcs = Split("""
  vector_field.cpp
""")


#env = ves_pkg.getEnv().Clone()
env = baseEnv.Clone()
vtk_options.apply( env )

multiblock = ves_pkg.createProgram('vectorField' + env["PROGSUFFIX"], env, 'bin')
multiblock.addSources( srcs )
multiblock.build()
