##
import os, sys, string
import SConsAddons.Util as sca_util
pj = os.path.join

Import( 'RootDir ves_pkg' )

fileBundle = ves_pkg.createFileBundle( pj( 'share', 'vesuite', 'examples', 'input_animation' ) )
fermentorDemoDir = pj( RootDir, 'share', 'examples', 'input_animation' )
iveFile = sca_util.getFilesRecursiveByExt( fermentorDemoDir, [ '.ive' ] )

fileBundle.addFiles( iveFile )
# fileBundle.addFiles( [ 'Icons/fermentor.jpg' ] )
# fileBundle.addFiles( [ 'fermentor.ves' ] )
fermentorSubdirs = Split("""
    animationGP
""")

##Run SConscript files in all of these folders.
for d in fermentorSubdirs:
   SConscript( dirs = d )
